function popSimilarityAllRec(onlyRun,recSel)
% compare the spike train similarity for different alignment conditions over all the recordings 
% recSel = 1, AL+PL with cue; recSel = 2, AL only

    GlobalConst;
    intervalT = 20;
    intervalD = 1800;
    tc = 500; % ms
    cost = 2/(tc/1000*sampleFq);
    
    thrCorrT = -1;
    
    RecordingList;
    
    if(recSel == 1)
        strTmp = '_ALPL';
    else
        strTmp = '_AL';
    end
    fileName = ['Z:\Yingxue\DataAnalysisRaphi\PopCorrTAlignedActive_AllRec_Stat' strTmp '.mat'];
    if(exist(fileName) ~= 0)
        load(fileName,'popSimRunAll','popSimRewAll','popSimCueAll');
    end
    
    popSimRunAll.CorrTGood = [];
    popSimRunAll.CorrTBad = [];
    popSimRunAll.CorrT = [];
    popSimRunAll.CorrTRecNo = [];
    popSimRunAll.CorrTGoodRecNo = [];
    popSimRunAll.CorrTBadRecNo = [];
    popSimRunAll.CorrTTask = [];
    popSimRunAll.CorrTGoodTask = [];
    popSimRunAll.CorrTBadTask = [];
        
    popSimRewAll.CorrTGood = [];
    popSimRewAll.CorrTBad = [];
    popSimRewAll.CorrT = [];
    
    popSimCueAll.CorrTGood = [];
    popSimCueAll.CorrTBad = [];
    popSimCueAll.CorrT = [];
    for i = 1:size(listRecordingsActiveLickPath,1)
        path = listRecordingsActiveLickPath(i,:);
        fileName = listRecordingsActiveLickFileName(i,:);
        mazeSess = mazeSessionActiveLick(i);
        fullPath = [path,fileName '_meanPopCorrT_msess'  num2str(mazeSess) '_Run' num2str(onlyRun) '_intT' ...
            num2str(intervalT) '.mat'];
        load(fullPath,'meanPopCorrTRun','meanPopCorrTRew','meanPopCorrTCue');
        
        fileNamePeakFR = [fileName '_PeakFR_msess' num2str(mazeSess) ...
                        '_RunOnset0.mat'];
        fullPath = [path fileNamePeakFR];
        if(exist(fullPath) == 0)
            disp(['The peak firing rate file does not exist. Please call ',...
                    'function "PeakFiringRate_Aligned" first.']);
            return;
        end
        load(fullPath,'pFRNonStimGoodStruct','pFRNonStimBadStruct');
        
        fileNameFW = [fileName '_FieldSpCorr_GoodTr_Run1.mat'];
        fullPath = [path fileNameFW];
        if(exist(fullPath) == 0)
            disp(['The field detection file does not exist. Please call ',...
                    'function "FieldDetection_GoodTr" first.']);
            return;
        end
        load(fullPath,'paramF'); 
        
        if(length(pFRNonStimGoodStruct.indLapList) >= paramF.minNumTr)
            popSimRunAll.CorrTGoodTask = [popSimRunAll.CorrTGoodTask ...
                2];
            popSimRunAll.CorrTGoodRecNo = [popSimRunAll.CorrTGoodRecNo ...
                i];
            popSimRunAll.CorrTGood = [popSimRunAll.CorrTGood ...
                meanPopCorrTRun.meanGood];
            popSimRewAll.CorrTGood = [popSimRewAll.CorrTGood ...
                meanPopCorrTRew.meanGood];
            popSimCueAll.CorrTGood = [popSimCueAll.CorrTGood ...
                meanPopCorrTCue.meanGood];
        end

        popSimRunAll.CorrTTask = [popSimRunAll.CorrTTask ...
                2];
        popSimRunAll.CorrTRecNo = [popSimRunAll.CorrTRecNo ...
                i];        
        popSimRunAll.CorrT = [popSimRunAll.CorrT ...
            meanPopCorrTRun.mean];
        popSimRewAll.CorrT = [popSimRewAll.CorrT ...
            meanPopCorrTRew.mean];
        popSimCueAll.CorrT = [popSimCueAll.CorrT ...
            meanPopCorrTCue.mean];

        if(~isempty(pFRNonStimBadStruct) && length(pFRNonStimBadStruct.indLapList) >= paramF.minNumTr)
            popSimRunAll.CorrTBadTask = [popSimRunAll.CorrTBadTask ...
                2];
            popSimRunAll.CorrTBadRecNo = [popSimRunAll.CorrTBadRecNo ...
                i];
            popSimRunAll.CorrTBad = [popSimRunAll.CorrTBad ...
                meanPopCorrTRun.meanBad];
            popSimRewAll.CorrTBad = [popSimRewAll.CorrTBad ...
                meanPopCorrTRew.meanBad];
            popSimCueAll.CorrTBad = [popSimCueAll.CorrTBad ...
                meanPopCorrTCue.meanBad];
        end

    %         path = listRecordingsActiveLickPath(i,:);
    %         fileName = listRecordingsActiveLickFileName(i,:);
    %         fullPath = [path,fileName, '_meanSpikesCorrDistAligned_Run' num2str(onlyRun) '_intD' ...
    %             num2str(intervalT) '.mat'];
    %         load(fullPath,'meanCorrDistRun','meanCorrDistRew','meanCorrDistCue');
    %         
    %         indSelCorrT = selNeuronsCorrD(path,fileName,onlyRun,intervalT,thrCorrD,minFR);
    %         spikeSimRunAll.CorrTNeuSel = [spikeSimRunAll.CorrTNeuSel ...
    %             find(indSelCorrT == 1)];
    %         spikeSimRunAll.CorrTRecNo = [spikeSimRunAll.CorrTRecNo ...
    %             i*ones(1,sum(indSelCorrT))];
    %         spikeSimRunAll.CorrTNonZeroGood = [spikeSimRunAll.CorrTNonZeroGood ...
    %             meanCorrTRun.meanGoodNZ(indSelCorrT)];
    %         spikeSimRewAll.CorrTNonZeroGood = [spikeSimRewAll.CorrTNonZeroGood ...
    %             meanCorrTRew.meanGoodNZ(indSelCorrT)];
    %         spikeSimCueAll.CorrTNonZeroGood = [spikeSimCueAll.CorrTNonZeroGood ...
    %             meanCorrTCue.meanGoodNZ(indSelCorrT)];
    %         
    %         spikeSimRunAll.CorrTGood = [spikeSimRunAll.CorrTGood ...
    %             meanCorrTRun.meanGood(indSelCorrT)];
    %         spikeSimRewAll.CorrTGood = [spikeSimRewAll.CorrTGood ...
    %             meanCorrTRew.meanGood(indSelCorrT)];
    %         spikeSimCueAll.CorrTGood = [spikeSimCueAll.CorrTGood ...
    %             meanCorrTCue.meanGood(indSelCorrT)];
    end
    
    if(recSel == 1)
        for i = 1:size(listRecordingsPassiveLickPath,1)
            path = listRecordingsPassiveLickPath(i,:);
            fileName = listRecordingsPassiveLickFileName(i,:);
            mazeSess = mazeSessionPassiveLick(i);
            fullPath = [path,fileName '_meanPopCorrT_msess'  num2str(mazeSess) '_Run' num2str(onlyRun) '_intT' ...
                num2str(intervalT) '.mat'];
            load(fullPath,'meanPopCorrTRun','meanPopCorrTRew','meanPopCorrTCue');
            
            fileNamePeakFR = [fileName '_PeakFR_msess' num2str(mazeSess) ...
                        '_RunOnset0.mat'];
            fullPath = [path fileNamePeakFR];
            if(exist(fullPath) == 0)
                disp(['The peak firing rate file does not exist. Please call ',...
                        'function "PeakFiringRate_Aligned" first.']);
                return;
            end
            load(fullPath,'pFRNonStimGoodStruct','pFRNonStimBadStruct');

            fileNameFW = [fileName '_FieldSpCorr_GoodTr_Run1.mat'];
            fullPath = [path fileNameFW];
            if(exist(fullPath) == 0)
                disp(['The field detection file does not exist. Please call ',...
                        'function "FieldDetection_GoodTr" first.']);
                return;
            end
            load(fullPath,'paramF'); 
            
            if(length(pFRNonStimGoodStruct.indLapList) >= paramF.minNumTr)
                popSimRunAll.CorrTGoodTask = [popSimRunAll.CorrTGoodTask ...
                    3];
                popSimRunAll.CorrTGoodRecNo = [popSimRunAll.CorrTGoodRecNo ...
                    i];
                popSimRunAll.CorrTGood = [popSimRunAll.CorrTGood ...
                    meanPopCorrTRun.meanGood];
                popSimRewAll.CorrTGood = [popSimRewAll.CorrTGood ...
                    meanPopCorrTRew.meanGood];
                popSimCueAll.CorrTGood = [popSimCueAll.CorrTGood ...
                    meanPopCorrTCue.meanGood];
            end
            
            popSimRunAll.CorrTTask = [popSimRunAll.CorrTTask ...
                    3];
            popSimRunAll.CorrTRecNo = [popSimRunAll.CorrTRecNo ...
                i];
            popSimRunAll.CorrT = [popSimRunAll.CorrT ...
                meanPopCorrTRun.mean];
            popSimRewAll.CorrT = [popSimRewAll.CorrT ...
                meanPopCorrTRew.mean];
            popSimCueAll.CorrT = [popSimCueAll.CorrT ...
                meanPopCorrTCue.mean];

            if(~isempty(pFRNonStimBadStruct) && length(pFRNonStimBadStruct.indLapList) >= paramF.minNumTr)
                popSimRunAll.CorrTBadTask = [popSimRunAll.CorrTBadTask ...
                    3];
                popSimRunAll.CorrTBadRecNo = [popSimRunAll.CorrTBadRecNo ...
                    i];
                popSimRunAll.CorrTBad = [popSimRunAll.CorrTBad ...
                    meanPopCorrTRun.meanBad];
                popSimRewAll.CorrTBad = [popSimRewAll.CorrTBad ...
                    meanPopCorrTRew.meanBad];
                popSimCueAll.CorrTBad = [popSimCueAll.CorrTBad ...
                    meanPopCorrTCue.meanBad];
            end

        %         path = listRecordingsActiveLickPath(i,:);
        %         fileName = listRecordingsActiveLickFileName(i,:);
        %         fullPath = [path,fileName, '_meanSpikesCorrDistAligned_Run' num2str(onlyRun) '_intD' ...
        %             num2str(intervalT) '.mat'];
        %         load(fullPath,'meanCorrDistRun','meanCorrDistRew','meanCorrDistCue');
        %         
        %         indSelCorrT = selNeuronsCorrD(path,fileName,onlyRun,intervalT,thrCorrD,minFR);
        %         spikeSimRunAll.CorrTNeuSel = [spikeSimRunAll.CorrTNeuSel ...
        %             find(indSelCorrT == 1)];
        %         spikeSimRunAll.CorrTRecNo = [spikeSimRunAll.CorrTRecNo ...
        %             i*ones(1,sum(indSelCorrT))];
        %         spikeSimRunAll.CorrTNonZeroGood = [spikeSimRunAll.CorrTNonZeroGood ...
        %             meanCorrTRun.meanGoodNZ(indSelCorrT)];
        %         spikeSimRewAll.CorrTNonZeroGood = [spikeSimRewAll.CorrTNonZeroGood ...
        %             meanCorrTRew.meanGoodNZ(indSelCorrT)];
        %         spikeSimCueAll.CorrTNonZeroGood = [spikeSimCueAll.CorrTNonZeroGood ...
        %             meanCorrTCue.meanGoodNZ(indSelCorrT)];
        %         
        %         spikeSimRunAll.CorrTGood = [spikeSimRunAll.CorrTGood ...
        %             meanCorrTRun.meanGood(indSelCorrT)];
        %         spikeSimRewAll.CorrTGood = [spikeSimRewAll.CorrTGood ...
        %             meanCorrTRew.meanGood(indSelCorrT)];
        %         spikeSimCueAll.CorrTGood = [spikeSimCueAll.CorrTGood ...
        %             meanCorrTCue.meanGood(indSelCorrT)];
        end
    end
    
    popSimRunAll.meanCorrTGood = mean(popSimRunAll.CorrTGood);
    popSimRewAll.meanCorrTGood = mean(popSimRewAll.CorrTGood);
    popSimCueAll.meanCorrTGood = mean(popSimCueAll.CorrTGood);
    
    popSimRunAll.meanCorrTBad = mean(popSimRunAll.CorrTBad);
    popSimRewAll.meanCorrTBad = mean(popSimRewAll.CorrTBad);
    popSimCueAll.meanCorrTBad = mean(popSimCueAll.CorrTBad);
    
    popSimRunAll.meanCorrT = mean(popSimRunAll.CorrT);
    popSimRewAll.meanCorrT = mean(popSimRewAll.CorrT);
    popSimCueAll.meanCorrT = mean(popSimCueAll.CorrT);
    
    popSimRunAll.pRS_CorrTGood_RR = ranksum(popSimRunAll.CorrTGood,...
        popSimRewAll.CorrTGood);
    popSimRunAll.pRS_CorrTGood_RC = ranksum(popSimRunAll.CorrTGood,...
        popSimCueAll.CorrTGood);
    popSimRunAll.pRS_CorrTGood_CR = ranksum(popSimRewAll.CorrTGood,...
        popSimCueAll.CorrTGood);
    
    popSimRunAll.pRS_CorrTBad_RR = ranksum(popSimRunAll.CorrTBad,...
        popSimRewAll.CorrTBad);
    popSimRunAll.pRS_CorrTBad_RC = ranksum(popSimRunAll.CorrTBad,...
        popSimCueAll.CorrTBad);
    popSimRunAll.pRS_CorrTBad_CR = ranksum(popSimRewAll.CorrTBad,...
        popSimCueAll.CorrTBad);
    
    popSimRunAll.pRS_CorrT_RR = ranksum(popSimRunAll.CorrT,...
        popSimRewAll.CorrT);
    popSimRunAll.pRS_CorrT_RC = ranksum(popSimRunAll.CorrT,...
        popSimCueAll.CorrT);
    popSimRunAll.pRS_CorrT_CR = ranksum(popSimRewAll.CorrT,...
        popSimCueAll.CorrT);
    
    popSimRunAll.pRS_CorrTGoodVsBad_Run = ranksum(popSimRunAll.CorrTGood,...
        popSimRunAll.CorrTBad);
    popSimCueAll.pRS_CorrTGoodVsBad_Cue = ranksum(popSimCueAll.CorrTGood,...
        popSimCueAll.CorrTBad);
    popSimRewAll.pRS_CorrTGoodVsBad_Rew = ranksum(popSimRewAll.CorrTGood,...
        popSimRewAll.CorrTBad);
    
    popSimRunAll.pRS_CorrTBadRunVsGoodCue = ranksum(popSimRunAll.CorrTBad,...
        popSimCueAll.CorrTGood);
    
    save(['Z:\Yingxue\DataAnalysisRaphi\PopCorrTAlignedActive_AllRec_Stat' strTmp '.mat'],...
        'popSimRunAll','popSimRewAll','popSimCueAll');
    
    plotSimCompxy(popSimCueAll.CorrT,...
        popSimRunAll.CorrT,...
        popSimCueAll.meanCorrT,...
        popSimRunAll.meanCorrT,...
        popSimRunAll.pRS_CorrT_RC,...
        'Pop. corr.',0.6);
    fileName1 = ['PopCorrTAligned_RunVsCue_AllRec' strTmp];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');
    
    plotSimCompxy(popSimCueAll.CorrTGood,...
        popSimRunAll.CorrTGood,...
        popSimCueAll.meanCorrTGood,...
        popSimRunAll.meanCorrTGood,...
        popSimRunAll.pRS_CorrTGood_RC,...
        'Pop. corr. good tr.',0.6);
    fileName1 = ['PopCorrTAligned_Good_RunVsCue_AllRec' strTmp];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');
    
    plotSimCompxy(popSimCueAll.CorrTBad,...
        popSimRunAll.CorrTBad,...
        popSimCueAll.meanCorrTBad,...
        popSimRunAll.meanCorrTBad,...
        popSimRunAll.pRS_CorrTBad_RC,...
        'Pop. corr. good tr.',0.6);
    fileName1 = ['PopCorrTAligned_Bad_RunVsCue_AllRec' strTmp];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');
    
    plotSimComp(popSimRunAll.CorrTGood,...
        popSimCueAll.CorrTGood,...
        popSimRewAll.CorrTGood,...
        popSimRunAll.meanCorrTGood,...
        popSimCueAll.meanCorrTGood,...
        popSimRewAll.meanCorrTGood,...
        popSimRunAll.pRS_CorrTGood_RC,...
        popSimRunAll.pRS_CorrTGood_RR,...
        popSimRunAll.pRS_CorrTGood_CR,...
        'Pop. corr. good tr.',0.6);
    fileName1 = ['PopCorrTAligned_Good_RunVsCueVsRew_AllRec' strTmp];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');
    
    plotSimComp(popSimRunAll.CorrTBad,...
        popSimCueAll.CorrTBad,...
        popSimRewAll.CorrTBad,...
        popSimRunAll.meanCorrTBad,...
        popSimCueAll.meanCorrTBad,...
        popSimRewAll.meanCorrTBad,...
        popSimRunAll.pRS_CorrTBad_RC,...
        popSimRunAll.pRS_CorrTBad_RR,...
        popSimRunAll.pRS_CorrTBad_CR,...
        'Pop. corr. bad tr.',0.6);
    fileName1 = ['PopCorrTAligned_Bad_RunVsCueVsRew_AllRec' strTmp];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');
    
    plotSimComp(popSimRunAll.CorrT,...
        popSimCueAll.CorrT,...
        popSimRewAll.CorrT,...
        popSimRunAll.meanCorrT,...
        popSimCueAll.meanCorrT,...
        popSimRewAll.meanCorrT,...
        popSimRunAll.pRS_CorrT_RC,...
        popSimRunAll.pRS_CorrT_RR,...
        popSimRunAll.pRS_CorrT_CR,...
        'Pop. corr.',0.6);
    fileName1 = ['PopCorrTAligned_All_RunVsCueVsRew_AllRec' strTmp];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');
    
    plotSimComp(popSimRunAll.CorrTGood,...
        popSimCueAll.CorrTGood,...
        popSimRunAll.CorrTBad,...
        popSimRunAll.meanCorrTGood,...
        popSimCueAll.meanCorrTGood,...
        popSimRunAll.meanCorrTBad,...
        popSimRunAll.pRS_CorrTGood_RC,...
        popSimRunAll.pRS_CorrTGoodVsBad_Run,...
        popSimRunAll.pRS_CorrTBadRunVsGoodCue,...
        'Pop. corr.',0.6);
    fileName1 = ['PopCorrTAligned_All_RunGoodVsCueGoodVsRunBad_AllRec' strTmp];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');
    
end

function plotSimComp(x,y,z,xm,ym,zm,pxy,pxz,pyz,yl,maxXY)
    [figNew,pos] = CreateFig();
    set(0,'Units','pixels')
    set(figure(figNew),'OuterPosition',...
            [pos(1) pos(2) 280 280])

    h = bar([1 2 3],[xm,ym,zm]);
    set(h,'FaceColor',[0.7 0.7 0.9],'EdgeColor',[0.5 0.5 0.5]);
    if(isempty(maxXY))
        maxXY = max([x,y z]);
    end
    hold on;
    h = plot(ones(1,length(x)),x,'k.');
    set(h,'MarkerSize',11);
    h = plot(2*ones(1,length(y)),y,'k.');
    set(h,'MarkerSize',11);
    h = plot(3*ones(1,length(z)),z,'k.');
    set(h,'MarkerSize',11);
    set(gca,'YLim',[0 maxXY]);
    title(['p12 = ' num2str(pxy) ' p13 = ' num2str(pxz) ' p23 = ' num2str(pyz)]);
    ylabel(yl)
end

function plotSimCompxy(x,y,xm,ym,pxy,yl,maxXY)
    [figNew,pos] = CreateFig();
    set(0,'Units','pixels')
    set(figure(figNew),'OuterPosition',...
            [pos(1) pos(2) 280 280])

    h = bar([1 2],[xm,ym]);
    set(h,'FaceColor',[0.7 0.7 0.9],'EdgeColor',[0.5 0.5 0.5]);
    if(isempty(maxXY))
        maxXY = max([x,y]);
    end
    hold on;
    h = plot(ones(1,length(x)),x,'k.');
    set(h,'MarkerSize',11);
    h = plot(2*ones(1,length(y)),y,'k.');
    set(h,'MarkerSize',11);
    set(gca,'YLim',[0 maxXY]);
    title(['p12 = ' num2str(pxy) ]);
    ylabel(yl)
end