function spikeTrainSimilarityAllRecALPL(onlyRun)
% compare the spike train similarity for different alignment conditions over all the recordings 

    GlobalConst;
    intervalT = 20;
    intervalD = 1800;
    tc = 500; % ms
    cost = 2/(tc/1000*sampleFq);
    
    thrCorrT = -1; %0.03;
    
    RecordingList;
    
    load('Z:\Yingxue\DataAnalysisRaphi\SpikeCorrTAlignedAL.mat','spikeSimRunAll',...
        'spikeSimRewAll','spikeSimCueAll');
    
    spikeSimRunAL = spikeSimRunAll;
    spikeSimRewAL = spikeSimRewAll;
    spikeSimCueAL = spikeSimCueAll;
    
    load('Z:\Yingxue\DataAnalysisRaphi\SpikeCorrTAlignedPL.mat','spikeSimRunAll',...
        'spikeSimRewAll','spikeSimCueAll');
    
    spikeSimRunAll.CorrTNeuSelGood = [spikeSimRunAL.CorrTNeuSelGood spikeSimRunAll.CorrTNeuSelGood];
    spikeSimRunAll.CorrTRecNoGood = [spikeSimRunAL.CorrTRecNoGood spikeSimRunAll.CorrTRecNoGood];
    spikeSimRunAll.CorrTNonZeroGood = [spikeSimRunAL.CorrTNonZeroGood spikeSimRunAll.CorrTNonZeroGood];
    spikeSimRewAll.CorrTNonZeroGood = [spikeSimRewAL.CorrTNonZeroGood spikeSimRewAll.CorrTNonZeroGood];
    spikeSimCueAll.CorrTNonZeroGood = [spikeSimCueAL.CorrTNonZeroGood spikeSimCueAll.CorrTNonZeroGood];
    
    spikeSimRunAll.CorrTGood = [spikeSimRunAL.CorrTGood spikeSimRunAll.CorrTGood];
    spikeSimRewAll.CorrTGood = [spikeSimRewAL.CorrTGood spikeSimRewAll.CorrTGood];
    spikeSimCueAll.CorrTGood = [spikeSimCueAL.CorrTGood spikeSimCueAll.CorrTGood];
    
    spikeSimRunAll.CorrTNeuSel = [spikeSimRunAL.CorrTNeuSel spikeSimRunAll.CorrTNeuSel];
    spikeSimRunAll.CorrTRecNo = [spikeSimRunAL.CorrTRecNo spikeSimRunAll.CorrTRecNo];
    spikeSimRunAll.CorrTNonZero = [spikeSimRunAL.CorrTNonZero spikeSimRunAll.CorrTNonZero];
    spikeSimRewAll.CorrTNonZero = [spikeSimRewAL.CorrTNonZero spikeSimRewAll.CorrTNonZero];
    spikeSimCueAll.CorrTNonZero = [spikeSimCueAL.CorrTNonZero spikeSimCueAll.CorrTNonZero];
    
    spikeSimRunAll.CorrT = [spikeSimRunAL.CorrT spikeSimRunAll.CorrT];
    spikeSimRewAll.CorrT = [spikeSimRewAL.CorrT spikeSimRewAll.CorrT];
    spikeSimCueAll.CorrT = [spikeSimCueAL.CorrT spikeSimCueAll.CorrT];
    
    spikeSimRunAll.pRS_CorrTNonZeroGood_RR = ranksum(spikeSimRunAll.CorrTNonZeroGood,...
        spikeSimRewAll.CorrTNonZeroGood);
    spikeSimRunAll.pRS_CorrTNonZeroGood_RC = ranksum(spikeSimRunAll.CorrTNonZeroGood,...
        spikeSimCueAll.CorrTNonZeroGood);
    
    spikeSimRunAll.pRS_CorrTGood_RR = ranksum(spikeSimRunAll.CorrTGood,...
        spikeSimRewAll.CorrTGood);
    spikeSimRunAll.pRS_CorrTGood_RC = ranksum(spikeSimRunAll.CorrTGood,...
        spikeSimCueAll.CorrTGood);
    
    spikeSimRunAll.pRS_CorrTNonZero_RR = ranksum(spikeSimRunAll.CorrTNonZero,...
        spikeSimRewAll.CorrTNonZero);
    spikeSimRunAll.pRS_CorrTNonZero_RC = ranksum(spikeSimRunAll.CorrTNonZero,...
        spikeSimCueAll.CorrTNonZero);
    
    spikeSimRunAll.pRS_CorrT_RR = ranksum(spikeSimRunAll.CorrT,...
        spikeSimRewAll.CorrT);
    spikeSimRunAll.pRS_CorrT_RC = ranksum(spikeSimRunAll.CorrT,...
        spikeSimCueAll.CorrT);
    
    save('Z:\Yingxue\DataAnalysisRaphi\SpikeCorrTAlignedALPL.mat','spikeSimRunAll',...
        'spikeSimRewAll','spikeSimCueAll');
    
    plotSimComp(spikeSimRunAll.CorrTNonZeroGood,...
        spikeSimRewAll.CorrTNonZeroGood,...
        spikeSimRunAll.pRS_CorrTNonZeroGood_RR,...
        'Spike corr. NZgood aligned to run onset',...
        'Spike corr. NZgood aligned to reward onset');
    fileName1 = ['SpikeCorrTAligned_NZGood_RunVsRew_AllRecALPL'];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');

    plotSimComp(spikeSimRunAll.CorrTNonZeroGood,...
        spikeSimCueAll.CorrTNonZeroGood,...
        spikeSimRunAll.pRS_CorrTNonZeroGood_RC,...
        'Spike corr. NZgood aligned to run onset',...
        'Spike corr. NZgood aligned to cue onset');
    fileName1 = ['SpikeCorrTAligned_NZGood_RunVsCue_AllRecALPL'];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');
    
    plotSimComp(spikeSimRunAll.CorrTGood,...
        spikeSimRewAll.CorrTGood,...
        spikeSimRunAll.pRS_CorrTGood_RR,...
        'Spike corr. good aligned to run onset',...
        'Spike corr. good aligned to reward onset');
    fileName1 = ['SpikeCorrTAligned_Good_RunVsRew_AllRecALPL'];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');

    plotSimComp(spikeSimRunAll.CorrTGood,...
        spikeSimCueAll.CorrTGood,...
        spikeSimRunAll.pRS_CorrTGood_RC,...
        'Spike corr. good aligned to run onset',...
        'Spike corr. good aligned to cue onset');
    fileName1 = ['SpikeCorrTAligned_Good_RunVsCue_AllRecALPL'];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');
    
    plotSimComp(spikeSimRunAll.CorrTNonZero,...
        spikeSimRewAll.CorrTNonZero,...
        spikeSimRunAll.pRS_CorrTNonZero_RR,...
        'Spike corr. NZgood aligned to run onset',...
        'Spike corr. NZgood aligned to reward onset');
    fileName1 = ['SpikeCorrTAligned_NZ_RunVsRew_AllRecALPL'];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');

    plotSimComp(spikeSimRunAll.CorrTNonZero,...
        spikeSimCueAll.CorrTNonZero,...
        spikeSimRunAll.pRS_CorrTNonZero_RC,...
        'Spike corr. NZgood aligned to run onset',...
        'Spike corr. NZgood aligned to cue onset');
    fileName1 = ['SpikeCorrTAligned_NZ_RunVsCue_AllRecALPL'];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');
    
    plotSimComp(spikeSimRunAll.CorrT,...
        spikeSimRewAll.CorrT,...
        spikeSimRunAll.pRS_CorrT_RR,...
        'Spike corr. good aligned to run onset',...
        'Spike corr. good aligned to reward onset');
    fileName1 = ['SpikeCorrTAligned_RunVsRew_AllRecALPL'];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');

    plotSimComp(spikeSimRunAll.CorrT,...
        spikeSimCueAll.CorrT,...
        spikeSimRunAll.pRS_CorrT_RC,...
        'Spike corr. good aligned to run onset',...
        'Spike corr. good aligned to cue onset');
    fileName1 = ['SpikeCorrTAligned_RunVsCue_AllRecALPL'];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');
    
    colorSel= 0;
    plotBoxPlot(spikeSimRunAll.CorrTGood,...
        spikeSimCueAll.CorrTGood,'Spike corr. good',...
        'SpikeCorrTAligned_Good_RunVsCue_AllRecALPLBox',...
        'Z:\Yingxue\DataAnalysisRaphi\',[],spikeSimRunAll.pRS_CorrTGood_RC,colorSel);
    
    plotBoxPlot(spikeSimRunAll.CorrTNonZeroGood,...
        spikeSimCueAll.CorrTNonZeroGood,'Spike corr. good (nonzero)',...
        'SpikeCorrTAligned_NZGood_RunVsCue_AllRecALPLBox',...
        'Z:\Yingxue\DataAnalysisRaphi\',[],spikeSimRunAll.pRS_CorrTNonZeroGood_RC,colorSel);
    
    plotBoxPlot(spikeSimRunAll.CorrT,...
        spikeSimCueAll.CorrT,'Spike corr.',...
        'SpikeCorrTAligned_RunVsCue_AllRecALPLBox',...
        'Z:\Yingxue\DataAnalysisRaphi\',[],spikeSimRunAll.pRS_CorrT_RC,colorSel);
    
    plotBoxPlot(spikeSimRunAll.CorrTNonZero,...
        spikeSimCueAll.CorrTNonZero,'Spike corr.(nonzero)',...
        'SpikeCorrTAligned_NZ_RunVsCue_AllRecALPLBox',...
        'Z:\Yingxue\DataAnalysisRaphi\',[],spikeSimRunAll.pRS_CorrTNonZero_RC,colorSel);
end

function plotSimComp(x,y,p,xl,yl)
    [figNew,pos] = CreateFig();
    set(0,'Units','pixels')
    set(figure(figNew),'OuterPosition',...
            [pos(1) pos(2) 280 280])
    h = plot(x,y,'.');
    set(h,'MarkerSize',4,'Color',[0.5 0.5 0.9]);
    maxXY = max([x,y]);
    hold on;
    h = plot([0 maxXY],[0 maxXY],'r:');
    set(h,'LineWidth',1);
    set(gca,'XLim',[0 maxXY],'YLim',[0 maxXY]);
    title(['p = ' num2str(p)]);
    xlabel(xl)
    ylabel(yl)
end

function plotBoxPlot(x1,x2,yl,fn,pathAnal,ylimit,p,colorSel)
    [figNew,pos] = CreateFig();
    set(0,'Units','pixels')
    set(figure(figNew),'OuterPosition',...
            [pos(1) pos(2) 200 400])
    if(colorSel == 0)
        colorArr = [163 207 98;...
                234 131 114]/255;
    elseif(colorSel == 1)            
        colorArr = [234 131 114;...
                116 53 61]/255;
    else        
        colorArr = [163 207 98;... 
            63 79 37]/255;
    end
    x = [x1';x2'];
    g = [repmat({'C1'},length(x1),1);...
        repmat({'C2'},length(x2),1)];
    boxplot(x,g,'Notch','on','Widths',0.3,'Symbol','');
    h = findobj(gca,'Tag','Box');
    for j = 1:length(h)
        patch(get(h(j),'XData'),get(h(j),'YData'),colorArr(j,:),'FaceAlpha',0.5);
    end
    if(~isempty(ylimit))
        set(gca,'YLim',ylimit);
    end
    ylabel(yl);
    title(['p = ' num2str(p)]);
    
    fileName1 = [pathAnal fn];
    saveas(gcf,fileName1);
    print('-painters', '-dpdf', fileName1, '-r600')
end