function spikeTrainCorrDistAllRecPassive(onlyRun)
% compare the spike train correlation over distance for different alignment conditions over all the recordings 

    GlobalConst;
    intervalT = 20;
    intervalD = 1800;
    tc = 500; % ms
    cost = 2/(tc/1000*sampleFq);
    
    thrCorrD = -1; %0.03;
    
    RecordingList;
    
    spikeSimRunAll.CorrDNonZeroGood = [];
    spikeSimRunAll.CorrDGood = [];
    spikeSimRunAll.CorrDNonZeroGoodMeanPerRec = [];
    spikeSimRunAll.CorrDGoodMeanPerRec = [];
    spikeSimRunAll.CorrDNeuSelGood = [];
    spikeSimRunAll.CorrDRecNoGood = [];
    spikeSimRunAll.CorrDNonZero = [];
    spikeSimRunAll.CorrD = [];
    spikeSimRunAll.CorrDNonZeroMeanPerRec = [];
    spikeSimRunAll.CorrDMeanPerRec = [];
    spikeSimRunAll.CorrDNeuSel = [];
    spikeSimRunAll.CorrDRecNo = [];
        
    spikeSimRewAll.CorrDNonZeroGood = [];
    spikeSimRewAll.CorrDGood = [];
    spikeSimRewAll.CorrDNonZeroGoodMeanPerRec = [];
    spikeSimRewAll.CorrDGoodMeanPerRec = [];
    spikeSimRewAll.CorrDNonZero = [];
    spikeSimRewAll.CorrD = [];
    spikeSimRewAll.CorrDNonZeroMeanPerRec = [];
    spikeSimRewAll.CorrDMeanPerRec = [];
    
    spikeSimCueAll.CorrDNonZeroGood = [];
    spikeSimCueAll.CorrDGood = [];
    spikeSimCueAll.CorrDNonZeroGoodMeanPerRec = [];
    spikeSimCueAll.CorrDGoodMeanPerRec = [];
    spikeSimCueAll.CorrDNonZero = [];
    spikeSimCueAll.CorrD = [];
    spikeSimCueAll.CorrDNonZeroMeanPerRec = [];
    spikeSimCueAll.CorrDMeanPerRec = [];
    for i = 1:size(listRecordingsPassiveLickPath,1)
        path = listRecordingsPassiveLickPath(i,:);
        fileName = listRecordingsPassiveLickFileName(i,:);
        mazeSess = mazeSessionPassiveLick(i);
        fullPath = [path,fileName, '_meanSpikesCorrDistAligned_msess' num2str(mazeSess) '_Run' num2str(onlyRun) '_intD' ...
            num2str(intervalD) '.mat'];
        load(fullPath,'meanCorrDistRun','meanCorrDistRew','meanCorrDistCue');
        
        fileNameInfo = [fileName '_Info.mat'];
        fullPath = [path fileNameInfo];
        if(exist(fullPath) == 0)
            disp('_Info.mat file does not exist.');
            return;
        end
        load(fullPath,'autoCorr','beh'); 
        
        fullPathFR = [fileName '_FR_Run' num2str(onlyRun) '.mat'];
        fullPath = [path fullPathFR];
        if(exist(fullPath) == 0)
            disp('_FR_Run.mat file does not exist.');
            return;
        end
        load(fullPath,'mFRStruct','mFRStructSess'); 
        if(length(beh.mazeSessAll) > 1)
            mFR = mFRStructSess{mazeSess};
        else
            mFR = mFRStruct;
        end
        
        indNeuSel = mFR.mFR > minFR & mFR.mFR < maxFR &...
                    autoCorr.isPyrneuron == 1;
                
        indSelCorrD = meanCorrDistRun.meanGoodNZ > thrCorrD;
        indSelCorrD = indNeuSel & indSelCorrD;
        spikeSimRunAll.CorrDNeuSelGood = [spikeSimRunAll.CorrDNeuSelGood ...
            find(indSelCorrD == 1)];
        spikeSimRunAll.CorrDRecNoGood = [spikeSimRunAll.CorrDRecNoGood ...
            i*ones(1,sum(indSelCorrD))];
        spikeSimRunAll.CorrDNonZeroGood = [spikeSimRunAll.CorrDNonZeroGood ...
            meanCorrDistRun.meanGoodNZ(indSelCorrD)];
        spikeSimRewAll.CorrDNonZeroGood = [spikeSimRewAll.CorrDNonZeroGood ...
            meanCorrDistRew.meanGoodNZ(indSelCorrD)];
        spikeSimCueAll.CorrDNonZeroGood = [spikeSimCueAll.CorrDNonZeroGood ...
            meanCorrDistCue.meanGoodNZ(indSelCorrD)];
        
        spikeSimRunAll.CorrDNonZeroGoodMeanPerRec = [...
            spikeSimRunAll.CorrDNonZeroGoodMeanPerRec ...
            mean(meanCorrDistRun.meanGoodNZ(indSelCorrD))];
        spikeSimRewAll.CorrDNonZeroGoodMeanPerRec = [...
            spikeSimRewAll.CorrDNonZeroGoodMeanPerRec ...
            mean(meanCorrDistRew.meanGoodNZ(indSelCorrD))];
        spikeSimCueAll.CorrDNonZeroGoodMeanPerRec = [...
            spikeSimCueAll.CorrDNonZeroGoodMeanPerRec ...
            mean(meanCorrDistCue.meanGoodNZ(indSelCorrD))];
        
        spikeSimRunAll.CorrDGood = [spikeSimRunAll.CorrDGood ...
            meanCorrDistRun.meanGood(indSelCorrD)];
        spikeSimRewAll.CorrDGood = [spikeSimRewAll.CorrDGood ...
            meanCorrDistRew.meanGood(indSelCorrD)];
        spikeSimCueAll.CorrDGood = [spikeSimCueAll.CorrDGood ...
            meanCorrDistCue.meanGood(indSelCorrD)];
        
        spikeSimRunAll.CorrDGoodMeanPerRec = [...
            spikeSimRunAll.CorrDGoodMeanPerRec ...
            mean(meanCorrDistRun.meanGood(indSelCorrD))];
        spikeSimRewAll.CorrDGoodMeanPerRec = [...
            spikeSimRewAll.CorrDGoodMeanPerRec ...
            mean(meanCorrDistRew.meanGood(indSelCorrD))];
        spikeSimCueAll.CorrDGoodMeanPerRec = [...
            spikeSimCueAll.CorrDGoodMeanPerRec ...
            mean(meanCorrDistCue.meanGood(indSelCorrD))];
        
        indSelCorrD = meanCorrDistRun.meanNZ > thrCorrD;
        indSelCorrD = indNeuSel & indSelCorrD;
        spikeSimRunAll.CorrDNeuSel = [spikeSimRunAll.CorrDNeuSel ...
            find(indSelCorrD == 1)];
        spikeSimRunAll.CorrDRecNo = [spikeSimRunAll.CorrDRecNo ...
            i*ones(1,sum(indSelCorrD))];
        spikeSimRunAll.CorrDNonZero = [spikeSimRunAll.CorrDNonZero ...
            meanCorrDistRun.meanNZ(indSelCorrD)];
        spikeSimRewAll.CorrDNonZero = [spikeSimRewAll.CorrDNonZero ...
            meanCorrDistRew.meanNZ(indSelCorrD)];
        spikeSimCueAll.CorrDNonZero = [spikeSimCueAll.CorrDNonZero ...
            meanCorrDistCue.meanNZ(indSelCorrD)];
                
        spikeSimRunAll.CorrDNonZeroMeanPerRec = [...
            spikeSimRunAll.CorrDNonZeroMeanPerRec ...
            mean(meanCorrDistRun.meanNZ(indSelCorrD))];
        spikeSimRewAll.CorrDNonZeroMeanPerRec = [...
            spikeSimRewAll.CorrDNonZeroMeanPerRec ...
            mean(meanCorrDistRew.meanNZ(indSelCorrD))];
        spikeSimCueAll.CorrDNonZeroMeanPerRec = [...
            spikeSimCueAll.CorrDNonZeroMeanPerRec ...
            mean(meanCorrDistCue.meanNZ(indSelCorrD))];
        
        spikeSimRunAll.CorrD = [spikeSimRunAll.CorrD ...
            meanCorrDistRun.mean(indSelCorrD)];
        spikeSimRewAll.CorrD = [spikeSimRewAll.CorrD ...
            meanCorrDistRew.mean(indSelCorrD)];
        spikeSimCueAll.CorrD = [spikeSimCueAll.CorrD ...
            meanCorrDistCue.mean(indSelCorrD)];
        
        spikeSimRunAll.CorrDMeanPerRec = [...
            spikeSimRunAll.CorrDMeanPerRec ...
            mean(meanCorrDistRun.mean(indSelCorrD))];
        spikeSimRewAll.CorrDMeanPerRec = [...
            spikeSimRewAll.CorrDMeanPerRec ...
            mean(meanCorrDistRew.mean(indSelCorrD))];
        spikeSimCueAll.CorrDMeanPerRec = [...
            spikeSimCueAll.CorrDMeanPerRec ...
            mean(meanCorrDistCue.mean(indSelCorrD))];
    end
    
    spikeSimRunAll.pRS_CorrDNonZeroGood_RR = ranksum(spikeSimRunAll.CorrDNonZeroGood,...
        spikeSimRewAll.CorrDNonZeroGood);
    spikeSimRunAll.pRS_CorrDNonZeroGood_RC = ranksum(spikeSimRunAll.CorrDNonZeroGood,...
        spikeSimCueAll.CorrDNonZeroGood);
    
    spikeSimRunAll.pRS_CorrDGood_RR = ranksum(spikeSimRunAll.CorrDGood,...
        spikeSimRewAll.CorrDGood);
    spikeSimRunAll.pRS_CorrDGood_RC = ranksum(spikeSimRunAll.CorrDGood,...
        spikeSimCueAll.CorrDGood);
    
    spikeSimRunAll.pRS_CorrDNonZero_RR = ranksum(spikeSimRunAll.CorrDNonZero,...
        spikeSimRewAll.CorrDNonZero);
    spikeSimRunAll.pRS_CorrDNonZero_RC = ranksum(spikeSimRunAll.CorrDNonZero,...
        spikeSimCueAll.CorrDNonZero);
    
    spikeSimRunAll.pRS_CorrD_RR = ranksum(spikeSimRunAll.CorrD,...
        spikeSimRewAll.CorrD);
    spikeSimRunAll.pRS_CorrD_RC = ranksum(spikeSimRunAll.CorrD,...
        spikeSimCueAll.CorrD);
    
    save('Z:\Yingxue\DataAnalysisRaphi\SpikeCorrDAlignedPL.mat','spikeSimRunAll',...
        'spikeSimRewAll','spikeSimCueAll');
    
    plotSimComp(spikeSimRunAll.CorrDNonZeroGood,...
        spikeSimRewAll.CorrDNonZeroGood,...
        spikeSimRunAll.pRS_CorrDNonZeroGood_RR,...
        'Spike corr. NZgood aligned to run onset',...
        'Spike corr. NZgood aligned to reward onset');
    fileName1 = ['SpikeCorrDAligned_NZGood_RunVsRew_ALRec'];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');

    plotSimComp(spikeSimRunAll.CorrDNonZeroGood,...
        spikeSimCueAll.CorrDNonZeroGood,...
        spikeSimRunAll.pRS_CorrDNonZeroGood_RC,...
        'Spike corr. NZgood aligned to run onset',...
        'Spike corr. NZgood aligned to cue onset');
    fileName1 = ['SpikeCorrDAligned_NZGood_RunVsCue_ALRec'];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');
    
    plotSimComp(spikeSimRunAll.CorrDGood,...
        spikeSimRewAll.CorrDGood,...
        spikeSimRunAll.pRS_CorrDGood_RR,...
        'Spike corr. good aligned to run onset',...
        'Spike corr. good aligned to reward onset');
    fileName1 = ['SpikeCorrDAligned_Good_RunVsRew_ALRec'];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');

    plotSimComp(spikeSimRunAll.CorrDGood,...
        spikeSimCueAll.CorrDGood,...
        spikeSimRunAll.pRS_CorrDGood_RC,...
        'Spike corr. good aligned to run onset',...
        'Spike corr. good aligned to cue onset');
    fileName1 = ['SpikeCorrDAligned_Good_RunVsCue_ALRec'];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');
    
    plotSimComp(spikeSimRunAll.CorrDNonZero,...
        spikeSimRewAll.CorrDNonZero,...
        spikeSimRunAll.pRS_CorrDNonZero_RR,...
        'Spike corr. NZ aligned to run onset',...
        'Spike corr. NZ aligned to reward onset');
    fileName1 = ['SpikeCorrDAligned_NZ_RunVsRew_ALRec'];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');

    plotSimComp(spikeSimRunAll.CorrDNonZero,...
        spikeSimCueAll.CorrDNonZero,...
        spikeSimRunAll.pRS_CorrDNonZero_RC,...
        'Spike corr. NZ aligned to run onset',...
        'Spike corr. NZ aligned to cue onset');
    fileName1 = ['SpikeCorrDAligned_NZ_RunVsCue_ALRec'];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');
    
    plotSimComp(spikeSimRunAll.CorrD,...
        spikeSimRewAll.CorrD,...
        spikeSimRunAll.pRS_CorrD_RR,...
        'Spike corr. aligned to run onset',...
        'Spike corr. aligned to reward onset');
    fileName1 = ['SpikeCorrDAligned_RunVsRew_ALRec'];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');

    plotSimComp(spikeSimRunAll.CorrD,...
        spikeSimCueAll.CorrD,...
        spikeSimRunAll.pRS_CorrD_RC,...
        'Spike corr. aligned to run onset',...
        'Spike corr. aligned to cue onset');
    fileName1 = ['SpikeCorrDAligned_RunVsCue_ALRec'];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');
    
    colorSel= 0;
    plotBoxPlot(spikeSimRunAll.CorrDGood,...
        spikeSimCueAll.CorrDGood,'Spike corr. good',...
        'SpikeCorrDAligned_Good_RunVsCue_ALRecBox',...
        'Z:\Yingxue\DataAnalysisRaphi\',[],spikeSimRunAll.pRS_CorrDGood_RC,colorSel);
    
    plotBoxPlot(spikeSimRunAll.CorrDNonZeroGood,...
        spikeSimCueAll.CorrDNonZeroGood,'Spike corr. good (nonzero)',...
        'SpikeCorrDAligned_NZGood_RunVsCue_ALRecBox',...
        'Z:\Yingxue\DataAnalysisRaphi\',[],spikeSimRunAll.pRS_CorrDNonZeroGood_RC,colorSel);
    
    plotBoxPlot(spikeSimRunAll.CorrD,...
        spikeSimCueAll.CorrD,'Spike corr.',...
        'SpikeCorrDAligned_RunVsCue_ALRecBox',...
        'Z:\Yingxue\DataAnalysisRaphi\',[],spikeSimRunAll.pRS_CorrD_RC,colorSel);
    
    plotBoxPlot(spikeSimRunAll.CorrDNonZero,...
        spikeSimCueAll.CorrDNonZero,'Spike corr.(nonzero)',...
        'SpikeCorrDAligned_NZ_RunVsCue_ALRecBox',...
        'Z:\Yingxue\DataAnalysisRaphi\',[],spikeSimRunAll.pRS_CorrDNonZero_RC,colorSel);
end

function plotSimComp(x,y,p,xl,yl)
    [figNew,pos] = CreateFig();
    set(0,'Units','pixels')
    set(figure(figNew),'OuterPosition',...
            [pos(1) pos(2) 280 280])
    h = plot(x,y,'.');
    set(h,'MarkerSize',4,'Color',[0.5 0.5 0.9]);
    maxXY = max([x,y]);
    hold on;
    h = plot([0 maxXY],[0 maxXY],'r:');
    set(h,'LineWidth',1);
    set(gca,'XLim',[0 maxXY],'YLim',[0 maxXY]);
    title(['p = ' num2str(p)]);
    xlabel(xl)
    ylabel(yl)
end

function plotBoxPlot(x1,x2,yl,fn,pathAnal,ylimit,p,colorSel)
    [figNew,pos] = CreateFig();
    set(0,'Units','pixels')
    set(figure(figNew),'OuterPosition',...
            [pos(1) pos(2) 200 400])
    if(colorSel == 0)
        colorArr = [163 207 98;...
                234 131 114]/255;
    elseif(colorSel == 1)            
        colorArr = [234 131 114;...
                116 53 61]/255;
    else        
        colorArr = [163 207 98;... 
            63 79 37]/255;
    end
    x = [x1';x2'];
    g = [repmat({'C1'},length(x1),1);...
        repmat({'C2'},length(x2),1)];
    boxplot(x,g,'Notch','on','Widths',0.3,'Symbol','');
    h = findobj(gca,'Tag','Box');
    for j = 1:length(h)
        patch(get(h(j),'XData'),get(h(j),'YData'),colorArr(j,:),'FaceAlpha',0.5);
    end
    if(~isempty(ylimit))
        set(gca,'YLim',ylimit);
    end
    ylabel(yl);
    title(['p = ' num2str(p)]);
    
    fileName1 = [pathAnal fn];
    saveas(gcf,fileName1);
    print('-painters', '-dpdf', fileName1, '-r600')
end