function spikeTrainCorrDistAllRecCompExp(onlyRun)
% compare the spike train similarity for different experiments 
% (passive no cue, passive licking, and active licking) over all the recordings 

    GlobalConst;
    intervalT = 20;
    intervalD = 1800;
    tc = 500; % ms
    cost = 2/(tc/1000*sampleFq);
    
    thrCorrT = -1;
    
    RecordingList;
    
    load('Z:\Yingxue\DataAnalysisRaphi\SpikeCorrDAlignedAL.mat','spikeSimRunAll',...
        'spikeSimRewAll','spikeSimCueAll');
    
    spikeSimActiveRunAll = spikeSimRunAll;
    spikeSimActiveRewAll = spikeSimRewAll;
    spikeSimActiveCueAll = spikeSimCueAll;
    
    load('Z:\Yingxue\DataAnalysisRaphi\SpikeCorrDAlignedPL.mat','spikeSimRunAll',...
        'spikeSimRewAll','spikeSimCueAll');
    
    spikeSimPassiveRunAll = spikeSimRunAll;
    spikeSimPassiveRewAll = spikeSimRewAll;
    spikeSimPassiveCueAll = spikeSimCueAll;
    
    load('Z:\Yingxue\DataAnalysisRaphi\SpikeCorrDAlignedPNC.mat','spikeSimRunAll',...
        'spikeSimRewAll','spikeSimCueAll');
    
    spikeSimPassiveNoCueRunAll = spikeSimRunAll;
    spikeSimPassiveNoCueRewAll = spikeSimRewAll;
    spikeSimPassiveNoCueCueAll = spikeSimCueAll;
    
    spikeSimRunAll = [];
    spikeSimCueAll = [];
    %% statistics for aligning to run onset
    spikeSimRunAll.pRS_CorrDNonZeroGood_PNCvsP = ranksum(spikeSimPassiveNoCueRunAll.CorrDNonZeroGood,...
        spikeSimPassiveRunAll.CorrDNonZeroGood);
    spikeSimRunAll.pRS_CorrDNonZeroGood_PNCvsA = ranksum(spikeSimPassiveNoCueRunAll.CorrDNonZeroGood,...
        spikeSimActiveRunAll.CorrDNonZeroGood);
    spikeSimRunAll.pRS_CorrDNonZeroGood_PvsA = ranksum(spikeSimPassiveRunAll.CorrDNonZeroGood,...
        spikeSimActiveRunAll.CorrDNonZeroGood);
    
    spikeSimRunAll.pRS_CorrDGood_PNCvsP = ranksum(spikeSimPassiveNoCueRunAll.CorrDGood,...
        spikeSimPassiveRunAll.CorrDGood);
    spikeSimRunAll.pRS_CorrDGood_PNCvsA = ranksum(spikeSimPassiveNoCueRunAll.CorrDGood,...
        spikeSimActiveRunAll.CorrDGood);
    spikeSimRunAll.pRS_CorrDGood_PvsA = ranksum(spikeSimPassiveRunAll.CorrDGood,...
        spikeSimActiveRunAll.CorrDGood);
    
    [~,spikeSimRunAll.pKS_CorrDNonZeroGood_PNCvsP] = kstest2(spikeSimPassiveNoCueRunAll.CorrDNonZeroGood,...
        spikeSimPassiveRunAll.CorrDNonZeroGood);
    [~,spikeSimRunAll.pKS_CorrDNonZeroGood_PNCvsA] = kstest2(spikeSimPassiveNoCueRunAll.CorrDNonZeroGood,...
        spikeSimActiveRunAll.CorrDNonZeroGood);
    [~,spikeSimRunAll.pKS_CorrDNonZeroGood_PvsA] = kstest2(spikeSimPassiveRunAll.CorrDNonZeroGood,...
        spikeSimActiveRunAll.CorrDNonZeroGood);
    
    [~,spikeSimRunAll.pKS_CorrDGood_PNCvsP] = kstest2(spikeSimPassiveNoCueRunAll.CorrDGood,...
        spikeSimPassiveRunAll.CorrDGood);
    [~,spikeSimRunAll.pKS_CorrDGood_PNCvsA] = kstest2(spikeSimPassiveNoCueRunAll.CorrDGood,...
        spikeSimActiveRunAll.CorrDGood);
    [~,spikeSimRunAll.pKS_CorrDGood_PvsA] = kstest2(spikeSimPassiveRunAll.CorrDGood,...
        spikeSimActiveRunAll.CorrDGood);
    
    spikeSimRunAll.pRS_CorrDNonZero_PNCvsP = ranksum(spikeSimPassiveNoCueRunAll.CorrDNonZero,...
        spikeSimPassiveRunAll.CorrDNonZero);
    spikeSimRunAll.pRS_CorrDNonZero_PNCvsA = ranksum(spikeSimPassiveNoCueRunAll.CorrDNonZero,...
        spikeSimActiveRunAll.CorrDNonZero);
    spikeSimRunAll.pRS_CorrDNonZero_PvsA = ranksum(spikeSimPassiveRunAll.CorrDNonZero,...
        spikeSimActiveRunAll.CorrDNonZero);
        
    spikeSimRunAll.pRS_CorrD_PNCvsP = ranksum(spikeSimPassiveNoCueRunAll.CorrD,...
        spikeSimPassiveRunAll.CorrD);
    spikeSimRunAll.pRS_CorrD_PNCvsA = ranksum(spikeSimPassiveNoCueRunAll.CorrD,...
        spikeSimActiveRunAll.CorrD);
    spikeSimRunAll.pRS_CorrD_PvsA = ranksum(spikeSimPassiveRunAll.CorrD,...
        spikeSimActiveRunAll.CorrD);
    
    [~,spikeSimRunAll.pKS_CorrDNonZero_PNCvsP] = kstest2(spikeSimPassiveNoCueRunAll.CorrDNonZero,...
        spikeSimPassiveRunAll.CorrDNonZero);
    [~,spikeSimRunAll.pKS_CorrDNonZero_PNCvsA] = kstest2(spikeSimPassiveNoCueRunAll.CorrDNonZero,...
        spikeSimActiveRunAll.CorrDNonZero);
    [~,spikeSimRunAll.pKS_CorrDNonZero_PvsA] = kstest2(spikeSimPassiveRunAll.CorrDNonZero,...
        spikeSimActiveRunAll.CorrDNonZero);
    
    [~,spikeSimRunAll.pKS_CorrD_PNCvsP] = kstest2(spikeSimPassiveNoCueRunAll.CorrD,...
        spikeSimPassiveRunAll.CorrD);
    [~,spikeSimRunAll.pKS_CorrD_PNCvsA] = kstest2(spikeSimPassiveNoCueRunAll.CorrD,...
        spikeSimActiveRunAll.CorrD);
    [~,spikeSimRunAll.pKS_CorrD_PvsA] = kstest2(spikeSimPassiveRunAll.CorrD,...
        spikeSimActiveRunAll.CorrD);
    
    %% statistics for aligning to cue
    spikeSimCueAll.pRS_CorrDNonZeroGood_PNCvsP = ranksum(spikeSimPassiveNoCueCueAll.CorrDNonZeroGood,...
        spikeSimPassiveCueAll.CorrDNonZeroGood);
    spikeSimCueAll.pRS_CorrDNonZeroGood_PNCvsA = ranksum(spikeSimPassiveNoCueCueAll.CorrDNonZeroGood,...
        spikeSimActiveCueAll.CorrDNonZeroGood);
    spikeSimCueAll.pRS_CorrDNonZeroGood_PvsA = ranksum(spikeSimPassiveCueAll.CorrDNonZeroGood,...
        spikeSimActiveCueAll.CorrDNonZeroGood);
    
    spikeSimCueAll.pRS_CorrDGood_PNCvsP = ranksum(spikeSimPassiveNoCueCueAll.CorrDGood,...
        spikeSimPassiveCueAll.CorrDGood);
    spikeSimCueAll.pRS_CorrDGood_PNCvsA = ranksum(spikeSimPassiveNoCueCueAll.CorrDGood,...
        spikeSimActiveCueAll.CorrDGood);
    spikeSimCueAll.pRS_CorrDGood_PvsA = ranksum(spikeSimPassiveCueAll.CorrDGood,...
        spikeSimActiveCueAll.CorrDGood);
    
    [~,spikeSimCueAll.pKS_CorrDNonZeroGood_PNCvsP] = kstest2(spikeSimPassiveNoCueCueAll.CorrDNonZeroGood,...
        spikeSimPassiveCueAll.CorrDNonZeroGood);
    [~,spikeSimCueAll.pKS_CorrDNonZeroGood_PNCvsA] = kstest2(spikeSimPassiveNoCueCueAll.CorrDNonZeroGood,...
        spikeSimActiveCueAll.CorrDNonZeroGood);
    [~,spikeSimCueAll.pKS_CorrDNonZeroGood_PvsA] = kstest2(spikeSimPassiveCueAll.CorrDNonZeroGood,...
        spikeSimActiveCueAll.CorrDNonZeroGood);
    
    [~,spikeSimCueAll.pKS_CorrDGood_PNCvsP] = kstest2(spikeSimPassiveNoCueCueAll.CorrDGood,...
        spikeSimPassiveCueAll.CorrDGood);
    [~,spikeSimCueAll.pKS_CorrDGood_PNCvsA] = kstest2(spikeSimPassiveNoCueCueAll.CorrDGood,...
        spikeSimActiveCueAll.CorrDGood);
    [~,spikeSimCueAll.pKS_CorrDGood_PvsA] = kstest2(spikeSimPassiveCueAll.CorrDGood,...
        spikeSimActiveCueAll.CorrDGood);
        
    spikeSimCueAll.pRS_CorrDNonZero_PNCvsP = ranksum(spikeSimPassiveNoCueCueAll.CorrDNonZero,...
        spikeSimPassiveCueAll.CorrDNonZero);
    spikeSimCueAll.pRS_CorrDNonZero_PNCvsA = ranksum(spikeSimPassiveNoCueCueAll.CorrDNonZero,...
        spikeSimActiveCueAll.CorrDNonZero);
    spikeSimCueAll.pRS_CorrDNonZero_PvsA = ranksum(spikeSimPassiveCueAll.CorrDNonZero,...
        spikeSimActiveCueAll.CorrDNonZero);
    
    spikeSimCueAll.pRS_CorrD_PNCvsP = ranksum(spikeSimPassiveNoCueCueAll.CorrD,...
        spikeSimPassiveCueAll.CorrD);
    spikeSimCueAll.pRS_CorrD_PNCvsA = ranksum(spikeSimPassiveNoCueCueAll.CorrD,...
        spikeSimActiveCueAll.CorrD);
    spikeSimCueAll.pRS_CorrD_PvsA = ranksum(spikeSimPassiveCueAll.CorrD,...
        spikeSimActiveCueAll.CorrD);
    
    [~,spikeSimCueAll.pKS_CorrDNonZero_PNCvsP] = kstest2(spikeSimPassiveNoCueCueAll.CorrDNonZero,...
        spikeSimPassiveCueAll.CorrDNonZero);
    [~,spikeSimCueAll.pKS_CorrDNonZero_PNCvsA] = kstest2(spikeSimPassiveNoCueCueAll.CorrDNonZero,...
        spikeSimActiveCueAll.CorrDNonZero);
    [~,spikeSimCueAll.pKS_CorrDNonZero_PvsA] = kstest2(spikeSimPassiveCueAll.CorrDNonZero,...
        spikeSimActiveCueAll.CorrDNonZero);
    
    [~,spikeSimCueAll.pKS_CorrD_PNCvsP] = kstest2(spikeSimPassiveNoCueCueAll.CorrD,...
        spikeSimPassiveCueAll.CorrD);
    [~,spikeSimCueAll.pKS_CorrD_PNCvsA] = kstest2(spikeSimPassiveNoCueCueAll.CorrD,...
        spikeSimActiveCueAll.CorrD);
    [~,spikeSimCueAll.pKS_CorrD_PvsA] = kstest2(spikeSimPassiveCueAll.CorrD,...
        spikeSimActiveCueAll.CorrD);
    
    save('Z:\Yingxue\DataAnalysisRaphi\SpikeCorrDAligned_AllRec_AllCond.mat',...
        'spikeSimRunAll','spikeSimCueAll');
    
    %% plot the distribution aligned to run onset
    maxVal = max([spikeSimPassiveNoCueRunAll.CorrDGood,spikeSimPassiveRunAll.CorrDGood,spikeSimActiveRunAll.CorrDGood]);
    minVal = min([spikeSimPassiveNoCueRunAll.CorrDGood,spikeSimPassiveRunAll.CorrDGood,spikeSimActiveRunAll.CorrDGood]);
    xbins = minVal-0.01:0.01:maxVal+0.01;
    countPNC = hist(spikeSimPassiveNoCueRunAll.CorrDGood,xbins)/length(spikeSimPassiveNoCueRunAll.CorrDGood);
    countP = hist(spikeSimPassiveRunAll.CorrDGood,xbins)/length(spikeSimPassiveRunAll.CorrDGood);
    countA = hist(spikeSimActiveRunAll.CorrDGood,xbins)/length(spikeSimActiveRunAll.CorrDGood);
    
    plotSimComp(xbins,countPNC,countP,countA,...
        spikeSimRunAll.pKS_CorrDGood_PNCvsP,spikeSimRunAll.pKS_CorrDGood_PNCvsA,...
        spikeSimRunAll.pRS_CorrDGood_PvsA,...
        'Spike CorrD. good aligned to run onset',...
        'Count');
    fileName1 = ['SpikeCorrDAlignedRun_Good_AllRec_AllCond_Distr'];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');

    maxVal = max([spikeSimPassiveNoCueRunAll.CorrDNonZeroGood,spikeSimPassiveRunAll.CorrDNonZeroGood,spikeSimActiveRunAll.CorrDNonZeroGood]);
    minVal = min([spikeSimPassiveNoCueRunAll.CorrDNonZeroGood,spikeSimPassiveRunAll.CorrDNonZeroGood,spikeSimActiveRunAll.CorrDNonZeroGood]);
    xbins = minVal-0.01:0.01:maxVal+0.01;
    countPNC = hist(spikeSimPassiveNoCueRunAll.CorrDNonZeroGood,xbins)/length(spikeSimPassiveNoCueRunAll.CorrDNonZeroGood);
    countP = hist(spikeSimPassiveRunAll.CorrDNonZeroGood,xbins)/length(spikeSimPassiveRunAll.CorrDNonZeroGood);
    countA = hist(spikeSimActiveRunAll.CorrDNonZeroGood,xbins)/length(spikeSimActiveRunAll.CorrDNonZeroGood);
    
    plotSimComp(xbins,countPNC,countP,countA,...
        spikeSimRunAll.pKS_CorrDNonZeroGood_PNCvsP,spikeSimRunAll.pKS_CorrDNonZeroGood_PNCvsA,...
        spikeSimRunAll.pRS_CorrDNonZeroGood_PvsA,...
        'Spike CorrD. NZgood aligned to run onset',...
        'Count');
    fileName1 = ['SpikeCorrDAlignedRun_NZGood_AllRec_AllCond_Distr'];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');
    
    maxVal = max([spikeSimPassiveNoCueRunAll.CorrD,spikeSimPassiveRunAll.CorrD,spikeSimActiveRunAll.CorrD]);
    minVal = min([spikeSimPassiveNoCueRunAll.CorrD,spikeSimPassiveRunAll.CorrD,spikeSimActiveRunAll.CorrD]);
    xbins = minVal-0.01:0.01:maxVal+0.01;
    countPNC = hist(spikeSimPassiveNoCueRunAll.CorrD,xbins)/length(spikeSimPassiveNoCueRunAll.CorrD);
    countP = hist(spikeSimPassiveRunAll.CorrD,xbins)/length(spikeSimPassiveRunAll.CorrD);
    countA = hist(spikeSimActiveRunAll.CorrD,xbins)/length(spikeSimActiveRunAll.CorrD);
    
    plotSimComp(xbins,countPNC,countP,countA,...
        spikeSimRunAll.pKS_CorrD_PNCvsP,spikeSimRunAll.pKS_CorrD_PNCvsA,...
        spikeSimRunAll.pRS_CorrD_PvsA,...
        'Spike CorrD. aligned to run onset',...
        'Count');
    fileName1 = ['SpikeCorrDAlignedRun_AllRec_AllCond_Distr'];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');

    maxVal = max([spikeSimPassiveNoCueRunAll.CorrDNonZero,spikeSimPassiveRunAll.CorrDNonZero,spikeSimActiveRunAll.CorrDNonZero]);
    minVal = min([spikeSimPassiveNoCueRunAll.CorrDNonZero,spikeSimPassiveRunAll.CorrDNonZero,spikeSimActiveRunAll.CorrDNonZero]);
    xbins = minVal-0.01:0.01:maxVal+0.01;
    countPNC = hist(spikeSimPassiveNoCueRunAll.CorrDNonZero,xbins)/length(spikeSimPassiveNoCueRunAll.CorrDNonZero);
    countP = hist(spikeSimPassiveRunAll.CorrDNonZero,xbins)/length(spikeSimPassiveRunAll.CorrDNonZero);
    countA = hist(spikeSimActiveRunAll.CorrDNonZero,xbins)/length(spikeSimActiveRunAll.CorrDNonZero);
    
    plotSimComp(xbins,countPNC,countP,countA,...
        spikeSimRunAll.pKS_CorrDNonZero_PNCvsP,spikeSimRunAll.pKS_CorrDNonZero_PNCvsA,...
        spikeSimRunAll.pRS_CorrDNonZero_PvsA,...
        'Spike CorrD. NZ aligned to run onset',...
        'Count');
    fileName1 = ['SpikeCorrDAlignedRun_NZ_AllRec_AllCond_Distr'];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');
    
    plotBars(spikeSimPassiveNoCueRunAll.CorrDGoodMeanPerRec,spikeSimActiveRunAll.CorrDGoodMeanPerRec,...
        [mean(spikeSimPassiveNoCueRunAll.CorrDGood),mean(spikeSimActiveRunAll.CorrDGood)],...
        [std(spikeSimPassiveNoCueRunAll.CorrDGood)/sqrt(length(spikeSimPassiveNoCueRunAll.CorrDGood)),...
        std(spikeSimActiveRunAll.CorrDGood)/sqrt(length(spikeSimActiveRunAll.CorrDGood))],...
        '','Spike corrT. good aligned to run', ['p=' num2str(spikeSimRunAll.pRS_CorrDGood_PNCvsA)],...
        'Z:\Yingxue\DataAnalysisRaphi\','SpikeCorrDAlignedRun_Good_AllRec_PNCVsAL')
    
    plotBars(spikeSimPassiveNoCueRunAll.CorrDNonZeroGoodMeanPerRec,spikeSimActiveRunAll.CorrDNonZeroGoodMeanPerRec,...
        [mean(spikeSimPassiveNoCueRunAll.CorrDNonZeroGood),mean(spikeSimActiveRunAll.CorrDNonZeroGood)],...
        [std(spikeSimPassiveNoCueRunAll.CorrDNonZeroGood)/sqrt(length(spikeSimPassiveNoCueRunAll.CorrDNonZeroGood)),...
        std(spikeSimActiveRunAll.CorrDNonZeroGood)/sqrt(length(spikeSimActiveRunAll.CorrDNonZeroGood))],...
        '','Spike corrT. NZgood aligned to run', ['p=' num2str(spikeSimRunAll.pRS_CorrDNonZeroGood_PNCvsA)],...
        'Z:\Yingxue\DataAnalysisRaphi\','SpikeCorrDAlignedRun_NZGood_AllRec_PNCVsAL')
    
    plotBars(spikeSimPassiveNoCueRunAll.CorrDMeanPerRec,spikeSimActiveRunAll.CorrDMeanPerRec,...
        [mean(spikeSimPassiveNoCueRunAll.CorrD),mean(spikeSimActiveRunAll.CorrD)],...
        [std(spikeSimPassiveNoCueRunAll.CorrD)/sqrt(length(spikeSimPassiveNoCueRunAll.CorrD)),...
        std(spikeSimActiveRunAll.CorrD)/sqrt(length(spikeSimActiveRunAll.CorrD))],...
        '','Spike corrT. aligned to run', ['p=' num2str(spikeSimRunAll.pRS_CorrD_PNCvsA)],...
        'Z:\Yingxue\DataAnalysisRaphi\','SpikeCorrDAlignedRun_AllRec_PNCVsAL')
    
    plotBars(spikeSimPassiveNoCueRunAll.CorrDNonZeroMeanPerRec,spikeSimActiveRunAll.CorrDNonZeroMeanPerRec,...
        [mean(spikeSimPassiveNoCueRunAll.CorrDNonZero),mean(spikeSimActiveRunAll.CorrDNonZero)],...
        [std(spikeSimPassiveNoCueRunAll.CorrDNonZero)/sqrt(length(spikeSimPassiveNoCueRunAll.CorrDNonZero)),...
        std(spikeSimActiveRunAll.CorrDNonZero)/sqrt(length(spikeSimActiveRunAll.CorrDNonZero))],...
        '','Spike corrT. NZ aligned to run', ['p=' num2str(spikeSimRunAll.pRS_CorrDNonZero_PNCvsA)],...
        'Z:\Yingxue\DataAnalysisRaphi\','SpikeCorrDAlignedRun_NZ_AllRec_PNCVsAL')
    
    %% plot the distribution aligned to cue
    maxVal = max([spikeSimPassiveNoCueCueAll.CorrDGood,spikeSimPassiveCueAll.CorrDGood,spikeSimActiveCueAll.CorrDGood]);
    minVal = min([spikeSimPassiveNoCueCueAll.CorrDGood,spikeSimPassiveCueAll.CorrDGood,spikeSimActiveCueAll.CorrDGood]);
    xbins = minVal-0.01:0.01:maxVal+0.01;
    countPNC = hist(spikeSimPassiveNoCueCueAll.CorrDGood,xbins)/length(spikeSimPassiveNoCueCueAll.CorrDGood);
    countP = hist(spikeSimPassiveCueAll.CorrDGood,xbins)/length(spikeSimPassiveCueAll.CorrDGood);
    countA = hist(spikeSimActiveCueAll.CorrDGood,xbins)/length(spikeSimActiveCueAll.CorrDGood);
    
    plotSimComp(xbins,countPNC,countP,countA,...
        spikeSimCueAll.pKS_CorrDGood_PNCvsP,spikeSimCueAll.pKS_CorrDGood_PNCvsA,...
        spikeSimCueAll.pRS_CorrDGood_PvsA,...
        'Spike CorrD. good aligned to cue onset',...
        'Count');
    fileName1 = ['SpikeCorrDAlignedCue_Good_AllRec_AllCond_Distr'];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');

    maxVal = max([spikeSimPassiveNoCueCueAll.CorrDNonZeroGood,spikeSimPassiveCueAll.CorrDNonZeroGood,spikeSimActiveCueAll.CorrDNonZeroGood]);
    minVal = min([spikeSimPassiveNoCueCueAll.CorrDNonZeroGood,spikeSimPassiveCueAll.CorrDNonZeroGood,spikeSimActiveCueAll.CorrDNonZeroGood]);
    xbins = minVal-0.01:0.01:maxVal+0.01;
    countPNC = hist(spikeSimPassiveNoCueCueAll.CorrDNonZeroGood,xbins)/length(spikeSimPassiveNoCueCueAll.CorrDNonZeroGood);
    countP = hist(spikeSimPassiveCueAll.CorrDNonZeroGood,xbins)/length(spikeSimPassiveCueAll.CorrDNonZeroGood);
    countA = hist(spikeSimActiveCueAll.CorrDNonZeroGood,xbins)/length(spikeSimActiveCueAll.CorrDNonZeroGood);
    
    plotSimComp(xbins,countPNC,countP,countA,...
        spikeSimCueAll.pKS_CorrDNonZeroGood_PNCvsP,spikeSimCueAll.pKS_CorrDNonZeroGood_PNCvsA,...
        spikeSimCueAll.pRS_CorrDNonZeroGood_PvsA,...
        'Spike CorrD. NZgood aligned to cue onset',...
        'Count');
    fileName1 = ['SpikeCorrDAlignedCue_NZGood_AllRec_AllCond_Distr'];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');
    
    maxVal = max([spikeSimPassiveNoCueCueAll.CorrD,spikeSimPassiveCueAll.CorrD,spikeSimActiveCueAll.CorrD]);
    minVal = min([spikeSimPassiveNoCueCueAll.CorrD,spikeSimPassiveCueAll.CorrD,spikeSimActiveCueAll.CorrD]);
    xbins = minVal-0.01:0.01:maxVal+0.01;
    countPNC = hist(spikeSimPassiveNoCueCueAll.CorrD,xbins)/length(spikeSimPassiveNoCueCueAll.CorrD);
    countP = hist(spikeSimPassiveCueAll.CorrD,xbins)/length(spikeSimPassiveCueAll.CorrD);
    countA = hist(spikeSimActiveCueAll.CorrD,xbins)/length(spikeSimActiveCueAll.CorrD);
    
    plotSimComp(xbins,countPNC,countP,countA,...
        spikeSimCueAll.pKS_CorrD_PNCvsP,spikeSimCueAll.pKS_CorrD_PNCvsA,...
        spikeSimCueAll.pRS_CorrD_PvsA,...
        'Spike CorrD. aligned to cue onset',...
        'Count');
    fileName1 = ['SpikeCorrDAlignedCue_AllRec_AllCond_Distr'];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');

    maxVal = max([spikeSimPassiveNoCueCueAll.CorrDNonZero,spikeSimPassiveCueAll.CorrDNonZero,spikeSimActiveCueAll.CorrDNonZero]);
    minVal = min([spikeSimPassiveNoCueCueAll.CorrDNonZero,spikeSimPassiveCueAll.CorrDNonZero,spikeSimActiveCueAll.CorrDNonZero]);
    xbins = minVal-0.01:0.01:maxVal+0.01;
    countPNC = hist(spikeSimPassiveNoCueCueAll.CorrDNonZero,xbins)/length(spikeSimPassiveNoCueCueAll.CorrDNonZero);
    countP = hist(spikeSimPassiveCueAll.CorrDNonZero,xbins)/length(spikeSimPassiveCueAll.CorrDNonZero);
    countA = hist(spikeSimActiveCueAll.CorrDNonZero,xbins)/length(spikeSimActiveCueAll.CorrDNonZero);
    
    plotSimComp(xbins,countPNC,countP,countA,...
        spikeSimCueAll.pKS_CorrDNonZero_PNCvsP,spikeSimCueAll.pKS_CorrDNonZero_PNCvsA,...
        spikeSimCueAll.pRS_CorrDNonZero_PvsA,...
        'Spike CorrD. NZ aligned to cue onset',...
        'Count');
    fileName1 = ['SpikeCorrDAlignedCue_NZ_AllRec_AllCond_Distr'];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');
    
    plotBars(spikeSimPassiveNoCueCueAll.CorrDGoodMeanPerRec,spikeSimActiveCueAll.CorrDGoodMeanPerRec,...
        [mean(spikeSimPassiveNoCueCueAll.CorrDGood),mean(spikeSimActiveCueAll.CorrDGood)],...
        [std(spikeSimPassiveNoCueCueAll.CorrDGood)/sqrt(length(spikeSimPassiveNoCueCueAll.CorrDGood)),...
        std(spikeSimActiveCueAll.CorrDGood)/sqrt(length(spikeSimActiveCueAll.CorrDGood))],...
        '','Spike corrT. good aligned to cue', ['p=' num2str(spikeSimCueAll.pRS_CorrDGood_PNCvsA)],...
        'Z:\Yingxue\DataAnalysisRaphi\','SpikeCorrDAlignedCue_Good_AllRec_PNCVsAL')
    
    plotBars(spikeSimPassiveNoCueCueAll.CorrDNonZeroGoodMeanPerRec,spikeSimActiveCueAll.CorrDNonZeroGoodMeanPerRec,...
        [mean(spikeSimPassiveNoCueCueAll.CorrDNonZeroGood),mean(spikeSimActiveCueAll.CorrDNonZeroGood)],...
        [std(spikeSimPassiveNoCueCueAll.CorrDNonZeroGood)/sqrt(length(spikeSimPassiveNoCueCueAll.CorrDNonZeroGood)),...
        std(spikeSimActiveCueAll.CorrDNonZeroGood)/sqrt(length(spikeSimActiveCueAll.CorrDNonZeroGood))],...
        '','Spike corrT. NZgood aligned to cue', ['p=' num2str(spikeSimCueAll.pRS_CorrDNonZeroGood_PNCvsA)],...
        'Z:\Yingxue\DataAnalysisRaphi\','SpikeCorrDAlignedCue_NZGood_AllRec_PNCVsAL')
    
    plotBars(spikeSimPassiveNoCueCueAll.CorrDMeanPerRec,spikeSimActiveCueAll.CorrDMeanPerRec,...
        [mean(spikeSimPassiveNoCueCueAll.CorrD),mean(spikeSimActiveCueAll.CorrD)],...
        [std(spikeSimPassiveNoCueCueAll.CorrD)/sqrt(length(spikeSimPassiveNoCueCueAll.CorrD)),...
        std(spikeSimActiveCueAll.CorrD)/sqrt(length(spikeSimActiveCueAll.CorrD))],...
        '','Spike corrT. aligned to cue', ['p=' num2str(spikeSimCueAll.pRS_CorrD_PNCvsA)],...
        'Z:\Yingxue\DataAnalysisRaphi\','SpikeCorrDAlignedCue_AllRec_PNCVsAL')
    
    plotBars(spikeSimPassiveNoCueCueAll.CorrDNonZeroMeanPerRec,spikeSimActiveCueAll.CorrDNonZeroMeanPerRec,...
        [mean(spikeSimPassiveNoCueCueAll.CorrDNonZero),mean(spikeSimActiveCueAll.CorrDNonZero)],...
        [std(spikeSimPassiveNoCueCueAll.CorrDNonZero)/sqrt(length(spikeSimPassiveNoCueCueAll.CorrDNonZero)),...
        std(spikeSimActiveCueAll.CorrDNonZero)/sqrt(length(spikeSimActiveCueAll.CorrDNonZero))],...
        '','Spike corrT. NZ aligned to cue', ['p=' num2str(spikeSimCueAll.pRS_CorrDNonZero_PNCvsA)],...
        'Z:\Yingxue\DataAnalysisRaphi\','SpikeCorrDAlignedCue_NZ_AllRec_PNCVsAL')
    
end

function plotSimComp(a,x,y,z,pxy,pxz,pyz,xl,yl)
    [figNew,pos] = CreateFig();
    set(0,'Units','pixels')
    set(figure(figNew),'OuterPosition',...
            [pos(1) pos(2) 280 280])
    h = plot(a,x,'-');
    set(h,'LineWidth',2,'Color',[0.5 0.5 0.9]);
    hold on;
    h = plot(a,y,'-');
    set(h,'LineWidth',2,'Color',[0.9 0.5 0.5]);
    h = plot(a,z,'-');
    set(h,'LineWidth',2,'Color',[0.5 0.9 0.5]);
    set(gca,'XLim',[min(a) max(a)],'YLim',[0 max([x,y,z]+0.1)]);
    title(['p12 = ' num2str(pxy) ',p13 = ' num2str(pxz) ',p23 = ' num2str(pyz)]);
    xlabel(xl)
    ylabel(yl)
end

function plotBars(data1,data2,mean,std,x1,y1,t,pathAnal,fn)
    fig = figure;
    set(0,'Units','pixels') 
    set(figure(fig),'OuterPosition',...
        [500 500 210 280])
    fig.Renderer = 'Painters';
    
    h = bar([1,2],mean,0.5);
    set(h,'EdgeColor',[0.3 0.3 0.3],'FaceColor',[187 189 192]/255);
    hold
    
    h = errorbar([1,2],mean,std);
    set(h,'Marker','.','MarkerSize',0.1,'Color',[0 0 0],'LineStyle','none')
    
    h = plot(1+0.15*rand(1,length(data1)),data1,'o');
    set(h,'MarkerSize',3,'Color',[167 169 171]/255);
    
    h = plot(2+0.15*rand(1,length(data2)),data2,'o');
    set(h,'MarkerSize',3,'Color',[27 117 187]/255);
    set(gca,'XLim',[0.5 2.5],'YLim',[0 max([data1 data2])+0.01]);
    
    xlabel(x1);
    ylabel(y1);
    title(t);
    
    fileName1 = [pathAnal fn];
    saveas(gcf,fileName1);
    print('-painters', '-dpdf', fileName1, '-r600')
end