function spikeTrainCorrDistAllRec(onlyRun,recSel)
% compare the spike train correlation over distance for different alignment conditions over all the recordings 

    GlobalConst;
    intervalT = 20;
    intervalD = 1800;
    tc = 500; % ms
    cost = 2/(tc/1000*sampleFq);
    
    thrCorrD = -1; %0.03;
    
    RecordingList;
    
    if(recSel == 1)
        strTmp = '_ALPL';
    else
        strTmp = '_AL';
    end
    fileName = ['Z:\Yingxue\DataAnalysisRaphi\SpikeCorrDAligned' strTmp '.mat'];
    if(exist(fileName) ~= 0)
        load(fileName,'spikeSimRunAll','spikeSimRewAll','spikeSimCueAll');
    end
        
    spikeSimRunAll.CorrDNonZeroGood = [];
    spikeSimRunAll.CorrDGood = [];
    spikeSimRunAll.CorrDNonZeroGoodMeanPerRec = [];
    spikeSimRunAll.CorrDGoodMeanPerRec = [];
    spikeSimRunAll.CorrDNeuSelGood = [];
    spikeSimRunAll.CorrDRecNoGood = [];
    spikeSimRunAll.CorrDTaskGood = [];
    
    spikeSimRunAll.CorrDNonZeroBad = [];
    spikeSimRunAll.CorrDBad = [];
    spikeSimRunAll.CorrDNonZeroBadMeanPerRec = [];
    spikeSimRunAll.CorrDBadMeanPerRec = [];
    spikeSimRunAll.CorrDNeuSelBad = [];
    spikeSimRunAll.CorrDRecNoBad = [];
    spikeSimRunAll.CorrDTaskBad = [];
    
    spikeSimRunAll.CorrDNonZero = [];
    spikeSimRunAll.CorrD = [];
    spikeSimRunAll.CorrDNonZeroMeanPerRec = [];
    spikeSimRunAll.CorrDMeanPerRec = [];
    spikeSimRunAll.CorrDNeuSel = [];
    spikeSimRunAll.CorrDRecNo = [];
    spikeSimRunAll.CorrDTask = [];
        
    spikeSimRewAll.CorrDNonZeroGood = [];
    spikeSimRewAll.CorrDGood = [];
    spikeSimRewAll.CorrDNonZeroGoodMeanPerRec = [];
    spikeSimRewAll.CorrDGoodMeanPerRec = [];
    
    spikeSimRewAll.CorrDNonZeroBad = [];
    spikeSimRewAll.CorrDBad = [];
    spikeSimRewAll.CorrDNonZeroBadMeanPerRec = [];
    spikeSimRewAll.CorrDBadMeanPerRec = [];
    
    spikeSimRewAll.CorrDNonZero = [];
    spikeSimRewAll.CorrD = [];
    spikeSimRewAll.CorrDNonZeroMeanPerRec = [];
    spikeSimRewAll.CorrDMeanPerRec = [];
    
    spikeSimCueAll.CorrDNonZeroGood = [];
    spikeSimCueAll.CorrDGood = [];
    spikeSimCueAll.CorrDNonZeroGoodMeanPerRec = [];
    spikeSimCueAll.CorrDGoodMeanPerRec = [];
    
    spikeSimCueAll.CorrDNonZeroBad = [];
    spikeSimCueAll.CorrDBad = [];
    spikeSimCueAll.CorrDNonZeroBadMeanPerRec = [];
    spikeSimCueAll.CorrDBadMeanPerRec = [];
    
    spikeSimCueAll.CorrDNonZero = [];
    spikeSimCueAll.CorrD = [];
    spikeSimCueAll.CorrDNonZeroMeanPerRec = [];
    spikeSimCueAll.CorrDMeanPerRec = [];
    
    [spikeSimRunAll,spikeSimRewAll,spikeSimCueAll] = accumCorrD(...
        spikeSimRunAll,spikeSimRewAll,spikeSimCueAll,...
        listRecordingsActiveLickPath,listRecordingsActiveLickFileName,mazeSessionActiveLick,...
        onlyRun,intervalD,thrCorrD,2);
    
    if(recSel == 1)
        [spikeSimRunAll,spikeSimRewAll,spikeSimCueAll] = accumCorrD(...
            spikeSimRunAll,spikeSimRewAll,spikeSimCueAll,...
            listRecordingsPassiveLickPath,listRecordingsPassiveLickFileName,mazeSessionPassiveLick,...
            onlyRun,intervalD,thrCorrD,3);
    end
    
    spikeSimRunAll.pRS_CorrDNonZeroGood_RR = ranksum(spikeSimRunAll.CorrDNonZeroGood,...
        spikeSimRewAll.CorrDNonZeroGood);
    spikeSimRunAll.pRS_CorrDNonZeroGood_RC = ranksum(spikeSimRunAll.CorrDNonZeroGood,...
        spikeSimCueAll.CorrDNonZeroGood);
    
    spikeSimRunAll.pRS_CorrDGood_RR = ranksum(spikeSimRunAll.CorrDGood,...
        spikeSimRewAll.CorrDGood);
    spikeSimRunAll.pRS_CorrDGood_RC = ranksum(spikeSimRunAll.CorrDGood,...
        spikeSimCueAll.CorrDGood);
    
    spikeSimRunAll.pRS_CorrDNonZero_RR = ranksum(spikeSimRunAll.CorrDNonZero,...
        spikeSimRewAll.CorrDNonZero);
    spikeSimRunAll.pRS_CorrDNonZero_RC = ranksum(spikeSimRunAll.CorrDNonZero,...
        spikeSimCueAll.CorrDNonZero);
    
    spikeSimRunAll.pRS_CorrD_RR = ranksum(spikeSimRunAll.CorrD,...
        spikeSimRewAll.CorrD);
    spikeSimRunAll.pRS_CorrD_RC = ranksum(spikeSimRunAll.CorrD,...
        spikeSimCueAll.CorrD);
    
    spikeSimRunAll.pRS_CorrDBadRunVsGoodRunNonZero = ranksum(spikeSimRunAll.CorrDNonZeroBad,...
        spikeSimRunAll.CorrDNonZeroGood);
    spikeSimCueAll.pRS_CorrDBadCueVsGoodCueNonZero = ranksum(spikeSimCueAll.CorrDNonZeroBad,...
        spikeSimCueAll.CorrDNonZeroGood);
    spikeSimRewAll.pRS_CorrDBadRewVsGoodRewNonZero = ranksum(spikeSimRewAll.CorrDNonZeroBad,...
        spikeSimRewAll.CorrDNonZeroGood);
    
    spikeSimRunAll.pRS_CorrDBadRunVsGoodRun = ranksum(spikeSimRunAll.CorrDBad,...
        spikeSimRunAll.CorrDGood);
    spikeSimCueAll.pRS_CorrDBadCueVsGoodCue = ranksum(spikeSimCueAll.CorrDBad,...
        spikeSimCueAll.CorrDGood);
    spikeSimRewAll.pRS_CorrDBadRewVsGoodRew = ranksum(spikeSimRewAll.CorrDBad,...
        spikeSimRewAll.CorrDGood);
    
    spikeSimRunAll.pRS_CorrDBadRunVsGoodCue = ranksum(spikeSimRunAll.CorrDBad,...
        spikeSimCueAll.CorrDGood);
    
    save(['Z:\Yingxue\DataAnalysisRaphi\SpikeCorrDAligned' strTmp '.mat'],'spikeSimRunAll',...
        'spikeSimRewAll','spikeSimCueAll');
    
    plotSimComp(spikeSimRunAll.CorrDNonZeroGood,...
        spikeSimRewAll.CorrDNonZeroGood,...
        spikeSimRunAll.pRS_CorrDNonZeroGood_RR,...
        'Spike corr. NZgood aligned to run onset',...
        'Spike corr. NZgood aligned to reward onset');
    fileName1 = ['SpikeCorrDAligned_NZGood_RunVsRew' strTmp];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');

    plotSimComp(spikeSimRunAll.CorrDNonZeroGood,...
        spikeSimCueAll.CorrDNonZeroGood,...
        spikeSimRunAll.pRS_CorrDNonZeroGood_RC,...
        'Spike corr. NZgood aligned to run onset',...
        'Spike corr. NZgood aligned to cue onset');
    fileName1 = ['SpikeCorrDAligned_NZGood_RunVsCue' strTmp];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');
    
    plotSimComp(spikeSimRunAll.CorrDGood,...
        spikeSimRewAll.CorrDGood,...
        spikeSimRunAll.pRS_CorrDGood_RR,...
        'Spike corr. good aligned to run onset',...
        'Spike corr. good aligned to reward onset');
    fileName1 = ['SpikeCorrDAligned_Good_RunVsRew' strTmp];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');

    plotSimComp(spikeSimRunAll.CorrDGood,...
        spikeSimCueAll.CorrDGood,...
        spikeSimRunAll.pRS_CorrDGood_RC,...
        'Spike corr. good aligned to run onset',...
        'Spike corr. good aligned to cue onset');
    fileName1 = ['SpikeCorrDAligned_Good_RunVsCue' strTmp];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');
    
    plotSimComp(spikeSimRunAll.CorrDNonZero,...
        spikeSimRewAll.CorrDNonZero,...
        spikeSimRunAll.pRS_CorrDNonZero_RR,...
        'Spike corr. NZ aligned to run onset',...
        'Spike corr. NZ aligned to reward onset');
    fileName1 = ['SpikeCorrDAligned_NZ_RunVsRew' strTmp];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');

    plotSimComp(spikeSimRunAll.CorrDNonZero,...
        spikeSimCueAll.CorrDNonZero,...
        spikeSimRunAll.pRS_CorrDNonZero_RC,...
        'Spike corr. NZ aligned to run onset',...
        'Spike corr. NZ aligned to cue onset');
    fileName1 = ['SpikeCorrDAligned_NZ_RunVsCue' strTmp];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');
    
    plotSimComp(spikeSimRunAll.CorrD,...
        spikeSimRewAll.CorrD,...
        spikeSimRunAll.pRS_CorrD_RR,...
        'Spike corr. aligned to run onset',...
        'Spike corr. aligned to reward onset');
    fileName1 = ['SpikeCorrDAligned_RunVsRew' strTmp];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');

    plotSimComp(spikeSimRunAll.CorrD,...
        spikeSimCueAll.CorrD,...
        spikeSimRunAll.pRS_CorrD_RC,...
        'Spike corr. aligned to run onset',...
        'Spike corr. aligned to cue onset');
    fileName1 = ['SpikeCorrDAligned_RunVsCue' strTmp];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');
        
    colorSel= 0;
    plotBoxPlot(spikeSimRunAll.CorrDGood,...
        spikeSimCueAll.CorrDGood,'Spike corr. good',...
        ['SpikeCorrDAligned_Good_RunVsCueBox' strTmp],...
        'Z:\Yingxue\DataAnalysisRaphi\',[],spikeSimRunAll.pRS_CorrDGood_RC,colorSel);
    
    plotBoxPlot(spikeSimRunAll.CorrDNonZeroGood,...
        spikeSimCueAll.CorrDNonZeroGood,'Spike corr. good (nonzero)',...
        ['SpikeCorrDAligned_NZGood_RunVsCueBox' strTmp],...
        'Z:\Yingxue\DataAnalysisRaphi\',[],spikeSimRunAll.pRS_CorrDNonZeroGood_RC,colorSel);
    
    plotBoxPlot(spikeSimRunAll.CorrD,...
        spikeSimCueAll.CorrD,'Spike corr.',...
        ['SpikeCorrDAligned_RunVsCueBox' strTmp],...
        'Z:\Yingxue\DataAnalysisRaphi\',[],spikeSimRunAll.pRS_CorrD_RC,colorSel);
    
    plotBoxPlot(spikeSimRunAll.CorrDNonZero,...
        spikeSimCueAll.CorrDNonZero,'Spike corr.(nonzero)',...
        ['SpikeCorrDAligned_NZ_RunVsCue_Box' strTmp],...
        'Z:\Yingxue\DataAnalysisRaphi\',[],spikeSimRunAll.pRS_CorrDNonZero_RC,colorSel);
    
    plotBoxPlot(spikeSimCueAll.CorrDNonZeroBad,...
        spikeSimCueAll.CorrDNonZeroGood,'Spike corr.(nonzero)',...
        ['SpikeCorrDAligned_NZ_CueGoodVsBad_Box' strTmp],...
        'Z:\Yingxue\DataAnalysisRaphi\',[-0.2 0.5],spikeSimCueAll.pRS_CorrDBadCueVsGoodCueNonZero,colorSel);
    
    plotBoxPlot(spikeSimCueAll.CorrDBad,...
        spikeSimCueAll.CorrDGood,'Spike corr.',...
        ['SpikeCorrDAligned_CueGoodVsBad_Box' strTmp],...
        'Z:\Yingxue\DataAnalysisRaphi\',[-0.1 0.3],spikeSimCueAll.pRS_CorrDBadCueVsGoodCue,colorSel);
           
end

function [spikeSimRunAll,spikeSimRewAll,spikeSimCueAll] = accumCorrD(...
        spikeSimRunAll,spikeSimRewAll,spikeSimCueAll,...
        listRecordingsPath,listRecordingsFileName,mazeSession,...
        onlyRun,intervalD,thrCorrD,task)
    
    GlobalConst;
    
    for i = 1:size(listRecordingsPath,1)
        path = listRecordingsPath(i,:);
        fileName = listRecordingsFileName(i,:);
        mazeSess = mazeSession(i);
        fullPath = [path,fileName, '_meanSpikesCorrDistAligned_msess' num2str(mazeSess) '_Run' num2str(onlyRun) '_intD' ...
            num2str(intervalD) '.mat'];
        load(fullPath,'meanCorrDistRun','meanCorrDistRew','meanCorrDistCue');
        
        fileNameInfo = [fileName '_Info.mat'];
        fullPath = [path fileNameInfo];
        if(exist(fullPath) == 0)
            disp('_Info.mat file does not exist.');
            return;
        end
        load(fullPath,'autoCorr','beh'); 
        
        fullPathFR = [fileName '_FR_Run' num2str(onlyRun) '.mat'];
        fullPath = [path fullPathFR];
        if(exist(fullPath) == 0)
            disp('_FR_Run.mat file does not exist.');
            return;
        end
        load(fullPath,'mFRStruct','mFRStructSess'); 
        if(length(beh.mazeSessAll) > 1)
            mFR = mFRStructSess{mazeSess};
        else
            mFR = mFRStruct;
        end
        
        fileNamePeakFR = [fileName '_PeakFR_msess' num2str(mazeSess) ...
                        '_RunOnset0.mat'];
        fullPath = [path fileNamePeakFR];
        if(exist(fullPath) == 0)
            disp(['The peak firing rate file does not exist. Please call ',...
                    'function "PeakFiringRate_Aligned" first.']);
            return;
        end
        load(fullPath,'pFRNonStimGoodStruct','pFRNonStimBadStruct');
        
        fileNameFW = [fileName '_FieldSpCorr_GoodTr_Run1.mat'];
        fullPath = [path fileNameFW];
        if(exist(fullPath) == 0)
            disp(['The field detection file does not exist. Please call ',...
                    'function "FieldDetection_GoodTr" first.']);
            return;
        end
        load(fullPath,'paramF'); 
        
        indNeuSel = mFR.mFR > minFR & mFR.mFR < maxFR &...
                    autoCorr.isPyrneuron == 1;
          
        %% all trials
        indSelCorrD = meanCorrDistRun.meanNZ > thrCorrD;
        indSelCorrD = indNeuSel & indSelCorrD;
        spikeSimRunAll.CorrDNeuSel = [spikeSimRunAll.CorrDNeuSel ...
            find(indSelCorrD == 1)];
        spikeSimRunAll.CorrDRecNo = [spikeSimRunAll.CorrDRecNo ...
            i*ones(1,sum(indSelCorrD))];
        spikeSimRunAll.CorrDTask = [spikeSimRunAll.CorrDTask ...
            task*ones(1,sum(indSelCorrD))];
        spikeSimRunAll.CorrDNonZero = [spikeSimRunAll.CorrDNonZero ...
            meanCorrDistRun.meanNZ(indSelCorrD)];
        spikeSimRewAll.CorrDNonZero = [spikeSimRewAll.CorrDNonZero ...
            meanCorrDistRew.meanNZ(indSelCorrD)];
        spikeSimCueAll.CorrDNonZero = [spikeSimCueAll.CorrDNonZero ...
            meanCorrDistCue.meanNZ(indSelCorrD)];
                
        spikeSimRunAll.CorrDNonZeroMeanPerRec = [...
            spikeSimRunAll.CorrDNonZeroMeanPerRec ...
            mean(meanCorrDistRun.meanNZ(indSelCorrD))];
        spikeSimRewAll.CorrDNonZeroMeanPerRec = [...
            spikeSimRewAll.CorrDNonZeroMeanPerRec ...
            mean(meanCorrDistRew.meanNZ(indSelCorrD))];
        spikeSimCueAll.CorrDNonZeroMeanPerRec = [...
            spikeSimCueAll.CorrDNonZeroMeanPerRec ...
            mean(meanCorrDistCue.meanNZ(indSelCorrD))];
        
        spikeSimRunAll.CorrD = [spikeSimRunAll.CorrD ...
            meanCorrDistRun.mean(indSelCorrD)];
        spikeSimRewAll.CorrD = [spikeSimRewAll.CorrD ...
            meanCorrDistRew.mean(indSelCorrD)];
        spikeSimCueAll.CorrD = [spikeSimCueAll.CorrD ...
            meanCorrDistCue.mean(indSelCorrD)];
        
        spikeSimRunAll.CorrDMeanPerRec = [...
            spikeSimRunAll.CorrDMeanPerRec ...
            mean(meanCorrDistRun.mean(indSelCorrD))];
        spikeSimRewAll.CorrDMeanPerRec = [...
            spikeSimRewAll.CorrDMeanPerRec ...
            mean(meanCorrDistRew.mean(indSelCorrD))];
        spikeSimCueAll.CorrDMeanPerRec = [...
            spikeSimCueAll.CorrDMeanPerRec ...
            mean(meanCorrDistCue.mean(indSelCorrD))];
        
        %% good trials
        if(length(pFRNonStimGoodStruct.indLapList) >= paramF.minNumTr)
            spikeSimRunAll.CorrDNeuSelGood = [spikeSimRunAll.CorrDNeuSelGood ...
                find(indSelCorrD == 1)];
            spikeSimRunAll.CorrDRecNoGood = [spikeSimRunAll.CorrDRecNoGood ...
                i*ones(1,sum(indSelCorrD))];
            spikeSimRunAll.CorrDTaskGood = [spikeSimRunAll.CorrDTaskGood ...
                task*ones(1,sum(indSelCorrD))];
            spikeSimRunAll.CorrDNonZeroGood = [spikeSimRunAll.CorrDNonZeroGood ...
                meanCorrDistRun.meanGoodNZ(indSelCorrD)];
            spikeSimRewAll.CorrDNonZeroGood = [spikeSimRewAll.CorrDNonZeroGood ...
                meanCorrDistRew.meanGoodNZ(indSelCorrD)];
            spikeSimCueAll.CorrDNonZeroGood = [spikeSimCueAll.CorrDNonZeroGood ...
                meanCorrDistCue.meanGoodNZ(indSelCorrD)];

            spikeSimRunAll.CorrDNonZeroGoodMeanPerRec = [...
                spikeSimRunAll.CorrDNonZeroGoodMeanPerRec ...
                mean(meanCorrDistRun.meanGoodNZ(indSelCorrD))];
            spikeSimRewAll.CorrDNonZeroGoodMeanPerRec = [...
                spikeSimRewAll.CorrDNonZeroGoodMeanPerRec ...
                mean(meanCorrDistRew.meanGoodNZ(indSelCorrD))];
            spikeSimCueAll.CorrDNonZeroGoodMeanPerRec = [...
                spikeSimCueAll.CorrDNonZeroGoodMeanPerRec ...
                mean(meanCorrDistCue.meanGoodNZ(indSelCorrD))];

            spikeSimRunAll.CorrDGood = [spikeSimRunAll.CorrDGood ...
                meanCorrDistRun.meanGood(indSelCorrD)];
            spikeSimRewAll.CorrDGood = [spikeSimRewAll.CorrDGood ...
                meanCorrDistRew.meanGood(indSelCorrD)];
            spikeSimCueAll.CorrDGood = [spikeSimCueAll.CorrDGood ...
                meanCorrDistCue.meanGood(indSelCorrD)];

            spikeSimRunAll.CorrDGoodMeanPerRec = [...
                spikeSimRunAll.CorrDGoodMeanPerRec ...
                mean(meanCorrDistRun.meanGood(indSelCorrD))];
            spikeSimRewAll.CorrDGoodMeanPerRec = [...
                spikeSimRewAll.CorrDGoodMeanPerRec ...
                mean(meanCorrDistRew.meanGood(indSelCorrD))];
            spikeSimCueAll.CorrDGoodMeanPerRec = [...
                spikeSimCueAll.CorrDGoodMeanPerRec ...
                mean(meanCorrDistCue.meanGood(indSelCorrD))];
        end
        
        %% bad trials
        if(~isempty(pFRNonStimBadStruct) && ...
                length(pFRNonStimBadStruct.indLapList) >= paramF.minNumTr)
            spikeSimRunAll.CorrDNeuSelBad = [spikeSimRunAll.CorrDNeuSelBad ...
                find(indSelCorrD == 1)];
            spikeSimRunAll.CorrDRecNoBad = [spikeSimRunAll.CorrDRecNoBad ...
                i*ones(1,sum(indSelCorrD))];
            spikeSimRunAll.CorrDTaskBad = [spikeSimRunAll.CorrDTaskBad ...
                task*ones(1,sum(indSelCorrD))];
            spikeSimRunAll.CorrDNonZeroBad = [spikeSimRunAll.CorrDNonZeroBad ...
                meanCorrDistRun.meanBadNZ(indSelCorrD)];
            spikeSimRewAll.CorrDNonZeroBad = [spikeSimRewAll.CorrDNonZeroBad ...
                meanCorrDistRew.meanBadNZ(indSelCorrD)];
            spikeSimCueAll.CorrDNonZeroBad = [spikeSimCueAll.CorrDNonZeroBad ...
                meanCorrDistCue.meanBadNZ(indSelCorrD)];

            spikeSimRunAll.CorrDNonZeroBadMeanPerRec = [...
                spikeSimRunAll.CorrDNonZeroBadMeanPerRec ...
                mean(meanCorrDistRun.meanBadNZ(indSelCorrD))];
            spikeSimRewAll.CorrDNonZeroBadMeanPerRec = [...
                spikeSimRewAll.CorrDNonZeroBadMeanPerRec ...
                mean(meanCorrDistRew.meanBadNZ(indSelCorrD))];
            spikeSimCueAll.CorrDNonZeroBadMeanPerRec = [...
                spikeSimCueAll.CorrDNonZeroBadMeanPerRec ...
                mean(meanCorrDistCue.meanBadNZ(indSelCorrD))];

            spikeSimRunAll.CorrDBad = [spikeSimRunAll.CorrDBad ...
                meanCorrDistRun.meanBad(indSelCorrD)];
            spikeSimRewAll.CorrDBad = [spikeSimRewAll.CorrDBad ...
                meanCorrDistRew.meanBad(indSelCorrD)];
            spikeSimCueAll.CorrDBad = [spikeSimCueAll.CorrDBad ...
                meanCorrDistCue.meanBad(indSelCorrD)];

            spikeSimRunAll.CorrDBadMeanPerRec = [...
                spikeSimRunAll.CorrDBadMeanPerRec ...
                mean(meanCorrDistRun.meanBad(indSelCorrD))];
            spikeSimRewAll.CorrDBadMeanPerRec = [...
                spikeSimRewAll.CorrDBadMeanPerRec ...
                mean(meanCorrDistRew.meanBad(indSelCorrD))];
            spikeSimCueAll.CorrDBadMeanPerRec = [...
                spikeSimCueAll.CorrDBadMeanPerRec ...
                mean(meanCorrDistCue.meanBad(indSelCorrD))];
        end
        
    end
end

function plotSimComp(x,y,p,xl,yl)
    [figNew,pos] = CreateFig();
    set(0,'Units','pixels')
    set(figure(figNew),'OuterPosition',...
            [pos(1) pos(2) 280 280])
    h = plot(x,y,'.');
    set(h,'MarkerSize',4,'Color',[0.5 0.5 0.9]);
    maxXY = max([x,y]);
    hold on;
    h = plot([0 maxXY],[0 maxXY],'r:');
    set(h,'LineWidth',1);
    set(gca,'XLim',[0 maxXY],'YLim',[0 maxXY]);
    title(['p = ' num2str(p)]);
    xlabel(xl)
    ylabel(yl)
end

function plotBoxPlot3(x1,x2,x3,yl,fn,pathAnal,ylimit,p12,p13,p23,colorSel)
    [figNew,pos] = CreateFig();
    set(0,'Units','pixels')
    set(figure(figNew),'OuterPosition',...
            [pos(1) pos(2) 200 400])
    if(colorSel == 0)
        colorArr = [163 207 98;...
                234 131 114;...
                200 150 200]/255;
    elseif(colorSel == 1)            
        colorArr = [234 131 114;...
                116 53 61;...
                200 150 200]/255;
    else        
        colorArr = [163 207 98;... 
            63 79 37;...
            200 150 200]/255;
    end
    x = [x1';x2';x3'];
    g = [repmat({'C1'},length(x1),1);...
        repmat({'C2'},length(x2),1);...
        repmat({'C3'},length(x3),1)];
    boxplot(x,g,'Notch','on','Widths',0.3,'Symbol','');
    h = findobj(gca,'Tag','Box');
    for j = 1:length(h)
        patch(get(h(j),'XData'),get(h(j),'YData'),colorArr(j,:),'FaceAlpha',0.5);
    end
    if(~isempty(ylimit))
        set(gca,'YLim',ylimit);
    end
    ylabel(yl);
    title(['p12 = ' num2str(p12) ',p13 = ' num2str(p13) ',p23 = ' num2str(p23)]);
    
    fileName1 = [pathAnal fn];
    saveas(gcf,fileName1);
    print('-painters', '-dpdf', fileName1, '-r600')
end

function plotBoxPlot(x1,x2,yl,fn,pathAnal,ylimit,p,colorSel)
    [figNew,pos] = CreateFig();
    set(0,'Units','pixels')
    set(figure(figNew),'OuterPosition',...
            [pos(1) pos(2) 200 400])
    if(colorSel == 0)
        colorArr = [163 207 98;...
                234 131 114]/255;
    elseif(colorSel == 1)            
        colorArr = [234 131 114;...
                116 53 61]/255;
    else        
        colorArr = [163 207 98;... 
            63 79 37]/255;
    end
    x = [x1';x2'];
    g = [repmat({'C1'},length(x1),1);...
        repmat({'C2'},length(x2),1)];
    boxplot(x,g,'Notch','on','Widths',0.3,'Symbol','');
    h = findobj(gca,'Tag','Box');
    for j = 1:length(h)
        patch(get(h(j),'XData'),get(h(j),'YData'),colorArr(j,:),'FaceAlpha',0.5);
    end
    if(~isempty(ylimit))
        set(gca,'YLim',ylimit);
    end
    ylabel(yl);
    title(['p = ' num2str(p)]);
    
    fileName1 = [pathAnal fn];
    saveas(gcf,fileName1);
    print('-painters', '-dpdf', fileName1, '-r600')
end