function spikeTrainSimilarityAllRecCompExp(onlyRun)
% compare the spike train similarity for different experiments 
% (passive no cue, passive licking, and active licking) over all the recordings 

    GlobalConst;
    intervalT = 20;
    intervalD = 1800;
    tc = 500; % ms
    cost = 2/(tc/1000*sampleFq);
    
    thrCorrT = -1;
    
    RecordingList;
    
    load('Z:\Yingxue\DataAnalysisRaphi\SpikeCorrTAlignedAL.mat','spikeSimRunAll',...
        'spikeSimRewAll','spikeSimCueAll');
    
    spikeSimActiveRunAll = spikeSimRunAll;
    spikeSimActiveRewAll = spikeSimRewAll;
    spikeSimActiveCueAll = spikeSimCueAll;
    
    load('Z:\Yingxue\DataAnalysisRaphi\SpikeCorrTAlignedPL.mat','spikeSimRunAll',...
        'spikeSimRewAll','spikeSimCueAll');
    
    spikeSimPassiveRunAll = spikeSimRunAll;
    spikeSimPassiveRewAll = spikeSimRewAll;
    spikeSimPassiveCueAll = spikeSimCueAll;
    
    load('Z:\Yingxue\DataAnalysisRaphi\SpikeCorrTAlignedPNC.mat','spikeSimRunAll',...
        'spikeSimRewAll','spikeSimCueAll');
    
    spikeSimPassiveNoCueRunAll = spikeSimRunAll;
    spikeSimPassiveNoCueRewAll = spikeSimRewAll;
    spikeSimPassiveNoCueCueAll = spikeSimCueAll;
    
    spikeSimRunAll = [];
    spikeSimCueAll = [];
    %% statistics for aligning to run onset
    spikeSimRunAll.pRS_CorrTNonZeroGood_PNCvsP = ranksum(spikeSimPassiveNoCueRunAll.CorrTNonZeroGood,...
        spikeSimPassiveRunAll.CorrTNonZeroGood);
    spikeSimRunAll.pRS_CorrTNonZeroGood_PNCvsA = ranksum(spikeSimPassiveNoCueRunAll.CorrTNonZeroGood,...
        spikeSimActiveRunAll.CorrTNonZeroGood);
    spikeSimRunAll.pRS_CorrTNonZeroGood_PvsA = ranksum(spikeSimPassiveRunAll.CorrTNonZeroGood,...
        spikeSimActiveRunAll.CorrTNonZeroGood);
    
    spikeSimRunAll.pRS_CorrTGood_PNCvsP = ranksum(spikeSimPassiveNoCueRunAll.CorrTGood,...
        spikeSimPassiveRunAll.CorrTGood);
    spikeSimRunAll.pRS_CorrTGood_PNCvsA = ranksum(spikeSimPassiveNoCueRunAll.CorrTGood,...
        spikeSimActiveRunAll.CorrTGood);
    spikeSimRunAll.pRS_CorrTGood_PvsA = ranksum(spikeSimPassiveRunAll.CorrTGood,...
        spikeSimActiveRunAll.CorrTGood);
    
    [~,spikeSimRunAll.pKS_CorrTNonZeroGood_PNCvsP] = kstest2(spikeSimPassiveNoCueRunAll.CorrTNonZeroGood,...
        spikeSimPassiveRunAll.CorrTNonZeroGood);
    [~,spikeSimRunAll.pKS_CorrTNonZeroGood_PNCvsA] = kstest2(spikeSimPassiveNoCueRunAll.CorrTNonZeroGood,...
        spikeSimActiveRunAll.CorrTNonZeroGood);
    [~,spikeSimRunAll.pKS_CorrTNonZeroGood_PvsA] = kstest2(spikeSimPassiveRunAll.CorrTNonZeroGood,...
        spikeSimActiveRunAll.CorrTNonZeroGood);
    
    [~,spikeSimRunAll.pKS_CorrTGood_PNCvsP] = kstest2(spikeSimPassiveNoCueRunAll.CorrTGood,...
        spikeSimPassiveRunAll.CorrTGood);
    [~,spikeSimRunAll.pKS_CorrTGood_PNCvsA] = kstest2(spikeSimPassiveNoCueRunAll.CorrTGood,...
        spikeSimActiveRunAll.CorrTGood);
    [~,spikeSimRunAll.pKS_CorrTGood_PvsA] = kstest2(spikeSimPassiveRunAll.CorrTGood,...
        spikeSimActiveRunAll.CorrTGood);
    
    spikeSimRunAll.pRS_CorrTNonZero_PNCvsP = ranksum(spikeSimPassiveNoCueRunAll.CorrTNonZero,...
        spikeSimPassiveRunAll.CorrTNonZero);
    spikeSimRunAll.pRS_CorrTNonZero_PNCvsA = ranksum(spikeSimPassiveNoCueRunAll.CorrTNonZero,...
        spikeSimActiveRunAll.CorrTNonZero);
    spikeSimRunAll.pRS_CorrTNonZero_PvsA = ranksum(spikeSimPassiveRunAll.CorrTNonZero,...
        spikeSimActiveRunAll.CorrTNonZero);
        
    spikeSimRunAll.pRS_CorrT_PNCvsP = ranksum(spikeSimPassiveNoCueRunAll.CorrT,...
        spikeSimPassiveRunAll.CorrT);
    spikeSimRunAll.pRS_CorrT_PNCvsA = ranksum(spikeSimPassiveNoCueRunAll.CorrT,...
        spikeSimActiveRunAll.CorrT);
    spikeSimRunAll.pRS_CorrT_PvsA = ranksum(spikeSimPassiveRunAll.CorrT,...
        spikeSimActiveRunAll.CorrT);
    
    [~,spikeSimRunAll.pKS_CorrTNonZero_PNCvsP] = kstest2(spikeSimPassiveNoCueRunAll.CorrTNonZero,...
        spikeSimPassiveRunAll.CorrTNonZero);
    [~,spikeSimRunAll.pKS_CorrTNonZero_PNCvsA] = kstest2(spikeSimPassiveNoCueRunAll.CorrTNonZero,...
        spikeSimActiveRunAll.CorrTNonZero);
    [~,spikeSimRunAll.pKS_CorrTNonZero_PvsA] = kstest2(spikeSimPassiveRunAll.CorrTNonZero,...
        spikeSimActiveRunAll.CorrTNonZero);
    
    [~,spikeSimRunAll.pKS_CorrT_PNCvsP] = kstest2(spikeSimPassiveNoCueRunAll.CorrT,...
        spikeSimPassiveRunAll.CorrT);
    [~,spikeSimRunAll.pKS_CorrT_PNCvsA] = kstest2(spikeSimPassiveNoCueRunAll.CorrT,...
        spikeSimActiveRunAll.CorrT);
    [~,spikeSimRunAll.pKS_CorrT_PvsA] = kstest2(spikeSimPassiveRunAll.CorrT,...
        spikeSimActiveRunAll.CorrT);
    
    %% statistics for aligning to cue
    spikeSimCueAll.pRS_CorrTNonZeroGood_PNCvsP = ranksum(spikeSimPassiveNoCueCueAll.CorrTNonZeroGood,...
        spikeSimPassiveCueAll.CorrTNonZeroGood);
    spikeSimCueAll.pRS_CorrTNonZeroGood_PNCvsA = ranksum(spikeSimPassiveNoCueCueAll.CorrTNonZeroGood,...
        spikeSimActiveCueAll.CorrTNonZeroGood);
    spikeSimCueAll.pRS_CorrTNonZeroGood_PvsA = ranksum(spikeSimPassiveCueAll.CorrTNonZeroGood,...
        spikeSimActiveCueAll.CorrTNonZeroGood);
    
    spikeSimCueAll.pRS_CorrTGood_PNCvsP = ranksum(spikeSimPassiveNoCueCueAll.CorrTGood,...
        spikeSimPassiveCueAll.CorrTGood);
    spikeSimCueAll.pRS_CorrTGood_PNCvsA = ranksum(spikeSimPassiveNoCueCueAll.CorrTGood,...
        spikeSimActiveCueAll.CorrTGood);
    spikeSimCueAll.pRS_CorrTGood_PvsA = ranksum(spikeSimPassiveCueAll.CorrTGood,...
        spikeSimActiveCueAll.CorrTGood);
    
    [~,spikeSimCueAll.pKS_CorrTNonZeroGood_PNCvsP] = kstest2(spikeSimPassiveNoCueCueAll.CorrTNonZeroGood,...
        spikeSimPassiveCueAll.CorrTNonZeroGood);
    [~,spikeSimCueAll.pKS_CorrTNonZeroGood_PNCvsA] = kstest2(spikeSimPassiveNoCueCueAll.CorrTNonZeroGood,...
        spikeSimActiveCueAll.CorrTNonZeroGood);
    [~,spikeSimCueAll.pKS_CorrTNonZeroGood_PvsA] = kstest2(spikeSimPassiveCueAll.CorrTNonZeroGood,...
        spikeSimActiveCueAll.CorrTNonZeroGood);
    
    [~,spikeSimCueAll.pKS_CorrTGood_PNCvsP] = kstest2(spikeSimPassiveNoCueCueAll.CorrTGood,...
        spikeSimPassiveCueAll.CorrTGood);
    [~,spikeSimCueAll.pKS_CorrTGood_PNCvsA] = kstest2(spikeSimPassiveNoCueCueAll.CorrTGood,...
        spikeSimActiveCueAll.CorrTGood);
    [~,spikeSimCueAll.pKS_CorrTGood_PvsA] = kstest2(spikeSimPassiveCueAll.CorrTGood,...
        spikeSimActiveCueAll.CorrTGood);
        
    spikeSimCueAll.pRS_CorrTNonZero_PNCvsP = ranksum(spikeSimPassiveNoCueCueAll.CorrTNonZero,...
        spikeSimPassiveCueAll.CorrTNonZero);
    spikeSimCueAll.pRS_CorrTNonZero_PNCvsA = ranksum(spikeSimPassiveNoCueCueAll.CorrTNonZero,...
        spikeSimActiveCueAll.CorrTNonZero);
    spikeSimCueAll.pRS_CorrTNonZero_PvsA = ranksum(spikeSimPassiveCueAll.CorrTNonZero,...
        spikeSimActiveCueAll.CorrTNonZero);
    
    spikeSimCueAll.pRS_CorrT_PNCvsP = ranksum(spikeSimPassiveNoCueCueAll.CorrT,...
        spikeSimPassiveCueAll.CorrT);
    spikeSimCueAll.pRS_CorrT_PNCvsA = ranksum(spikeSimPassiveNoCueCueAll.CorrT,...
        spikeSimActiveCueAll.CorrT);
    spikeSimCueAll.pRS_CorrT_PvsA = ranksum(spikeSimPassiveCueAll.CorrT,...
        spikeSimActiveCueAll.CorrT);
    
    [~,spikeSimCueAll.pKS_CorrTNonZero_PNCvsP] = kstest2(spikeSimPassiveNoCueCueAll.CorrTNonZero,...
        spikeSimPassiveCueAll.CorrTNonZero);
    [~,spikeSimCueAll.pKS_CorrTNonZero_PNCvsA] = kstest2(spikeSimPassiveNoCueCueAll.CorrTNonZero,...
        spikeSimActiveCueAll.CorrTNonZero);
    [~,spikeSimCueAll.pKS_CorrTNonZero_PvsA] = kstest2(spikeSimPassiveCueAll.CorrTNonZero,...
        spikeSimActiveCueAll.CorrTNonZero);
    
    [~,spikeSimCueAll.pKS_CorrT_PNCvsP] = kstest2(spikeSimPassiveNoCueCueAll.CorrT,...
        spikeSimPassiveCueAll.CorrT);
    [~,spikeSimCueAll.pKS_CorrT_PNCvsA] = kstest2(spikeSimPassiveNoCueCueAll.CorrT,...
        spikeSimActiveCueAll.CorrT);
    [~,spikeSimCueAll.pKS_CorrT_PvsA] = kstest2(spikeSimPassiveCueAll.CorrT,...
        spikeSimActiveCueAll.CorrT);
    
    save('Z:\Yingxue\DataAnalysisRaphi\SpikeCorrTAligned_AllRec_AllCond.mat',...
        'spikeSimRunAll','spikeSimCueAll');
    
    %% plot the distribution aligned to run onset
    maxVal = max([spikeSimPassiveNoCueRunAll.CorrTGood,spikeSimPassiveRunAll.CorrTGood,spikeSimActiveRunAll.CorrTGood]);
    minVal = min([spikeSimPassiveNoCueRunAll.CorrTGood,spikeSimPassiveRunAll.CorrTGood,spikeSimActiveRunAll.CorrTGood]);
    xbins = minVal-0.01:0.01:maxVal+0.01;
    countPNC = hist(spikeSimPassiveNoCueRunAll.CorrTGood,xbins)/length(spikeSimPassiveNoCueRunAll.CorrTGood);
    countP = hist(spikeSimPassiveRunAll.CorrTGood,xbins)/length(spikeSimPassiveRunAll.CorrTGood);
    countA = hist(spikeSimActiveRunAll.CorrTGood,xbins)/length(spikeSimActiveRunAll.CorrTGood);
    
    plotSimComp(xbins,countPNC,countP,countA,...
        spikeSimRunAll.pKS_CorrTGood_PNCvsP,spikeSimRunAll.pKS_CorrTGood_PNCvsA,...
        spikeSimRunAll.pRS_CorrTGood_PvsA,...
        'Spike CorrT. good aligned to run onset',...
        'Count');
    fileName1 = ['SpikeCorrTAlignedRun_Good_AllRec_AllCond_Distr'];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');

    maxVal = max([spikeSimPassiveNoCueRunAll.CorrTNonZeroGood,spikeSimPassiveRunAll.CorrTNonZeroGood,spikeSimActiveRunAll.CorrTNonZeroGood]);
    minVal = min([spikeSimPassiveNoCueRunAll.CorrTNonZeroGood,spikeSimPassiveRunAll.CorrTNonZeroGood,spikeSimActiveRunAll.CorrTNonZeroGood]);
    xbins = minVal-0.01:0.01:maxVal+0.01;
    countPNC = hist(spikeSimPassiveNoCueRunAll.CorrTNonZeroGood,xbins)/length(spikeSimPassiveNoCueRunAll.CorrTNonZeroGood);
    countP = hist(spikeSimPassiveRunAll.CorrTNonZeroGood,xbins)/length(spikeSimPassiveRunAll.CorrTNonZeroGood);
    countA = hist(spikeSimActiveRunAll.CorrTNonZeroGood,xbins)/length(spikeSimActiveRunAll.CorrTNonZeroGood);
    
    plotSimComp(xbins,countPNC,countP,countA,...
        spikeSimRunAll.pKS_CorrTNonZeroGood_PNCvsP,spikeSimRunAll.pKS_CorrTNonZeroGood_PNCvsA,...
        spikeSimRunAll.pRS_CorrTNonZeroGood_PvsA,...
        'Spike CorrT. NZgood aligned to run onset',...
        'Count');
    fileName1 = ['SpikeCorrTAlignedRun_NZGood_AllRec_AllCond_Distr'];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');
    
    maxVal = max([spikeSimPassiveNoCueRunAll.CorrT,spikeSimPassiveRunAll.CorrT,spikeSimActiveRunAll.CorrT]);
    minVal = min([spikeSimPassiveNoCueRunAll.CorrT,spikeSimPassiveRunAll.CorrT,spikeSimActiveRunAll.CorrT]);
    xbins = minVal-0.01:0.01:maxVal+0.01;
    countPNC = hist(spikeSimPassiveNoCueRunAll.CorrT,xbins)/length(spikeSimPassiveNoCueRunAll.CorrT);
    countP = hist(spikeSimPassiveRunAll.CorrT,xbins)/length(spikeSimPassiveRunAll.CorrT);
    countA = hist(spikeSimActiveRunAll.CorrT,xbins)/length(spikeSimActiveRunAll.CorrT);
    
    plotSimComp(xbins,countPNC,countP,countA,...
        spikeSimRunAll.pKS_CorrT_PNCvsP,spikeSimRunAll.pKS_CorrT_PNCvsA,...
        spikeSimRunAll.pRS_CorrT_PvsA,...
        'Spike CorrT. aligned to run onset',...
        'Count');
    fileName1 = ['SpikeCorrTAlignedRun_AllRec_AllCond_Distr'];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');

    maxVal = max([spikeSimPassiveNoCueRunAll.CorrTNonZero,spikeSimPassiveRunAll.CorrTNonZero,spikeSimActiveRunAll.CorrTNonZero]);
    minVal = min([spikeSimPassiveNoCueRunAll.CorrTNonZero,spikeSimPassiveRunAll.CorrTNonZero,spikeSimActiveRunAll.CorrTNonZero]);
    xbins = minVal-0.01:0.01:maxVal+0.01;
    countPNC = hist(spikeSimPassiveNoCueRunAll.CorrTNonZero,xbins)/length(spikeSimPassiveNoCueRunAll.CorrTNonZero);
    countP = hist(spikeSimPassiveRunAll.CorrTNonZero,xbins)/length(spikeSimPassiveRunAll.CorrTNonZero);
    countA = hist(spikeSimActiveRunAll.CorrTNonZero,xbins)/length(spikeSimActiveRunAll.CorrTNonZero);
    
    plotSimComp(xbins,countPNC,countP,countA,...
        spikeSimRunAll.pKS_CorrTNonZero_PNCvsP,spikeSimRunAll.pKS_CorrTNonZero_PNCvsA,...
        spikeSimRunAll.pRS_CorrTNonZero_PvsA,...
        'Spike CorrT. NZ aligned to run onset',...
        'Count');
    fileName1 = ['SpikeCorrTAlignedRun_NZ_AllRec_AllCond_Distr'];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');
    
    plotBars(spikeSimPassiveNoCueRunAll.CorrTGoodMeanPerRec,spikeSimActiveRunAll.CorrTGoodMeanPerRec,...
        [mean(spikeSimPassiveNoCueRunAll.CorrTGood),mean(spikeSimActiveRunAll.CorrTGood)],...
        [std(spikeSimPassiveNoCueRunAll.CorrTGood)/sqrt(length(spikeSimPassiveNoCueRunAll.CorrTGood)),...
        std(spikeSimActiveRunAll.CorrTGood)/sqrt(length(spikeSimActiveRunAll.CorrTGood))],...
        '','Spike corrT. good aligned to run', ['p=' num2str(spikeSimRunAll.pRS_CorrTGood_PNCvsA)],...
        'Z:\Yingxue\DataAnalysisRaphi\','SpikeCorrTAlignedRun_Good_AllRec_PNCVsAL')
    
    plotBars(spikeSimPassiveNoCueRunAll.CorrTNonZeroGoodMeanPerRec,spikeSimActiveRunAll.CorrTNonZeroGoodMeanPerRec,...
        [mean(spikeSimPassiveNoCueRunAll.CorrTNonZeroGood),mean(spikeSimActiveRunAll.CorrTNonZeroGood)],...
        [std(spikeSimPassiveNoCueRunAll.CorrTNonZeroGood)/sqrt(length(spikeSimPassiveNoCueRunAll.CorrTNonZeroGood)),...
        std(spikeSimActiveRunAll.CorrTNonZeroGood)/sqrt(length(spikeSimActiveRunAll.CorrTNonZeroGood))],...
        '','Spike corrT. NZgood aligned to run', ['p=' num2str(spikeSimRunAll.pRS_CorrTNonZeroGood_PNCvsA)],...
        'Z:\Yingxue\DataAnalysisRaphi\','SpikeCorrTAlignedRun_NZGood_AllRec_PNCVsAL')
    
    plotBars(spikeSimPassiveNoCueRunAll.CorrTMeanPerRec,spikeSimActiveRunAll.CorrTMeanPerRec,...
        [mean(spikeSimPassiveNoCueRunAll.CorrT),mean(spikeSimActiveRunAll.CorrT)],...
        [std(spikeSimPassiveNoCueRunAll.CorrT)/sqrt(length(spikeSimPassiveNoCueRunAll.CorrT)),...
        std(spikeSimActiveRunAll.CorrT)/sqrt(length(spikeSimActiveRunAll.CorrT))],...
        '','Spike corrT. aligned to run', ['p=' num2str(spikeSimRunAll.pRS_CorrT_PNCvsA)],...
        'Z:\Yingxue\DataAnalysisRaphi\','SpikeCorrTAlignedRun_AllRec_PNCVsAL')
    
    plotBars(spikeSimPassiveNoCueRunAll.CorrTNonZeroMeanPerRec,spikeSimActiveRunAll.CorrTNonZeroMeanPerRec,...
        [mean(spikeSimPassiveNoCueRunAll.CorrTNonZero),mean(spikeSimActiveRunAll.CorrTNonZero)],...
        [std(spikeSimPassiveNoCueRunAll.CorrTNonZero)/sqrt(length(spikeSimPassiveNoCueRunAll.CorrTNonZero)),...
        std(spikeSimActiveRunAll.CorrTNonZero)/sqrt(length(spikeSimActiveRunAll.CorrTNonZero))],...
        '','Spike corrT. NZ aligned to run', ['p=' num2str(spikeSimRunAll.pRS_CorrTNonZero_PNCvsA)],...
        'Z:\Yingxue\DataAnalysisRaphi\','SpikeCorrTAlignedRun_NZ_AllRec_PNCVsAL')
    
    %% plot the distribution aligned to cue
    maxVal = max([spikeSimPassiveNoCueCueAll.CorrTGood,spikeSimPassiveCueAll.CorrTGood,spikeSimActiveCueAll.CorrTGood]);
    minVal = min([spikeSimPassiveNoCueCueAll.CorrTGood,spikeSimPassiveCueAll.CorrTGood,spikeSimActiveCueAll.CorrTGood]);
    xbins = minVal-0.01:0.01:maxVal+0.01;
    countPNC = hist(spikeSimPassiveNoCueCueAll.CorrTGood,xbins)/length(spikeSimPassiveNoCueCueAll.CorrTGood);
    countP = hist(spikeSimPassiveCueAll.CorrTGood,xbins)/length(spikeSimPassiveCueAll.CorrTGood);
    countA = hist(spikeSimActiveCueAll.CorrTGood,xbins)/length(spikeSimActiveCueAll.CorrTGood);
    
    plotSimComp(xbins,countPNC,countP,countA,...
        spikeSimCueAll.pKS_CorrTGood_PNCvsP,spikeSimCueAll.pKS_CorrTGood_PNCvsA,...
        spikeSimCueAll.pRS_CorrTGood_PvsA,...
        'Spike CorrT. good aligned to cue onset',...
        'Count');
    fileName1 = ['SpikeCorrTAlignedCue_Good_AllRec_AllCond_Distr'];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');

    maxVal = max([spikeSimPassiveNoCueCueAll.CorrTNonZeroGood,spikeSimPassiveCueAll.CorrTNonZeroGood,spikeSimActiveCueAll.CorrTNonZeroGood]);
    minVal = min([spikeSimPassiveNoCueCueAll.CorrTNonZeroGood,spikeSimPassiveCueAll.CorrTNonZeroGood,spikeSimActiveCueAll.CorrTNonZeroGood]);
    xbins = minVal-0.01:0.01:maxVal+0.01;
    countPNC = hist(spikeSimPassiveNoCueCueAll.CorrTNonZeroGood,xbins)/length(spikeSimPassiveNoCueCueAll.CorrTNonZeroGood);
    countP = hist(spikeSimPassiveCueAll.CorrTNonZeroGood,xbins)/length(spikeSimPassiveCueAll.CorrTNonZeroGood);
    countA = hist(spikeSimActiveCueAll.CorrTNonZeroGood,xbins)/length(spikeSimActiveCueAll.CorrTNonZeroGood);
    
    plotSimComp(xbins,countPNC,countP,countA,...
        spikeSimCueAll.pKS_CorrTNonZeroGood_PNCvsP,spikeSimCueAll.pKS_CorrTNonZeroGood_PNCvsA,...
        spikeSimCueAll.pRS_CorrTNonZeroGood_PvsA,...
        'Spike CorrT. NZgood aligned to cue onset',...
        'Count');
    fileName1 = ['SpikeCorrTAlignedCue_NZGood_AllRec_AllCond_Distr'];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');
    
    maxVal = max([spikeSimPassiveNoCueCueAll.CorrT,spikeSimPassiveCueAll.CorrT,spikeSimActiveCueAll.CorrT]);
    minVal = min([spikeSimPassiveNoCueCueAll.CorrT,spikeSimPassiveCueAll.CorrT,spikeSimActiveCueAll.CorrT]);
    xbins = minVal-0.01:0.01:maxVal+0.01;
    countPNC = hist(spikeSimPassiveNoCueCueAll.CorrT,xbins)/length(spikeSimPassiveNoCueCueAll.CorrT);
    countP = hist(spikeSimPassiveCueAll.CorrT,xbins)/length(spikeSimPassiveCueAll.CorrT);
    countA = hist(spikeSimActiveCueAll.CorrT,xbins)/length(spikeSimActiveCueAll.CorrT);
    
    plotSimComp(xbins,countPNC,countP,countA,...
        spikeSimCueAll.pKS_CorrT_PNCvsP,spikeSimCueAll.pKS_CorrT_PNCvsA,...
        spikeSimCueAll.pRS_CorrT_PvsA,...
        'Spike CorrT. aligned to cue onset',...
        'Count');
    fileName1 = ['SpikeCorrTAlignedCue_AllRec_AllCond_Distr'];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');

    maxVal = max([spikeSimPassiveNoCueCueAll.CorrTNonZero,spikeSimPassiveCueAll.CorrTNonZero,spikeSimActiveCueAll.CorrTNonZero]);
    minVal = min([spikeSimPassiveNoCueCueAll.CorrTNonZero,spikeSimPassiveCueAll.CorrTNonZero,spikeSimActiveCueAll.CorrTNonZero]);
    xbins = minVal-0.01:0.01:maxVal+0.01;
    countPNC = hist(spikeSimPassiveNoCueCueAll.CorrTNonZero,xbins)/length(spikeSimPassiveNoCueCueAll.CorrTNonZero);
    countP = hist(spikeSimPassiveCueAll.CorrTNonZero,xbins)/length(spikeSimPassiveCueAll.CorrTNonZero);
    countA = hist(spikeSimActiveCueAll.CorrTNonZero,xbins)/length(spikeSimActiveCueAll.CorrTNonZero);
    
    plotSimComp(xbins,countPNC,countP,countA,...
        spikeSimCueAll.pKS_CorrTNonZero_PNCvsP,spikeSimCueAll.pKS_CorrTNonZero_PNCvsA,...
        spikeSimCueAll.pRS_CorrTNonZero_PvsA,...
        'Spike CorrT. NZ aligned to cue onset',...
        'Count');
    fileName1 = ['SpikeCorrTAlignedCue_NZ_AllRec_AllCond_Distr'];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');
    
    plotBars(spikeSimPassiveNoCueCueAll.CorrTGoodMeanPerRec,spikeSimActiveCueAll.CorrTGoodMeanPerRec,...
        [mean(spikeSimPassiveNoCueCueAll.CorrTGood),mean(spikeSimActiveCueAll.CorrTGood)],...
        [std(spikeSimPassiveNoCueCueAll.CorrTGood)/sqrt(length(spikeSimPassiveNoCueCueAll.CorrTGood)),...
        std(spikeSimActiveCueAll.CorrTGood)/sqrt(length(spikeSimActiveCueAll.CorrTGood))],...
        '','Spike corrT. good aligned to cue', ['p=' num2str(spikeSimCueAll.pRS_CorrTGood_PNCvsA)],...
        'Z:\Yingxue\DataAnalysisRaphi\','SpikeCorrTAlignedCue_Good_AllRec_PNCVsAL')
    
    plotBars(spikeSimPassiveNoCueCueAll.CorrTNonZeroGoodMeanPerRec,spikeSimActiveCueAll.CorrTNonZeroGoodMeanPerRec,...
        [mean(spikeSimPassiveNoCueCueAll.CorrTNonZeroGood),mean(spikeSimActiveCueAll.CorrTNonZeroGood)],...
        [std(spikeSimPassiveNoCueCueAll.CorrTNonZeroGood)/sqrt(length(spikeSimPassiveNoCueCueAll.CorrTNonZeroGood)),...
        std(spikeSimActiveCueAll.CorrTNonZeroGood)/sqrt(length(spikeSimActiveCueAll.CorrTNonZeroGood))],...
        '','Spike corrT. NZgood aligned to cue', ['p=' num2str(spikeSimCueAll.pRS_CorrTNonZeroGood_PNCvsA)],...
        'Z:\Yingxue\DataAnalysisRaphi\','SpikeCorrTAlignedCue_NZGood_AllRec_PNCVsAL')
    
    plotBars(spikeSimPassiveNoCueCueAll.CorrTMeanPerRec,spikeSimActiveCueAll.CorrTMeanPerRec,...
        [mean(spikeSimPassiveNoCueCueAll.CorrT),mean(spikeSimActiveCueAll.CorrT)],...
        [std(spikeSimPassiveNoCueCueAll.CorrT)/sqrt(length(spikeSimPassiveNoCueCueAll.CorrT)),...
        std(spikeSimActiveCueAll.CorrT)/sqrt(length(spikeSimActiveCueAll.CorrT))],...
        '','Spike corrT. aligned to cue', ['p=' num2str(spikeSimCueAll.pRS_CorrT_PNCvsA)],...
        'Z:\Yingxue\DataAnalysisRaphi\','SpikeCorrTAlignedCue_AllRec_PNCVsAL')
    
    plotBars(spikeSimPassiveNoCueCueAll.CorrTNonZeroMeanPerRec,spikeSimActiveCueAll.CorrTNonZeroMeanPerRec,...
        [mean(spikeSimPassiveNoCueCueAll.CorrTNonZero),mean(spikeSimActiveCueAll.CorrTNonZero)],...
        [std(spikeSimPassiveNoCueCueAll.CorrTNonZero)/sqrt(length(spikeSimPassiveNoCueCueAll.CorrTNonZero)),...
        std(spikeSimActiveCueAll.CorrTNonZero)/sqrt(length(spikeSimActiveCueAll.CorrTNonZero))],...
        '','Spike corrT. NZ aligned to cue', ['p=' num2str(spikeSimCueAll.pRS_CorrTNonZero_PNCvsA)],...
        'Z:\Yingxue\DataAnalysisRaphi\','SpikeCorrTAlignedCue_NZ_AllRec_PNCVsAL')
    
end

function plotSimComp(a,x,y,z,pxy,pxz,pyz,xl,yl)
    [figNew,pos] = CreateFig();
    set(0,'Units','pixels')
    set(figure(figNew),'OuterPosition',...
            [pos(1) pos(2) 280 280])
    h = plot(a,x,'-');
    set(h,'LineWidth',2,'Color',[0.5 0.5 0.9]);
    hold on;
    h = plot(a,y,'-');
    set(h,'LineWidth',2,'Color',[0.9 0.5 0.5]);
    h = plot(a,z,'-');
    set(h,'LineWidth',2,'Color',[0.5 0.9 0.5]);
    set(gca,'XLim',[min(a) max(a)],'YLim',[0 max([x,y,z]+0.1)]);
    title(['p12 = ' num2str(pxy) ',p13 = ' num2str(pxz) ',p23 = ' num2str(pyz)]);
    xlabel(xl)
    ylabel(yl)
end

function plotBars(data1,data2,mean,std,x1,y1,t,pathAnal,fn)
    fig = figure;
    set(0,'Units','pixels') 
    set(figure(fig),'OuterPosition',...
        [500 500 210 280])
    fig.Renderer = 'Painters';
    
    h = bar([1,2],mean,0.5);
    set(h,'EdgeColor',[0.3 0.3 0.3],'FaceColor',[187 189 192]/255);
    hold
    
    h = errorbar([1,2],mean,std);
    set(h,'Marker','.','MarkerSize',0.1,'Color',[0 0 0],'LineStyle','none')
    
    h = plot(1+0.15*rand(1,length(data1)),data1,'o');
    set(h,'MarkerSize',3,'Color',[167 169 171]/255);
    
    h = plot(2+0.15*rand(1,length(data2)),data2,'o');
    set(h,'MarkerSize',3,'Color',[27 117 187]/255);
    set(gca,'XLim',[0.5 2.5],'YLim',[0 max([data1 data2])+0.01]);
    
    xlabel(x1);
    ylabel(y1);
    title(t);
    
    fileName1 = [pathAnal fn];
    saveas(gcf,fileName1);
    print('-painters', '-dpdf', fileName1, '-r600')
end