function spikeTrainSimilarityVPAllRec(onlyRun)
% compare the spike train similarity for different alignment conditions over all the recordings 

    GlobalConst;
    intervalT = 20;
    intervalD = 1800;
    tc = 500; % ms
    cost = 2/(tc/1000*sampleFq);
    
    s = num2str(cost);
    ind = strfind(s,'.');
    s(ind) = 'p';
    
    thrCorrT = 0;
    
    RecordingList;
    
    spikeSimRunAll.SimVPNonZeroGood = [];
    spikeSimRunAll.SimVPGood = [];
    spikeSimRunAll.SimVPNeuSelGood = [];
    spikeSimRunAll.SimVPRecNoGood = [];
    spikeSimRunAll.SimVPNonZero = [];
    spikeSimRunAll.SimVP = [];
    spikeSimRunAll.SimVPNeuSel = [];
    spikeSimRunAll.SimVPRecNo = [];
        
    spikeSimRewAll.SimVPNonZeroGood = [];
    spikeSimRewAll.SimVPGood = [];
    spikeSimRewAll.SimVPNonZero = [];
    spikeSimRewAll.SimVP = [];
    
    spikeSimCueAll.SimVPNonZeroGood = [];
    spikeSimCueAll.SimVPGood = [];
    spikeSimCueAll.SimVPNonZero = [];
    spikeSimCueAll.SimVP = [];
    for i = 1:size(listRecordingsActiveLickPath,1)
        path = listRecordingsActiveLickPath(i,:);
        fileName = listRecordingsActiveLickFileName(i,:);
        mazeSess = mazeSessionActiveLick(i);
        fullPath = [path,fileName, '_meanSpikeTrainSimVP_msess' num2str(mazeSess) '_Run' num2str(onlyRun) '_q' s '_intT' ...
            num2str(intervalT) '.mat'];
        load(fullPath,'meanSimVPRun','meanSimVPRew','meanSimVPCue');
        
        fileNameInfo = [fileName '_Info.mat'];
        fullPath = [path fileNameInfo];
        if(exist(fullPath) == 0)
            disp('_Info.mat file does not exist.');
            return;
        end
        load(fullPath,'autoCorr','beh'); 
        
        fullPathFR = [fileName '_FR_Run' num2str(onlyRun) '.mat'];
        fullPath = [path fullPathFR];
        if(exist(fullPath) == 0)
            disp('_FR_Run.mat file does not exist.');
            return;
        end
        load(fullPath,'mFRStruct','mFRStructSess'); 
        if(length(beh.mazeSessAll) > 1)
            mFR = mFRStructSess{mazeSess};
        else
            mFR = mFRStruct;
        end
        
        indNeuSel = mFR.mFR > minFR & mFR.mFR < maxFR &...
                    autoCorr.isPyrneuron == 1;
                        
        indSelSimVP = meanSimVPRun.meanGoodNZ > thrCorrT;
        indSelSimVP = indNeuSel & indSelSimVP;
        spikeSimRunAll.SimVPNeuSelGood = [spikeSimRunAll.SimVPNeuSelGood ...
            find(indSelSimVP == 1)];
        spikeSimRunAll.SimVPRecNoGood = [spikeSimRunAll.SimVPRecNoGood ...
            i*ones(1,sum(indSelSimVP))];
        spikeSimRunAll.SimVPNonZeroGood = [spikeSimRunAll.SimVPNonZeroGood ...
            meanSimVPRun.meanGoodNZ(indSelSimVP)];
        spikeSimRewAll.SimVPNonZeroGood = [spikeSimRewAll.SimVPNonZeroGood ...
            meanSimVPRew.meanGoodNZ(indSelSimVP)];
        spikeSimCueAll.SimVPNonZeroGood = [spikeSimCueAll.SimVPNonZeroGood ...
            meanSimVPCue.meanGoodNZ(indSelSimVP)];
        
        spikeSimRunAll.SimVPGood = [spikeSimRunAll.SimVPGood ...
            meanSimVPRun.meanGood(indSelSimVP)];
        spikeSimRewAll.SimVPGood = [spikeSimRewAll.SimVPGood ...
            meanSimVPRew.meanGood(indSelSimVP)];
        spikeSimCueAll.SimVPGood = [spikeSimCueAll.SimVPGood ...
            meanSimVPCue.meanGood(indSelSimVP)];

        indSelSimVP = meanSimVPRun.meanNZ > thrCorrT;
        indSelSimVP = indNeuSel & indSelSimVP;
        spikeSimRunAll.SimVPNeuSel = [spikeSimRunAll.SimVPNeuSel ...
            find(indSelSimVP == 1)];
        spikeSimRunAll.SimVPRecNo = [spikeSimRunAll.SimVPRecNo ...
            i*ones(1,sum(indSelSimVP))];
        spikeSimRunAll.SimVPNonZero = [spikeSimRunAll.SimVPNonZero ...
            meanSimVPRun.meanNZ(indSelSimVP)];
        spikeSimRewAll.SimVPNonZero = [spikeSimRewAll.SimVPNonZero ...
            meanSimVPRew.meanNZ(indSelSimVP)];
        spikeSimCueAll.SimVPNonZero = [spikeSimCueAll.SimVPNonZero ...
            meanSimVPCue.meanNZ(indSelSimVP)];
        
        spikeSimRunAll.SimVP = [spikeSimRunAll.SimVP ...
            meanSimVPRun.mean(indSelSimVP)];
        spikeSimRewAll.SimVP = [spikeSimRewAll.SimVP ...
            meanSimVPRew.mean(indSelSimVP)];
        spikeSimCueAll.SimVP = [spikeSimCueAll.SimVP ...
            meanSimVPCue.mean(indSelSimVP)];
    end
    
    spikeSimRunAll.pRS_SimVPNonZeroGood_RR = ranksum(spikeSimRunAll.SimVPNonZeroGood,...
        spikeSimRewAll.SimVPNonZeroGood);
    spikeSimRunAll.pRS_SimVPNonZeroGood_RC = ranksum(spikeSimRunAll.SimVPNonZeroGood,...
        spikeSimCueAll.SimVPNonZeroGood);
    
    spikeSimRunAll.pRS_SimVPGood_RR = ranksum(spikeSimRunAll.SimVPGood,...
        spikeSimRewAll.SimVPGood);
    spikeSimRunAll.pRS_SimVPGood_RC = ranksum(spikeSimRunAll.SimVPGood,...
        spikeSimCueAll.SimVPGood);
    
    spikeSimRunAll.pRS_SimVPNonZero_RR = ranksum(spikeSimRunAll.SimVPNonZero,...
        spikeSimRewAll.SimVPNonZero);
    spikeSimRunAll.pRS_SimVPNonZero_RC = ranksum(spikeSimRunAll.SimVPNonZero,...
        spikeSimCueAll.SimVPNonZero);
    
    spikeSimRunAll.pRS_SimVP_RR = ranksum(spikeSimRunAll.SimVP,...
        spikeSimRewAll.SimVP);
    spikeSimRunAll.pRS_SimVP_RC = ranksum(spikeSimRunAll.SimVP,...
        spikeSimCueAll.SimVP);
    
    save('Z:\Yingxue\DataAnalysisRaphi\SpikeSimVPAlignedAL.mat','spikeSimRunAll',...
        'spikeSimRewAll','spikeSimCueAll');
    
    plotSimComp(spikeSimRunAll.SimVPNonZeroGood,...
        spikeSimRewAll.SimVPNonZeroGood,...
        spikeSimRunAll.pRS_SimVPNonZeroGood_RR,...
        'Spike Dist VP NZgood aligned to run onset',...
        'Spike Dist VP NZgood aligned to reward onset');
    fileName1 = ['SpikeDistVPAligned_NZGood_RunVsRew_ALRec'];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');

    plotSimComp(spikeSimRunAll.SimVPNonZeroGood,...
        spikeSimCueAll.SimVPNonZeroGood,...
        spikeSimRunAll.pRS_SimVPNonZeroGood_RC,...
        'Spike Dist VP NZgood aligned to run onset',...
        'Spike Dist VP NZgood aligned to cue onset');
    fileName1 = ['SpikeDistVPAligned_NZGood_RunVsCue_ALRec'];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');
    
    plotSimComp(spikeSimRunAll.SimVPGood,...
        spikeSimRewAll.SimVPGood,...
        spikeSimRunAll.pRS_SimVPGood_RR,...
        'Spike Dist VP good aligned to run onset',...
        'Spike Dist VP good aligned to reward onset');
    fileName1 = ['SpikeDistVPAligned_Good_RunVsRew_ALRec'];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');

    plotSimComp(spikeSimRunAll.SimVPGood,...
        spikeSimCueAll.SimVPGood,...
        spikeSimRunAll.pRS_SimVPGood_RC,...
        'Spike Dist VP good aligned to run onset',...
        'Spike Dist VP good aligned to cue onset');
    fileName1 = ['SpikeDistVPAligned_Good_RunVsCue_ALRec'];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');
    
    plotSimComp(spikeSimRunAll.SimVPNonZero,...
        spikeSimRewAll.SimVPNonZero,...
        spikeSimRunAll.pRS_SimVPNonZero_RR,...
        'Spike Dist VP NZ aligned to run onset',...
        'Spike Dist VP NZ aligned to reward onset');
    fileName1 = ['SpikeDistVPAligned_NZ_RunVsRew_ALRec'];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');

    plotSimComp(spikeSimRunAll.SimVPNonZero,...
        spikeSimCueAll.SimVPNonZero,...
        spikeSimRunAll.pRS_SimVPNonZero_RC,...
        'Spike Dist VP NZ aligned to run onset',...
        'Spike Dist VP NZ aligned to cue onset');
    fileName1 = ['SpikeDistVPAligned_NZ_RunVsCue_ALRec'];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');
    
    plotSimComp(spikeSimRunAll.SimVP,...
        spikeSimRewAll.SimVP,...
        spikeSimRunAll.pRS_SimVP_RR,...
        'Spike Dist VP aligned to run onset',...
        'Spike Dist VP aligned to reward onset');
    fileName1 = ['SpikeDistVPAligned_RunVsRew_ALRec'];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');

    plotSimComp(spikeSimRunAll.SimVP,...
        spikeSimCueAll.SimVP,...
        spikeSimRunAll.pRS_SimVP_RC,...
        'Spike Dist VP aligned to run onset',...
        'Spike Dist VP aligned to cue onset');
    fileName1 = ['SpikeDistVPAligned_RunVsCue_ALRec'];
    print('-painters','-dpdf',['Z:\Yingxue\DataAnalysisRaphi\' fileName1],'-r600');
    
    colorSel= 0;
    plotBoxPlot(spikeSimRunAll.SimVPGood,...
        spikeSimCueAll.SimVPGood,'Spike corr. good',...
        'SpikeSimVPAligned_Good_RunVsCue_ALRecBox',...
        'Z:\Yingxue\DataAnalysisRaphi\',[],spikeSimRunAll.pRS_SimVPGood_RC,colorSel);
    
    plotBoxPlot(spikeSimRunAll.SimVPNonZeroGood,...
        spikeSimCueAll.SimVPNonZeroGood,'Spike corr. good (nonzero)',...
        'SpikeSimVPAligned_NZGood_RunVsCue_ALRecBox',...
        'Z:\Yingxue\DataAnalysisRaphi\',[],spikeSimRunAll.pRS_SimVPNonZeroGood_RC,colorSel);
    
    plotBoxPlot(spikeSimRunAll.SimVP,...
        spikeSimCueAll.SimVP,'Spike corr.',...
        'SpikeSimVPAligned_RunVsCue_ALRecBox',...
        'Z:\Yingxue\DataAnalysisRaphi\',[],spikeSimRunAll.pRS_SimVP_RC,colorSel);
    
    plotBoxPlot(spikeSimRunAll.SimVPNonZero,...
        spikeSimCueAll.SimVPNonZero,'Spike corr.(nonzero)',...
        'SpikeSimVPAligned_NZ_RunVsCue_ALRecBox',...
        'Z:\Yingxue\DataAnalysisRaphi\',[],spikeSimRunAll.pRS_SimVPNonZero_RC,colorSel);
end

function plotSimComp(x,y,p,xl,yl)
    [figNew,pos] = CreateFig();
    set(0,'Units','pixels')
    set(figure(figNew),'OuterPosition',...
            [pos(1) pos(2) 280 280])
    h = plot(x,y,'.');
    set(h,'MarkerSize',4,'Color',[0.5 0.5 0.9]);
    maxXY = max([x,y]);
    hold on;
    h = plot([0 maxXY],[0 maxXY],'r:');
    set(h,'LineWidth',1);
    set(gca,'XLim',[0 maxXY],'YLim',[0 maxXY]);
    title(['p = ' num2str(p)]);
    xlabel(xl)
    ylabel(yl)
end