function meanActivityCorrDiffBeh(pathAnal,onlyRun,type1,type2)
% compare the passive no cue recordings with the active licking no cue
% behavior, and look at the activity correlation on single neuron level
% default analysis path ['Z:\Raphael_tests\mice_expdata\Analysis\'];
% e.g.  meanActivityCorrDiffBeh('Z:\Raphael_tests\mice_expdata\Analysis\',3,2)
% type1/type2 = 1, passive licking; 2, active licking; 3, passive no cue

    load([pathAnal 'recList' num2str(type1) '_activityCorrNeu_Run1.mat']);
    recList1 = recListActivityCorr;
    
    load([pathAnal 'recList' num2str(type2) '_activityCorrNeu_Run1.mat']);
    recList2 = recListActivityCorr;
    
    trialTypeDiffActCorr.meanPercGoodPyrNeuPerRec = [mean(recList1.percGoodPyrNeuPerRec),...
        mean(recList2.percGoodPyrNeuPerRec)];
    trialTypeDiffActCorr.stdPercGoodPyrNeuPerRec = [std(recList1.percGoodPyrNeuPerRec)/...
        sqrt(length(recList1.percGoodPyrNeuPerRec)),...
        std(recList2.percGoodPyrNeuPerRec)/...
        sqrt(length(recList2.percGoodPyrNeuPerRec))...
        ];
    trialTypeDiffActCorr.pPercGoodPyrNeuPerRec = ranksum(recList1.percGoodPyrNeuPerRec,...
        recList2.percGoodPyrNeuPerRec);
    
    trialTypeDiffActCorr.meanMCorrActiveTrPerNeuPerRec = ...
        [mean(recList1.meanCorrActiveTrPerNeuPerRec),...
        mean(recList2.meanCorrActiveTrPerNeuPerRec)];
    trialTypeDiffActCorr.stdMCorrActiveTrPerNeuPerRec = ...
        [std(recList1.meanCorrActiveTrPerNeuPerRec)/...
        sqrt(length(recList1.meanCorrActiveTrPerNeuPerRec)),...
        std(recList2.meanCorrActiveTrPerNeuPerRec)/...
        sqrt(length(recList2.meanCorrActiveTrPerNeuPerRec))];
    trialTypeDiffActCorr.pMCorrActiveTrPerNeuPerRec = ...
        ranksum(recList1.meanCorrActiveTrPerNeuPerRec,...
        recList2.meanCorrActiveTrPerNeuPerRec);
    
    trialTypeDiffActCorr.meanMCorrActiveTrGoodNeuPerRec = ...
        [mean(recList1.meanCorrActiveTrGoodNeuPerRec),...
        mean(recList2.meanCorrActiveTrGoodNeuPerRec)];
    trialTypeDiffActCorr.stdMCorrActiveTrGoodNeuPerRec = ...
        [std(recList1.meanCorrActiveTrGoodNeuPerRec)/...
        sqrt(length(recList1.meanCorrActiveTrGoodNeuPerRec)),...
        std(recList2.meanCorrActiveTrGoodNeuPerRec)/...
        sqrt(length(recList2.meanCorrActiveTrGoodNeuPerRec))];
    trialTypeDiffActCorr.pMCorrActiveTrGoodNeuPerRec = ...
        ranksum(recList1.meanCorrActiveTrGoodNeuPerRec,...
        recList2.meanCorrActiveTrGoodNeuPerRec);
    
    trialTypeDiffActCorr.pMeanCorrActiveTrPerNeu = ...
        ranksum(recList1.meanCorrActiveTrPerNeu,recList2.meanCorrActiveTrPerNeu);
    
    trialTypeDiffActCorr.pMeanFRActiveTrPerNeu = ...
        ranksum(recList1.meanFRActiveTrPerNeu,recList2.meanFRActiveTrPerNeu);
    
    fullPath = ['Z:\Raphael_tests\mice_expdata\Analysis\'];
    fullPath = [fullPath 'compRecList' num2str(type1) '-' num2str(type2) '_actCorr_Run' num2str(onlyRun) '.mat'];
    save(fullPath,'trialTypeDiffActCorr');
    
    plotBars(recList1.percGoodPyrNeuPerRec,recList2.percGoodPyrNeuPerRec,...
        trialTypeDiffActCorr.meanPercGoodPyrNeuPerRec,...
        trialTypeDiffActCorr.stdPercGoodPyrNeuPerRec,'','Perc. neurons', ...
        ['Perc. neurons with high activity corr.: p=' ...
        num2str(trialTypeDiffActCorr.pPercGoodPyrNeuPerRec)]);
    print('-painters','-dpdf',[pathAnal 'TrialTypeCompPercNeuHighCorr' num2str(type1) '-' num2str(type2)],'-r600');
    
    plotBars(recList1.meanCorrActiveTrPerNeuPerRec,...
        recList2.meanCorrActiveTrPerNeuPerRec,...
        trialTypeDiffActCorr.meanMCorrActiveTrPerNeuPerRec,...
        trialTypeDiffActCorr.stdMCorrActiveTrPerNeuPerRec,...
        '','Mean activity corr.', ...
        ['Mean activity corr.: p=' ...
        num2str(trialTypeDiffActCorr.pMCorrActiveTrPerNeuPerRec)]);
    print('-painters','-dpdf',[pathAnal 'TrialTypeCompMeanActivityCorr' num2str(type1) '-' num2str(type2)],'-r600');
        
    plotBars(recList1.meanCorrActiveTrGoodNeuPerRec,...
        recList2.meanCorrActiveTrGoodNeuPerRec,...
        trialTypeDiffActCorr.meanMCorrActiveTrGoodNeuPerRec,...
        trialTypeDiffActCorr.stdMCorrActiveTrGoodNeuPerRec,...
        '','Mean activity corr.', ...
        ['Mean activity corr. for high corr. neurons: p=' ...
        num2str(trialTypeDiffActCorr.pMCorrActiveTrGoodNeuPerRec)]);
    print('-painters','-dpdf',[pathAnal 'TrialTypeCompMeanActivityCorrHighCorrNeu' num2str(type1) '-' num2str(type2)],'-r600');
    
end

function plotBars(data1,data2,mean,std,x1,y1,t)
    fig = figure;
    set(0,'Units','pixels') 
    set(figure(fig),'OuterPosition',...
        [500 500 210 280])
    fig.Renderer = 'Painters';
    
    h = bar([1,2],mean,0.5);
    set(h,'EdgeColor',[0.3 0.3 0.3],'FaceColor',[187 189 192]/255);
    hold
    
    h = errorbar([1,2],mean,std);
    set(h,'Marker','.','MarkerSize',0.1,'Color',[0 0 0],'LineStyle','none')
    
    h = plot(1+0.1*rand(1,length(data1)),data1,'o');
    set(h,'MarkerSize',5,'Color',[167 169 171]/255);
    
    h = plot(2+0.1*rand(1,length(data2)),data2,'o');
    set(h,'MarkerSize',5,'Color',[27 117 187]/255);
    set(gca,'XLim',[0.5 2.5],'YLim',[0 max([data1 data2])+0.01]);
    
    xlabel(x1);
    ylabel(y1);
    title(t);
end
