function PyrBehAlignedAllRec(onlyRun,task)

    RecordingList;
    pathAnal0 = 'Z:\Yingxue\DataAnalysisRaphi\Pyramidal\';
    if(task == 1) % including all the neurons
        pathAnal = 'Z:\Yingxue\DataAnalysisRaphi\Pyramidal\';
    elseif(task == 2) % including AL and PL neurons
        pathAnal = 'Z:\Yingxue\DataAnalysisRaphi\PyramidalALPL\';
    else
        pathAnal = 'Z:\Yingxue\DataAnalysisRaphi\PyramidalAL\';
    end
    
    load([pathAnal0 'autoCorrPyrAllRec.mat']);
    
    if(exist([pathAnal0 'behAllRec.mat']))
        load([pathAnal0 'behAllRec.mat']);
    end
    
%     disp('No cue')
%     behAlignedNoCue = accumBeh(listRecordingsNoCuePath,...
%         listRecordingsNoCueFileName,mazeSessionNoCue,1,onlyRun);
%     behAlignedSpeedBefTimeNoCue = accumSpeedTime(listRecordingsNoCuePath,...
%         listRecordingsNoCueFileName,mazeSessionNoCue,1,0);
%     disp('Active licking')
%     behAlignedAL = accumBeh(listRecordingsActiveLickPath,...
%         listRecordingsActiveLickFileName,mazeSessionActiveLick,2,onlyRun);
%     behAlignedSpeedBefTimeAL = accumSpeedTime(listRecordingsActiveLickPath,...
%         listRecordingsActiveLickFileName,mazeSessionActiveLick,2,0);
%     disp('Passive licking')
%     behAlignedPL = accumBeh(listRecordingsPassiveLickPath,...
%         listRecordingsPassiveLickFileName,mazeSessionPassiveLick,3,onlyRun);
%     behAlignedSpeedBefTimePL = accumSpeedTime(listRecordingsPassiveLickPath,...
%         listRecordingsPassiveLickFileName,mazeSessionPassiveLick,3,0);
%     save([pathAnal 'behAllRec.mat'],'behAlignedNoCue','behAlignedAL','behAlignedPL',...
%         'behAlignedSpeedBefTimeNoCue','behAlignedSpeedBefTimeAL',...
%         'behAlignedSpeedBefTimePL'); 
    
    behAligned.indRecNoCue = unique(autoCorrPyrNoCue.indRec(autoCorrPyrNoCue.task == 1));
    behAligned.indRecNoCueField = unique(autoCorrPyrNoCue.indRec(autoCorrPyrNoCue.task == 1 &...
        modPyrNoCue.nNeuWithField > 1));
    behAligned.indRecNoCueNoField = unique(autoCorrPyrNoCue.indRec(autoCorrPyrNoCue.task == 1 &...
        modPyrNoCue.nNeuWithField == 0));
    
    behAligned.indRecAL = unique(autoCorrPyrAL.indRec(autoCorrPyrAL.task == 2));
    behAligned.indRecALField = unique(autoCorrPyrAL.indRec(autoCorrPyrAL.task == 2 &...
        modPyrAL.nNeuWithField > 1));
    behAligned.indRecALNoField = unique(autoCorrPyrAL.indRec(autoCorrPyrAL.task == 2 &...
        modPyrAL.nNeuWithField == 0));
    
    behAligned.indRecPL = unique(autoCorrPyrPL.indRec(autoCorrPyrPL.task == 3));
    behAligned.indRecPLField = unique(autoCorrPyrPL.indRec(autoCorrPyrPL.task == 3 &...
        modPyrPL.nNeuWithField > 1));
    behAligned.indRecPLNoField = unique(autoCorrPyrPL.indRec(autoCorrPyrPL.task == 3 &...
        modPyrPL.nNeuWithField == 0));
    
    behAlignedMeanField = accumMean(behAlignedNoCue,behAlignedAL,behAlignedPL,behAligned);
    behAlignedMeanFieldStat = accumMeanStat(behAlignedMeanField,behAlignedNoCue.spaceStepsLick,...
        behAlignedNoCue.spaceStepsSpeed);
    
    behAlignedMean = accumMeanGoodBad(behAlignedNoCue,behAlignedAL,behAlignedPL,task);
    
    behAlignedMeanStat = accumMeanStatGoodBad(behAlignedMean,...
        behAlignedNoCue.spaceStepsLick,behAlignedNoCue.spaceStepsSpeed);
    
    if(task == 1)
        save([pathAnal 'behAllRec.mat'],'behAligned','behAlignedMean',...
            'behAlignedMeanField','behAlignedMeanFieldStat',...
            'behAlignedMeanStat','-append'); 
    elseif(task == 2)
        save([pathAnal 'behALPLRec.mat'],'behAligned','behAlignedMean',...
            'behAlignedMeanField','behAlignedMeanFieldStat',...
            'behAlignedMeanStat');
    else
        save([pathAnal 'behALRec.mat'],'behAligned','behAlignedMean',...
            'behAlignedMeanField','behAlignedMeanFieldStat',...
            'behAlignedMeanStat'); 
    end
        
    plotSpeedRec(pathAnal,behAlignedSpeedBefTimeAL.timeStep,...
        behAlignedSpeedBefTimeAL.meanSpeedTimeNonStimGoodPerRec(15,:)/10,...
        behAlignedSpeedBefTimeAL.semSpeedTimeNonStimGoodPerRec(15,:)/10,[-3 7],'A023-20191219-01')
    
    plotSpeed(pathAnal,behAlignedNoCue.spaceStepsSpeed,...
        behAlignedMeanField.speedTraceNonStimGoodPerRecField,...
        behAlignedMeanField.speedTraceNonStimGoodPerRecNoField,[{'Field'} {'No Field'}],...
        [pathAnal 'SpeedVsDist-Field-NoField']);
    plotLick(pathAnal,behAlignedNoCue.spaceStepsLick,...
        behAlignedMeanField.lickTraceNonStimGoodPerRecField,...
        behAlignedMeanField.lickTraceNonStimGoodPerRecNoField,[{'Field'} {'No Field'}],...
        [pathAnal 'LickVsDist-Field-NoField']);
    plotBehAlignedMean(pathAnal,behAlignedMeanField,behAlignedMeanFieldStat);
    
    plotSpeed(pathAnal,behAlignedNoCue.spaceStepsSpeed,...
        behAlignedMean.speedTraceNonStimGoodPerRec,...
        behAlignedMean.speedTraceNonStimBadPerRec,[{'Good'} {'Bad'}],...
        [pathAnal 'SpeedVsDist-GoodBad']);
    plotLick(pathAnal,behAlignedNoCue.spaceStepsLick,...
        behAlignedMean.lickTraceNonStimGoodPerRec,...
        behAlignedMean.lickTraceNonStimBadPerRec,[{'Good'} {'Bad'}],...
        [pathAnal 'LickVsDist-GoodBad']);
    plotSpeed(pathAnal,behAlignedNoCue.spaceStepsSpeed,...
        behAlignedMean.meanSpeedPerRecNonStimGood,...
        behAlignedMean.meanSpeedPerRecNonStimBad,[{'Good'} {'Bad'}],...
        [pathAnal 'MeanSpeedVsDist-GoodBad']);
    plotLick(pathAnal,behAlignedNoCue.spaceStepsLick,...
        behAlignedMean.meanLickPerRecNonStimGood,...
        behAlignedMean.meanLickPerRecNonStimBad,[{'Good'} {'Bad'}],...
        [pathAnal 'MeanLickVsDist-GoodBad']);
    plotBehAlignedMeanGoodBad(pathAnal,behAlignedMean,behAlignedMeanStat)
end

function behAligned = accumBeh(paths,filenames,mazeSess,task,onlyRun)
    randTrNo = 15;
    randTrNoGood = 15;
    randTrNoBad = 15;
    randTrNoStim = 15;

    numRec = size(paths,1);
    behAligned = struct('task',[],... % no cue - 1, AL - 2, PL - 3
                    'taskNonStimGood',[],... % no cue - 1, AL - 2, PL - 3
                    'taskNonStimBad',[],... % no cue - 1, AL - 2, PL - 3
                    'taskStim',[],... % no cue - 1, AL - 2, PL - 3
                    ...
                    'indRec',[],... % recording index for all the recordings
                    'indRecNonStimGood',[],... % recording index for all the recordings with non-stimulated good trials
                    'indRecNonStimBad',[],... % recording index for all the recordings with non-stimulated bad trials
                    'indRecStim',[],... % recording index for all the reoordings with stimulated trials
                    'pulseMeth',[],... % pulse method
                    ...
                    'meanLickPerRec',[],... % mean lick trace per recording
                    'semLickPerRec',[],... % mean lick trace per recording
                    'lickTracePerRec',{cell(1,numRec)},...
                    ...
                    'meanLickNonStimGoodPerRec',[],... % mean lick trace per recording (non-stimulated good trials)
                    'semLickNonStimGoodPerRec',[],... % mean lick trace per recording (non-stimulated good trials)
                    'lickTraceNonStimGoodPerRec',{cell(1,numRec)},... (non-stimulated good trials)
                    ...
                    'meanLickNonStimBadPerRec',[],... % mean lick trace per recording (non-stimulated bad trials)
                    'semLickNonStimBadPerRec',[],... % mean lick trace per recording (non-stimulated bad trials)
                    'lickTraceNonStimBadPerRec',{cell(1,numRec)},... (non-stimulated bad trials)
                    ...
                    'meanLickStimPerRec',[],... % mean lick trace per recording (stimulated trials)
                    'semLickStimPerRec',[],... % mean lick trace per recording (stimulated trials)
                    'lickTraceStimPerRec',{cell(1,numRec)},... (stimulated trials)
                    ...
                    'meanSpeedPerRec',[],... % mean speed trace per recording
                    'semSpeedPerRec',[],... % mean speed trace per recording
                    'speedTracePerRec',{cell(1,numRec)},... 
                    ...
                    'meanSpeedNonStimGoodPerRec',[],... % mean speed trace per recording (non-stimulated good trials)
                    'semSpeedNonStimGoodPerRec',[],... % mean speed trace per recording (non-stimulated good trials)
                    'speedTraceNonStimGoodPerRec',{cell(1,numRec)},... (non-stimulated good trials)
                    ...
                    'meanSpeedNonStimBadPerRec',[],... % mean speed trace per recording (non-stimulated bad trials)
                    'semSpeedNonStimBadPerRec',[],... % mean speed trace per recording (non-stimulated bad trials)
                    'speedTraceNonStimBadPerRec',{cell(1,numRec)},... (non-stimulated bad trials)
                    ...
                    'meanSpeedStimPerRec',[],... % mean speed trace per recording (stimulated trials)
                    'semSpeedStimPerRec',[],... % mean speed trace per recording (stimulated trials)
                    'speedTraceStimPerRec',{cell(1,numRec)}); % (stimulated trials)
                
    for i = 1:numRec
        if(task == 3 & i == 8)
            a = 1;
        end
        disp(filenames(i,:));            
        
        fullPathLick = [filenames(i,:) '_lickDist_msess' num2str(mazeSess(i)) '_Run' num2str(onlyRun) '.mat'];
        fullPath = [paths(i,:) fullPathLick];
        if(exist(fullPath) == 0)
            disp('_lickDist.mat file does not exist.');
            return;
        end
        load(fullPath,'lickOverDist','param');
        paramLick = param;
        
        fullPathSpeed = [filenames(i,:) '_runSpeedDist_msess' num2str(mazeSess(i)) '_Run' num2str(onlyRun) '.mat'];
        fullPath = [paths(i,:) fullPathSpeed];
        if(exist(fullPath) == 0)
            disp('_runSpeedDist.mat file does not exist.');
            return;
        end
        load(fullPath,'speedOverDist','param');
        paramSpeed = param;
        
        fullPath = [paths(i,:) filenames(i,:) '_PeakFRAligned_msess' num2str(mazeSess(i)) '_Run' num2str(onlyRun) '.mat'];    
        if(exist(fullPath) == 0)
            disp('The _PeakFRAligned file does not exist');
            return;
        end
        load(fullPath,'trialNoNonStimGood','trialNoNonStimBad','trialNoStim','pulseMeth');
        
        fileNameFW = [filenames(i,:) '_FieldSpCorr_GoodTr_Run1.mat'];
        fullPath = [paths(i,:) fileNameFW];
        if(exist(fullPath) == 0)
            disp(['The field detection file does not exist. Please call ',...
                    'function "FieldDetection_GoodTr" first.']);
            return;
        end
        load(fullPath,'paramF'); 
        
        behAligned.spaceStepsLick = paramLick.spaceSteps;
        behAligned.spaceStepsSpeed = paramSpeed.spaceSteps;
        behAligned.task = [behAligned.task task];
        behAligned.indRec = [behAligned.indRec i];            
        if(isempty(behAligned.meanLickPerRec))
            behAligned.meanLickPerRec = lickOverDist.meanRun;
            behAligned.semLickPerRec = lickOverDist.SEMRun;

            behAligned.meanSpeedPerRec = speedOverDist.meanRun;
            behAligned.semSpeedPerRec = speedOverDist.SEMRun;

        else
            behAligned.meanLickPerRec = [behAligned.meanLickPerRec; lickOverDist.meanRun];
            behAligned.semLickPerRec = [behAligned.semLickPerRec; lickOverDist.SEMRun];

            behAligned.meanSpeedPerRec = [behAligned.meanSpeedPerRec; speedOverDist.meanRun];
            behAligned.semSpeedPerRec = [behAligned.semSpeedPerRec; speedOverDist.SEMRun];
        end
        
        if(~isempty(trialNoNonStimGood) & length(trialNoNonStimGood) > paramF.minNumTr)
            behAligned.taskNonStimGood = [behAligned.taskNonStimGood task];
            behAligned.indRecNonStimGood = [behAligned.indRecNonStimGood i];            
            if(isempty(behAligned.meanLickNonStimGoodPerRec))
                behAligned.meanLickNonStimGoodPerRec = lickOverDist.meanRunNonStimGood;
                behAligned.semLickNonStimGoodPerRec = lickOverDist.SEMRunNonStimGood;

                behAligned.meanSpeedNonStimGoodPerRec = speedOverDist.meanRunNonStimGood;
                behAligned.semSpeedNonStimGoodPerRec = speedOverDist.SEMRunNonStimGood;

            else
                behAligned.meanLickNonStimGoodPerRec = [behAligned.meanLickNonStimGoodPerRec; ...
                    lickOverDist.meanRunNonStimGood];
                behAligned.semLickNonStimGoodPerRec = [behAligned.semLickNonStimGoodPerRec;...
                    lickOverDist.SEMRunNonStimGood];

                behAligned.meanSpeedNonStimGoodPerRec = [behAligned.meanSpeedNonStimGoodPerRec; ...
                    speedOverDist.meanRunNonStimGood];
                behAligned.semSpeedNonStimGoodPerRec = [behAligned.semSpeedNonStimGoodPerRec;...
                    speedOverDist.SEMRunNonStimGood];
            end
        end
        
        if(~isempty(trialNoNonStimBad) & length(trialNoNonStimBad) > paramF.minNumTr)
            behAligned.taskNonStimBad = [behAligned.taskNonStimBad task];
            behAligned.indRecNonStimBad = [behAligned.indRecNonStimBad i];
            if(isempty(behAligned.meanLickNonStimBadPerRec))
                behAligned.meanLickNonStimBadPerRec = lickOverDist.meanRunNonStimBad;
                behAligned.semLickNonStimBadPerRec = lickOverDist.SEMRunNonStimBad;
                
                behAligned.meanSpeedNonStimBadPerRec = speedOverDist.meanRunNonStimBad;
                behAligned.semSpeedNonStimBadPerRec = speedOverDist.SEMRunNonStimBad;
                
            else
                behAligned.meanLickNonStimBadPerRec = [behAligned.meanLickNonStimBadPerRec;...
                    lickOverDist.meanRunNonStimBad];
                behAligned.semLickNonStimBadPerRec = [behAligned.semLickNonStimBadPerRec;...
                    lickOverDist.SEMRunNonStimBad];
                
                behAligned.meanSpeedNonStimBadPerRec = [behAligned.meanSpeedNonStimBadPerRec;...
                    speedOverDist.meanRunNonStimBad];
                behAligned.semSpeedNonStimBadPerRec = [behAligned.semSpeedNonStimBadPerRec;...
                    speedOverDist.SEMRunNonStimBad];                
            end
        end
        
        for j = 1:length(trialNoStim)
            if(~isempty(trialNoStim{j}) & length(trialNoStim{j}) > paramF.minNumTr)
                behAligned.taskStim = [behAligned.taskStim task];
                behAligned.indRecStim = [behAligned.indRecStim i];
                behAligned.pulseMeth = [behAligned.pulseMeth pulseMeth(j)];
                if(isempty(behAligned.meanLickStimPerRec))
                    behAligned.meanLickStimPerRec = lickOverDist.meanRunStim{j};
                    behAligned.semLickStimPerRec = lickOverDist.SEMRunStim{j};

                    behAligned.meanSpeedStimPerRec = speedOverDist.meanRunStim{j};
                    behAligned.semSpeedStimPerRec = speedOverDist.SEMRunStim{j};

                else
                    behAligned.meanLickStimPerRec = [behAligned.meanLickStimPerRec;...
                        lickOverDist.meanRunStim{j}];
                    behAligned.semLickStimPerRec = [behAligned.semLickStimPerRec;...
                        lickOverDist.SEMRunStim{j}];

                    behAligned.meanSpeedStimPerRec = [behAligned.meanSpeedStimPerRec;...
                        speedOverDist.meanRunStim{j}];
                    behAligned.semSpeedStimPerRec = [behAligned.semSpeedStimPerRec;...
                        speedOverDist.SEMRunStim{j}];
                end
            end
        end
        
        nTr = size(speedOverDist.Run,1);
        if(nTr > randTrNo)
            indTrR = randperm(nTr);
            behAligned.lickTracePerRec{i} = lickOverDist.Run(indTrR(1:randTrNo),:);
            behAligned.speedTracePerRec{i} = speedOverDist.Run(indTrR(1:randTrNo),:);
        else
            behAligned.lickTracePerRec{i} = lickOverDist.Run;
            behAligned.speedTracePerRec{i} = speedOverDist.Run;
        end
        
        nTr = length(trialNoNonStimGood);
        if(nTr > randTrNoGood)
            indTrR = randperm(nTr);
            behAligned.lickTraceNonStimGoodPerRec{i} = lickOverDist.Run(trialNoNonStimGood(indTrR(1:randTrNoGood)),:);
            behAligned.speedTraceNonStimGoodPerRec{i} = speedOverDist.Run(trialNoNonStimGood(indTrR(1:randTrNoGood)),:);
        else
            behAligned.lickTraceNonStimGoodPerRec{i} = lickOverDist.Run(trialNoNonStimGood,:);
            behAligned.speedTraceNonStimGoodPerRec{i} = speedOverDist.Run(trialNoNonStimGood,:);
        end
        
        nTr = length(trialNoNonStimBad);
        if(nTr > randTrNoBad)
            indTrR = randperm(nTr);
            behAligned.lickTraceNonStimBadPerRec{i} = lickOverDist.Run(trialNoNonStimBad(indTrR(1:randTrNoBad)),:);
            behAligned.speedTraceNonStimBadPerRec{i} = speedOverDist.Run(trialNoNonStimBad(indTrR(1:randTrNoBad)),:);
        elseif(nTr > 0)
            behAligned.lickTraceNonStimBadPerRec{i} = lickOverDist.Run(trialNoNonStimBad,:);
            behAligned.speedTraceNonStimBadPerRec{i} = speedOverDist.Run(trialNoNonStimBad,:);
        end
        
        for j = 1:length(trialNoStim)
            nTr = length(trialNoStim{j});
            if(nTr > randTrNoStim)
                indTrR = randperm(nTr);
                behAligned.lickTraceStimPerRec{i,j} = lickOverDist.Run(trialNoStim{j}(indTrR(1:randTrNoStim)),:);
                behAligned.speedTraceStimPerRec{i,j} = speedOverDist.Run(trialNoStim{j}(indTrR(1:randTrNoStim)),:);
            elseif(nTr > 0)
                behAligned.lickTraceStimPerRec{i,j} = lickOverDist.Run(trialNoStim{j},:);
                behAligned.speedTraceStimPerRec{i,j} = speedOverDist.Run(trialNoStim{j},:);
            end
        end
    end        
end

function behAligned = accumSpeedTime(paths,filenames,mazeSess,task,onlyRun)
    
    numRec = size(paths,1);
    behAligned = struct(...
                    'taskNonStimGood',[],... % no cue - 1, AL - 2, PL - 3
                    'taskNonStimBad',[],... % no cue - 1, AL - 2, PL - 3
                    ...
                    'indRecNonStimGood',[],... % recording index for all the reoordings with non-stimulated good trials
                    'indRecNonStimBad',[],... % recording index for all the reoordings with non-stimulated bad trials
                    ...
                    'timeStep',[],...
                    ...
                    'meanSpeedTimeNonStimGoodPerRec',[],... % mean speed trace per recording (non-stimulated good trials)
                    'semSpeedTimeNonStimGoodPerRec',[],... % mean speed trace per recording (non-stimulated good trials)
                    ...
                    'meanSpeedTimeNonStimBadPerRec',[],... % mean speed trace per recording (non-stimulated bad trials)
                    'semSpeedTimeNonStimBadPerRec',[]); % mean speed trace per recording (non-stimulated bad trials)

    for i = 1:numRec
        if(task == 3 & i == 8)
            a = 1;
        end
        disp(filenames(i,:));            
        
        fullPathSpeed = [filenames(i,:) '_thetaPhaseOverTimeligned_msess' num2str(mazeSess(i)) '_Run' num2str(onlyRun) '.mat'];
        fullPath = [paths(i,:) fullPathSpeed];
        if(exist(fullPath) == 0)
            disp('_thetaPhaseOverTimeligned.mat file does not exist.');
            return;
        end
        load(fullPath,'runSpeedNonStimGood','runSpeedNonStimBad','paramC');
        
        fullPath = [paths(i,:) filenames(i,:) '_PeakFRAligned_msess' num2str(mazeSess(i)) '_Run1.mat'];    
        if(exist(fullPath) == 0)
            disp('The _PeakFRAligned file does not exist');
            return;
        end
        load(fullPath,'trialNoNonStimGood','trialNoNonStimBad','trialNoStim','pulseMeth');
        
        fileNameFW = [filenames(i,:) '_FieldSpCorr_GoodTr_Run1.mat'];
        fullPath = [paths(i,:) fileNameFW];
        if(exist(fullPath) == 0)
            disp(['The field detection file does not exist. Please call ',...
                    'function "FieldDetection_GoodTr" first.']);
            return;
        end
        load(fullPath,'paramF'); 
        
        behAligned.timeStep = paramC.timeIncBef;
        
        if(~isempty(trialNoNonStimGood) & length(trialNoNonStimGood) > paramF.minNumTr)
            behAligned.taskNonStimGood = [behAligned.taskNonStimGood task];
            behAligned.indRecNonStimGood = [behAligned.indRecNonStimGood i];
            meanRunNonStimGood = mean(runSpeedNonStimGood);
            SEMRunNonStimGood = std(runSpeedNonStimGood)/sqrt(length(trialNoNonStimGood));
            if(isempty(behAligned.meanSpeedTimeNonStimGoodPerRec))
                behAligned.meanSpeedTimeNonStimGoodPerRec = meanRunNonStimGood;
                behAligned.semSpeedTimeNonStimGoodPerRec = SEMRunNonStimGood;
            else
                behAligned.meanSpeedTimeNonStimGoodPerRec = [behAligned.meanSpeedTimeNonStimGoodPerRec; ...
                    meanRunNonStimGood];
                behAligned.semSpeedTimeNonStimGoodPerRec = [behAligned.semSpeedTimeNonStimGoodPerRec;...
                    SEMRunNonStimGood];
            end
        end
        
        if(~isempty(trialNoNonStimBad) & length(trialNoNonStimBad) > paramF.minNumTr)
            behAligned.taskNonStimBad = [behAligned.taskNonStimBad task];
            behAligned.indRecNonStimBad = [behAligned.indRecNonStimBad i];
            meanRunNonStimBad = mean(runSpeedNonStimBad);
            SEMRunNonStimBad = std(runSpeedNonStimBad)/sqrt(length(trialNoNonStimBad));
            if(isempty(behAligned.meanSpeedTimeNonStimBadPerRec))
                behAligned.meanSpeedTimeNonStimBadPerRec = meanRunNonStimBad;
                behAligned.semSpeedTimeNonStimBadPerRec = SEMRunNonStimBad;
            else
                behAligned.meanSpeedTimeNonStimBadPerRec = [behAligned.meanSpeedTimeNonStimBadPerRec;...
                    meanRunNonStimBad];
                behAligned.semSpeedTimeNonStimBadPerRec = [behAligned.semSpeedTimeNonStimBadPerRec;...
                    SEMRunNonStimBad];
            end
        end
        
    end        
end

function behAlignedMean = accumMeanGoodBad(behAlignedNoCue,behAlignedAL,behAlignedPL,task)
    if(task == 1)
        behAlignedMean.meanLickPerRecNonStimGood = ...
            [behAlignedNoCue.meanLickNonStimGoodPerRec;...
            behAlignedAL.meanLickNonStimGoodPerRec;...
            behAlignedPL.meanLickNonStimGoodPerRec];
        behAlignedMean.meanLickPerRecNonStimBad = ...
            [behAlignedNoCue.meanLickNonStimBadPerRec;...
            behAlignedAL.meanLickNonStimBadPerRec;...
            behAlignedPL.meanLickNonStimBadPerRec];        
        GoodTmp = [behAlignedNoCue.lickTraceNonStimGoodPerRec ...
            behAlignedAL.lickTraceNonStimGoodPerRec ...
            behAlignedPL.lickTraceNonStimGoodPerRec];
        BadTmp = [behAlignedNoCue.lickTraceNonStimBadPerRec ...
            behAlignedAL.lickTraceNonStimBadPerRec ...
            behAlignedPL.lickTraceNonStimBadPerRec];
        
        behAlignedMean.meanSpeedPerRecNonStimGood = ...
            [behAlignedNoCue.meanSpeedNonStimGoodPerRec;...
            behAlignedAL.meanSpeedNonStimGoodPerRec;...
            behAlignedPL.meanSpeedNonStimGoodPerRec];
        behAlignedMean.meanSpeedPerRecNonStimBad = ...
            [behAlignedNoCue.meanSpeedNonStimBadPerRec;...
            behAlignedAL.meanSpeedNonStimBadPerRec;...
            behAlignedPL.meanSpeedNonStimBadPerRec];        
        GoodSpeedTmp = [behAlignedNoCue.speedTraceNonStimGoodPerRec ...
            behAlignedAL.speedTraceNonStimGoodPerRec ...
            behAlignedPL.speedTraceNonStimGoodPerRec];
        BadSpeedTmp = [behAlignedNoCue.speedTraceNonStimBadPerRec ...
            behAlignedAL.speedTraceNonStimBadPerRec ...
            behAlignedPL.speedTraceNonStimBadPerRec]; 
    elseif(task == 2)
        behAlignedMean.meanLickPerRecNonStimGood = ...
            [behAlignedAL.meanLickNonStimGoodPerRec;...
            behAlignedPL.meanLickNonStimGoodPerRec];
        behAlignedMean.meanLickPerRecNonStimBad = ...
            [behAlignedAL.meanLickNonStimBadPerRec;...
            behAlignedPL.meanLickNonStimBadPerRec];        
        GoodTmp = [behAlignedAL.lickTraceNonStimGoodPerRec ...
            behAlignedPL.lickTraceNonStimGoodPerRec];   
        BadTmp = [behAlignedAL.lickTraceNonStimBadPerRec ...
            behAlignedPL.lickTraceNonStimBadPerRec];
        
        behAlignedMean.meanSpeedPerRecNonStimGood = ...
            [behAlignedAL.meanSpeedNonStimGoodPerRec;...
            behAlignedPL.meanSpeedNonStimGoodPerRec];
        behAlignedMean.meanSpeedPerRecNonStimBad = ...
            [behAlignedAL.meanSpeedNonStimBadPerRec;...
            behAlignedPL.meanSpeedNonStimBadPerRec];        
        GoodSpeedTmp = [behAlignedAL.speedTraceNonStimGoodPerRec ...
            behAlignedPL.speedTraceNonStimGoodPerRec];
        BadSpeedTmp = [behAlignedAL.speedTraceNonStimBadPerRec ...
            behAlignedPL.speedTraceNonStimBadPerRec]; 
    else
        behAlignedMean.meanLickPerRecNonStimGood = ...
            behAlignedAL.meanLickNonStimGoodPerRec;
        behAlignedMean.meanLickPerRecNonStimBad = ...
            behAlignedAL.meanLickNonStimBadPerRec;
        GoodTmp = behAlignedAL.lickTraceNonStimGoodPerRec; 
        BadTmp = behAlignedAL.lickTraceNonStimBadPerRec;
        
        behAlignedMean.meanSpeedPerRecNonStimGood = ...
            behAlignedAL.meanSpeedNonStimGoodPerRec;
        behAlignedMean.meanSpeedPerRecNonStimBad = ...
            behAlignedAL.meanSpeedNonStimBadPerRec;       
        GoodSpeedTmp = behAlignedAL.speedTraceNonStimGoodPerRec;
        BadSpeedTmp = behAlignedAL.speedTraceNonStimBadPerRec; 
    end
    
    behAlignedMean.lickTraceNonStimGoodPerRec = [];
    for i = 1:length(GoodTmp)
        behAlignedMean.lickTraceNonStimGoodPerRec = [...
            behAlignedMean.lickTraceNonStimGoodPerRec; ...
            GoodTmp{i}];
    end  
    behAlignedMean.lickTraceNonStimBadPerRec = [];
    for i = 1:length(BadTmp)
        behAlignedMean.lickTraceNonStimBadPerRec = [...
            behAlignedMean.lickTraceNonStimBadPerRec; ...
            BadTmp{i}];
    end  
    behAlignedMean.meanLickTraceNonStimGoodPerRec = ...
        mean(behAlignedMean.lickTraceNonStimGoodPerRec);
    behAlignedMean.semLickTraceNonStimGoodPerRec = ...
        std(behAlignedMean.lickTraceNonStimGoodPerRec)/...
        sqrt(size(behAlignedMean.lickTraceNonStimGoodPerRec,1)); 
    behAlignedMean.meanLickTraceNonStimBadPerRec = ...
        mean(behAlignedMean.lickTraceNonStimBadPerRec);
    behAlignedMean.semLickTraceNonStimBadPerRec = ...
        std(behAlignedMean.lickTraceNonStimBadPerRec)/...
        sqrt(size(behAlignedMean.lickTraceNonStimBadPerRec,1));
    
    behAlignedMean.speedTraceNonStimGoodPerRec = [];
    for i = 1:length(GoodSpeedTmp)
        behAlignedMean.speedTraceNonStimGoodPerRec = [...
            behAlignedMean.speedTraceNonStimGoodPerRec; ...
            GoodSpeedTmp{i}];
    end
    behAlignedMean.speedTraceNonStimBadPerRec = [];
    for i = 1:length(BadSpeedTmp)
        behAlignedMean.speedTraceNonStimBadPerRec = [...
            behAlignedMean.speedTraceNonStimBadPerRec; ...
            BadSpeedTmp{i}];
    end    
    behAlignedMean.meanSpeedTraceNonStimGoodPerRec = ...
        mean(behAlignedMean.speedTraceNonStimGoodPerRec);
    behAlignedMean.semSpeedTraceNonStimGoodPerRec = ...
        std(behAlignedMean.speedTraceNonStimGoodPerRec)/...
        sqrt(size(behAlignedMean.speedTraceNonStimGoodPerRec,1));
    behAlignedMean.meanSpeedTraceNonStimBadPerRec = ...
        mean(behAlignedMean.speedTraceNonStimBadPerRec);
    behAlignedMean.semSpeedTraceNonStimBadPerRec = ...
        std(behAlignedMean.speedTraceNonStimBadPerRec)/...
        sqrt(size(behAlignedMean.speedTraceNonStimBadPerRec,1));
end

function behAlignedMeanStat = accumMeanStatGoodBad(behAlignedMean,spaceStepsLick,spaceStepsSpeed)
    
    %% total mean
    indLickAfter30 = find(spaceStepsLick >= 300 & spaceStepsLick < 2100);
    behAlignedMeanStat.indLickAfter30 = indLickAfter30;
    behAlignedMeanStat.meanLickPerRec = [...
        mean(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLickAfter30))),...
        mean(mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLickAfter30)))];
    
    behAlignedMeanStat.pRSLickTracePerRec = ...
        ranksum(reshape(behAlignedMean.lickTraceNonStimGoodPerRec(:,indLickAfter30),[],1),...
        reshape(behAlignedMean.lickTraceNonStimBadPerRec(:,indLickAfter30),[],1));
    
    behAlignedMeanStat.pRSMeanLickMeanPerRec = ...
        ranksum(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLickAfter30),2),...
        mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLickAfter30),2));
            
    behAlignedMeanStat.pRSMeanLickTracePerRec = ...
        ranksum(mean(behAlignedMean.lickTraceNonStimGoodPerRec(:,indLickAfter30),2),...
        mean(behAlignedMean.lickTraceNonStimBadPerRec(:,indLickAfter30),2));

    %% distance 30 to 100
    indLick30to100 = find(spaceStepsLick >= 300 & spaceStepsLick < 1000);
    behAlignedMeanStat.indLick30to100 = indLick30to100;
    behAlignedMeanStat.meanLickPerRec30to100 = [...
        mean(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLick30to100))),...
        mean(mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLick30to100)))];
    
    behAlignedMeanStat.pRSLickTracePerRec30to100 = ...
        ranksum(reshape(behAlignedMean.lickTraceNonStimGoodPerRec(:,indLick30to100),[],1),...
        reshape(behAlignedMean.lickTraceNonStimBadPerRec(:,indLick30to100),[],1));
    
    behAlignedMeanStat.pRSMeanLickMeanPerRec30to100 = ...
        ranksum(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLick30to100),2),...
        mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLick30to100),2));
            
    behAlignedMeanStat.pRSMeanLickTracePerRec30to100 = ...
        ranksum(mean(behAlignedMean.lickTraceNonStimGoodPerRec(:,indLick30to100),2),...
        mean(behAlignedMean.lickTraceNonStimBadPerRec(:,indLick30to100),2));
    
    %% distance 100 to 150
    indLick100to150 = find(spaceStepsLick >= 1000 & spaceStepsLick < 1500);
    behAlignedMeanStat.indLick100to150 = indLick100to150;
    behAlignedMeanStat.meanLickPerRec100to150 = [...
        mean(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLick100to150))),...
        mean(mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLick100to150)))];
    
    behAlignedMeanStat.pRSLickTracePerRec100to150 = ...
        ranksum(reshape(behAlignedMean.lickTraceNonStimGoodPerRec(:,indLick100to150),[],1),...
        reshape(behAlignedMean.lickTraceNonStimBadPerRec(:,indLick100to150),[],1));
    
    behAlignedMeanStat.pRSMeanLickMeanPerRec100to150 = ...
        ranksum(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLick100to150),2),...
        mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLick100to150),2));
            
    behAlignedMeanStat.pRSMeanLickTracePerRec100to150 = ...
        ranksum(mean(behAlignedMean.lickTraceNonStimGoodPerRec(:,indLick100to150),2),...
        mean(behAlignedMean.lickTraceNonStimBadPerRec(:,indLick100to150),2));
    
    %% distance 150 to 180
    indLick150to180 = find(spaceStepsLick >= 1500 & spaceStepsLick < 1800);
    behAlignedMeanStat.indLick150to180 = indLick150to180;
    behAlignedMeanStat.meanLickPerRec150to180 = [...
        mean(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLick150to180))),...
        mean(mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLick150to180)))];
    
    behAlignedMeanStat.pRSLickTracePerRec150to180 = ...
        ranksum(reshape(behAlignedMean.lickTraceNonStimGoodPerRec(:,indLick150to180),[],1),...
        reshape(behAlignedMean.lickTraceNonStimBadPerRec(:,indLick150to180),[],1));
    
    behAlignedMeanStat.pRSMeanLickMeanPerRec150to180 = ...
        ranksum(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLick150to180),2),...
        mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLick150to180),2));
            
    behAlignedMeanStat.pRSMeanLickTracePerRec150to180 = ...
        ranksum(mean(behAlignedMean.lickTraceNonStimGoodPerRec(:,indLick150to180),2),...
        mean(behAlignedMean.lickTraceNonStimBadPerRec(:,indLick150to180),2));
        
    %% distance after 180
    indLickAfter180 = find(spaceStepsLick >= 1800 & spaceStepsLick < 2100);
    behAlignedMeanStat.indLickAfter180 = indLickAfter180;
    behAlignedMeanStat.meanLickPerRecAfter180 = [...
        mean(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLickAfter180))),...
        mean(mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLickAfter180)))];
        
    behAlignedMeanStat.pRSLickTracePerRecAfter180 = ...
        ranksum(reshape(behAlignedMean.lickTraceNonStimGoodPerRec(:,indLickAfter180),[],1),...
        reshape(behAlignedMean.lickTraceNonStimBadPerRec(:,indLickAfter180),[],1));
    
    behAlignedMeanStat.pRSMeanLickMeanPerRecAfter180 = ...
        ranksum(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLickAfter180),2),...
        mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLickAfter180),2));
            
    behAlignedMeanStat.pRSMeanLickTracePerRecAfter180 = ...
        ranksum(mean(behAlignedMean.lickTraceNonStimGoodPerRec(:,indLickAfter180),2),...
        mean(behAlignedMean.lickTraceNonStimBadPerRec(:,indLickAfter180),2));
    
    %% total mean
    behAlignedMeanStat.meanSpeedPerRec = [...
        mean(behAlignedMean.meanSpeedPerRecNonStimGood(:)),...
        mean(behAlignedMean.meanSpeedPerRecNonStimBad(:))];
    
    behAlignedMeanStat.pRSSpeedTracePerRec = ...
        ranksum(behAlignedMean.speedTraceNonStimGoodPerRec(:),...
        behAlignedMean.speedTraceNonStimBadPerRec(:));
    
    behAlignedMeanStat.pRSMeanSpeedMeanPerRec = ...
        ranksum(mean(behAlignedMean.meanSpeedPerRecNonStimGood,2),...
        mean(behAlignedMean.meanSpeedPerRecNonStimBad,2));
    
    behAlignedMeanStat.pRSMeanSpeedTracePerRec = ...
        ranksum(mean(behAlignedMean.speedTraceNonStimGoodPerRec,2),...
        mean(behAlignedMean.speedTraceNonStimBadPerRec,2));
    
    %% distance 30 to 100
    indSpeed30to100 = find(spaceStepsSpeed >= 300 & spaceStepsSpeed < 1000);
    behAlignedMeanStat.indSpeed30to100 = indSpeed30to100;
    behAlignedMeanStat.meanSpeedPerRec30to100 = [...
        mean(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,indSpeed30to100))),...
        mean(mean(behAlignedMean.meanSpeedPerRecNonStimBad(:,indSpeed30to100)))];
    
    behAlignedMeanStat.pRSSpeedTracePerRec30to100 = ...
        ranksum(reshape(behAlignedMean.speedTraceNonStimGoodPerRec(:,indSpeed30to100),[],1),...
        reshape(behAlignedMean.speedTraceNonStimBadPerRec(:,indSpeed30to100),[],1));
    
    behAlignedMeanStat.pRSMeanSpeedMeanPerRec30to100 = ...
        ranksum(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,indSpeed30to100),2),...
        mean(behAlignedMean.meanSpeedPerRecNonStimBad(:,indSpeed30to100),2));
    
    behAlignedMeanStat.pRSMeanSpeedTracePerRec30to100 = ...
        ranksum(mean(behAlignedMean.speedTraceNonStimGoodPerRec(:,indSpeed30to100),2),...
        mean(behAlignedMean.speedTraceNonStimBadPerRec(:,indSpeed30to100),2));
    
    %% distance > 100
    indSpeedAfter100 = find(spaceStepsSpeed >= 1000);
    behAlignedMeanStat.indSpeedAfter100 = indSpeedAfter100;
    behAlignedMeanStat.meanSpeedPerRecAfter100 = [...
        mean(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,indSpeedAfter100))),...
        mean(mean(behAlignedMean.meanSpeedPerRecNonStimBad(:,indSpeedAfter100)))];
    
    behAlignedMeanStat.pRSSpeedTracePerRecAfter100 = ...
        ranksum(reshape(behAlignedMean.speedTraceNonStimGoodPerRec(:,indSpeedAfter100),[],1),...
        reshape(behAlignedMean.speedTraceNonStimBadPerRec(:,indSpeedAfter100),[],1));
    
    behAlignedMeanStat.pRSMeanSpeedMeanPerRecAfter100 = ...
        ranksum(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,indSpeedAfter100),2),...
        mean(behAlignedMean.meanSpeedPerRecNonStimBad(:,indSpeedAfter100),2));
    
    behAlignedMeanStat.pRSMeanSpeedTracePerRecAfter100 = ...
        ranksum(mean(behAlignedMean.speedTraceNonStimGoodPerRec(:,indSpeedAfter100),2),...
        mean(behAlignedMean.speedTraceNonStimBadPerRec(:,indSpeedAfter100),2));
    
end

function behAlignedMean = accumMean(behAlignedNoCue,behAlignedAL,behAlignedPL,behAligned)   
    % mean behavior for recordings with fields
    behAlignedMean.meanLickPerRecField = ...
        [behAlignedNoCue.meanLickPerRec(behAligned.indRecNoCueField,:);...
        behAlignedAL.meanLickPerRec(behAligned.indRecALField,:);...
        behAlignedPL.meanLickPerRec(behAligned.indRecPLField,:)];
  
    [~,nonStimGoodRecNoCueField] = intersect(behAlignedNoCue.indRecNonStimGood,behAligned.indRecNoCueField);
    [~,nonStimGoodRecALField] = intersect(behAlignedAL.indRecNonStimGood,behAligned.indRecALField);
    [~,nonStimGoodRecPLField] = intersect(behAlignedPL.indRecNonStimGood,behAligned.indRecPLField);
    behAlignedMean.meanLickNonStimGoodPerRecField = ...
        [behAlignedNoCue.meanLickNonStimGoodPerRec(nonStimGoodRecNoCueField,:);...
        behAlignedAL.meanLickNonStimGoodPerRec(nonStimGoodRecALField,:);...
        behAlignedPL.meanLickNonStimGoodPerRec(nonStimGoodRecPLField,:)];
    
    fieldTmp = [behAlignedNoCue.lickTraceNonStimGoodPerRec(behAligned.indRecNoCueField) ...
        behAlignedAL.lickTraceNonStimGoodPerRec(behAligned.indRecALField) ...
        behAlignedPL.lickTraceNonStimGoodPerRec(behAligned.indRecPLField)];
    behAlignedMean.lickTraceNonStimGoodPerRecField = [];
    for i = 1:length(fieldTmp)
        behAlignedMean.lickTraceNonStimGoodPerRecField = [...
            behAlignedMean.lickTraceNonStimGoodPerRecField; ...
            fieldTmp{i}];
    end
    behAlignedMean.meanLickTraceNonStimGoodPerRecField = ...
        mean(behAlignedMean.lickTraceNonStimGoodPerRecField);
    behAlignedMean.semLickTraceNonStimGoodPerRecField = ...
        std(behAlignedMean.lickTraceNonStimGoodPerRecField)/...
        sqrt(size(behAlignedMean.lickTraceNonStimGoodPerRecField,1));
          
    [~,nonStimBadRecNoCueField] = intersect(behAlignedNoCue.indRecNonStimBad,behAligned.indRecNoCueField);
    [~,nonStimBadRecALField] = intersect(behAlignedAL.indRecNonStimBad,behAligned.indRecALField);
    [~,nonStimBadRecPLField] = intersect(behAlignedPL.indRecNonStimBad,behAligned.indRecPLField);
    behAlignedMean.meanLickNonStimBadPerRecField = ...
        [behAlignedNoCue.meanLickNonStimBadPerRec(nonStimBadRecNoCueField,:);...
        behAlignedAL.meanLickNonStimBadPerRec(nonStimBadRecALField,:);...
        behAlignedPL.meanLickNonStimBadPerRec(nonStimBadRecPLField,:)];
    
    [~,stimRecNoCueField] = intersect(behAlignedNoCue.indRecStim,behAligned.indRecNoCueField);
    [~,stimRecALField] = intersect(behAlignedAL.indRecStim,behAligned.indRecALField);
    [~,stimRecPLField] = intersect(behAlignedPL.indRecStim,behAligned.indRecPLField);
    behAlignedMean.meanLickStimPerRecField = ...
        [behAlignedNoCue.meanLickStimPerRec(stimRecNoCueField,:);...
        behAlignedAL.meanLickStimPerRec(stimRecALField,:);...
        behAlignedPL.meanLickStimPerRec(stimRecPLField,:)];
    
    behAlignedMean.meanSpeedPerRecField = ...
        [behAlignedNoCue.meanSpeedPerRec(nonStimGoodRecNoCueField,:);...
        behAlignedAL.meanSpeedPerRec(nonStimGoodRecALField,:);...
        behAlignedPL.meanSpeedPerRec(nonStimGoodRecPLField,:)];
    
    behAlignedMean.meanSpeedNonStimGoodPerRecField = ...
        [behAlignedNoCue.meanSpeedNonStimGoodPerRec(nonStimGoodRecNoCueField,:);...
        behAlignedAL.meanSpeedNonStimGoodPerRec(nonStimGoodRecALField,:);...
        behAlignedPL.meanSpeedNonStimGoodPerRec(nonStimGoodRecPLField,:)];
    
    fieldTmp = [behAlignedNoCue.speedTraceNonStimGoodPerRec(nonStimGoodRecNoCueField) ...
        behAlignedAL.speedTraceNonStimGoodPerRec(nonStimGoodRecALField) ...
        behAlignedPL.speedTraceNonStimGoodPerRec(nonStimGoodRecPLField)];
    behAlignedMean.speedTraceNonStimGoodPerRecField = [];
    for i = 1:length(fieldTmp)
        behAlignedMean.speedTraceNonStimGoodPerRecField = [...
            behAlignedMean.speedTraceNonStimGoodPerRecField; ...
            fieldTmp{i}];
    end
    behAlignedMean.meanSpeedTraceNonStimGoodPerRecField = ...
        mean(behAlignedMean.speedTraceNonStimGoodPerRecField);
    behAlignedMean.semSpeedTraceNonStimGoodPerRecField = ...
        std(behAlignedMean.speedTraceNonStimGoodPerRecField)/...
        sqrt(size(behAlignedMean.speedTraceNonStimGoodPerRecField,1));
    
    behAlignedMean.meanSpeedNonStimBadPerRecField = ...
        [behAlignedNoCue.meanSpeedNonStimBadPerRec(nonStimBadRecNoCueField,:);...
        behAlignedAL.meanSpeedNonStimBadPerRec(nonStimBadRecALField,:);...
        behAlignedPL.meanSpeedNonStimBadPerRec(nonStimBadRecPLField,:)];
    
    behAlignedMean.meanSpeedStimPerRecField = ...
        [behAlignedNoCue.meanSpeedStimPerRec(stimRecNoCueField,:);...
        behAlignedAL.meanSpeedStimPerRec(stimRecALField,:);...
        behAlignedPL.meanSpeedStimPerRec(stimRecPLField,:)];
    
    % mean behavior for recordings without fields
    behAlignedMean.meanLickPerRecNoField = ...
        [behAlignedNoCue.meanLickPerRec(behAligned.indRecNoCueNoField,:);...
        behAlignedAL.meanLickPerRec(behAligned.indRecALNoField,:);...
        behAlignedPL.meanLickPerRec(behAligned.indRecPLNoField,:)];
  
    [~,nonStimGoodRecNoCueNoField] = intersect(behAlignedNoCue.indRecNonStimGood,behAligned.indRecNoCueNoField);
    [~,nonStimGoodRecALNoField] = intersect(behAlignedAL.indRecNonStimGood,behAligned.indRecALNoField);
    [~,nonStimGoodRecPLNoField] = intersect(behAlignedPL.indRecNonStimGood,behAligned.indRecPLNoField);
    behAlignedMean.meanLickNonStimGoodPerRecNoField = ...
        [behAlignedNoCue.meanLickNonStimGoodPerRec(nonStimGoodRecNoCueNoField,:);...
        behAlignedAL.meanLickNonStimGoodPerRec(nonStimGoodRecALNoField,:);...
        behAlignedPL.meanLickNonStimGoodPerRec(nonStimGoodRecPLNoField,:)];
    
    noFieldTmp = [behAlignedNoCue.lickTraceNonStimGoodPerRec(nonStimGoodRecNoCueNoField) ...
        behAlignedAL.lickTraceNonStimGoodPerRec(nonStimGoodRecALNoField) ...
        behAlignedPL.lickTraceNonStimGoodPerRec(nonStimGoodRecPLNoField)];
    behAlignedMean.lickTraceNonStimGoodPerRecNoField = [];
    for i = 1:length(noFieldTmp)
        behAlignedMean.lickTraceNonStimGoodPerRecNoField = [...
            behAlignedMean.lickTraceNonStimGoodPerRecNoField; ...
            noFieldTmp{i}];
    end
    behAlignedMean.meanLickTraceNonStimGoodPerRecNoField = ...
        mean(behAlignedMean.lickTraceNonStimGoodPerRecNoField);
    behAlignedMean.semLickTraceNonStimGoodPerRecNoField = ...
        std(behAlignedMean.lickTraceNonStimGoodPerRecNoField)/...
        sqrt(size(behAlignedMean.lickTraceNonStimGoodPerRecNoField,1));
          
    [~,nonStimBadRecNoCueNoField] = intersect(behAlignedNoCue.indRecNonStimBad,behAligned.indRecNoCueNoField);
    [~,nonStimBadRecALNoField] = intersect(behAlignedAL.indRecNonStimBad,behAligned.indRecALNoField);
    [~,nonStimBadRecPLNoField] = intersect(behAlignedPL.indRecNonStimBad,behAligned.indRecPLNoField);
    behAlignedMean.meanLickNonStimBadPerRecNoField = ...
        [behAlignedNoCue.meanLickNonStimBadPerRec(nonStimBadRecNoCueNoField,:);...
        behAlignedAL.meanLickNonStimBadPerRec(nonStimBadRecALNoField,:);...
        behAlignedPL.meanLickNonStimBadPerRec(nonStimBadRecPLNoField,:)];
    
    [~,stimRecNoCueNoField] = intersect(behAlignedNoCue.indRecStim,behAligned.indRecNoCueNoField);
    [~,stimRecALNoField] = intersect(behAlignedAL.indRecStim,behAligned.indRecALNoField);
    [~,stimRecPLNoField] = intersect(behAlignedPL.indRecStim,behAligned.indRecPLNoField);
    behAlignedMean.meanLickStimPerRecNoField = ...
        [behAlignedNoCue.meanLickStimPerRec(stimRecNoCueNoField,:);...
        behAlignedAL.meanLickStimPerRec(stimRecALNoField,:);...
        behAlignedPL.meanLickStimPerRec(stimRecPLNoField,:)];
    
    behAlignedMean.meanSpeedPerRecNoField = ...
        [behAlignedNoCue.meanSpeedPerRec(behAligned.indRecNoCueNoField,:);...
        behAlignedAL.meanSpeedPerRec(behAligned.indRecALNoField,:);...
        behAlignedPL.meanSpeedPerRec(behAligned.indRecPLNoField,:)];
    
    behAlignedMean.meanSpeedNonStimGoodPerRecNoField = ...
        [behAlignedNoCue.meanSpeedNonStimGoodPerRec(nonStimGoodRecNoCueNoField,:);...
        behAlignedAL.meanSpeedNonStimGoodPerRec(nonStimGoodRecALNoField,:);...
        behAlignedPL.meanSpeedNonStimGoodPerRec(nonStimGoodRecPLNoField,:)];
    
    noFieldTmp = [behAlignedNoCue.speedTraceNonStimGoodPerRec(nonStimGoodRecNoCueNoField) ...
        behAlignedAL.speedTraceNonStimGoodPerRec(nonStimGoodRecALNoField) ...
        behAlignedPL.speedTraceNonStimGoodPerRec(nonStimGoodRecPLNoField)];
    behAlignedMean.speedTraceNonStimGoodPerRecNoField = [];
    for i = 1:length(noFieldTmp)
        behAlignedMean.speedTraceNonStimGoodPerRecNoField = [...
            behAlignedMean.speedTraceNonStimGoodPerRecNoField; ...
            noFieldTmp{i}];
    end
    behAlignedMean.meanSpeedTraceNonStimGoodPerRecNoField = ...
        mean(behAlignedMean.speedTraceNonStimGoodPerRecNoField);
    behAlignedMean.semSpeedTraceNonStimGoodPerRecNoField = ...
        std(behAlignedMean.speedTraceNonStimGoodPerRecNoField)/...
        sqrt(size(behAlignedMean.speedTraceNonStimGoodPerRecNoField,1));
    
    behAlignedMean.meanSpeedNonStimBadPerRecNoField = ...
        [behAlignedNoCue.meanSpeedNonStimBadPerRec(nonStimBadRecNoCueNoField,:);...
        behAlignedAL.meanSpeedNonStimBadPerRec(nonStimBadRecALNoField,:);...
        behAlignedPL.meanSpeedNonStimBadPerRec(nonStimBadRecPLNoField,:)];
    
    behAlignedMean.meanSpeedStimPerRecNoField = ...
        [behAlignedNoCue.meanSpeedStimPerRec(stimRecNoCueNoField,:);...
        behAlignedAL.meanSpeedStimPerRec(stimRecALNoField,:);...
        behAlignedPL.meanSpeedStimPerRec(stimRecPLNoField,:)];
end

function behAlignedMeanStat = accumMeanStat(behAlignedMean,spaceStepsLick,spaceStepsSpeed)
    
    %% total mean
    indLickAfter30 = find(spaceStepsLick >= 300 & spaceStepsLick < 2100);
    behAlignedMeanStat.indLickAfter30 = indLickAfter30;
    behAlignedMeanStat.meanLickPerRecField = [...
        mean(mean(behAlignedMean.meanLickPerRecField(:,indLickAfter30))),...
        mean(mean(behAlignedMean.meanLickPerRecNoField(:,indLickAfter30)))];
    behAlignedMeanStat.meanLickNonStimGoodPerRecField = [...
        mean(mean(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLickAfter30))),...
        mean(mean(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLickAfter30)))];
    behAlignedMeanStat.meanLickNonStimBadPerRecField = [...
        mean(mean(behAlignedMean.meanLickNonStimBadPerRecField(:,indLickAfter30))),...
        mean(mean(behAlignedMean.meanLickNonStimBadPerRecNoField(:,indLickAfter30)))];
    
    behAlignedMeanStat.pRSMeanLickPerRecField = ...
        ranksum(reshape(behAlignedMean.meanLickPerRecField(:,indLickAfter30),[],1),...
        reshape(behAlignedMean.meanLickPerRecNoField(:,indLickAfter30),[],1));
    behAlignedMeanStat.pRSMeanLickNonStimGoodPerRecField = ...
        ranksum(reshape(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLickAfter30),[],1),...
        reshape(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLickAfter30),[],1));
    behAlignedMeanStat.pRSMeanLickNonStimBadPerRecField = ...
        ranksum(reshape(behAlignedMean.meanLickNonStimBadPerRecField(:,indLickAfter30),[],1),...
        reshape(behAlignedMean.meanLickNonStimBadPerRecNoField(:,indLickAfter30),[],1));
    
    behAlignedMeanStat.pRSMeanLickNonStimGoodMeanPerRecField = ...
        ranksum(mean(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLickAfter30),2),...
        mean(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLickAfter30),2));
    
    behAlignedMeanStat.pRSLickTraceNonStimGoodMeanPerRecField = ...
        ranksum(mean(behAlignedMean.lickTraceNonStimGoodPerRecField(:,indLickAfter30),2),...
        mean(behAlignedMean.lickTraceNonStimGoodPerRecNoField(:,indLickAfter30),2));

    %% distance 30 to 100
    indLick30to100 = find(spaceStepsLick >= 300 & spaceStepsLick < 1000);
    behAlignedMeanStat.indLick30to100 = indLick30to100;
    behAlignedMeanStat.meanLickPerRecField30to100 = [...
        mean(mean(behAlignedMean.meanLickPerRecField(:,indLick30to100))),...
        mean(mean(behAlignedMean.meanLickPerRecNoField(:,indLick30to100)))];
    behAlignedMeanStat.meanLickNonStimGoodPerRecField30to100 = [...
        mean(mean(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLick30to100))),...
        mean(mean(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLick30to100)))];
    behAlignedMeanStat.meanLickNonStimBadPerRecField30to100 = [...
        mean(mean(behAlignedMean.meanLickNonStimBadPerRecField(:,indLick30to100))),...
        mean(mean(behAlignedMean.meanLickNonStimBadPerRecNoField(:,indLick30to100)))];
    
    behAlignedMeanStat.pRSMeanLickPerRecField30to100 = ...
        ranksum(reshape(behAlignedMean.meanLickPerRecField(:,indLick30to100),[],1),...
        reshape(behAlignedMean.meanLickPerRecNoField(:,indLick30to100),[],1));
    behAlignedMeanStat.pRSMeanLickNonStimGoodPerRecField30to100 = ...
        ranksum(reshape(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLick30to100),[],1),...
        reshape(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLick30to100),[],1));
    behAlignedMeanStat.pRSMeanLickNonStimBadPerRecField30to100 = ...
        ranksum(reshape(behAlignedMean.meanLickNonStimBadPerRecField(:,indLick30to100),[],1),...
        reshape(behAlignedMean.meanLickNonStimBadPerRecNoField(:,indLick30to100),[],1));
    
    behAlignedMeanStat.pRSMeanLickNonStimGoodMeanPerRecField30to100 = ...
        ranksum(mean(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLick30to100),2),...
        mean(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLick30to100),2));
    
    behAlignedMeanStat.pRSLickTraceNonStimGoodMeanPerRecField30to100 = ...
        ranksum(mean(behAlignedMean.lickTraceNonStimGoodPerRecField(:,indLick30to100),2),...
        mean(behAlignedMean.lickTraceNonStimGoodPerRecNoField(:,indLick30to100),2));
    
    %% distance 100 to 150
    indLick100to150 = find(spaceStepsLick >= 1000 & spaceStepsLick < 1500);
    behAlignedMeanStat.indLick100to150 = indLick100to150;
    behAlignedMeanStat.meanLickPerRecField100to150 = [...
        mean(mean(behAlignedMean.meanLickPerRecField(:,indLick100to150))),...
        mean(mean(behAlignedMean.meanLickPerRecNoField(:,indLick100to150)))];
    behAlignedMeanStat.meanLickNonStimGoodPerRecField100to150 = [...
        mean(mean(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLick100to150))),...
        mean(mean(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLick100to150)))];
    behAlignedMeanStat.meanLickNonStimBadPerRecField100to150 = [...
        mean(mean(behAlignedMean.meanLickNonStimBadPerRecField(:,indLick100to150))),...
        mean(mean(behAlignedMean.meanLickNonStimBadPerRecNoField(:,indLick100to150)))];
    
    behAlignedMeanStat.pRSMeanLickPerRecField100to150 = ...
        ranksum(reshape(behAlignedMean.meanLickPerRecField(:,indLick100to150),[],1),...
        reshape(behAlignedMean.meanLickPerRecNoField(:,indLick100to150),[],1));
    behAlignedMeanStat.pRSMeanLickNonStimGoodPerRecField100to150 = ...
        ranksum(reshape(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLick100to150),[],1),...
        reshape(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLick100to150),[],1));
    behAlignedMeanStat.pRSMeanLickNonStimBadPerRecField100to150 = ...
        ranksum(reshape(behAlignedMean.meanLickNonStimBadPerRecField(:,indLick100to150),[],1),...
        reshape(behAlignedMean.meanLickNonStimBadPerRecNoField(:,indLick100to150),[],1));
    
    behAlignedMeanStat.pRSMeanLickNonStimGoodMeanPerRecField100to150 = ...
        ranksum(mean(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLick100to150),2),...
        mean(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLick100to150),2));
    
    behAlignedMeanStat.pRSLickTraceNonStimGoodMeanPerRecField100to150 = ...
        ranksum(mean(behAlignedMean.lickTraceNonStimGoodPerRecField(:,indLick100to150),2),...
        mean(behAlignedMean.lickTraceNonStimGoodPerRecNoField(:,indLick100to150),2));
    
    %% distance 150 to 180
    indLick150to180 = find(spaceStepsLick >= 1500 & spaceStepsLick < 1800);
    behAlignedMeanStat.indLick150to180 = indLick150to180;
    behAlignedMeanStat.meanLickPerRecField150to180 = [...
        mean(mean(behAlignedMean.meanLickPerRecField(:,indLick150to180))),...
        mean(mean(behAlignedMean.meanLickPerRecNoField(:,indLick150to180)))];
    behAlignedMeanStat.meanLickNonStimGoodPerRecField150to180 = [...
        mean(mean(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLick150to180))),...
        mean(mean(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLick150to180)))];
    behAlignedMeanStat.meanLickNonStimBadPerRecField150to180 = [...
        mean(mean(behAlignedMean.meanLickNonStimBadPerRecField(:,indLick150to180))),...
        mean(mean(behAlignedMean.meanLickNonStimBadPerRecNoField(:,indLick150to180)))];
    
    behAlignedMeanStat.pRSMeanLickPerRecField150to180 = ...
        ranksum(reshape(behAlignedMean.meanLickPerRecField(:,indLick150to180),[],1),...
        reshape(behAlignedMean.meanLickPerRecNoField(:,indLick150to180),[],1));
    behAlignedMeanStat.pRSMeanLickNonStimGoodPerRecField150to180 = ...
        ranksum(reshape(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLick150to180),[],1),...
        reshape(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLick150to180),[],1));
    behAlignedMeanStat.pRSMeanLickNonStimBadPerRecField150to180 = ...
        ranksum(reshape(behAlignedMean.meanLickNonStimBadPerRecField(:,indLick150to180),[],1),...
        reshape(behAlignedMean.meanLickNonStimBadPerRecNoField(:,indLick150to180),[],1));
    
    behAlignedMeanStat.pRSMeanLickNonStimGoodMeanPerRecField150to180 = ...
        ranksum(mean(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLick150to180),2),...
        mean(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLick150to180),2));
    
    behAlignedMeanStat.pRSLickTraceNonStimGoodMeanPerRecField150to180 = ...
        ranksum(mean(behAlignedMean.lickTraceNonStimGoodPerRecField(:,indLick150to180),2),...
        mean(behAlignedMean.lickTraceNonStimGoodPerRecNoField(:,indLick150to180),2));
        
    %% distance after 180
    indLickAfter180 = find(spaceStepsLick >= 1800 & spaceStepsLick < 2100);
    behAlignedMeanStat.indLickAfter180 = indLickAfter180;
    behAlignedMeanStat.meanLickPerRecFieldAfter180 = [...
        mean(mean(behAlignedMean.meanLickPerRecField(:,indLickAfter180))),...
        mean(mean(behAlignedMean.meanLickPerRecNoField(:,indLickAfter180)))];
    behAlignedMeanStat.meanLickNonStimGoodPerRecFieldAfter180 = [...
        mean(mean(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLickAfter180))),...
        mean(mean(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLickAfter180)))];
    behAlignedMeanStat.meanLickNonStimBadPerRecFieldAfter180 = [...
        mean(mean(behAlignedMean.meanLickNonStimBadPerRecField(:,indLickAfter180))),...
        mean(mean(behAlignedMean.meanLickNonStimBadPerRecNoField(:,indLickAfter180)))];
    
    behAlignedMeanStat.pRSMeanLickPerRecFieldAfter180 = ...
        ranksum(reshape(behAlignedMean.meanLickPerRecField(:,indLickAfter180),[],1),...
        reshape(behAlignedMean.meanLickPerRecNoField(:,indLickAfter180),[],1));
    behAlignedMeanStat.pRSMeanLickNonStimGoodPerRecFieldAfter180 = ...
        ranksum(reshape(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLickAfter180),[],1),...
        reshape(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLickAfter180),[],1));
    behAlignedMeanStat.pRSMeanLickNonStimBadPerRecFieldAfter180 = ...
        ranksum(reshape(behAlignedMean.meanLickNonStimBadPerRecField(:,indLickAfter180),[],1),...
        reshape(behAlignedMean.meanLickNonStimBadPerRecNoField(:,indLickAfter180),[],1));
    
    behAlignedMeanStat.pRSMeanLickNonStimGoodMeanPerRecFieldAfter180 = ...
        ranksum(mean(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLickAfter180),2),...
        mean(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLickAfter180),2));
    
    behAlignedMeanStat.pRSLickTraceNonStimGoodMeanPerRecFieldAfter180 = ...
        ranksum(mean(behAlignedMean.lickTraceNonStimGoodPerRecField(:,indLickAfter180),2),...
        mean(behAlignedMean.lickTraceNonStimGoodPerRecNoField(:,indLickAfter180),2));
    
    %% total mean
    behAlignedMeanStat.meanSpeedPerRecField = [...
        mean(behAlignedMean.meanSpeedPerRecField(:)),...
        mean(behAlignedMean.meanSpeedPerRecNoField(:))];
    behAlignedMeanStat.meanSpeedNonStimGoodPerRecField = [...
        mean(behAlignedMean.meanSpeedNonStimGoodPerRecField(:)),...
        mean(behAlignedMean.meanSpeedNonStimGoodPerRecNoField(:))];
    behAlignedMeanStat.meanSpeedNonStimBadPerRecField = [...
        mean(behAlignedMean.meanSpeedNonStimBadPerRecField(:)),...
        mean(behAlignedMean.meanSpeedNonStimBadPerRecNoField(:))];
    
    behAlignedMeanStat.pRSMeanSpeedPerRecField = ...
        ranksum(behAlignedMean.meanSpeedPerRecField(:),...
        behAlignedMean.meanSpeedPerRecNoField(:));
    behAlignedMeanStat.pRSMeanSpeedNonStimGoodPerRecField = ...
        ranksum(behAlignedMean.meanSpeedNonStimGoodPerRecField(:),...
        behAlignedMean.meanSpeedNonStimGoodPerRecNoField(:));
    behAlignedMeanStat.pRSMeanSpeedNonStimBadPerRecField = ...
        ranksum(behAlignedMean.meanSpeedNonStimBadPerRecField(:),...
        behAlignedMean.meanSpeedNonStimBadPerRecNoField(:));
    
    behAlignedMeanStat.pRSMeanSpeedNonStimGoodMeanPerRecField = ...
        ranksum(mean(behAlignedMean.meanSpeedNonStimGoodPerRecField,2),...
        mean(behAlignedMean.meanSpeedNonStimGoodPerRecNoField,2));
    
    behAlignedMeanStat.pRSSpeedTraceNonStimGoodMeanPerRecField = ...
        ranksum(mean(behAlignedMean.speedTraceNonStimGoodPerRecField,2),...
        mean(behAlignedMean.speedTraceNonStimGoodPerRecNoField,2));
    
    %% distance 30 to 100
    indSpeed30to100 = find(spaceStepsSpeed >= 300 & spaceStepsSpeed < 1000);
    behAlignedMeanStat.indSpeed30to100 = indSpeed30to100;
    behAlignedMeanStat.meanSpeedPerRecField30to100 = [...
        mean(mean(behAlignedMean.meanSpeedPerRecField(:,indSpeed30to100))),...
        mean(mean(behAlignedMean.meanSpeedPerRecNoField(:,indSpeed30to100)))];
    behAlignedMeanStat.meanSpeedNonStimGoodPerRecField30to100 = [...
        mean(mean(behAlignedMean.meanSpeedNonStimGoodPerRecField(:,indSpeed30to100))),...
        mean(mean(behAlignedMean.meanSpeedNonStimGoodPerRecNoField(:,indSpeed30to100)))];
    behAlignedMeanStat.meanSpeedNonStimBadPerRecField30to100 = [...
        mean(mean(behAlignedMean.meanSpeedNonStimBadPerRecField(:,indSpeed30to100))),...
        mean(mean(behAlignedMean.meanSpeedNonStimBadPerRecNoField(:,indSpeed30to100)))];
    
    behAlignedMeanStat.pRSMeanSpeedPerRecField30to100 = ...
        ranksum(reshape(behAlignedMean.meanSpeedPerRecField(:,indSpeed30to100),[],1),...
        reshape(behAlignedMean.meanSpeedPerRecNoField(:,indSpeed30to100),[],1));
    behAlignedMeanStat.pRSMeanSpeedNonStimGoodPerRecField30to100 = ...
        ranksum(reshape(behAlignedMean.meanSpeedNonStimGoodPerRecField(:,indSpeed30to100),[],1),...
        reshape(behAlignedMean.meanSpeedNonStimGoodPerRecNoField(:,indSpeed30to100),[],1));
    behAlignedMeanStat.pRSMeanSpeedNonStimBadPerRecField30to100 = ...
        ranksum(reshape(behAlignedMean.meanSpeedNonStimBadPerRecField(:,indSpeed30to100),[],1),...
        reshape(behAlignedMean.meanSpeedNonStimBadPerRecNoField(:,indSpeed30to100),[],1));
    
    behAlignedMeanStat.pRSMeanSpeedNonStimGoodMeanPerRecField30to100 = ...
        ranksum(mean(behAlignedMean.meanSpeedNonStimGoodPerRecField(:,indSpeed30to100),2),...
        mean(behAlignedMean.meanSpeedNonStimGoodPerRecNoField(:,indSpeed30to100),2));
    
    behAlignedMeanStat.pRSSpeedTraceNonStimGoodMeanPerRecField30to100 = ...
        ranksum(mean(behAlignedMean.speedTraceNonStimGoodPerRecField(:,indSpeed30to100),2),...
        mean(behAlignedMean.speedTraceNonStimGoodPerRecNoField(:,indSpeed30to100),2));
    
    %% distance > 100
    indSpeedAfter100 = find(spaceStepsSpeed >= 1000);
    behAlignedMeanStat.indSpeedAfter100 = indSpeedAfter100;
    behAlignedMeanStat.meanSpeedPerRecFieldAfter100 = [...
        mean(mean(behAlignedMean.meanSpeedPerRecField(:,indSpeedAfter100))),...
        mean(mean(behAlignedMean.meanSpeedPerRecNoField(:,indSpeedAfter100)))];
    behAlignedMeanStat.meanSpeedNonStimGoodPerRecFieldAfter100 = [...
        mean(mean(behAlignedMean.meanSpeedNonStimGoodPerRecField(:,indSpeedAfter100))),...
        mean(mean(behAlignedMean.meanSpeedNonStimGoodPerRecNoField(:,indSpeedAfter100)))];
    behAlignedMeanStat.meanSpeedNonStimBadPerRecFieldAfter100 = [...
        mean(mean(behAlignedMean.meanSpeedNonStimBadPerRecField(:,indSpeedAfter100))),...
        mean(mean(behAlignedMean.meanSpeedNonStimBadPerRecNoField(:,indSpeedAfter100)))];
    
    behAlignedMeanStat.pRSMeanSpeedPerRecFieldAfter100 = ...
        ranksum(reshape(behAlignedMean.meanSpeedPerRecField(:,indSpeedAfter100),[],1),...
        reshape(behAlignedMean.meanSpeedPerRecNoField(:,indSpeedAfter100),[],1));
    behAlignedMeanStat.pRSMeanSpeedNonStimGoodPerRecFieldAfter100 = ...
        ranksum(reshape(behAlignedMean.meanSpeedNonStimGoodPerRecField(:,indSpeedAfter100),[],1),...
        reshape(behAlignedMean.meanSpeedNonStimGoodPerRecNoField(:,indSpeedAfter100),[],1));
    behAlignedMeanStat.pRSMeanSpeedNonStimBadPerRecFieldAfter100 = ...
        ranksum(reshape(behAlignedMean.meanSpeedNonStimBadPerRecField(:,indSpeedAfter100),[],1),...
        reshape(behAlignedMean.meanSpeedNonStimBadPerRecNoField(:,indSpeedAfter100),[],1));
    
    behAlignedMeanStat.pRSMeanSpeedNonStimGoodMeanPerRecFieldAfter100 = ...
        ranksum(mean(behAlignedMean.meanSpeedNonStimGoodPerRecField(:,indSpeedAfter100),2),...
        mean(behAlignedMean.meanSpeedNonStimGoodPerRecNoField(:,indSpeedAfter100),2));
    
    behAlignedMeanStat.pRSSpeedTraceNonStimGoodMeanPerRecFieldAfter100 = ...
        ranksum(mean(behAlignedMean.speedTraceNonStimGoodPerRecField(:,indSpeedAfter100),2),...
        mean(behAlignedMean.speedTraceNonStimGoodPerRecNoField(:,indSpeedAfter100),2));

end

function plotBoxPlot(x1,x2,yl,fn,pathAnal,ylimit,p,colorSel)
    [figNew,pos] = CreateFig();
    set(0,'Units','pixels')
    set(figure(figNew),'OuterPosition',...
            [pos(1) pos(2) 200 400])
    if(colorSel == 0)
        colorArr = [163 207 98;...
                234 131 114]/255;
    elseif(colorSel == 1)            
        colorArr = [234 131 114;...
                116 53 61]/255;
    else        
        colorArr = [163 207 98;... 
            63 79 37]/255;
    end
    x = [x1;x2];
    g = [repmat({'C1'},length(x1),1);...
        repmat({'C2'},length(x2),1)];
    boxplot(x,g,'Notch','on','Widths',0.3,'Symbol','');
    h = findobj(gca,'Tag','Box');
    for j = 1:length(h)
        patch(get(h(j),'XData'),get(h(j),'YData'),colorArr(j,:),'FaceAlpha',0.5);
    end
    if(~isempty(ylimit))
        set(gca,'YLim',ylimit);
    end
    ylabel(yl);
    title(['p = ' num2str(p)]);
    
    fileName1 = [pathAnal fn];
    saveas(gcf,fileName1);
    print('-painters', '-dpdf', fileName1, '-r600')
end

function plotSpeed(pathAnal,spaceStepsSpeed,speedField,speedNoField,leg,fileName1)
    options.handle     = figure;
    set(options.handle,'OuterPosition',...
        [500 500 280 280])
    options.color_areaX = [27 117 187]./255;    % Blue theme
    options.color_lineX = [ 39 169 225]./255;
    options.color_areaY = [187 189 192]./255;    % Orange theme
    options.color_lineY = [167 169  171]./255;
    options.alpha      = 0.5;
    options.line_width = 0.5;
    options.error      = 'sem';
    options.x_axisX = spaceStepsSpeed/10;
    options.x_axisY = spaceStepsSpeed/10;
    plot_areaerrorbarXY(speedField, speedNoField,...
        options);
    set(gca,'XLim',[0 180]);
    xlabel('Dist (cm)')
    ylabel('Speed (cm/s) ')
    legend('',leg{1},'',leg{2})
        
    saveas(gcf,fileName1);
    print('-painters', '-dpdf', fileName1, '-r600')
end

function plotSpeedRec(pathAnal,spaceStepsSpeed,data_meanX,errorX,xli,fileName)
    options.handle     = figure;
    set(options.handle,'OuterPosition',...
        [500 500 280 280])
    options.color_areaX = [27 117 187]./255;    % Blue theme
    options.color_lineX = [ 39 169 225]./255;
    options.alpha      = 0.5;
    options.line_width = 0.5;
    options.error      = 'sem';
    options.x_axisX = spaceStepsSpeed;
    options.x_axisY = spaceStepsSpeed;
    figure(options.handle);
    x_vectorX = [options.x_axisX, fliplr(options.x_axisX)];
    patch = fill(x_vectorX, [data_meanX+errorX,fliplr(data_meanX-errorX)], options.color_areaX);
    set(patch, 'edgecolor', 'none');
    set(patch, 'FaceAlpha', options.alpha);
    hold on;
    plot(options.x_axisX, data_meanX, 'color', options.color_lineX, ...
        'LineWidth', options.line_width);
    set(gca,'XLim',xli);
    xlabel('Time (s)')
    ylabel('Speed (cm/s) ')
    
    fileName1 = [pathAnal ...
        'SpeedVsDist-' fileName];
    saveas(gcf,fileName1);
    print('-painters', '-dpdf', fileName1, '-r600')
end

function plotLick(pathAnal,spaceStepsLick,lickField,lickNoField,leg,fileName1)
    options.handle     = figure;
    set(options.handle,'OuterPosition',...
        [500 500 280 280])
    options.color_areaX = [27 117 187]./255;    % Blue theme
    options.color_lineX = [ 39 169 225]./255;
    options.color_areaY = [187 189 192]./255;    % Orange theme
    options.color_lineY = [167 169  171]./255;
    options.alpha      = 0.5;
    options.line_width = 0.5;
    options.error      = 'sem';
    options.x_axisX = spaceStepsLick/10;
    options.x_axisY = spaceStepsLick/10;
    plot_areaerrorbarXY(lickField, lickNoField,...
        options);
    set(gca,'XLim',[30 210]);
    xlabel('Dist (cm)')
    ylabel('Num. licks')
    legend('',leg{1},'',leg{2})
    
    saveas(gcf,fileName1);
    print('-painters', '-dpdf', fileName1, '-r600')
end

function plotBehAlignedMean(pathAnal,behAlignedMean,behAlignedMeanStat)
    colorSel = 0;
    % total licks
    plotBoxPlot(reshape(behAlignedMean.meanLickPerRecField(:,behAlignedMeanStat.indLickAfter30),[],1),...
        reshape(behAlignedMean.meanLickPerRecNoField(:,behAlignedMeanStat.indLickAfter30),[],1),...
        'No. licks','meanLickPerRecFieldVsNoFieldBox',...
        pathAnal,[-0.1 0.5],behAlignedMeanStat.pRSMeanLickPerRecField,colorSel);
    
    plotBoxPlot(reshape(behAlignedMean.meanLickNonStimGoodPerRecField(:,behAlignedMeanStat.indLickAfter30),[],1),...
        reshape(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,behAlignedMeanStat.indLickAfter30),[],1),...
        'No. licks (good trials)','meanLickNonStimGoodPerRecFieldVsNoFieldBox',...
        pathAnal,[-0.1 0.5],behAlignedMeanStat.pRSMeanLickNonStimGoodPerRecField,colorSel);
    
    plotBoxPlot(reshape(behAlignedMean.meanLickNonStimBadPerRecField(:,behAlignedMeanStat.indLickAfter30),[],1),...
        reshape(behAlignedMean.meanLickNonStimBadPerRecNoField(:,behAlignedMeanStat.indLickAfter30),[],1),...
        'No. licks (bad trials)','meanLickNonStimBadPerRecFieldVsNoFieldBox',...
        pathAnal,[-0.1 0.5],behAlignedMeanStat.pRSMeanLickNonStimBadPerRecField,colorSel);
    
    plotBoxPlot(mean(behAlignedMean.lickTraceNonStimGoodPerRecField(:,behAlignedMeanStat.indLickAfter30),2),...
        mean(behAlignedMean.lickTraceNonStimGoodPerRecNoField(:,behAlignedMeanStat.indLickAfter30),2),...
        'No. licks (good trials)','lickTraceNonStimGoodPerRecFieldVsNoFieldBox',...
        pathAnal,[-0.1 0.5],behAlignedMeanStat.pRSLickTraceNonStimGoodMeanPerRecField,colorSel);
    
    % distance 30 to 100 cm
    plotBoxPlot(reshape(behAlignedMean.meanLickPerRecField(:,behAlignedMeanStat.indLick30to100),[],1),...
        reshape(behAlignedMean.meanLickPerRecNoField(:,behAlignedMeanStat.indLick30to100),[],1),...
        'No. licks (30-100 cm)','meanLickPerRecFieldVsNoField30to100Box',...
        pathAnal,[-0.1 0.2],behAlignedMeanStat.pRSMeanLickPerRecField30to100,colorSel);
    
    plotBoxPlot(reshape(behAlignedMean.meanLickNonStimGoodPerRecField(:,behAlignedMeanStat.indLick30to100),[],1),...
        reshape(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,behAlignedMeanStat.indLick30to100),[],1),...
        'No. licks (good trials, 30-100 cm)','meanLickNonStimGoodPerRecFieldVsNoField30to100Box',...
        pathAnal,[-0.1 0.2],behAlignedMeanStat.pRSMeanLickNonStimGoodPerRecField30to100,colorSel);
    
    plotBoxPlot(reshape(behAlignedMean.meanLickNonStimBadPerRecField(:,behAlignedMeanStat.indLick30to100),[],1),...
        reshape(behAlignedMean.meanLickNonStimBadPerRecNoField(:,behAlignedMeanStat.indLick30to100),[],1),...
        'No. licks (bad trials, 30-100 cm)','meanLickNonStimBadPerRecFieldVsNoField30to100Box',...
        pathAnal,[-0.1 0.2],behAlignedMeanStat.pRSMeanLickNonStimBadPerRecField30to100,colorSel);
    
    plotBoxPlot(mean(behAlignedMean.lickTraceNonStimGoodPerRecField(:,behAlignedMeanStat.indLick30to100),2),...
        mean(behAlignedMean.lickTraceNonStimGoodPerRecNoField(:,behAlignedMeanStat.indLick30to100),2),...
        'No. licks (good trials, 30-100 cm)','lickTraceNonStimGoodPerRecFieldVsNoField30to100Box',...
        pathAnal,[-0.1 0.2],behAlignedMeanStat.pRSLickTraceNonStimGoodMeanPerRecField30to100,colorSel);
    
    % distance 100 to 150 cm
    plotBoxPlot(reshape(behAlignedMean.meanLickPerRecField(:,behAlignedMeanStat.indLick100to150),[],1),...
        reshape(behAlignedMean.meanLickPerRecNoField(:,behAlignedMeanStat.indLick100to150),[],1),...
        'No. licks (100-150 cm)','meanLickPerRecFieldVsNoField100to150Box',...
        pathAnal,[-0.1 0.4],behAlignedMeanStat.pRSMeanLickPerRecField100to150,colorSel);
    
    plotBoxPlot(reshape(behAlignedMean.meanLickNonStimGoodPerRecField(:,behAlignedMeanStat.indLick100to150),[],1),...
        reshape(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,behAlignedMeanStat.indLick100to150),[],1),...
        'No. licks (good trials, 100-150 cm)','meanLickNonStimGoodPerRecFieldVsNoField100to150Box',...
        pathAnal,[-0.1 0.4],behAlignedMeanStat.pRSMeanLickNonStimGoodPerRecField100to150,colorSel);
    
    plotBoxPlot(reshape(behAlignedMean.meanLickNonStimBadPerRecField(:,behAlignedMeanStat.indLick100to150),[],1),...
        reshape(behAlignedMean.meanLickNonStimBadPerRecNoField(:,behAlignedMeanStat.indLick100to150),[],1),...
        'No. licks (bad trials, 100-150 cm)','meanLickNonStimBadPerRecFieldVsNoField100to150Box',...
        pathAnal,[-0.1 0.4],behAlignedMeanStat.pRSMeanLickNonStimBadPerRecField100to150,colorSel);
    
    plotBoxPlot(mean(behAlignedMean.lickTraceNonStimGoodPerRecField(:,behAlignedMeanStat.indLick100to150),2),...
        mean(behAlignedMean.lickTraceNonStimGoodPerRecNoField(:,behAlignedMeanStat.indLick100to150),2),...
        'No. licks (good trials, 100-150 cm)','lickTraceNonStimGoodPerRecFieldVsNoField100to150Box',...
        pathAnal,[-0.1 0.4],behAlignedMeanStat.pRSLickTraceNonStimGoodMeanPerRecField100to150,colorSel);
    
    % distance 150 to 180 cm
    plotBoxPlot(reshape(behAlignedMean.meanLickPerRecField(:,behAlignedMeanStat.indLick150to180),[],1),...
        reshape(behAlignedMean.meanLickPerRecNoField(:,behAlignedMeanStat.indLick150to180),[],1),...
        'No. licks (150-180 cm)','meanLickPerRecFieldVsNoField150to180Box',...
        pathAnal,[-0.1 0.8],behAlignedMeanStat.pRSMeanLickPerRecField150to180,colorSel);
    
    plotBoxPlot(reshape(behAlignedMean.meanLickNonStimGoodPerRecField(:,behAlignedMeanStat.indLick150to180),[],1),...
        reshape(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,behAlignedMeanStat.indLick150to180),[],1),...
        'No. licks (good trials, 150-180 cm)','meanLickNonStimGoodPerRecFieldVsNoField150to180Box',...
        pathAnal,[-0.1 0.8],behAlignedMeanStat.pRSMeanLickNonStimGoodPerRecField150to180,colorSel);
    
    plotBoxPlot(reshape(behAlignedMean.meanLickNonStimBadPerRecField(:,behAlignedMeanStat.indLick150to180),[],1),...
        reshape(behAlignedMean.meanLickNonStimBadPerRecNoField(:,behAlignedMeanStat.indLick150to180),[],1),...
        'No. licks (bad trials, 150-180 cm)','meanLickNonStimBadPerRecFieldVsNoField150to180Box',...
        pathAnal,[-0.1 0.8],behAlignedMeanStat.pRSMeanLickNonStimBadPerRecField150to180,colorSel);
    
    plotBoxPlot(mean(behAlignedMean.lickTraceNonStimGoodPerRecField(:,behAlignedMeanStat.indLick150to180),2),...
        mean(behAlignedMean.lickTraceNonStimGoodPerRecNoField(:,behAlignedMeanStat.indLick150to180),2),...
        'No. licks (good trials, 150-180 cm)','lickTraceNonStimGoodPerRecFieldVsNoField150to180Box',...
        pathAnal,[-0.1 0.9],behAlignedMeanStat.pRSLickTraceNonStimGoodMeanPerRecField150to180,colorSel);
    
    % distance after 180 cm
    plotBoxPlot(reshape(behAlignedMean.meanLickPerRecField(:,behAlignedMeanStat.indLickAfter180),[],1),...
        reshape(behAlignedMean.meanLickPerRecNoField(:,behAlignedMeanStat.indLickAfter180),[],1),...
        'No. licks (>=180 cm)','meanLickPerRecFieldVsNoFieldAfter180Box',...
        pathAnal,[-0.1 1.5],behAlignedMeanStat.pRSMeanLickPerRecFieldAfter180,colorSel);
    
    plotBoxPlot(reshape(behAlignedMean.meanLickNonStimGoodPerRecField(:,behAlignedMeanStat.indLickAfter180),[],1),...
        reshape(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,behAlignedMeanStat.indLickAfter180),[],1),...
        'No. licks (good trials, >=180 cm)','meanLickNonStimGoodPerRecFieldVsNoFieldAfter180Box',...
        pathAnal,[-0.1 1.5],behAlignedMeanStat.pRSMeanLickNonStimGoodPerRecFieldAfter180,colorSel);
    
    plotBoxPlot(reshape(behAlignedMean.meanLickNonStimBadPerRecField(:,behAlignedMeanStat.indLickAfter180),[],1),...
        reshape(behAlignedMean.meanLickNonStimBadPerRecNoField(:,behAlignedMeanStat.indLickAfter180),[],1),...
        'No. licks (bad trials, >=180 cm)','meanLickNonStimBadPerRecFieldVsNoFieldAfter180Box',...
        pathAnal,[-0.1 1.5],behAlignedMeanStat.pRSMeanLickNonStimBadPerRecFieldAfter180,colorSel);
    
    plotBoxPlot(mean(behAlignedMean.lickTraceNonStimGoodPerRecField(:,behAlignedMeanStat.indLickAfter180),2),...
        mean(behAlignedMean.lickTraceNonStimGoodPerRecNoField(:,behAlignedMeanStat.indLickAfter180),2),...
        'No. licks (good trials)','lickTraceNonStimGoodPerRecFieldVsNoFieldAfter180Box',...
        pathAnal,[-0.1 1.5],behAlignedMeanStat.pRSLickTraceNonStimGoodMeanPerRecFieldAfter180,colorSel);
    
    % mean speed
    plotBoxPlot(behAlignedMean.meanSpeedPerRecField(:)/10,...
        behAlignedMean.meanSpeedPerRecNoField(:)/10,...
        'Speed (cm/s)','meanSpeedPerRecFieldVsNoFieldBox',...
        pathAnal,[10 70],behAlignedMeanStat.pRSMeanSpeedPerRecField,colorSel);
    
    plotBoxPlot(behAlignedMean.meanSpeedNonStimGoodPerRecField(:)/10,...
        behAlignedMean.meanSpeedNonStimGoodPerRecNoField(:)/10,...
        'Speed (cm/s) good trials','meanSpeedNonStimGoodPerRecFieldVsNoFieldBox',...
        pathAnal,[10 70],behAlignedMeanStat.pRSMeanSpeedNonStimGoodPerRecField,colorSel);
    
    plotBoxPlot(behAlignedMean.meanSpeedNonStimBadPerRecField(:)/10,...
        behAlignedMean.meanSpeedNonStimBadPerRecNoField(:)/10,...
        'Speed (cm/s) bad trials','meanSpeedNonStimBadPerRecFieldVsNoFieldBox',...
        pathAnal,[0 70],behAlignedMeanStat.pRSMeanSpeedNonStimBadPerRecField,colorSel);
    
    plotBoxPlot(mean(behAlignedMean.speedTraceNonStimGoodPerRecField,2)/10,...
        mean(behAlignedMean.speedTraceNonStimGoodPerRecNoField,2)/10,...
        'Speed (cm/s) good trials','speedTraceNonStimGoodPerRecFieldVsNoFieldBox',...
        pathAnal,[0 70],behAlignedMeanStat.pRSSpeedTraceNonStimGoodMeanPerRecField,colorSel);
    
    % distance 30 to 100 cm
    plotBoxPlot(reshape(behAlignedMean.meanSpeedPerRecField(:,behAlignedMeanStat.indSpeed30to100),[],1)/10,...
        reshape(behAlignedMean.meanSpeedPerRecNoField(:,behAlignedMeanStat.indSpeed30to100),[],1)/10,...
        'Speed (30-100 cm)','meanSpeedPerRecFieldVsNoField30to100Box',...
        pathAnal,[10 70],behAlignedMeanStat.pRSMeanSpeedPerRecField30to100,colorSel);
    
    plotBoxPlot(reshape(behAlignedMean.meanSpeedNonStimGoodPerRecField(:,behAlignedMeanStat.indSpeed30to100),[],1)/10,...
        reshape(behAlignedMean.meanSpeedNonStimGoodPerRecNoField(:,behAlignedMeanStat.indSpeed30to100),[],1)/10,...
        'Speed (good trials, 30-100 cm)','meanSpeedNonStimGoodPerRecFieldVsNoField30to100Box',...
        pathAnal,[10 70],behAlignedMeanStat.pRSMeanSpeedNonStimGoodPerRecField30to100,colorSel);
    
    plotBoxPlot(reshape(behAlignedMean.meanSpeedNonStimBadPerRecField(:,behAlignedMeanStat.indSpeed30to100),[],1)/10,...
        reshape(behAlignedMean.meanSpeedNonStimBadPerRecNoField(:,behAlignedMeanStat.indSpeed30to100),[],1)/10,...
        'Speed (bad trials, 30-100 cm)','meanSpeedNonStimBadPerRecFieldVsNoField30to100Box',...
        pathAnal,[10 70],behAlignedMeanStat.pRSMeanSpeedNonStimBadPerRecField30to100,colorSel);
    
    plotBoxPlot(mean(behAlignedMean.speedTraceNonStimGoodPerRecField(:,behAlignedMeanStat.indSpeed30to100),2)/10,...
        mean(behAlignedMean.speedTraceNonStimGoodPerRecNoField(:,behAlignedMeanStat.indSpeed30to100),2)/10,...
        'Speed (good trials, 30-100 cm)','speedTraceNonStimGoodPerRecFieldVsNoField30to100Box',...
        pathAnal,[10 80],behAlignedMeanStat.pRSSpeedTraceNonStimGoodMeanPerRecField30to100,colorSel);
    
    % distance after 100 cm
    plotBoxPlot(reshape(behAlignedMean.meanSpeedPerRecField(:,behAlignedMeanStat.indSpeedAfter100),[],1)/10,...
        reshape(behAlignedMean.meanSpeedPerRecNoField(:,behAlignedMeanStat.indSpeedAfter100),[],1)/10,...
        'Speed (>=100 cm)','meanSpeedPerRecFieldVsNoFieldAfter100Box',...
        pathAnal,[10 70],behAlignedMeanStat.pRSMeanSpeedPerRecFieldAfter100,colorSel);
    
    plotBoxPlot(reshape(behAlignedMean.meanSpeedNonStimGoodPerRecField(:,behAlignedMeanStat.indSpeedAfter100),[],1)/10,...
        reshape(behAlignedMean.meanSpeedNonStimGoodPerRecNoField(:,behAlignedMeanStat.indSpeedAfter100),[],1)/10,...
        'Speed (good trials, >=100 cm)','meanSpeedNonStimGoodPerRecFieldVsNoFieldAfter100Box',...
        pathAnal,[10 70],behAlignedMeanStat.pRSMeanSpeedNonStimGoodPerRecFieldAfter100,colorSel);
    
    plotBoxPlot(reshape(behAlignedMean.meanSpeedNonStimBadPerRecField(:,behAlignedMeanStat.indSpeedAfter100),[],1)/10,...
        reshape(behAlignedMean.meanSpeedNonStimBadPerRecNoField(:,behAlignedMeanStat.indSpeedAfter100),[],1)/10,...
        'Speed (bad trials, >=100 cm)','meanSpeedNonStimBadPerRecFieldVsNoFieldAfter100Box',...
        pathAnal,[10 70],behAlignedMeanStat.pRSMeanSpeedNonStimBadPerRecFieldAfter100,colorSel);
    
    plotBoxPlot(mean(behAlignedMean.speedTraceNonStimGoodPerRecField(:,behAlignedMeanStat.indSpeedAfter100),2)/10,...
        mean(behAlignedMean.speedTraceNonStimGoodPerRecNoField(:,behAlignedMeanStat.indSpeedAfter100),2)/10,...
        'Speed (good trials, 30-100 cm)','speedTraceNonStimGoodPerRecFieldVsNoFieldAfter100Box',...
        pathAnal,[10 70],behAlignedMeanStat.pRSSpeedTraceNonStimGoodMeanPerRecFieldAfter100,colorSel);
end

function plotBehAlignedMeanGoodBad(pathAnal,behAlignedMean,behAlignedMeanStat)
    colorSel = 0;
    % total licks
    plotBoxPlot(reshape(behAlignedMean.meanLickPerRecNonStimGood(:,behAlignedMeanStat.indLickAfter30),[],1),...
        reshape(behAlignedMean.meanLickPerRecNonStimBad(:,behAlignedMeanStat.indLickAfter30),[],1),...
        'No. licks','meanLickPerRecGoodVsBadBox',...
        pathAnal,[-0.1 0.5],behAlignedMeanStat.pRSMeanLickMeanPerRec,colorSel);
   
    plotBoxPlot(mean(behAlignedMean.lickTraceNonStimGoodPerRec(:,behAlignedMeanStat.indLickAfter30),2),...
        mean(behAlignedMean.lickTraceNonStimBadPerRec(:,behAlignedMeanStat.indLickAfter30),2),...
        'No. licks','lickTracePerRecGoodVsBadBox',...
        pathAnal,[-0.1 0.5],behAlignedMeanStat.pRSMeanLickTracePerRec,colorSel);
    
    % distance 30 to 100 cm
    plotBoxPlot(reshape(behAlignedMean.meanLickPerRecNonStimGood(:,behAlignedMeanStat.indLick30to100),[],1),...
        reshape(behAlignedMean.meanLickPerRecNonStimBad(:,behAlignedMeanStat.indLick30to100),[],1),...
        'No. licks (30-100 cm)','meanLickPerRecGoodVsBad30to100Box',...
        pathAnal,[-0.1 0.2],behAlignedMeanStat.pRSMeanLickMeanPerRec30to100,colorSel);
    
    plotBoxPlot(mean(behAlignedMean.lickTraceNonStimGoodPerRec(:,behAlignedMeanStat.indLick30to100),2),...
        mean(behAlignedMean.lickTraceNonStimBadPerRec(:,behAlignedMeanStat.indLick30to100),2),...
        'No. licks (30-100 cm)','lickTracePerRecGoodVsBad30to100Box',...
        pathAnal,[-0.1 0.2],behAlignedMeanStat.pRSMeanLickTracePerRec30to100,colorSel);
    
    % distance 100 to 150 cm
    plotBoxPlot(reshape(behAlignedMean.meanLickPerRecNonStimGood(:,behAlignedMeanStat.indLick100to150),[],1),...
        reshape(behAlignedMean.meanLickPerRecNonStimBad(:,behAlignedMeanStat.indLick100to150),[],1),...
        'No. licks (100-150 cm)','meanLickPerRecGoodVsBad100to150Box',...
        pathAnal,[-0.1 0.4],behAlignedMeanStat.pRSMeanLickMeanPerRec100to150,colorSel);
    
    plotBoxPlot(mean(behAlignedMean.lickTraceNonStimGoodPerRec(:,behAlignedMeanStat.indLick100to150),2),...
        mean(behAlignedMean.lickTraceNonStimBadPerRec(:,behAlignedMeanStat.indLick100to150),2),...
        'No. licks (100-150 cm)','lickTracePerRecGoodVsBad100to150Box',...
        pathAnal,[-0.1 0.4],behAlignedMeanStat.pRSMeanLickTracePerRec100to150,colorSel);
    
    % distance 150 to 180 cm
    plotBoxPlot(reshape(behAlignedMean.meanLickPerRecNonStimGood(:,behAlignedMeanStat.indLick150to180),[],1),...
        reshape(behAlignedMean.meanLickPerRecNonStimBad(:,behAlignedMeanStat.indLick150to180),[],1),...
        'No. licks (150-180 cm)','meanLickPerRecGoodVsBad150to180Box',...
        pathAnal,[-0.1 0.85],behAlignedMeanStat.pRSMeanLickMeanPerRec150to180,colorSel);
    
    plotBoxPlot(mean(behAlignedMean.lickTraceNonStimGoodPerRec(:,behAlignedMeanStat.indLick150to180),2),...
        mean(behAlignedMean.lickTraceNonStimBadPerRec(:,behAlignedMeanStat.indLick150to180),2),...
        'No. licks (150-180 cm)','lickTracePerRecGoodVsBad150to180Box',...
        pathAnal,[-0.1 0.85],behAlignedMeanStat.pRSMeanLickTracePerRec150to180,colorSel);
    
    % distance after 180 cm
    plotBoxPlot(reshape(behAlignedMean.meanLickPerRecNonStimGood(:,behAlignedMeanStat.indLickAfter180),[],1),...
        reshape(behAlignedMean.meanLickPerRecNonStimBad(:,behAlignedMeanStat.indLickAfter180),[],1),...
        'No. licks (>=180 cm)','meanLickPerRecGoodVsBadAfter180Box',...
        pathAnal,[-0.1 1.2],behAlignedMeanStat.pRSMeanLickMeanPerRecAfter180,colorSel);
    
    plotBoxPlot(mean(behAlignedMean.lickTraceNonStimGoodPerRec(:,behAlignedMeanStat.indLickAfter180),2),...
        mean(behAlignedMean.lickTraceNonStimBadPerRec(:,behAlignedMeanStat.indLickAfter180),2),...
        'No. licks (>=180 cm)','lickTracePerRecGoodVsBadAfter180Box',...
        pathAnal,[-0.1 1.1],behAlignedMeanStat.pRSMeanLickTracePerRecAfter180,colorSel);
   
    % mean speed
    plotBoxPlot(reshape(behAlignedMean.meanSpeedPerRecNonStimGood,[],1)/10,...
        reshape(behAlignedMean.meanSpeedPerRecNonStimBad,[],1)/10,...
        'Speed (cm/s)','meanSpeedPerRecGoodVsBadBox',...
        pathAnal,[0 80],behAlignedMeanStat.pRSMeanSpeedMeanPerRec,colorSel);
   
    plotBoxPlot(mean(behAlignedMean.speedTraceNonStimGoodPerRec,2)/10,...
        mean(behAlignedMean.speedTraceNonStimBadPerRec,2)/10,...
        'Speed (cm/s)','speedTracePerRecGoodVsBadBox',...
        pathAnal,[0 80],behAlignedMeanStat.pRSMeanSpeedTracePerRec,colorSel);
    
    % distance 30 to 100 cm
    plotBoxPlot(reshape(behAlignedMean.meanSpeedPerRecNonStimGood(:,behAlignedMeanStat.indSpeed30to100),[],1)/10,...
        reshape(behAlignedMean.meanSpeedPerRecNonStimBad(:,behAlignedMeanStat.indSpeed30to100),[],1)/10,...
        'Speed (cm/s) (30-100 cm)','meanSpeedPerRecGoodVsBad30to100Box',...
        pathAnal,[10 90],behAlignedMeanStat.pRSMeanSpeedMeanPerRec30to100,colorSel);
   
    plotBoxPlot(mean(behAlignedMean.speedTraceNonStimGoodPerRec(:,behAlignedMeanStat.indSpeed30to100),2)/10,...
        mean(behAlignedMean.speedTraceNonStimBadPerRec(:,behAlignedMeanStat.indSpeed30to100),2)/10,...
        'Speed (cm/s) (30-100 cm)','speedTracePerRecGoodVsBad30to100Box',...
        pathAnal,[10 90],behAlignedMeanStat.pRSMeanSpeedTracePerRec30to100,colorSel);
    
    % distance after 100 cm
    plotBoxPlot(reshape(behAlignedMean.meanSpeedPerRecNonStimGood(:,behAlignedMeanStat.indSpeedAfter100),[],1)/10,...
        reshape(behAlignedMean.meanSpeedPerRecNonStimBad(:,behAlignedMeanStat.indSpeedAfter100),[],1)/10,...
        'Speed (cm/s) (>100 cm)','meanSpeedPerRecGoodVsBadAfter100Box',...
        pathAnal,[10 80],behAlignedMeanStat.pRSMeanSpeedMeanPerRecAfter100,colorSel);
   
    plotBoxPlot(mean(behAlignedMean.speedTraceNonStimGoodPerRec(:,behAlignedMeanStat.indSpeedAfter100),2)/10,...
        mean(behAlignedMean.speedTraceNonStimBadPerRec(:,behAlignedMeanStat.indSpeedAfter100),2)/10,...
        'Speed (cm/s) (>100 cm)','speedTracePerRecGoodVsBadAfter100Box',...
        pathAnal,[10 80],behAlignedMeanStat.pRSMeanSpeedTracePerRecAfter100,colorSel);
    
end
