function PyrThetaAlignedAllRec()

    RecordingList;
    pathAnal = 'Z:\Yingxue\DataAnalysisRaphi\Pyramidal\';
    
    GlobalConst;
    
%     load([pathAnal 'autoCorrPyrAllRec.mat']);
    load([pathAnal 'behAllRec.mat'],'behAligned',...
        'behAlignedNoCue','behAlignedAL','behAlignedPL');
    if(exist([pathAnal 'thetaAllRec.mat']))
        load([pathAnal 'thetaAllRec.mat']);
    end
    
    disp('No cue')
    thetaAlignedNoCue = accumTheta(listRecordingsNoCuePath,...
        listRecordingsNoCueFileName,mazeSessionNoCue,1,behAlignedNoCue);
    disp('Active licking')
    thetaAlignedAL = accumTheta(listRecordingsActiveLickPath,...
        listRecordingsActiveLickFileName,mazeSessionActiveLick,2,behAlignedAL);
    disp('Passive licking')
    thetaAlignedPL = accumTheta(listRecordingsPassiveLickPath,...
        listRecordingsPassiveLickFileName,mazeSessionPassiveLick,3,behAlignedPL);
    save([pathAnal 'thetaAllRec.mat'],'thetaAlignedNoCue','thetaAlignedAL','thetaAlignedPL'); 
    
    % exclude no cue recordings 
    behAligned.indRecNoCueField = [];
    behAligned.indRecNoCueNoField = [];
    
    thetaAlignedMean = accumMean(thetaAlignedNoCue,thetaAlignedAL,thetaAlignedPL,behAligned);
    thetaAlignedMeanStat = accumMeanStat(thetaAlignedMean,thetaAlignedNoCue.timeStepRun);
    
    save([pathAnal 'thetaAllRec.mat'],'thetaAlignedMean','thetaAlignedMeanStat','-append'); 
    
    plotThetaAlignedMean(pathAnal,thetaAlignedMean,thetaAlignedMeanStat);
    
    plotTheta(pathAnal,thetaAlignedNoCue.timeStepRun,...
        thetaAlignedMean.meanThetaFreqNonStimGoodFiltPerRecField,...
        thetaAlignedMean.meanThetaFreqNonStimGoodFiltPerRecNoField,[-3 4.5],'Theta freq. (Hz)',...
        'thetaFreqTrace');
        
    plotTheta(pathAnal,thetaAlignedNoCue.timeStepRun,...
        thetaAlignedMean.meanThetaAmpNonStimGoodPerRecField,...
        thetaAlignedMean.meanThetaAmpNonStimGoodPerRecNoField,[-3 7],'Theta amp.',...
        'thetaAmpTrace');
    
end

function thetaAligned = accumTheta(paths,filenames,mazeSess,task,behAligned)
  
    numRec = size(paths,1);
    thetaAligned = struct('task',[],... % no cue - 1, AL - 2, PL - 3
                    'indRec',[],... % recording index
                    'indRecNonStimBad',behAligned.indRecNonStimBad,... % recording index for all the reoordings with non-stimulated bad trials
                    'indRecStim',behAligned.indRecStim,... % recording index for all the reoordings with stimulated trials
                    'timeStepRun',[],...
                    ...
                    'meanThetaFreqNonStimGoodPerRec',[],... % mean ThetaFreq trace per recording (non-stimulated good trials)
                    'meanThetaFreqNonStimGoodFiltPerRec',[],... % filtered mean ThetaFreq trace per recording (non-stimulated good trials)
                    'stdThetaFreqNonStimGoodPerRec',[],... % mean ThetaFreq trace per recording (non-stimulated good trials)
                    'meanThetaFreqNonStimBadPerRec',[],... % mean ThetaFreq trace per recording (non-stimulated bad trials)
                    'meanThetaFreqNonStimBadFiltPerRec',[],... % filtered mean ThetaFreq trace per recording (non-stimulated bad trials)
                    'stdThetaFreqNonStimBadPerRec',[],... % mean ThetaFreq trace per recording (non-stimulated bad trials)
                    'meanThetaFreqStimPerRec',[],... % mean ThetaFreq trace per recording (stimulated trials)
                    'meanThetaFreqStimFiltPerRec',[],... % filtered mean ThetaFreq trace per recording (stimulated trials)
                    'stdThetaFreqStimPerRec',[],... % mean ThetaFreq trace per recording (stimulated trials)
                    ...
                    'meanThetaAmpNonStimGoodPerRec',[],... % mean ThetaAmp trace per recording (non-stimulated good trials)
                    'stdThetaAmpNonStimGoodPerRec',[],... % mean ThetaAmp trace per recording (non-stimulated good trials)
                    'meanThetaAmpNonStimBadPerRec',[],... % mean ThetaFreq trace per recording (non-stimulated bad trials)
                    'stdThetaAmpNonStimBadPerRec',[],... % mean ThetaFreq trace per recording (non-stimulated bad trials)
                    'meanThetaAmpStimPerRec',[],... % mean ThetaFreq trace per recording (stimulated trials)
                    'stdThetaAmpStimPerRec',[]); % mean ThetaFreq trace per recording (stimulated trials)
     
    for i = 1:numRec
        if(task == 3 & i == 8)
            a = 1;
        end
        disp(filenames(i,:));            
        
        fullPath = [paths(i,:) filenames(i,:) '_ThetaAlignRun_msess' num2str(mazeSess(i)) '.mat']; 
        if(exist(fullPath) == 0)
            disp('_ThetaAlignRun.mat file does not exist.');
            return;
        end
        load(fullPath,'meanThetaNonStimGood','meanThetaNonStimBad',...
            'meanThetaStim','t');
        
        thetaAligned.task = [thetaAligned.task task];
        thetaAligned.indRec = [thetaAligned.indRec i];
        thetaAligned.timeStepRun = t;
        if(isempty(thetaAligned.meanThetaFreqNonStimGoodPerRec))
            thetaAligned.meanThetaFreqNonStimGoodPerRec = meanThetaNonStimGood.meanThetaFreqGoodTr;
            thetaAligned.meanThetaFreqNonStimGoodFiltPerRec = meanThetaNonStimGood.meanThetaFreqFiltGoodTr;
            thetaAligned.stdThetaFreqNonStimGoodPerRec = meanThetaNonStimGood.stdThetaFreqGoodTr;
                        
            thetaAligned.meanThetaAmpNonStimGoodPerRec = meanThetaNonStimGood.meanThetaAmpGoodTr;
            thetaAligned.stdThetaAmpNonStimGoodPerRec = meanThetaNonStimGood.stdThetaAmpGoodTr;
        else
            thetaAligned.meanThetaFreqNonStimGoodPerRec = ...
                [thetaAligned.meanThetaFreqNonStimGoodPerRec; meanThetaNonStimGood.meanThetaFreqGoodTr];
            thetaAligned.meanThetaFreqNonStimGoodFiltPerRec = ...
                [thetaAligned.meanThetaFreqNonStimGoodFiltPerRec; meanThetaNonStimGood.meanThetaFreqFiltGoodTr];
            thetaAligned.stdThetaFreqNonStimGoodPerRec = ...
                [thetaAligned.stdThetaFreqNonStimGoodPerRec; meanThetaNonStimGood.stdThetaFreqGoodTr];
            
            thetaAligned.meanThetaAmpNonStimGoodPerRec = ...
                [thetaAligned.meanThetaAmpNonStimGoodPerRec; meanThetaNonStimGood.meanThetaAmpGoodTr];
            thetaAligned.stdThetaAmpNonStimGoodPerRec = ...
                [thetaAligned.stdThetaAmpNonStimGoodPerRec; meanThetaNonStimGood.stdThetaAmpGoodTr];
                        
        end      
        
        if(sum(behAligned.indRecNonStimBad == i) > 0)
            if(isempty(thetaAligned.meanThetaFreqNonStimBadPerRec))
                thetaAligned.meanThetaFreqNonStimBadPerRec = meanThetaNonStimBad.meanThetaFreqGoodTr;
                thetaAligned.meanThetaFreqNonStimBadFiltPerRec = meanThetaNonStimBad.meanThetaFreqFiltGoodTr;
                thetaAligned.stdThetaFreqNonStimBadPerRec = meanThetaNonStimBad.stdThetaFreqGoodTr;

                thetaAligned.meanThetaAmpNonStimBadPerRec = meanThetaNonStimBad.meanThetaAmpGoodTr;
                thetaAligned.stdThetaAmpNonStimBadPerRec = meanThetaNonStimBad.stdThetaAmpGoodTr;
            else
                thetaAligned.meanThetaFreqNonStimBadPerRec = ...
                    [thetaAligned.meanThetaFreqNonStimBadPerRec; meanThetaNonStimBad.meanThetaFreqGoodTr];
                thetaAligned.meanThetaFreqNonStimBadFiltPerRec = ...
                    [thetaAligned.meanThetaFreqNonStimBadFiltPerRec; meanThetaNonStimBad.meanThetaFreqFiltGoodTr];
                thetaAligned.stdThetaFreqNonStimBadPerRec = ...
                    [thetaAligned.stdThetaFreqNonStimBadPerRec; meanThetaNonStimBad.stdThetaFreqGoodTr];

                thetaAligned.meanThetaAmpNonStimBadPerRec = ...
                    [thetaAligned.meanThetaAmpNonStimBadPerRec; meanThetaNonStimBad.meanThetaAmpGoodTr];
                thetaAligned.stdThetaAmpNonStimBadPerRec = ...
                    [thetaAligned.stdThetaAmpNonStimBadPerRec; meanThetaNonStimBad.stdThetaAmpGoodTr];
            end
        end
        
        if(sum(behAligned.indRecStim == i) > 0)
            if(isempty(thetaAligned.meanThetaFreqStimPerRec))
                thetaAligned.meanThetaFreqStimPerRec = meanThetaStim.meanThetaFreqGoodTr;
                thetaAligned.meanThetaFreqStimFiltPerRec = meanThetaStim.meanThetaFreqFiltGoodTr;
                thetaAligned.stdThetaFreqStimPerRec = meanThetaStim.stdThetaFreqGoodTr;
            
                thetaAligned.meanThetaAmpStimPerRec = meanThetaStim.meanThetaAmpGoodTr;
                thetaAligned.stdThetaAmpStimPerRec = meanThetaStim.stdThetaAmpGoodTr;
            else                
                thetaAligned.meanThetaFreqStimPerRec = ...
                    [thetaAligned.meanThetaFreqStimPerRec; meanThetaStim.meanThetaFreqGoodTr];
                thetaAligned.meanThetaFreqStimFiltPerRec = ...
                    [thetaAligned.meanThetaFreqStimFiltPerRec; meanThetaStim.meanThetaFreqFiltGoodTr];
                thetaAligned.stdThetaFreqStimPerRec = ...
                    [thetaAligned.stdThetaFreqStimPerRec; meanThetaStim.stdThetaFreqGoodTr];
            
                thetaAligned.meanThetaAmpStimPerRec = ...
                    [thetaAligned.meanThetaAmpStimPerRec; meanThetaStim.meanThetaAmpGoodTr];
                thetaAligned.stdThetaAmpStimPerRec = ...
                    [thetaAligned.stdThetaAmpStimPerRec; meanThetaStim.stdThetaAmpGoodTr];
            end
        end
    end        
end

function thetaAlignedMean = accumMean(thetaAlignedNoCue,thetaAlignedAL,thetaAlignedPL,behAligned)   
    % mean theta for recordings with fields
    thetaAlignedMean.meanThetaFreqNonStimGoodPerRecField = ...
        [thetaAlignedNoCue.meanThetaFreqNonStimGoodPerRec(behAligned.indRecNoCueField,:);...
        thetaAlignedAL.meanThetaFreqNonStimGoodPerRec(behAligned.indRecALField,:);...
        thetaAlignedPL.meanThetaFreqNonStimGoodPerRec(behAligned.indRecPLField,:)];
    
    thetaAlignedMean.meanThetaFreqNonStimGoodFiltPerRecField = ...
        [thetaAlignedNoCue.meanThetaFreqNonStimGoodFiltPerRec(behAligned.indRecNoCueField,:);...
        thetaAlignedAL.meanThetaFreqNonStimGoodFiltPerRec(behAligned.indRecALField,:);...
        thetaAlignedPL.meanThetaFreqNonStimGoodFiltPerRec(behAligned.indRecPLField,:)];
  
    thetaAlignedMean.meanThetaAmpNonStimGoodPerRecField = ...
        [thetaAlignedNoCue.meanThetaAmpNonStimGoodPerRec(behAligned.indRecNoCueField,:);...
        thetaAlignedAL.meanThetaAmpNonStimGoodPerRec(behAligned.indRecALField,:);...
        thetaAlignedPL.meanThetaAmpNonStimGoodPerRec(behAligned.indRecPLField,:)];
    
    [~,nonStimBadRecNoCueField] = intersect(thetaAlignedNoCue.indRecNonStimBad,behAligned.indRecNoCueField);
    [~,nonStimBadRecALField] = intersect(thetaAlignedAL.indRecNonStimBad,behAligned.indRecALField);
    [~,nonStimBadRecPLField] = intersect(thetaAlignedPL.indRecNonStimBad,behAligned.indRecPLField);
    thetaAlignedMean.meanThetaFreqNonStimBadPerRecField = ...
        [thetaAlignedNoCue.meanThetaFreqNonStimBadPerRec(nonStimBadRecNoCueField,:);...
        thetaAlignedAL.meanThetaFreqNonStimBadPerRec(nonStimBadRecALField,:);...
        thetaAlignedPL.meanThetaFreqNonStimBadPerRec(nonStimBadRecPLField,:)];
    
    thetaAlignedMean.meanThetaFreqNonStimBadFiltPerRecField = ...
        [thetaAlignedNoCue.meanThetaFreqNonStimBadFiltPerRec(nonStimBadRecNoCueField,:);...
        thetaAlignedAL.meanThetaFreqNonStimBadFiltPerRec(nonStimBadRecALField,:);...
        thetaAlignedPL.meanThetaFreqNonStimBadFiltPerRec(nonStimBadRecPLField,:)];
  
    thetaAlignedMean.meanThetaAmpNonStimBadPerRecField = ...
        [thetaAlignedNoCue.meanThetaAmpNonStimBadPerRec(nonStimBadRecNoCueField,:);...
        thetaAlignedAL.meanThetaAmpNonStimBadPerRec(nonStimBadRecALField,:);...
        thetaAlignedPL.meanThetaAmpNonStimBadPerRec(nonStimBadRecPLField,:)];
    
    [~,stimRecNoCueField] = intersect(thetaAlignedNoCue.indRecStim,behAligned.indRecNoCueField);
    [~,stimRecALField] = intersect(thetaAlignedAL.indRecStim,behAligned.indRecALField);
    [~,stimRecPLField] = intersect(thetaAlignedPL.indRecStim,behAligned.indRecPLField);
    thetaAlignedMean.meanThetaFreqStimPerRecField = ...
        [thetaAlignedNoCue.meanThetaFreqStimPerRec(stimRecNoCueField,:);...
        thetaAlignedAL.meanThetaFreqStimPerRec(stimRecALField,:);...
        thetaAlignedPL.meanThetaFreqStimPerRec(stimRecPLField,:)];
    
    thetaAlignedMean.meanThetaFreqStimFiltPerRecField = ...
        [thetaAlignedNoCue.meanThetaFreqStimFiltPerRec(stimRecNoCueField,:);...
        thetaAlignedAL.meanThetaFreqStimFiltPerRec(stimRecALField,:);...
        thetaAlignedPL.meanThetaFreqStimFiltPerRec(stimRecPLField,:)];
  
    thetaAlignedMean.meanThetaAmpStimPerRecField = ...
        [thetaAlignedNoCue.meanThetaAmpStimPerRec(stimRecNoCueField,:);...
        thetaAlignedAL.meanThetaAmpStimPerRec(stimRecALField,:);...
        thetaAlignedPL.meanThetaAmpStimPerRec(stimRecPLField,:)];
    
    % mean theta for recordings without fields
    thetaAlignedMean.meanThetaFreqNonStimGoodPerRecNoField = ...
        [thetaAlignedNoCue.meanThetaFreqNonStimGoodPerRec(behAligned.indRecNoCueNoField,:);...
        thetaAlignedAL.meanThetaFreqNonStimGoodPerRec(behAligned.indRecALNoField,:);...
        thetaAlignedPL.meanThetaFreqNonStimGoodPerRec(behAligned.indRecPLNoField,:)];
    
    thetaAlignedMean.meanThetaFreqNonStimGoodFiltPerRecNoField = ...
        [thetaAlignedNoCue.meanThetaFreqNonStimGoodFiltPerRec(behAligned.indRecNoCueNoField,:);...
        thetaAlignedAL.meanThetaFreqNonStimGoodFiltPerRec(behAligned.indRecALNoField,:);...
        thetaAlignedPL.meanThetaFreqNonStimGoodFiltPerRec(behAligned.indRecPLNoField,:)];
  
    thetaAlignedMean.meanThetaAmpNonStimGoodPerRecNoField = ...
        [thetaAlignedNoCue.meanThetaAmpNonStimGoodPerRec(behAligned.indRecNoCueNoField,:);...
        thetaAlignedAL.meanThetaAmpNonStimGoodPerRec(behAligned.indRecALNoField,:);...
        thetaAlignedPL.meanThetaAmpNonStimGoodPerRec(behAligned.indRecPLNoField,:)];
    
    [~,nonStimBadRecNoCueNoField] = intersect(thetaAlignedNoCue.indRecNonStimBad,behAligned.indRecNoCueNoField);
    [~,nonStimBadRecALNoField] = intersect(thetaAlignedAL.indRecNonStimBad,behAligned.indRecALNoField);
    [~,nonStimBadRecPLNoField] = intersect(thetaAlignedPL.indRecNonStimBad,behAligned.indRecPLNoField);
    thetaAlignedMean.meanThetaFreqNonStimBadPerRecNoField = ...
        [thetaAlignedNoCue.meanThetaFreqNonStimBadPerRec(nonStimBadRecNoCueNoField,:);...
        thetaAlignedAL.meanThetaFreqNonStimBadPerRec(nonStimBadRecALNoField,:);...
        thetaAlignedPL.meanThetaFreqNonStimBadPerRec(nonStimBadRecPLNoField,:)];
    
    thetaAlignedMean.meanThetaFreqNonStimBadFiltPerRecNoField = ...
        [thetaAlignedNoCue.meanThetaFreqNonStimBadFiltPerRec(nonStimBadRecNoCueNoField,:);...
        thetaAlignedAL.meanThetaFreqNonStimBadFiltPerRec(nonStimBadRecALNoField,:);...
        thetaAlignedPL.meanThetaFreqNonStimBadFiltPerRec(nonStimBadRecPLNoField,:)];
  
    thetaAlignedMean.meanThetaAmpNonStimBadPerRecNoField = ...
        [thetaAlignedNoCue.meanThetaAmpNonStimBadPerRec(nonStimBadRecNoCueNoField,:);...
        thetaAlignedAL.meanThetaAmpNonStimBadPerRec(nonStimBadRecALNoField,:);...
        thetaAlignedPL.meanThetaAmpNonStimBadPerRec(nonStimBadRecPLNoField,:)];
    
    [~,stimRecNoCueNoField] = intersect(thetaAlignedNoCue.indRecStim,behAligned.indRecNoCueNoField);
    [~,stimRecALNoField] = intersect(thetaAlignedAL.indRecStim,behAligned.indRecALNoField);
    [~,stimRecPLNoField] = intersect(thetaAlignedPL.indRecStim,behAligned.indRecPLNoField);
    thetaAlignedMean.meanThetaFreqStimPerRecNoField = ...
        [thetaAlignedNoCue.meanThetaFreqStimPerRec(stimRecNoCueNoField,:);...
        thetaAlignedAL.meanThetaFreqStimPerRec(stimRecALNoField,:);...
        thetaAlignedPL.meanThetaFreqStimPerRec(stimRecPLNoField,:)];
    
    thetaAlignedMean.meanThetaFreqStimFiltPerRecNoField = ...
        [thetaAlignedNoCue.meanThetaFreqStimFiltPerRec(stimRecNoCueNoField,:);...
        thetaAlignedAL.meanThetaFreqStimFiltPerRec(stimRecALNoField,:);...
        thetaAlignedPL.meanThetaFreqStimFiltPerRec(stimRecPLNoField,:)];
  
    thetaAlignedMean.meanThetaAmpStimPerRecNoField = ...
        [thetaAlignedNoCue.meanThetaAmpStimPerRec(stimRecNoCueNoField,:);...
        thetaAlignedAL.meanThetaAmpStimPerRec(stimRecALNoField,:);...
        thetaAlignedPL.meanThetaAmpStimPerRec(stimRecPLNoField,:)];
      
end

function thetaAlignedMeanStat = accumMeanStat(thetaAlignedMean,timeStepRun)

    %% baseline
    indThetaBaseline = find(timeStepRun >= -3 & timeStepRun < -2);
    thetaAlignedMeanStat.indThetaBaseline = indThetaBaseline;
    thetaAlignedMeanStat.meanThetaFreqNonStimGoodPerRecFieldBaseline = [...
        mean(mean(thetaAlignedMean.meanThetaFreqNonStimGoodPerRecField(:,indThetaBaseline))),...
        mean(mean(thetaAlignedMean.meanThetaFreqNonStimGoodPerRecNoField(:,indThetaBaseline)))];
    thetaAlignedMeanStat.meanThetaAmpNonStimGoodPerRecFieldBaseline = [...
        mean(mean(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecField(:,indThetaBaseline))),...
        mean(mean(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecNoField(:,indThetaBaseline)))];
    
    thetaAlignedMeanStat.meanThetaFreqNonStimBadPerRecFieldBaseline = [...
        mean(mean(thetaAlignedMean.meanThetaFreqNonStimBadPerRecField(:,indThetaBaseline))),...
        mean(mean(thetaAlignedMean.meanThetaFreqNonStimBadPerRecNoField(:,indThetaBaseline)))];
    thetaAlignedMeanStat.meanThetaAmpNonStimBadPerRecFieldBaseline = [...
        mean(mean(thetaAlignedMean.meanThetaAmpNonStimBadPerRecField(:,indThetaBaseline))),...
        mean(mean(thetaAlignedMean.meanThetaAmpNonStimBadPerRecNoField(:,indThetaBaseline)))];
    
    thetaAlignedMeanStat.meanThetaFreqStimPerRecFieldBaseline = [...
        mean(mean(thetaAlignedMean.meanThetaFreqStimPerRecField(:,indThetaBaseline))),...
        mean(mean(thetaAlignedMean.meanThetaFreqStimPerRecNoField(:,indThetaBaseline)))];
    thetaAlignedMeanStat.meanThetaAmpStimPerRecFieldBaseline = [...
        mean(mean(thetaAlignedMean.meanThetaAmpStimPerRecField(:,indThetaBaseline))),...
        mean(mean(thetaAlignedMean.meanThetaAmpStimPerRecNoField(:,indThetaBaseline)))];
    
    thetaAlignedMeanStat.pRSMeanThetaFreqNonStimGoodPerRecFieldBaseline = ...
        ranksum(reshape(thetaAlignedMean.meanThetaFreqNonStimGoodPerRecField(:,indThetaBaseline),[],1),...
        reshape(thetaAlignedMean.meanThetaFreqNonStimGoodPerRecNoField(:,indThetaBaseline),[],1));
    thetaAlignedMeanStat.pRSMeanThetaAmpNonStimGoodPerRecFieldBaseline = ...
        ranksum(reshape(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecField(:,indThetaBaseline),[],1),...
        reshape(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecNoField(:,indThetaBaseline),[],1));
    
    thetaAlignedMeanStat.pRSMeanThetaFreqNonStimBadPerRecFieldBaseline = ...
        ranksum(reshape(thetaAlignedMean.meanThetaFreqNonStimBadPerRecField(:,indThetaBaseline),[],1),...
        reshape(thetaAlignedMean.meanThetaFreqNonStimBadPerRecNoField(:,indThetaBaseline),[],1));
    thetaAlignedMeanStat.pRSMeanThetaAmpNonStimBadPerRecFieldBaseline = ...
        ranksum(reshape(thetaAlignedMean.meanThetaAmpNonStimBadPerRecField(:,indThetaBaseline),[],1),...
        reshape(thetaAlignedMean.meanThetaAmpNonStimBadPerRecNoField(:,indThetaBaseline),[],1));
    
    thetaAlignedMeanStat.pRSMeanThetaFreqStimPerRecFieldBaseline = ...
        ranksum(reshape(thetaAlignedMean.meanThetaFreqStimPerRecField(:,indThetaBaseline),[],1),...
        reshape(thetaAlignedMean.meanThetaFreqStimPerRecNoField(:,indThetaBaseline),[],1));
    thetaAlignedMeanStat.pRSMeanThetaAmpStimPerRecFieldBaseline = ...
        ranksum(reshape(thetaAlignedMean.meanThetaAmpStimPerRecField(:,indThetaBaseline),[],1),...
        reshape(thetaAlignedMean.meanThetaAmpStimPerRecNoField(:,indThetaBaseline),[],1));
    
    thetaAlignedMeanStat.pRSMeanThetaFreqNonStimGoodMeanPerRecFieldBaseline = ...
        ranksum(mean(thetaAlignedMean.meanThetaFreqNonStimGoodPerRecField(:,indThetaBaseline),2),...
        mean(thetaAlignedMean.meanThetaFreqNonStimGoodPerRecNoField(:,indThetaBaseline),2));
    thetaAlignedMeanStat.pRSMeanThetaAmpNonStimGoodMeanPerRecFieldBaseline = ...
        ranksum(mean(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecField(:,indThetaBaseline),2),...
        mean(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecNoField(:,indThetaBaseline),2));
        
    %% before run
    indThetaBefRun = find(timeStepRun >= -0.5 & timeStepRun < 0);
    thetaAlignedMeanStat.indThetaBefRun = indThetaBefRun;
    thetaAlignedMeanStat.meanThetaFreqNonStimGoodPerRecFieldBefRun = [...
        mean(mean(thetaAlignedMean.meanThetaFreqNonStimGoodPerRecField(:,indThetaBefRun))),...
        mean(mean(thetaAlignedMean.meanThetaFreqNonStimGoodPerRecNoField(:,indThetaBefRun)))];
    thetaAlignedMeanStat.meanThetaAmpNonStimGoodPerRecFieldBefRun = [...
        mean(mean(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecField(:,indThetaBefRun))),...
        mean(mean(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecNoField(:,indThetaBefRun)))];
    
    thetaAlignedMeanStat.meanThetaFreqNonStimBadPerRecFieldBefRun = [...
        mean(mean(thetaAlignedMean.meanThetaFreqNonStimBadPerRecField(:,indThetaBefRun))),...
        mean(mean(thetaAlignedMean.meanThetaFreqNonStimBadPerRecNoField(:,indThetaBefRun)))];
    thetaAlignedMeanStat.meanThetaAmpNonStimBadPerRecFieldBefRun = [...
        mean(mean(thetaAlignedMean.meanThetaAmpNonStimBadPerRecField(:,indThetaBefRun))),...
        mean(mean(thetaAlignedMean.meanThetaAmpNonStimBadPerRecNoField(:,indThetaBefRun)))];
    
    thetaAlignedMeanStat.meanThetaFreqStimPerRecFieldBefRun = [...
        mean(mean(thetaAlignedMean.meanThetaFreqStimPerRecField(:,indThetaBefRun))),...
        mean(mean(thetaAlignedMean.meanThetaFreqStimPerRecNoField(:,indThetaBefRun)))];
    thetaAlignedMeanStat.meanThetaAmpStimPerRecFieldBefRun = [...
        mean(mean(thetaAlignedMean.meanThetaAmpStimPerRecField(:,indThetaBefRun))),...
        mean(mean(thetaAlignedMean.meanThetaAmpStimPerRecNoField(:,indThetaBefRun)))];
    
    thetaAlignedMeanStat.pRSMeanThetaFreqNonStimGoodPerRecFieldBefRun = ...
        ranksum(reshape(thetaAlignedMean.meanThetaFreqNonStimGoodPerRecField(:,indThetaBefRun),[],1),...
        reshape(thetaAlignedMean.meanThetaFreqNonStimGoodPerRecNoField(:,indThetaBefRun),[],1));
    thetaAlignedMeanStat.pRSMeanThetaAmpNonStimGoodPerRecFieldBefRun = ...
        ranksum(reshape(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecField(:,indThetaBefRun),[],1),...
        reshape(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecNoField(:,indThetaBefRun),[],1));
    
    thetaAlignedMeanStat.pRSMeanThetaFreqNonStimBadPerRecFieldBefRun = ...
        ranksum(reshape(thetaAlignedMean.meanThetaFreqNonStimBadPerRecField(:,indThetaBefRun),[],1),...
        reshape(thetaAlignedMean.meanThetaFreqNonStimBadPerRecNoField(:,indThetaBefRun),[],1));
    thetaAlignedMeanStat.pRSMeanThetaAmpNonStimBadPerRecFieldBefRun = ...
        ranksum(reshape(thetaAlignedMean.meanThetaAmpNonStimBadPerRecField(:,indThetaBefRun),[],1),...
        reshape(thetaAlignedMean.meanThetaAmpNonStimBadPerRecNoField(:,indThetaBefRun),[],1));
    
    thetaAlignedMeanStat.pRSMeanThetaFreqStimPerRecFieldBefRun = ...
        ranksum(reshape(thetaAlignedMean.meanThetaFreqStimPerRecField(:,indThetaBefRun),[],1),...
        reshape(thetaAlignedMean.meanThetaFreqStimPerRecNoField(:,indThetaBefRun),[],1));
    thetaAlignedMeanStat.pRSMeanThetaAmpStimPerRecFieldBefRun = ...
        ranksum(reshape(thetaAlignedMean.meanThetaAmpStimPerRecField(:,indThetaBefRun),[],1),...
        reshape(thetaAlignedMean.meanThetaAmpStimPerRecNoField(:,indThetaBefRun),[],1));
    
    thetaAlignedMeanStat.pRSMeanThetaFreqNonStimGoodMeanPerRecFieldBefRun = ...
        ranksum(mean(thetaAlignedMean.meanThetaFreqNonStimGoodPerRecField(:,indThetaBefRun),2),...
        mean(thetaAlignedMean.meanThetaFreqNonStimGoodPerRecNoField(:,indThetaBefRun),2));
    thetaAlignedMeanStat.pRSMeanThetaAmpNonStimGoodMeanPerRecFieldBefRun = ...
        ranksum(mean(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecField(:,indThetaBefRun),2),...
        mean(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecNoField(:,indThetaBefRun),2));
    
    %% 1 sec after run
    indTheta0to0p5s = find(timeStepRun >= 0 & timeStepRun < 0.5);
    thetaAlignedMeanStat.indTheta0to0p5s = indTheta0to0p5s;
    thetaAlignedMeanStat.meanThetaFreqNonStimGoodPerRecField0to0p5s = [...
        mean(mean(thetaAlignedMean.meanThetaFreqNonStimGoodPerRecField(:,indTheta0to0p5s))),...
        mean(mean(thetaAlignedMean.meanThetaFreqNonStimGoodPerRecNoField(:,indTheta0to0p5s)))];
    thetaAlignedMeanStat.meanThetaAmpNonStimGoodPerRecField0to0p5s = [...
        mean(mean(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecField(:,indTheta0to0p5s))),...
        mean(mean(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecNoField(:,indTheta0to0p5s)))];
    
    thetaAlignedMeanStat.meanThetaFreqNonStimBadPerRecField0to0p5s = [...
        mean(mean(thetaAlignedMean.meanThetaFreqNonStimBadPerRecField(:,indTheta0to0p5s))),...
        mean(mean(thetaAlignedMean.meanThetaFreqNonStimBadPerRecNoField(:,indTheta0to0p5s)))];
    thetaAlignedMeanStat.meanThetaAmpNonStimBadPerRecField0to0p5s = [...
        mean(mean(thetaAlignedMean.meanThetaAmpNonStimBadPerRecField(:,indTheta0to0p5s))),...
        mean(mean(thetaAlignedMean.meanThetaAmpNonStimBadPerRecNoField(:,indTheta0to0p5s)))];
    
    thetaAlignedMeanStat.meanThetaFreqStimPerRecField0to0p5s = [...
        mean(mean(thetaAlignedMean.meanThetaFreqStimPerRecField(:,indTheta0to0p5s))),...
        mean(mean(thetaAlignedMean.meanThetaFreqStimPerRecNoField(:,indTheta0to0p5s)))];
    thetaAlignedMeanStat.meanThetaAmpStimPerRecField0to0p5s = [...
        mean(mean(thetaAlignedMean.meanThetaAmpStimPerRecField(:,indTheta0to0p5s))),...
        mean(mean(thetaAlignedMean.meanThetaAmpStimPerRecNoField(:,indTheta0to0p5s)))];
    
    thetaAlignedMeanStat.pRSMeanThetaFreqNonStimGoodPerRecField0to0p5s = ...
        ranksum(reshape(thetaAlignedMean.meanThetaFreqNonStimGoodPerRecField(:,indTheta0to0p5s),[],1),...
        reshape(thetaAlignedMean.meanThetaFreqNonStimGoodPerRecNoField(:,indTheta0to0p5s),[],1));
    thetaAlignedMeanStat.pRSMeanThetaAmpNonStimGoodPerRecField0to0p5s = ...
        ranksum(reshape(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecField(:,indTheta0to0p5s),[],1),...
        reshape(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecNoField(:,indTheta0to0p5s),[],1));
    
    thetaAlignedMeanStat.pRSMeanThetaFreqNonStimBadPerRecField0to0p5s = ...
        ranksum(reshape(thetaAlignedMean.meanThetaFreqNonStimBadPerRecField(:,indTheta0to0p5s),[],1),...
        reshape(thetaAlignedMean.meanThetaFreqNonStimBadPerRecNoField(:,indTheta0to0p5s),[],1));
    thetaAlignedMeanStat.pRSMeanThetaAmpNonStimBadPerRecField0to0p5s = ...
        ranksum(reshape(thetaAlignedMean.meanThetaAmpNonStimBadPerRecField(:,indTheta0to0p5s),[],1),...
        reshape(thetaAlignedMean.meanThetaAmpNonStimBadPerRecNoField(:,indTheta0to0p5s),[],1));
    
    thetaAlignedMeanStat.pRSMeanThetaFreqStimPerRecField0to0p5s = ...
        ranksum(reshape(thetaAlignedMean.meanThetaFreqStimPerRecField(:,indTheta0to0p5s),[],1),...
        reshape(thetaAlignedMean.meanThetaFreqStimPerRecNoField(:,indTheta0to0p5s),[],1));
    thetaAlignedMeanStat.pRSMeanThetaAmpStimPerRecField0to0p5s = ...
        ranksum(reshape(thetaAlignedMean.meanThetaAmpStimPerRecField(:,indTheta0to0p5s),[],1),...
        reshape(thetaAlignedMean.meanThetaAmpStimPerRecNoField(:,indTheta0to0p5s),[],1));
    
    thetaAlignedMeanStat.pRSMeanThetaFreqNonStimGoodMeanPerRecField0to0p5s = ...
        ranksum(mean(thetaAlignedMean.meanThetaFreqNonStimGoodPerRecField(:,indTheta0to0p5s),2),...
        mean(thetaAlignedMean.meanThetaFreqNonStimGoodPerRecNoField(:,indTheta0to0p5s),2));
    thetaAlignedMeanStat.pRSMeanThetaAmpNonStimGoodMeanPerRecField0to0p5s = ...
        ranksum(mean(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecField(:,indTheta0to0p5s),2),...
        mean(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecNoField(:,indTheta0to0p5s),2));
    
    %% 1-5 sec after run
    indTheta1to5s = find(timeStepRun >= 1 & timeStepRun < 5);
    thetaAlignedMeanStat.indTheta1to5s = indTheta1to5s;
    thetaAlignedMeanStat.meanThetaFreqNonStimGoodPerRecField1to5s = [...
        mean(mean(thetaAlignedMean.meanThetaFreqNonStimGoodPerRecField(:,indTheta1to5s))),...
        mean(mean(thetaAlignedMean.meanThetaFreqNonStimGoodPerRecNoField(:,indTheta1to5s)))];
    thetaAlignedMeanStat.meanThetaAmpNonStimGoodPerRecField1to5s = [...
        mean(mean(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecField(:,indTheta1to5s))),...
        mean(mean(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecNoField(:,indTheta1to5s)))];
    
    thetaAlignedMeanStat.meanThetaFreqNonStimBadPerRecField1to5s = [...
        mean(mean(thetaAlignedMean.meanThetaFreqNonStimBadPerRecField(:,indTheta1to5s))),...
        mean(mean(thetaAlignedMean.meanThetaFreqNonStimBadPerRecNoField(:,indTheta1to5s)))];
    thetaAlignedMeanStat.meanThetaAmpNonStimBadPerRecField1to5s = [...
        mean(mean(thetaAlignedMean.meanThetaAmpNonStimBadPerRecField(:,indTheta1to5s))),...
        mean(mean(thetaAlignedMean.meanThetaAmpNonStimBadPerRecNoField(:,indTheta1to5s)))];
    
    thetaAlignedMeanStat.meanThetaFreqStimPerRecField1to5s = [...
        mean(mean(thetaAlignedMean.meanThetaFreqStimPerRecField(:,indTheta1to5s))),...
        mean(mean(thetaAlignedMean.meanThetaFreqStimPerRecNoField(:,indTheta1to5s)))];
    thetaAlignedMeanStat.meanThetaAmpStimPerRecField1to5s = [...
        mean(mean(thetaAlignedMean.meanThetaAmpStimPerRecField(:,indTheta1to5s))),...
        mean(mean(thetaAlignedMean.meanThetaAmpStimPerRecNoField(:,indTheta1to5s)))];
    
    thetaAlignedMeanStat.pRSMeanThetaFreqNonStimGoodPerRecField1to5s = ...
        ranksum(reshape(thetaAlignedMean.meanThetaFreqNonStimGoodPerRecField(:,indTheta1to5s),[],1),...
        reshape(thetaAlignedMean.meanThetaFreqNonStimGoodPerRecNoField(:,indTheta1to5s),[],1));
    thetaAlignedMeanStat.pRSMeanThetaAmpNonStimGoodPerRecField1to5s = ...
        ranksum(reshape(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecField(:,indTheta1to5s),[],1),...
        reshape(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecNoField(:,indTheta1to5s),[],1));
    
    thetaAlignedMeanStat.pRSMeanThetaFreqNonStimBadPerRecField1to5s = ...
        ranksum(reshape(thetaAlignedMean.meanThetaFreqNonStimBadPerRecField(:,indTheta1to5s),[],1),...
        reshape(thetaAlignedMean.meanThetaFreqNonStimBadPerRecNoField(:,indTheta1to5s),[],1));
    thetaAlignedMeanStat.pRSMeanThetaAmpNonStimBadPerRecField1to5s = ...
        ranksum(reshape(thetaAlignedMean.meanThetaAmpNonStimBadPerRecField(:,indTheta1to5s),[],1),...
        reshape(thetaAlignedMean.meanThetaAmpNonStimBadPerRecNoField(:,indTheta1to5s),[],1));
    
    thetaAlignedMeanStat.pRSMeanThetaFreqStimPerRecField1to5s = ...
        ranksum(reshape(thetaAlignedMean.meanThetaFreqStimPerRecField(:,indTheta1to5s),[],1),...
        reshape(thetaAlignedMean.meanThetaFreqStimPerRecNoField(:,indTheta1to5s),[],1));
    thetaAlignedMeanStat.pRSMeanThetaAmpStimPerRecField1to5s = ...
        ranksum(reshape(thetaAlignedMean.meanThetaAmpStimPerRecField(:,indTheta1to5s),[],1),...
        reshape(thetaAlignedMean.meanThetaAmpStimPerRecNoField(:,indTheta1to5s),[],1));
    
    thetaAlignedMeanStat.pRSMeanThetaFreqNonStimGoodMeanPerRecField1to5s = ...
        ranksum(mean(thetaAlignedMean.meanThetaFreqNonStimGoodPerRecField(:,indTheta1to5s),2),...
        mean(thetaAlignedMean.meanThetaFreqNonStimGoodPerRecNoField(:,indTheta1to5s),2));
    thetaAlignedMeanStat.pRSMeanThetaAmpNonStimGoodMeanPerRecField1to5s = ...
        ranksum(mean(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecField(:,indTheta1to5s),2),...
        mean(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecNoField(:,indTheta1to5s),2));
    
    %% after run
    indTheta0to5s = find(timeStepRun >= 0 & timeStepRun < 5);
    thetaAlignedMeanStat.indTheta0to5s = indTheta0to5s;
    thetaAlignedMeanStat.meanThetaFreqNonStimGoodPerRecField0to5s = [...
        mean(mean(thetaAlignedMean.meanThetaFreqNonStimGoodPerRecField(:,indTheta0to5s))),...
        mean(mean(thetaAlignedMean.meanThetaFreqNonStimGoodPerRecNoField(:,indTheta0to5s)))];
    thetaAlignedMeanStat.meanThetaAmpNonStimGoodPerRecField0to5s = [...
        mean(mean(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecField(:,indTheta0to5s))),...
        mean(mean(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecNoField(:,indTheta0to5s)))];
    
    thetaAlignedMeanStat.meanThetaFreqNonStimBadPerRecField0to5s = [...
        mean(mean(thetaAlignedMean.meanThetaFreqNonStimBadPerRecField(:,indTheta0to5s))),...
        mean(mean(thetaAlignedMean.meanThetaFreqNonStimBadPerRecNoField(:,indTheta0to5s)))];
    thetaAlignedMeanStat.meanThetaAmpNonStimBadPerRecField0to5s = [...
        mean(mean(thetaAlignedMean.meanThetaAmpNonStimBadPerRecField(:,indTheta0to5s))),...
        mean(mean(thetaAlignedMean.meanThetaAmpNonStimBadPerRecNoField(:,indTheta0to5s)))];
    
    thetaAlignedMeanStat.meanThetaFreqStimPerRecField0to5s = [...
        mean(mean(thetaAlignedMean.meanThetaFreqStimPerRecField(:,indTheta0to5s))),...
        mean(mean(thetaAlignedMean.meanThetaFreqStimPerRecNoField(:,indTheta0to5s)))];
    thetaAlignedMeanStat.meanThetaAmpStimPerRecField0to5s = [...
        mean(mean(thetaAlignedMean.meanThetaAmpStimPerRecField(:,indTheta0to5s))),...
        mean(mean(thetaAlignedMean.meanThetaAmpStimPerRecNoField(:,indTheta0to5s)))];
    
    thetaAlignedMeanStat.pRSMeanThetaFreqNonStimGoodPerRecField0to5s = ...
        ranksum(reshape(thetaAlignedMean.meanThetaFreqNonStimGoodPerRecField(:,indTheta0to5s),[],1),...
        reshape(thetaAlignedMean.meanThetaFreqNonStimGoodPerRecNoField(:,indTheta0to5s),[],1));
    thetaAlignedMeanStat.pRSMeanThetaAmpNonStimGoodPerRecField0to5s = ...
        ranksum(reshape(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecField(:,indTheta0to5s),[],1),...
        reshape(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecNoField(:,indTheta0to5s),[],1));
    
    thetaAlignedMeanStat.pRSMeanThetaFreqNonStimBadPerRecField0to5s = ...
        ranksum(reshape(thetaAlignedMean.meanThetaFreqNonStimBadPerRecField(:,indTheta0to5s),[],1),...
        reshape(thetaAlignedMean.meanThetaFreqNonStimBadPerRecNoField(:,indTheta0to5s),[],1));
    thetaAlignedMeanStat.pRSMeanThetaAmpNonStimBadPerRecField0to5s = ...
        ranksum(reshape(thetaAlignedMean.meanThetaAmpNonStimBadPerRecField(:,indTheta0to5s),[],1),...
        reshape(thetaAlignedMean.meanThetaAmpNonStimBadPerRecNoField(:,indTheta0to5s),[],1));
    
    thetaAlignedMeanStat.pRSMeanThetaFreqStimPerRecField0to5s = ...
        ranksum(reshape(thetaAlignedMean.meanThetaFreqStimPerRecField(:,indTheta0to5s),[],1),...
        reshape(thetaAlignedMean.meanThetaFreqStimPerRecNoField(:,indTheta0to5s),[],1));
    thetaAlignedMeanStat.pRSMeanThetaAmpStimPerRecField0to5s = ...
        ranksum(reshape(thetaAlignedMean.meanThetaAmpStimPerRecField(:,indTheta0to5s),[],1),...
        reshape(thetaAlignedMean.meanThetaAmpStimPerRecNoField(:,indTheta0to5s),[],1));
    
    thetaAlignedMeanStat.pRSMeanThetaFreqNonStimGoodMeanPerRecField0to5s = ...
        ranksum(mean(thetaAlignedMean.meanThetaFreqNonStimGoodPerRecField(:,indTheta0to5s),2),...
        mean(thetaAlignedMean.meanThetaFreqNonStimGoodPerRecNoField(:,indTheta0to5s),2));
    thetaAlignedMeanStat.pRSMeanThetaAmpNonStimGoodMeanPerRecField0to5s = ...
        ranksum(mean(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecField(:,indTheta0to5s),2),...
        mean(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecNoField(:,indTheta0to5s),2));
        
    %% find change at the beginning of running onset
    % with field
    indThetaM0to0p5s = find(timeStepRun >= 0 & timeStepRun < 0.5);
    thetaAlignedMeanStat.mThetaFreqNonStimGoodFiltField = mean(thetaAlignedMean.meanThetaFreqNonStimGoodFiltPerRecField(:,indThetaM0to0p5s),2);        
    thetaAlignedMeanStat.mThetaFreqNonStimBadFiltField = mean(thetaAlignedMean.meanThetaFreqNonStimBadFiltPerRecField(:,indThetaM0to0p5s),2);
    thetaAlignedMeanStat.mThetaFreqStimFiltField = mean(thetaAlignedMean.meanThetaFreqStimFiltPerRecField(:,indThetaM0to0p5s),2);
    
    thetaAlignedMeanStat.mThetaAmpNonStimGoodField = mean(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecField(:,indThetaM0to0p5s),2);
    thetaAlignedMeanStat.mThetaAmpNonStimBadField = mean(thetaAlignedMean.meanThetaAmpNonStimBadPerRecField(:,indThetaM0to0p5s),2);
    thetaAlignedMeanStat.mThetaAmpStimField = mean(thetaAlignedMean.meanThetaAmpStimPerRecField(:,indThetaM0to0p5s),2);
    
    % without field
    thetaAlignedMeanStat.mThetaFreqNonStimGoodFiltNoField = mean(thetaAlignedMean.meanThetaFreqNonStimGoodFiltPerRecNoField(:,indThetaM0to0p5s),2);
    thetaAlignedMeanStat.mThetaFreqNonStimBadFiltNoField = mean(thetaAlignedMean.meanThetaFreqNonStimBadFiltPerRecNoField(:,indThetaM0to0p5s),2);
    thetaAlignedMeanStat.mThetaFreqStimFiltNoField = mean(thetaAlignedMean.meanThetaFreqStimFiltPerRecNoField(:,indThetaM0to0p5s),2);
    
    thetaAlignedMeanStat.mThetaAmpNonStimGoodNoField = mean(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecNoField(:,indThetaM0to0p5s),2);
    thetaAlignedMeanStat.mThetaAmpNonStimBadNoField = mean(thetaAlignedMean.meanThetaAmpNonStimBadPerRecNoField(:,indThetaM0to0p5s),2);
    thetaAlignedMeanStat.mThetaAmpStimNoField = mean(thetaAlignedMean.meanThetaAmpStimPerRecNoField(:,indThetaM0to0p5s),2);
    
    %% percent change
    indTheta2to5s = find(timeStepRun >= 2 & timeStepRun < 5);
    thetaAlignedMeanStat.percChangeThetaFreqNonStimGoodFiltField = ...
        (thetaAlignedMeanStat.mThetaFreqNonStimGoodFiltField - ...
        mean(thetaAlignedMean.meanThetaFreqNonStimGoodFiltPerRecField(:,indTheta2to5s),2))./...
        mean(thetaAlignedMean.meanThetaFreqNonStimGoodFiltPerRecField(:,indTheta2to5s),2);
    
    thetaAlignedMeanStat.percChangeThetaFreqNonStimGoodFiltNoField = ...
        (thetaAlignedMeanStat.mThetaFreqNonStimGoodFiltNoField - ...
        mean(thetaAlignedMean.meanThetaFreqNonStimGoodFiltPerRecNoField(:,indTheta2to5s),2))./...
        mean(thetaAlignedMean.meanThetaFreqNonStimGoodFiltPerRecNoField(:,indTheta2to5s),2);
    
    thetaAlignedMeanStat.percChangeThetaFreqNonStimBadFiltField = ...
        (thetaAlignedMeanStat.mThetaFreqNonStimBadFiltField - ...
        mean(thetaAlignedMean.meanThetaFreqNonStimBadFiltPerRecField(:,indTheta2to5s),2))./...
        mean(thetaAlignedMean.meanThetaFreqNonStimBadFiltPerRecField(:,indTheta2to5s),2);
    
    thetaAlignedMeanStat.percChangeThetaFreqNonStimBadFiltNoField = ...
        (thetaAlignedMeanStat.mThetaFreqNonStimBadFiltNoField - ...
        mean(thetaAlignedMean.meanThetaFreqNonStimBadFiltPerRecNoField(:,indTheta2to5s),2))./...
        mean(thetaAlignedMean.meanThetaFreqNonStimBadFiltPerRecNoField(:,indTheta2to5s),2);
    
    thetaAlignedMeanStat.percChangeThetaAmpNonStimGoodField = ...
        (thetaAlignedMeanStat.mThetaAmpNonStimGoodField - ...
        mean(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecField(:,indTheta2to5s),2))./...
        mean(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecField(:,indTheta2to5s),2);
    
    thetaAlignedMeanStat.percChangeThetaAmpNonStimGoodNoField = ...
        (thetaAlignedMeanStat.mThetaAmpNonStimGoodNoField - ...
        mean(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecNoField(:,indTheta2to5s),2))./...
        mean(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecNoField(:,indTheta2to5s),2);
    
    thetaAlignedMeanStat.percChangeThetaAmpNonStimBadField = ...
        (thetaAlignedMeanStat.mThetaAmpNonStimBadField - ...
        mean(thetaAlignedMean.meanThetaAmpNonStimBadPerRecField(:,indTheta2to5s),2))./...
        mean(thetaAlignedMean.meanThetaAmpNonStimBadPerRecField(:,indTheta2to5s),2);
    
    thetaAlignedMeanStat.percChangeThetaAmpNonStimBadNoField = ...
        (thetaAlignedMeanStat.mThetaAmpNonStimBadNoField - ...
        mean(thetaAlignedMean.meanThetaAmpNonStimBadPerRecNoField(:,indTheta2to5s),2))./...
        mean(thetaAlignedMean.meanThetaAmpNonStimBadPerRecNoField(:,indTheta2to5s),2);
    
    thetaAlignedMeanStat.pRSPercChangeThetaFreqNonStimGoodFilt = ranksum(...
        thetaAlignedMeanStat.percChangeThetaFreqNonStimGoodFiltField,...
        thetaAlignedMeanStat.percChangeThetaFreqNonStimGoodFiltNoField);
    
    thetaAlignedMeanStat.pRSPercChangeThetaFreqNonStimBadFilt = ranksum(...
        thetaAlignedMeanStat.percChangeThetaFreqNonStimBadFiltField,...
        thetaAlignedMeanStat.percChangeThetaFreqNonStimBadFiltNoField);
    
    thetaAlignedMeanStat.pRSPercChangeThetaAmpNonStimGood = ranksum(...
        thetaAlignedMeanStat.percChangeThetaAmpNonStimGoodField,...
        thetaAlignedMeanStat.percChangeThetaAmpNonStimGoodNoField);
    
    thetaAlignedMeanStat.pRSPercChangeThetaAmpNonStimBad = ranksum(...
        thetaAlignedMeanStat.percChangeThetaAmpNonStimBadField,...
        thetaAlignedMeanStat.percChangeThetaAmpNonStimBadNoField);
end

function plotTheta(pathAnal,timeSteps,field,noField,xli,yl,filename)
    options.handle     = figure;
    set(options.handle,'OuterPosition',...
        [500 500 280 280])
    options.color_areaX = [27 117 187]./255;    % Blue theme
    options.color_lineX = [ 39 169 225]./255;
    options.color_areaY = [187 189 192]./255;    % Orange theme
    options.color_lineY = [167 169  171]./255;
    options.alpha      = 0.5;
    options.line_width = 0.5;
    options.error      = 'sem';
    options.x_axisX = timeSteps;
    options.x_axisY = timeSteps;
    plot_areaerrorbarXY(field, noField,...
        options);
    set(gca,'XLim',xli);
    xlabel('Time (s)')
    ylabel(yl)
    legend('','Field','','No Field')
    
    fileName1 = [pathAnal filename...
        '-Field-NoField'];
    saveas(gcf,fileName1);
    print('-painters', '-dpdf', fileName1, '-r600')
end

function plotBoxPlot(x1,x2,yl,fn,pathAnal,ylimit,p,colorSel)
    [figNew,pos] = CreateFig();
    set(0,'Units','pixels')
    set(figure(figNew),'OuterPosition',...
            [pos(1) pos(2) 200 400])
    if(colorSel == 0)
        colorArr = [163 207 98;...
                234 131 114]/255;
    elseif(colorSel == 1)            
        colorArr = [234 131 114;...
                116 53 61]/255;
    else        
        colorArr = [163 207 98;... 
            63 79 37]/255;
    end
    x = [x1;x2];
    g = [repmat({'C1'},length(x1),1);...
        repmat({'C2'},length(x2),1)];
    boxplot(x,g,'Notch','on','Widths',0.3,'Symbol','');
    h = findobj(gca,'Tag','Box');
    for j = 1:length(h)
        patch(get(h(j),'XData'),get(h(j),'YData'),colorArr(j,:),'FaceAlpha',0.5);
    end
    if(~isempty(ylimit))
        set(gca,'YLim',ylimit);
    end
    ylabel(yl);
    title(['p = ' num2str(p)]);
    
    fileName1 = [pathAnal fn];
    saveas(gcf,fileName1);
    print('-painters', '-dpdf', fileName1, '-r600')
end

function plotThetaAlignedMean(pathAnal,thetaAlignedMean,thetaAlignedMeanStat)
    colorSel = 0;
    % baseline
    plotBoxPlot(reshape(thetaAlignedMean.meanThetaFreqNonStimGoodPerRecField...
        (:,thetaAlignedMeanStat.indThetaBaseline),[],1),...
        reshape(thetaAlignedMean.meanThetaFreqNonStimGoodPerRecNoField...
        (:,thetaAlignedMeanStat.indThetaBaseline),[],1),...
        'Theta freq. (Hz) baseline good trials','meanThetaFreqNonStimGoodPerRecFieldBaselineBox',...
        pathAnal,[6 9],thetaAlignedMeanStat.pRSMeanThetaFreqNonStimGoodPerRecFieldBaseline,colorSel);
    
    plotBoxPlot(reshape(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecField...
        (:,thetaAlignedMeanStat.indThetaBaseline),[],1),...
        reshape(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecNoField...
        (:,thetaAlignedMeanStat.indThetaBaseline),[],1),...
        'Theta amp. baseline good trials','meanThetaAmpNonStimGoodPerRecFieldBaselineBox',...
        pathAnal,[0 500],thetaAlignedMeanStat.pRSMeanThetaAmpNonStimGoodPerRecFieldBaseline,colorSel);
    
    % before run
    plotBoxPlot(reshape(thetaAlignedMean.meanThetaFreqNonStimGoodPerRecField...
        (:,thetaAlignedMeanStat.indThetaBefRun),[],1),...
        reshape(thetaAlignedMean.meanThetaFreqNonStimGoodPerRecNoField...
        (:,thetaAlignedMeanStat.indThetaBefRun),[],1),...
        'Theta freq. (Hz) bef. run good trials','meanThetaFreqNonStimGoodPerRecFieldBefRunBox',...
        pathAnal,[6 9],thetaAlignedMeanStat.pRSMeanThetaFreqNonStimGoodPerRecFieldBefRun,colorSel);
    
    plotBoxPlot(reshape(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecField...
        (:,thetaAlignedMeanStat.indThetaBefRun),[],1),...
        reshape(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecNoField...
        (:,thetaAlignedMeanStat.indThetaBefRun),[],1),...
        'Theta amp. bef run good trials','meanThetaAmpNonStimGoodPerRecFieldBefRunBox',...
        pathAnal,[0 500],thetaAlignedMeanStat.pRSMeanThetaAmpNonStimGoodPerRecFieldBefRun,colorSel);
    
    % 0-0.5 s
    plotBoxPlot(reshape(thetaAlignedMean.meanThetaFreqNonStimGoodPerRecField...
        (:,thetaAlignedMeanStat.indTheta0to0p5s),[],1),...
        reshape(thetaAlignedMean.meanThetaFreqNonStimGoodPerRecNoField...
        (:,thetaAlignedMeanStat.indTheta0to0p5s),[],1),...
        'Theta freq. (Hz) 0-0.5s good trials','meanThetaFreqNonStimGoodPerRecField0to0p5sBox',...
        pathAnal,[6 9],thetaAlignedMeanStat.pRSMeanThetaFreqNonStimGoodPerRecField0to0p5s,colorSel);
    
    plotBoxPlot(reshape(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecField...
        (:,thetaAlignedMeanStat.indTheta0to0p5s),[],1),...
        reshape(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecNoField...
        (:,thetaAlignedMeanStat.indTheta0to0p5s),[],1),...
        'Theta amp. 0-0.5s good trials','meanThetaAmpNonStimGoodPerRecField0to0p5sBox',...
        pathAnal,[0 500],thetaAlignedMeanStat.pRSMeanThetaAmpNonStimGoodPerRecField0to0p5s,colorSel);
    
    % 1-5 s
    plotBoxPlot(reshape(thetaAlignedMean.meanThetaFreqNonStimGoodPerRecField...
        (:,thetaAlignedMeanStat.indTheta1to5s),[],1),...
        reshape(thetaAlignedMean.meanThetaFreqNonStimGoodPerRecNoField...
        (:,thetaAlignedMeanStat.indTheta1to5s),[],1),...
        'Theta freq. (Hz) 1-5s good trials','meanThetaFreqNonStimGoodPerRecField1to5sBox',...
        pathAnal,[6 9],thetaAlignedMeanStat.pRSMeanThetaFreqNonStimGoodPerRecField1to5s,colorSel);
    
    plotBoxPlot(reshape(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecField...
        (:,thetaAlignedMeanStat.indTheta1to5s),[],1),...
        reshape(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecNoField...
        (:,thetaAlignedMeanStat.indTheta1to5s),[],1),...
        'Theta amp. 1-5s good trials','meanThetaAmpNonStimGoodPerRecField1to5sBox',...
        pathAnal,[0 500],thetaAlignedMeanStat.pRSMeanThetaAmpNonStimGoodPerRecField1to5s,colorSel);
    
    % 0-5 s
    plotBoxPlot(reshape(thetaAlignedMean.meanThetaFreqNonStimGoodPerRecField...
        (:,thetaAlignedMeanStat.indTheta0to5s),[],1),...
        reshape(thetaAlignedMean.meanThetaFreqNonStimGoodPerRecNoField...
        (:,thetaAlignedMeanStat.indTheta0to5s),[],1),...
        'Theta freq. (Hz) 0-5s good trials','meanThetaFreqNonStimGoodPerRecField0to5sBox',...
        pathAnal,[6 9],thetaAlignedMeanStat.pRSMeanThetaFreqNonStimGoodPerRecField0to5s,colorSel);
    
    plotBoxPlot(reshape(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecField...
        (:,thetaAlignedMeanStat.indTheta0to5s),[],1),...
        reshape(thetaAlignedMean.meanThetaAmpNonStimGoodPerRecNoField...
        (:,thetaAlignedMeanStat.indTheta0to5s),[],1),...
        'Theta amp. 0-5s good trials','meanThetaAmpNonStimGoodPerRecField0to5sBox',...
        pathAnal,[0 500],thetaAlignedMeanStat.pRSMeanThetaAmpNonStimGoodPerRecField0to5s,colorSel);
    
    %% perc change from 0-1s vs 1-5s
    plotBoxPlot(thetaAlignedMeanStat.percChangeThetaFreqNonStimGoodFiltField,...
        thetaAlignedMeanStat.percChangeThetaFreqNonStimGoodFiltNoField,...
        'Theta freq. (Hz) 0-0.5s/2-5s good trials','percChangeThetaFreqNonStimGoodFiltFieldVsNoField',...
        pathAnal,[],thetaAlignedMeanStat.pRSPercChangeThetaFreqNonStimGoodFilt,colorSel);
    
    plotBoxPlot(thetaAlignedMeanStat.percChangeThetaAmpNonStimGoodField,...
        thetaAlignedMeanStat.percChangeThetaAmpNonStimGoodNoField,...
        'Theta amp. 0-0.5s/2-5s good trials','percChangeThetaAmpNonStimGoodFieldVsNoField',...
        pathAnal,[],thetaAlignedMeanStat.pRSPercChangeThetaAmpNonStimGood,colorSel);

end
