function accumulateRecData()
    
    RecordingListNT;
%     
%     % muscimol active licking
%     disp('muscimol active licking')
%     recDataLabel{1} = 'Muscimol active licking';
%     [recDataRunPre{1},recDataRunManip{1},recDataRunPost{1}] = ...
%                 accumRecDataRun(activeLickMuscPath,recSessionsALMusc,...
%                                 ALMuscSessions,ALMuscMazeSession);
%     [recDataCuePre{1},recDataCueManip{1},recDataCuePost{1}] = ...
%                 accumRecDataCue(activeLickMuscPath,recSessionsALMusc,...
%                                 ALMuscSessions,ALMuscMazeSession);
        
%     % muscimol passive licking
%     disp('muscimol passive licking')
%     recDataLabel{2} = 'Muscimol passive licking';
%     [recDataRunPre{2},recDataRunManip{2},recDataRunPost{2}] = ...
%             accumRecDataRun(passiveLickMuscPath,recSessionsPLMusc,...
%                             PLMuscSessions,PLMuscMazeSession);
%     [recDataCuePre{2},recDataCueManip{2},recDataCuePost{2}] = ...
%             accumRecDataCue(passiveLickMuscPath,recSessionsPLMusc,...
%                             PLMuscSessions,PLMuscMazeSession);
%     
  %%  scopolamine active licking
    disp('scopolamine active licking')
    recDataLabel{3} = 'Scopolamine active licking';
    [recDataRunPre{3},recDataRunManip{3},recDataRunPost{3}] = ...
            accumRecDataRun(activeLickScopPath,recSessionsALScop,...
                            ALScopSessions,ALScopMazeSession);
    [recDataCuePre{3},recDataCueManip{3},recDataCuePost{3}] = ...
            accumRecDataCue(activeLickScopPath,recSessionsALScop,...
                            ALScopSessions,ALScopMazeSession);
        
%     % pirenzepine active licking
%     disp('pirenzepine active licking')
%     recDataLabel{4} = 'Pirenzepine active licking';
%     [recDataRunPre{4},recDataRunManip{4},recDataRunPost{4}] = ...
%             accumRecDataRun(activeLickPirePath,recSessionsALPire,...
%                             ALPireSessions,ALPireMazeSession);
%     [recDataCuePre{4},recDataCueManip{4},recDataCuePost{4}] = ...
%             accumRecDataCue(activeLickPirePath,recSessionsALPire,...
%                             ALPireSessions,ALPireMazeSession);
%     
%     % propranolol active licking
%     disp('propranolol active licking')
%     recDataLabel{5} = 'propranolol active licking';
%     [recDataRunPre{5},recDataRunManip{5},recDataRunPost{5}] = ...
%             accumRecDataRun(activeLickPropPath,recSessionsALProp,...
%                             ALPropSessions,ALPropMazeSession);
%     [recDataCuePre{5},recDataCueManip{5},recDataCuePost{5}] = ...
%             accumRecDataCue(activeLickPropPath,recSessionsALProp,...
%                             ALPropSessions,ALPropMazeSession);
%     
%     % SCH23390 active licking
%     disp('SCH23390 active licking')
%     recDataLabel{6} = 'SCH23390 active licking';
%     [recDataRunPre{6},recDataRunManip{6},recDataRunPost{6}] = ...
%             accumRecDataRun(activeLickSCHPath,recSessionsALSCH,...
%                             ALSCHSessions,ALSCHMazeSession);
%     [recDataCuePre{6},recDataCueManip{6},recDataCuePost{6}] = ...
%             accumRecDataCue(activeLickSCHPath,recSessionsALSCH,...
%                             ALSCHSessions,ALSCHMazeSession);
%     
%     %% saline active licking
%     disp('saline active licking')
%     recDataLabel{7} = 'saline active licking';
%     [recDataRunPre{7},recDataRunManip{7},recDataRunPost{7}] = ...
%             accumRecDataRun(activeLickSalPath,recSessionsALSal,...
%                             ALSalSessions,ALSalMazeSession);
%     [recDataCuePre{7},recDataCueManip{7},recDataCuePost{7}] = ...
%             accumRecDataCue(activeLickSalPath,recSessionsALSal,...
%                             ALSalSessions,ALSalMazeSession);
    
%     %% CNO Som-cre active licking (1mM)
%     disp('CNO Som-cre active licking (1mM)')
%     recDataLabel{8} = 'CNO SST-IRES-Cre hipp. HM4Di inj. 1mM';
%     [recDataRunPre{8},recDataRunManip{8},recDataRunPost{8}] = ...
%             accumRecDataRun(activeLickSOMCNO1mMPath,recSessionsALSOMCNO1mM,...
%                             ALSOMCNO1mMSessions,ALSOMCNO1mMMazeSession);
%     [recDataCuePre{8},recDataCueManip{8},recDataCuePost{8}] = ...
%             accumRecDataCue(activeLickSOMCNO1mMPath,recSessionsALSOMCNO1mM,...
%                             ALSOMCNO1mMSessions,ALSOMCNO1mMMazeSession);
%                         
%     %% CNO Som-cre active licking (3mM)
%     disp('CNO Som-cre active licking (3mM)')
%     recDataLabel{9} = 'CNO SST-IRES-Cre hipp. HM4Di inj. 3mM';
%     [recDataRunPre{9},recDataRunManip{9},recDataRunPost{9}] = ...
%             accumRecDataRun(activeLickSOMCNO3mMPath,recSessionsALSOMCNO3mM,...
%                             ALSOMCNO3mMSessions,ALSOMCNO3mMMazeSession);
%     [recDataCuePre{9},recDataCueManip{9},recDataCuePost{9}] = ...
%             accumRecDataCue(activeLickSOMCNO3mMPath,recSessionsALSOMCNO3mM,...
%                             ALSOMCNO3mMSessions,ALSOMCNO3mMMazeSession);
    
%     %% Saline Som-cre active licking
%     disp('Saline Som-cre active licking')
%     recDataLabel{10} = 'Saline SST-IRES-Cre hipp. HM4Di inj.';
%     [recDataRunPre{10},recDataRunManip{10},recDataRunPost{10}] = ...
%             accumRecDataRun(activeLickSOMSalPath,recSessionsALSOMSal,...
%                             ALSOMSalSessions,ALSOMSalMazeSession);
%     [recDataCuePre{10},recDataCueManip{10},recDataCuePost{10}] = ...
%             accumRecDataCue(activeLickSOMSalPath,recSessionsALSOMSal,...
%                             ALSOMSalSessions,ALSOMSalMazeSession);
%     
%     %% CNO PV-cre active licking (1mM)
%     disp('CNO PV-cre active licking (1mM)')
%     recDataLabel{11} = 'CNO PV-Cre hipp. HM4Di inj. 1mM';
%     [recDataRunPre{11},recDataRunManip{11},recDataRunPost{11}] = ...
%             accumRecDataRun(activeLickPVCNO1mMPath,recSessionsALPVCNO1mM,...
%                             ALPVCNO1mMSessions,ALPVCNO1mMMazeSession);
%     [recDataCuePre{11},recDataCueManip{11},recDataCuePost{11}] = ...
%             accumRecDataCue(activeLickPVCNO1mMPath,recSessionsALPVCNO1mM,...
%                             ALPVCNO1mMSessions,ALPVCNO1mMMazeSession);
%                         
%     %% CNO PV-cre active licking (3mM)
%     disp('CNO PV-cre active licking (3mM)')
%     recDataLabel{12} = 'CNO PV-Cre hipp. HM4Di inj. 3mM';
%     [recDataRunPre{12},recDataRunManip{12},recDataRunPost{12}] = ...
%             accumRecDataRun(activeLickPVCNO3mMPath,recSessionsALPVCNO3mM,...
%                             ALPVCNO3mMSessions,ALPVCNO3mMMazeSession);
%     [recDataCuePre{12},recDataCueManip{12},recDataCuePost{12}] = ...
%             accumRecDataCue(activeLickPVCNO3mMPath,recSessionsALPVCNO3mM,...
%                             ALPVCNO3mMSessions,ALPVCNO3mMMazeSession);
%     
%     %% Saline PV-cre active licking
%     disp('Saline PV-cre active licking')
%     recDataLabel{13} = 'Saline PV-Cre hipp. HM4Di inj.';
%     [recDataRunPre{13},recDataRunManip{13},recDataRunPost{13}] = ...
%             accumRecDataRun(activeLickPVSalPath,recSessionsALPVSal,...
%                             ALPVSalSessions,ALPVSalMazeSession);
%     [recDataCuePre{13},recDataCueManip{13},recDataCuePost{13}] = ...
%             accumRecDataCue(activeLickPVSalPath,recSessionsALPVSal,...
%                             ALPVSalSessions,ALPVSalMazeSession);

%     %% CNO control animal active licking
%     disp('CNO control animal active licking')
%     recDataLabel{14} = 'CNO C57Bl6J';
%     [recDataRunPre{14},recDataRunManip{14},recDataRunPost{14}] = ...
%             accumRecDataRun(activeLickCNOPath,recSessionsALCNO,...
%                             ALCNOSessions,ALCNOMazeSession);
%     [recDataCuePre{14},recDataCueManip{14},recDataCuePost{14}] = ...
%             accumRecDataCue(activeLickCNOPath,recSessionsALCNO,...
%                             ALCNOSessions,ALCNOMazeSession);
                        
%     %% atropine-DART animal active licking
%     disp('atropine-DART CA1 neurons animal active licking')
%     recDataLabel{15} = 'atropine-DART C57Bl6J Flex-DART+iCre';
%     [recDataRunPre{15},recDataRunManip{15},recDataRunPost{15}] = ...
%             accumRecDataRun(activeLickAtroDARTPath,recSessionsALAtroDART,...
%                             ALAtroDARTSessions,ALAtroDARTMazeSession);
%     [recDataCuePre{15},recDataCueManip{15},recDataCuePost{15}] = ...
%             accumRecDataCue(activeLickAtroDARTPath,recSessionsALAtroDART,...
%                             ALAtroDARTSessions,ALAtroDARTMazeSession);
%                         
%     %% atropine-DART control animal active licking
%     disp('atropine-DART in control animal active licking')
%     recDataLabel{16} = 'atropine-DART C57Bl6J';
%     [recDataRunPre{16},recDataRunManip{16},recDataRunPost{16}] = ...
%             accumRecDataRun(activeLickAtroDARTCtrlPath,recSessionsALAtroDARTCtrl,...
%                             ALAtroDARTCtrlSessions,ALAtroDARTCtrlMazeSession);
%     [recDataCuePre{16},recDataCueManip{16},recDataCuePost{16}] = ...
%             accumRecDataCue(activeLickAtroDARTCtrlPath,recSessionsALAtroDARTCtrl,...
%                             ALAtroDARTCtrlSessions,ALAtroDARTCtrlMazeSession);
    
%    CNO Som-cre active licking Kori(3mM)
    disp('CNO Som-cre active licking Kori (3mM)')
    recDataLabel{17} = 'CNO SST-IRES-Cre hipp. HM4Di inj. 3mM Kori ';
    [recDataRunPre{17},recDataRunManip{17},recDataRunPost{17}] = ...
            accumRecDataRun(activeLickSOMCNO3mMKoriPath,recSessionsALSOMCNO3mMKori,...
                            ALSOMCNO3mMKoriSessions,ALSOMCNO3mMKoriMazeSession);
    [recDataCuePre{17},recDataCueManip{17},recDataCuePost{17}] = ...
            accumRecDataCue(activeLickSOMCNO3mMKoriPath,recSessionsALSOMCNO3mMKori,...
                            ALSOMCNO3mMKoriSessions,ALSOMCNO3mMKoriMazeSession);
% 
%     fullPath = [folderPath 'allRecData.mat'];
%     save(fullPath,'recDataRunPre','recDataRunManip','recDataRunPost',...
%         'recDataCuePre','recDataCueManip','recDataCuePost','recDataLabel','-v7.3');
%     
%         %% CNO Som-cre active licking Kori(1mM)
%     disp('CNO Som-cre active licking Kori (1mM)')
%     recDataLabel{18} = 'CNO SST-IRES-Cre hipp. HM4Di inj. 1mM Kori ';
%     [recDataRunPre{18},recDataRunManip{18},recDataRunPost{18}] = ...
%             accumRecDataRun(activeLickSOMCNO1mMKoriPath,recSessionsALSOMCNO1mMKori,...
%                             ALSOMCNO1mMKoriSessions,ALSOMCNO1mMKoriMazeSession);
%     [recDataCuePre{18},recDataCueManip{18},recDataCuePost{18}] = ...
%             accumRecDataCue(activeLickSOMCNO1mMKoriPath,recSessionsALSOMCNO1mMKori,...
%                             ALSOMCNO1mMKoriSessions,ALSOMCNO1mMKoriMazeSession);
% 
%     fullPath = [folderPath 'allRecData.mat'];
%     save(fullPath,'recDataRunPre','recDataRunManip','recDataRunPost',...
%         'recDataCuePre','recDataCueManip','recDataCuePost','recDataLabel','-v7.3');'

%             % Saline Som-cre active licking Kori
%     disp('CNO Som-cre active licking Kori saline')
%     recDataLabel{19} = 'Saline SST-IRES-Cre hipp. HM4Di inj. Kori ';
%     [recDataRunPre{19},recDataRunManip{19},recDataRunPost{19}] = ...
%             accumRecDataRun(activeLickSOMSalineKoriPath,recSessionsALSOMSalineKori,...
%                             ALSOMSalineKoriSessions,ALSOMSalineKoriMazeSession);
%     [recDataCuePre{19},recDataCueManip{19},recDataCuePost{19}] = ...
%             accumRecDataCue(activeLickSOMSalineKoriPath,recSessionsALSOMSalineKori,...
%                             ALSOMSalineKoriSessions,ALSOMSalineKoriMazeSession);
%     fullPath = [folderPath 'allRecData.mat'];
%     save(fullPath,'recDataRunPre','recDataRunManip','recDataRunPost',...
%         'recDataCuePre','recDataCueManip','recDataCuePost','recDataLabel','-v7.3');            

%     %% CNO PV-cre active licking Kori(3mM)
%     disp('CNO PV-cre active licking Kori (3mM)')
%     recDataLabel{20} = 'CNO PV-Cre hipp. HM4Di inj. 3mM Kori ';
%     [recDataRunPre{20},recDataRunManip{20},recDataRunPost{20}] = ...
%             accumRecDataRun(activeLickPVCNO3mMKoriPath,recSessionsALPVCNO3mMKori,...
%                             ALPVCNO3mMKoriSessions,ALPVCNO3mMKoriMazeSession);
%     [recDataCuePre{20},recDataCueManip{20},recDataCuePost{20}] = ...
%             accumRecDataCue(activeLickPVCNO3mMKoriPath,recSessionsALPVCNO3mMKori,...
%                             ALPVCNO3mMKoriSessions,ALPVCNO3mMKoriMazeSession);

%     fullPath = [folderPath 'allRecData.mat'];
%     save(fullPath,'recDataRunPre','recDataRunManip','recDataRunPost',...
%         'recDataCuePre','recDataCueManip','recDataCuePost','recDataLabel','-v7.3');
    
%         %% CNO PV-cre active licking Kori(1mM)
%     disp('CNO PV-cre active licking Kori (1mM)')
%     recDataLabel{21} = 'CNO PV-Cre hipp. HM4Di inj. 1mM Kori ';
%     [recDataRunPre{21},recDataRunManip{21},recDataRunPost{21}] = ...
%             accumRecDataRun(activeLickPVCNO1mMKoriPath,recSessionsALPVCNO1mMKori,...
%                             ALPVCNO1mMKoriSessions,ALPVCNO1mMKoriMazeSession);
%     [recDataCuePre{21},recDataCueManip{21},recDataCuePost{21}] = ...
%             accumRecDataCue(activeLickPVCNO1mMKoriPath,recSessionsALPVCNO1mMKori,...
%                             ALPVCNO1mMKoriSessions,ALPVCNO1mMKoriMazeSession);
%     fullPath = [folderPath 'allRecData.mat'];
%     save(fullPath,'recDataRunPre','recDataRunManip','recDataRunPost',...
%         'recDataCuePre','recDataCueManip','recDataCuePost','recDataLabel','-v7.3');

%      %% Saline PV-cre active licking Kori
%     disp('CNO PV-cre active licking Kori saline')
%     recDataLabel{22} = 'Saline PV-Cre hipp. HM4Di inj. Kori ';
%     [recDataRunPre{22},recDataRunManip{22},recDataRunPost{22}] = ...
%             accumRecDataRun(activeLickPVSalineKoriPath,recSessionsALPVSalineKori,...
%                             ALPVSalineKoriSessions,ALPVSalineKoriMazeSession);
%     [recDataCuePre{22},recDataCueManip{22},recDataCuePost{22}] = ...
%             accumRecDataCue(activeLickPVSalineKoriPath,recSessionsALPVSalineKori,...
%                             ALPVSalineKoriSessions,ALPVSalineKoriMazeSession);
% 
%     %% C21 Som-cre active licking(3mM)
%     disp('C21 Som-cre active licking (3mM)')
%     recDataLabel{23} = 'C21 SST-IRES-Cre hipp. 3mM ';
%     [recDataRunPre{23},recDataRunManip{23},recDataRunPost{23}] = ...
%             accumRecDataRun(activeLickSOMC213mMPath,recSessionsALSOMC213mM,...
%                             ALSOMC213mMSessions,ALSOMC213mMMazeSession);
%     [recDataCuePre{23},recDataCueManip{23},recDataCuePost{23}] = ...
%             accumRecDataCue(activeLickSOMC213mMPath,recSessionsALSOMC213mM,...
%                             ALSOMC213mMSessions,ALSOMC213mMMazeSession);

    fullPath = [folderPath 'allRecData.mat'];
    save(fullPath,'recDataRunPre','recDataRunManip','recDataRunPost',...
        'recDataCuePre','recDataCueManip','recDataCuePost','recDataLabel','-v7.3');
end
