function accumulateRecData_opto(mode, summExp, optoStim)
    
    if(mode == 1)
        RecordingListNT_opto1; % including the continous stimulation
    elseif(mode == 2)
        RecordingListNT_opto2; % excluding the continous stimulation
    else
        RecordingListNT_opto; 
    end
    
    % SCH active licking reward
    if(summExp == 1)
        disp('SCH23390 active licking reward')
        n = 1;
        recDataLabel{n} = 'SCH23390 active licking reward';
        optoStim = 1;
        [recDataRunPre{n},recDataRunManip{n},recDataRunPost{n},...
            recDataRunPreOpt{n},recDataRunManipOpt{n},recDataRunPostOpt{n},...
            recDataRunPreOptCtrl{n},recDataRunManipOptCtrl{n},recDataRunPostOptCtrl{n}] = ...
                    accumRecDataRun_opto(activeLickSCHPath,ALRecSessionsSCH,...
                                    ALMazeTypeSCH,ALMazeSessionSCH,...
                                    ALOptoStimPulseWSCH,optoStim);
        [recDataCuePre{n},recDataCueManip{n},recDataCuePost{n},...
            recDataCuePreOpt{n},recDataCueManipOpt{n},recDataCuePostOpt{n},...
            recDataCuePreOptCtrl{n},recDataCueManipOptCtrl{n},recDataCuePostOptCtrl{n}] = ...
                    accumRecDataCue_opto(activeLickSCHPath,ALRecSessionsSCH,...
                                    ALMazeTypeSCH,ALMazeSessionSCH,...
                                    ALOptoStimPulseWSCH,optoStim);
        [recDataRewPre{n},recDataRewManip{n},recDataRewPost{n},...
            recDataRewPreOpt{n},recDataRewManipOpt{n},recDataRewPostOpt{n},...
            recDataRewPreOptCtrl{n},recDataRewManipOptCtrl{n},recDataRewPostOptCtrl{n}] = ...
                    accumRecDataRew_opto(activeLickSCHPath,ALRecSessionsSCH,...
                                    ALMazeTypeSCH,ALMazeSessionSCH,...
                                    ALOptoStimPulseWSCH,optoStim);
    end
    
    % saline active licking reward
    if(summExp == 4)
        disp('saline active licking reward')
        n = 1;
        recDataLabel{n} = 'saline active licking reward';
        optoStim = 1;
        [recDataRunPre{n},recDataRunManip{n},recDataRunPost{n},...
            recDataRunPreOpt{n},recDataRunManipOpt{n},recDataRunPostOpt{n},...
            recDataRunPreOptCtrl{n},recDataRunManipOptCtrl{n},recDataRunPostOptCtrl{n}] = ...
                    accumRecDataRun_opto(activeLickSalPath,ALRecSessionsSal,...
                                    ALMazeTypeSal,ALMazeSessionSal,...
                                    ALOptoStimPulseWSal,optoStim);
        [recDataCuePre{n},recDataCueManip{n},recDataCuePost{n},...
            recDataCuePreOpt{n},recDataCueManipOpt{n},recDataCuePostOpt{n},...
            recDataCuePreOptCtrl{n},recDataCueManipOptCtrl{n},recDataCuePostOptCtrl{n}] = ...
                    accumRecDataCue_opto(activeLickSalPath,ALRecSessionsSal,...
                                    ALMazeTypeSal,ALMazeSessionSal,...
                                    ALOptoStimPulseWSal,optoStim);
        [recDataRewPre{n},recDataRewManip{n},recDataRewPost{n},...
            recDataRewPreOpt{n},recDataRewManipOpt{n},recDataRewPostOpt{n},...
            recDataRewPreOptCtrl{n},recDataRewManipOptCtrl{n},recDataRewPostOptCtrl{n}] = ...
                    accumRecDataRew_opto(activeLickSalPath,ALRecSessionsSal,...
                                    ALMazeTypeSal,ALMazeSessionSal,...
                                    ALOptoStimPulseWSal,optoStim);
    end
    
    % Dbh active licking reward
    if(summExp == 2)
        disp('Dbh active licking running')
        n = 1;
        recDataLabel{n} = 'Dbh active licking running';
%         optoStim = 3;
        if(optoStim == 2)
            disp(['optoStim = ' 'run-onset'])
        elseif(optoStim == 3)
            disp(['optoStim = ' 'mid-trial'])
        elseif(optoStim == 4)
            disp(['optoStim = ' 'reward-delivery'])
        elseif(optoStim == 9)
            disp(['optoStim = ' 'un-coupled 0-2-0'])
        elseif(optoStim == 10)
            disp(['optoStim = ' 'un-coupled 0-3-0'])
        elseif(optoStim == 11)
            disp(['optoStim = ' 'un-coupled 0-4-0'])
        end
        [recDataRunPre{n},recDataRunManip{n},recDataRunPost{n},...
            recDataRunPreOpt{n},recDataRunManipOpt{n},recDataRunPostOpt{n},...
            recDataRunPreOptCtrl{n},recDataRunManipOptCtrl{n},recDataRunPostOptCtrl{n}] = ...
                    accumRecDataRun_opto(activeLickOptoDbhPath,ALRecSessionsOptoDbh,...
                                    ALMazeTypeOptoDbh,ALMazeSessionOptoDbh,...
                                    ALOptoStimPulseWDbh,optoStim);
        [recDataCuePre{n},recDataCueManip{n},recDataCuePost{n},...
            recDataCuePreOpt{n},recDataCueManipOpt{n},recDataCuePostOpt{n},...
            recDataCuePreOptCtrl{n},recDataCueManipOptCtrl{n},recDataCuePostOptCtrl{n}] = ...
                    accumRecDataCue_opto(activeLickOptoDbhPath,ALRecSessionsOptoDbh,...
                                    ALMazeTypeOptoDbh,ALMazeSessionOptoDbh,...
                                    ALOptoStimPulseWDbh,optoStim);
        [recDataRewPre{n},recDataRewManip{n},recDataRewPost{n},...
            recDataRewPreOpt{n},recDataRewManipOpt{n},recDataRewPostOpt{n},...
            recDataRewPreOptCtrl{n},recDataRewManipOptCtrl{n},recDataRewPostOptCtrl{n}] = ...
                    accumRecDataRew_opto(activeLickOptoDbhPath,ALRecSessionsOptoDbh,...
                                    ALMazeTypeOptoDbh,ALMazeSessionOptoDbh,...
                                    ALOptoStimPulseWDbh,optoStim);
    end
    
    % Dbh activation active
    if(summExp == 6)
        disp('Dbh active licking running (activation hChR2)')
        n = 1;
        recDataLabel{n} = 'Dbh active licking running (activation hChR2)';
%         optoStim = 4;
        if(optoStim == 2)
            disp(['optoStim = ' 'run-onset'])
        elseif(optoStim == 3)
            disp(['optoStim = ' 'mid-trial'])
        elseif(optoStim == 4)
            disp(['optoStim = ' 'reward-delivery'])
        elseif(optoStim == 9)
            disp(['optoStim = ' 'un-coupled 0-2-0'])
        elseif(optoStim == 10)
            disp(['optoStim = ' 'un-coupled 0-3-0'])
        elseif(optoStim == 11)
            disp(['optoStim = ' 'un-coupled 0-4-0'])
        end
        [recDataRunPre{n},recDataRunManip{n},recDataRunPost{n},...
            recDataRunPreOpt{n},recDataRunManipOpt{n},recDataRunPostOpt{n},...
            recDataRunPreOptCtrl{n},recDataRunManipOptCtrl{n},recDataRunPostOptCtrl{n}] = ...
                    accumRecDataRun_opto(activeLickOptoDbhActPath,ALRecSessionsOptoDbhAct,...
                                    ALMazeTypeOptoDbhAct,ALMazeSessionOptoDbhAct,...
                                    ALOptoStimPulseWDbhAct,optoStim);
        [recDataCuePre{n},recDataCueManip{n},recDataCuePost{n},...
            recDataCuePreOpt{n},recDataCueManipOpt{n},recDataCuePostOpt{n},...
            recDataCuePreOptCtrl{n},recDataCueManipOptCtrl{n},recDataCuePostOptCtrl{n}] = ...
                    accumRecDataCue_opto(activeLickOptoDbhActPath,ALRecSessionsOptoDbhAct,...
                                    ALMazeTypeOptoDbhAct,ALMazeSessionOptoDbhAct,...
                                    ALOptoStimPulseWDbhAct,optoStim);
        [recDataRewPre{n},recDataRewManip{n},recDataRewPost{n},...
            recDataRewPreOpt{n},recDataRewManipOpt{n},recDataRewPostOpt{n},...
            recDataRewPreOptCtrl{n},recDataRewManipOptCtrl{n},recDataRewPostOptCtrl{n}] = ...
                    accumRecDataRew_opto(activeLickOptoDbhActPath,ALRecSessionsOptoDbhAct,...
                                    ALMazeTypeOptoDbhAct,ALMazeSessionOptoDbhAct,...
                                    ALOptoStimPulseWDbhAct,optoStim);
    end
    
    % SUL active licking reward
    if(summExp == 3)
        disp('Sulpiride active licking running')
        n = 1;
        recDataLabel{n} = 'Sulpiride active licking running';
        optoStim = 1;
        [recDataRunPre{n},recDataRunManip{n},recDataRunPost{n},...
            recDataRunPreOpt{n},recDataRunManipOpt{n},recDataRunPostOpt{n},...
            recDataRunPreOptCtrl{n},recDataRunManipOptCtrl{n},recDataRunPostOptCtrl{n}] = ...
                    accumRecDataRun_opto(activeLickSulPath,ALRecSessionsSul,...
                                    ALMazeTypeSul,ALMazeSessionSul,...
                                    ALOptoStimPulseWSul,optoStim);
        [recDataCuePre{n},recDataCueManip{n},recDataCuePost{n},...
            recDataCuePreOpt{n},recDataCueManipOpt{n},recDataCuePostOpt{n},...
            recDataCuePreOptCtrl{n},recDataCueManipOptCtrl{n},recDataCuePostOptCtrl{n}] = ...
                    accumRecDataCue_opto(activeLickSulPath,ALRecSessionsSul,...
                                    ALMazeTypeSul,ALMazeSessionSul,...
                                    ALOptoStimPulseWSul,optoStim);
        [recDataRewPre{n},recDataRewManip{n},recDataRewPost{n},...
            recDataRewPreOpt{n},recDataRewManipOpt{n},recDataRewPostOpt{n},...
            recDataRewPreOptCtrl{n},recDataRewManipOptCtrl{n},recDataRewPostOptCtrl{n}] = ...
                    accumRecDataRew_opto(activeLickSulPath,ALRecSessionsSul,...
                                    ALMazeTypeSul,ALMazeSessionSul,...
                                    ALOptoStimPulseWSul,optoStim);
    end
    
%     Saline active licking reward
%     disp('Saline active licking running stim')
%     n = 1;
%     recDataLabel{n} = 'Saline active licking running stim';
%     optoStim = 1;
%     [recDataRunPre{n},recDataRunManip{n},recDataRunPost{n},...
%         recDataRunPreOpt{n},recDataRunManipOpt{n},recDataRunPostOpt{n},...
%         recDataRunPreOptCtrl{n},recDataRunManipOptCtrl{n},recDataRunPostOptCtrl{n}] = ...
%                 accumRecDataRun_opto(activeLickSalPath,ALRecSessionsSal,...
%                                 ALMazeTypeSal,ALMazeSessionSal,...
%                                 ALOptoStimPulseWSal,optoStim);
%     [recDataCuePre{n},recDataCueManip{n},recDataCuePost{n},...
%         recDataCuePreOpt{n},recDataCueManipOpt{n},recDataCuePostOpt{n},...
%         recDataCuePreOptCtrl{n},recDataCueManipOptCtrl{n},recDataCuePostOptCtrl{n}] = ...
%                 accumRecDataCue_opto(activeLickSalPath,ALRecSessionsSal,...
%                                 ALMazeTypeSal,ALMazeSessionSal,...
%                                 ALOptoStimPulseWSal,optoStim);
%     [recDataRewPre{n},recDataRewManip{n},recDataRewPost{n},...
%         recDataRewPreOpt{n},recDataRewManipOpt{n},recDataRewPostOpt{n},...
%         recDataRewPreOptCtrl{n},recDataRewManipOptCtrl{n},recDataRewPostOptCtrl{n}] = ...
%                 accumRecDataRew_opto(activeLickSalPath,ALRecSessionsSal,...
%                                 ALMazeTypeSal,ALMazeSessionSal,...
%                                 ALOptoStimPulseWSal,optoStim);
%                             
%     disp('SST active licking running onset stim 3 sec')
%     n = 4;
%     recDataLabel{n} = 'SST active licking running onset stim 3 sec';
%     optoStim = 2;
%     [recDataRunPre{n},recDataRunManip{n},recDataRunPost{n},...
%         recDataRunPreOpt{n},recDataRunManipOpt{n},recDataRunPostOpt{n},...
%         recDataRunPreOptCtrl{n},recDataRunManipOptCtrl{n},recDataRunPostOptCtrl{n}] = ...
%                 accumRecDataRun_opto(activeLickOptoSSTPath,ALRecSessionsOptoSST,...
%                                 ALOptoMazeTypeSST,ALOptoMazeSessionSST,...
%                                 ALOptoStimPulseWSST,optoStim);
%     [recDataCuePre{n},recDataCueManip{n},recDataCuePost{n},...
%         recDataCuePreOpt{n},recDataCueManipOpt{n},recDataCuePostOpt{n},...
%         recDataCuePreOptCtrl{n},recDataCueManipOptCtrl{n},recDataCuePostOptCtrl{n}] = ...
%                 accumRecDataCue_opto(activeLickOptoSSTPath,ALRecSessionsOptoSST,...
%                                 ALOptoMazeTypeSST,ALOptoMazeSessionSST,...
%                                 ALOptoStimPulseWSST,optoStim);
%     [recDataRewPre{n},recDataRewManip{n},recDataRewPost{n},...
%         recDataRewPreOpt{n},recDataRewManipOpt{n},recDataRewPostOpt{n},...
%         recDataRewPreOptCtrl{n},recDataRewManipOptCtrl{n},recDataRewPostOptCtrl{n}] = ...
%                 accumRecDataRew_opto(activeLickOptoSSTPath,ALRecSessionsOptoSST,...
%                                 ALOptoMazeTypeSST,ALOptoMazeSessionSST,...
%                                 ALOptoStimPulseWSST,optoStim);
%                             
%     disp('SST active licking cue onset stim 3 sec')
%     n = 5;
%     recDataLabel{n} = 'SST active licking cue onset stim 3 sec';
%     optoStim = 1;
%     [recDataRunPre{n},recDataRunManip{n},recDataRunPost{n},...
%         recDataRunPreOpt{n},recDataRunManipOpt{n},recDataRunPostOpt{n},...
%         recDataRunPreOptCtrl{n},recDataRunManipOptCtrl{n},recDataRunPostOptCtrl{n}] = ...
%                 accumRecDataRun_opto(activeLickOptoSSTPath,ALRecSessionsOptoSST,...
%                                 ALOptoMazeTypeSST,ALOptoMazeSessionSST,...
%                                 ALOptoStimPulseWSST,optoStim);
%     [recDataCuePre{n},recDataCueManip{n},recDataCuePost{n},...
%         recDataCuePreOpt{n},recDataCueManipOpt{n},recDataCuePostOpt{n},...
%         recDataCuePreOptCtrl{n},recDataCueManipOptCtrl{n},recDataCuePostOptCtrl{n}] = ...
%                 accumRecDataCue_opto(activeLickOptoSSTPath,ALRecSessionsOptoSST,...
%                                 ALOptoMazeTypeSST,ALOptoMazeSessionSST,...
%                                 ALOptoStimPulseWSST,optoStim);
%     [recDataRewPre{n},recDataRewManip{n},recDataRewPost{n},...
%         recDataRewPreOpt{n},recDataRewManipOpt{n},recDataRewPostOpt{n},...
%         recDataRewPreOptCtrl{n},recDataRewManipOptCtrl{n},recDataRewPostOptCtrl{n}] = ...
%                 accumRecDataRew_opto(activeLickOptoSSTPath,ALRecSessionsOptoSST,...
%                                 ALOptoMazeTypeSST,ALOptoMazeSessionSST,...
%                                 ALOptoStimPulseWSST,optoStim);
%                             
%     disp('SST active licking middle cue stim 3 sec')
%     n = 6;
%     recDataLabel{n} = 'SST active licking middle cue stim 3 sec';
%     optoStim = 3;
%     [recDataRunPre{n},recDataRunManip{n},recDataRunPost{n},...
%         recDataRunPreOpt{n},recDataRunManipOpt{n},recDataRunPostOpt{n},...
%         recDataRunPreOptCtrl{n},recDataRunManipOptCtrl{n},recDataRunPostOptCtrl{n}] = ...
%                 accumRecDataRun_opto(activeLickOptoSSTPath,ALRecSessionsOptoSST,...
%                                 ALOptoMazeTypeSST,ALOptoMazeSessionSST,...
%                                 ALOptoStimPulseWSST,optoStim);
%     [recDataCuePre{n},recDataCueManip{n},recDataCuePost{n},...
%         recDataCuePreOpt{n},recDataCueManipOpt{n},recDataCuePostOpt{n},...
%         recDataCuePreOptCtrl{n},recDataCueManipOptCtrl{n},recDataCuePostOptCtrl{n}] = ...
%                 accumRecDataCue_opto(activeLickOptoSSTPath,ALRecSessionsOptoSST,...
%                                 ALOptoMazeTypeSST,ALOptoMazeSessionSST,...
%                                 ALOptoStimPulseWSST,optoStim);
%     [recDataRewPre{n},recDataRewManip{n},recDataRewPost{n},...
%         recDataRewPreOpt{n},recDataRewManipOpt{n},recDataRewPostOpt{n},...
%         recDataRewPreOptCtrl{n},recDataRewManipOptCtrl{n},recDataRewPostOptCtrl{n}] = ...
%                 accumRecDataRew_opto(activeLickOptoSSTPath,ALRecSessionsOptoSST,...
%                                 ALOptoMazeTypeSST,ALOptoMazeSessionSST,...
%                                 ALOptoStimPulseWSST,optoStim);
%                             
%     disp('SST active licking start cue stim 3 sec or to < 100 cm')
%     n = 7;
%     recDataLabel{n} = 'SST active licking start cue stim 3 sec or to < 100 cm';
%     optoStim = 7;
%     [recDataRunPre{n},recDataRunManip{n},recDataRunPost{n},...
%         recDataRunPreOpt{n},recDataRunManipOpt{n},recDataRunPostOpt{n},...
%         recDataRunPreOptCtrl{n},recDataRunManipOptCtrl{n},recDataRunPostOptCtrl{n}] = ...
%                 accumRecDataRun_opto(activeLickOptoSSTPath,ALRecSessionsOptoSST,...
%                                 ALOptoMazeTypeSST,ALOptoMazeSessionSST,...
%                                 ALOptoStimPulseWSST,optoStim);
%     [recDataCuePre{n},recDataCueManip{n},recDataCuePost{n},...
%         recDataCuePreOpt{n},recDataCueManipOpt{n},recDataCuePostOpt{n},...
%         recDataCuePreOptCtrl{n},recDataCueManipOptCtrl{n},recDataCuePostOptCtrl{n}] = ...
%                 accumRecDataCue_opto(activeLickOptoSSTPath,ALRecSessionsOptoSST,...
%                                 ALOptoMazeTypeSST,ALOptoMazeSessionSST,...
%                                 ALOptoStimPulseWSST,optoStim);
%     [recDataRewPre{n},recDataRewManip{n},recDataRewPost{n},...
%         recDataRewPreOpt{n},recDataRewManipOpt{n},recDataRewPostOpt{n},...
%         recDataRewPreOptCtrl{n},recDataRewManipOptCtrl{n},recDataRewPostOptCtrl{n}] = ...
%                 accumRecDataRew_opto(activeLickOptoSSTPath,ALRecSessionsOptoSST,...
%                                 ALOptoMazeTypeSST,ALOptoMazeSessionSST,...
%                                 ALOptoStimPulseWSST,optoStim);
%                             
%     disp('SST active licking middle cue stim 3 sec or to black out start')
%     n = 8;
%     recDataLabel{n} = 'SST active licking middle cue stim 3 sec or to black out start';
%     optoStim = 8;
%     [recDataRunPre{n},recDataRunManip{n},recDataRunPost{n},...
%         recDataRunPreOpt{n},recDataRunManipOpt{n},recDataRunPostOpt{n},...
%         recDataRunPreOptCtrl{n},recDataRunManipOptCtrl{n},recDataRunPostOptCtrl{n}] = ...
%                 accumRecDataRun_opto(activeLickOptoSSTPath,ALRecSessionsOptoSST,...
%                                 ALOptoMazeTypeSST,ALOptoMazeSessionSST,...
%                                 ALOptoStimPulseWSST,optoStim);
%     [recDataCuePre{n},recDataCueManip{n},recDataCuePost{n},...
%         recDataCuePreOpt{n},recDataCueManipOpt{n},recDataCuePostOpt{n},...
%         recDataCuePreOptCtrl{n},recDataCueManipOptCtrl{n},recDataCuePostOptCtrl{n}] = ...
%                 accumRecDataCue_opto(activeLickOptoSSTPath,ALRecSessionsOptoSST,...
%                                 ALOptoMazeTypeSST,ALOptoMazeSessionSST,...
%                                 ALOptoStimPulseWSST,optoStim);
%     [recDataRewPre{n},recDataRewManip{n},recDataRewPost{n},...
%         recDataRewPreOpt{n},recDataRewManipOpt{n},recDataRewPostOpt{n},...
%         recDataRewPreOptCtrl{n},recDataRewManipOptCtrl{n},recDataRewPostOptCtrl{n}] = ...
%                 accumRecDataRew_opto(activeLickOptoSSTPath,ALRecSessionsOptoSST,...
%                                 ALOptoMazeTypeSST,ALOptoMazeSessionSST,...
%                                 ALOptoStimPulseWSST,optoStim);
%                             
%     disp('SST active licking control, fiber not completely plugged in')
%     n = 9;
%     recDataLabel{n} = 'SST active licking control, fiber not completely plugged in';
%     optoStim = 9;
%     [recDataRunPre{n},recDataRunManip{n},recDataRunPost{n},...
%         recDataRunPreOpt{n},recDataRunManipOpt{n},recDataRunPostOpt{n},...
%         recDataRunPreOptCtrl{n},recDataRunManipOptCtrl{n},recDataRunPostOptCtrl{n}] = ...
%                 accumRecDataRun_opto(activeLickOptoSSTPath,ALRecSessionsOptoSST,...
%                                 ALOptoMazeTypeSST,ALOptoMazeSessionSST,...
%                                 ALOptoStimPulseWSST,optoStim);
%     [recDataCuePre{n},recDataCueManip{n},recDataCuePost{n},...
%         recDataCuePreOpt{n},recDataCueManipOpt{n},recDataCuePostOpt{n},...
%         recDataCuePreOptCtrl{n},recDataCueManipOptCtrl{n},recDataCuePostOptCtrl{n}] = ...
%                 accumRecDataCue_opto(activeLickOptoSSTPath,ALRecSessionsOptoSST,...
%                                 ALOptoMazeTypeSST,ALOptoMazeSessionSST,...
%                                 ALOptoStimPulseWSST,optoStim);
%     [recDataRewPre{n},recDataRewManip{n},recDataRewPost{n},...
%         recDataRewPreOpt{n},recDataRewManipOpt{n},recDataRewPostOpt{n},...
%         recDataRewPreOptCtrl{n},recDataRewManipOptCtrl{n},recDataRewPostOptCtrl{n}] = ...
%                 accumRecDataRew_opto(activeLickOptoSSTPath,ALRecSessionsOptoSST,...
%                                 ALOptoMazeTypeSST,ALOptoMazeSessionSST,...
%                                 ALOptoStimPulseWSST,optoStim);
%         
%     PV active licking reward stim
%     disp('PV active licking reward stim')
%     n = 10;
%     recDataLabel{n} = 'PV active licking reward stim';
%     optoStim = 6;
%     [recDataRunPre{n},recDataRunManip{n},recDataRunPost{n},...
%         recDataRunPreOpt{n},recDataRunManipOpt{n},recDataRunPostOpt{n},...
%         recDataRunPreOptCtrl{n},recDataRunManipOptCtrl{n},recDataRunPostOptCtrl{n}] = ...
%                 accumRecDataRun_opto(activeLickOptoPVPath,ALRecSessionsOptoPV,...
%                                 ALOptoMazeTypePV,ALOptoMazeSessionPV,...
%                                 ALOptoStimPulseWPV,optoStim);
%     [recDataCuePre{n},recDataCueManip{n},recDataCuePost{n},...
%         recDataCuePreOpt{n},recDataCueManipOpt{n},recDataCuePostOpt{n},...
%         recDataCuePreOptCtrl{n},recDataCueManipOptCtrl{n},recDataCuePostOptCtrl{n}] = ...
%                 accumRecDataCue_opto(activeLickOptoPVPath,ALRecSessionsOptoPV,...
%                                 ALOptoMazeTypePV,ALOptoMazeSessionPV,...
%                                 ALOptoStimPulseWPV,optoStim);
%     [recDataRewPre{n},recDataRewManip{n},recDataRewPost{n},...
%         recDataRewPreOpt{n},recDataRewManipOpt{n},recDataRewPostOpt{n},...
%         recDataRewPreOptCtrl{n},recDataRewManipOptCtrl{n},recDataRewPostOptCtrl{n}] = ...
%                 accumRecDataRew_opto(activeLickOptoPVPath,ALRecSessionsOptoPV,...
%                                 ALOptoMazeTypePV,ALOptoMazeSessionPV,...
%                                 ALOptoStimPulseWPV,optoStim);
%                             
%     disp('PV active licking running stim')
%     n = 11;
%     recDataLabel{n} = 'PV active licking running stim';
%     optoStim = 5;
%     [recDataRunPre{n},recDataRunManip{n},recDataRunPost{n},...
%         recDataRunPreOpt{n},recDataRunManipOpt{n},recDataRunPostOpt{n},...
%         recDataRunPreOptCtrl{n},recDataRunManipOptCtrl{n},recDataRunPostOptCtrl{n}] = ...
%                 accumRecDataRun_opto(activeLickOptoPVPath,ALRecSessionsOptoPV,...
%                                 ALOptoMazeTypePV,ALOptoMazeSessionPV,...
%                                 ALOptoStimPulseWPV,optoStim);
%     [recDataCuePre{n},recDataCueManip{n},recDataCuePost{n},...
%         recDataCuePreOpt{n},recDataCueManipOpt{n},recDataCuePostOpt{n},...
%         recDataCuePreOptCtrl{n},recDataCueManipOptCtrl{n},recDataCuePostOptCtrl{n}] = ...
%                 accumRecDataCue_opto(activeLickOptoPVPath,ALRecSessionsOptoPV,...
%                                 ALOptoMazeTypePV,ALOptoMazeSessionPV,...
%                                 ALOptoStimPulseWPV,optoStim);
%     [recDataRewPre{n},recDataRewManip{n},recDataRewPost{n},...
%         recDataRewPreOpt{n},recDataRewManipOpt{n},recDataRewPostOpt{n},...
%         recDataRewPreOptCtrl{n},recDataRewManipOptCtrl{n},recDataRewPostOptCtrl{n}] = ...
%                 accumRecDataRew_opto(activeLickOptoPVPath,ALRecSessionsOptoPV,...
%                                 ALOptoMazeTypePV,ALOptoMazeSessionPV,...
%                                 ALOptoStimPulseWPV,optoStim);
%                             
%     disp('PV active licking reward stim 3 sec')
%     n = 12;
%     recDataLabel{n} = 'PV active licking reward stim 3 sec';
%     optoStim = 4;
%     [recDataRunPre{n},recDataRunManip{n},recDataRunPost{n},...
%         recDataRunPreOpt{n},recDataRunManipOpt{n},recDataRunPostOpt{n},...
%         recDataRunPreOptCtrl{n},recDataRunManipOptCtrl{n},recDataRunPostOptCtrl{n}] = ...
%                 accumRecDataRun_opto(activeLickOptoPVPath,ALRecSessionsOptoPV,...
%                                 ALOptoMazeTypePV,ALOptoMazeSessionPV,...
%                                 ALOptoStimPulseWPV,optoStim);
%     [recDataCuePre{n},recDataCueManip{n},recDataCuePost{n},...
%         recDataCuePreOpt{n},recDataCueManipOpt{n},recDataCuePostOpt{n},...
%         recDataCuePreOptCtrl{n},recDataCueManipOptCtrl{n},recDataCuePostOptCtrl{n}] = ...
%                 accumRecDataCue_opto(activeLickOptoPVPath,ALRecSessionsOptoPV,...
%                                 ALOptoMazeTypePV,ALOptoMazeSessionPV,...
%                                 ALOptoStimPulseWPV,optoStim);
%     [recDataRewPre{n},recDataRewManip{n},recDataRewPost{n},...
%         recDataRewPreOpt{n},recDataRewManipOpt{n},recDataRewPostOpt{n},...
%         recDataRewPreOptCtrl{n},recDataRewManipOptCtrl{n},recDataRewPostOptCtrl{n}] = ...
%                 accumRecDataRew_opto(activeLickOptoPVPath,ALRecSessionsOptoPV,...
%                                 ALOptoMazeTypePV,ALOptoMazeSessionPV,...
%                                 ALOptoStimPulseWPV,optoStim);
%                             
%     disp('PV active licking running onset stim 3 sec')
%     n = 13;
%     recDataLabel{n} = 'PV active licking running onset stim 3 sec';
%     optoStim = 2;
%     [recDataRunPre{n},recDataRunManip{n},recDataRunPost{n},...
%         recDataRunPreOpt{n},recDataRunManipOpt{n},recDataRunPostOpt{n},...
%         recDataRunPreOptCtrl{n},recDataRunManipOptCtrl{n},recDataRunPostOptCtrl{n}] = ...
%                 accumRecDataRun_opto(activeLickOptoPVPath,ALRecSessionsOptoPV,...
%                                 ALOptoMazeTypePV,ALOptoMazeSessionPV,...
%                                 ALOptoStimPulseWPV,optoStim);
%     [recDataCuePre{n},recDataCueManip{n},recDataCuePost{n},...
%         recDataCuePreOpt{n},recDataCueManipOpt{n},recDataCuePostOpt{n},...
%         recDataCuePreOptCtrl{n},recDataCueManipOptCtrl{n},recDataCuePostOptCtrl{n}] = ...
%                 accumRecDataCue_opto(activeLickOptoPVPath,ALRecSessionsOptoPV,...
%                                 ALOptoMazeTypePV,ALOptoMazeSessionPV,...
%                                 ALOptoStimPulseWPV,optoStim);
%     [recDataRewPre{n},recDataRewManip{n},recDataRewPost{n},...
%         recDataRewPreOpt{n},recDataRewManipOpt{n},recDataRewPostOpt{n},...
%         recDataRewPreOptCtrl{n},recDataRewManipOptCtrl{n},recDataRewPostOptCtrl{n}] = ...
%                 accumRecDataRew_opto(activeLickOptoPVPath,ALRecSessionsOptoPV,...
%                                 ALOptoMazeTypePV,ALOptoMazeSessionPV,...
%                                 ALOptoStimPulseWPV,optoStim);
%                             
%     disp('PV active licking cue onset stim 3 sec')
%     n = 14;
%     recDataLabel{n} = 'PV active licking cue onset stim 3 sec';
%     optoStim = 1;
%     [recDataRunPre{n},recDataRunManip{n},recDataRunPost{n},...
%         recDataRunPreOpt{n},recDataRunManipOpt{n},recDataRunPostOpt{n},...
%         recDataRunPreOptCtrl{n},recDataRunManipOptCtrl{n},recDataRunPostOptCtrl{n}] = ...
%                 accumRecDataRun_opto(activeLickOptoPVPath,ALRecSessionsOptoPV,...
%                                 ALOptoMazeTypePV,ALOptoMazeSessionPV,...
%                                 ALOptoStimPulseWPV,optoStim);
%     [recDataCuePre{n},recDataCueManip{n},recDataCuePost{n},...
%         recDataCuePreOpt{n},recDataCueManipOpt{n},recDataCuePostOpt{n},...
%         recDataCuePreOptCtrl{n},recDataCueManipOptCtrl{n},recDataCuePostOptCtrl{n}] = ...
%                 accumRecDataCue_opto(activeLickOptoPVPath,ALRecSessionsOptoPV,...
%                                 ALOptoMazeTypePV,ALOptoMazeSessionPV,...
%                                 ALOptoStimPulseWPV,optoStim);
%     [recDataRewPre{n},recDataRewManip{n},recDataRewPost{n},...
%         recDataRewPreOpt{n},recDataRewManipOpt{n},recDataRewPostOpt{n},...
%         recDataRewPreOptCtrl{n},recDataRewManipOptCtrl{n},recDataRewPostOptCtrl{n}] = ...
%                 accumRecDataRew_opto(activeLickOptoPVPath,ALRecSessionsOptoPV,...
%                                 ALOptoMazeTypePV,ALOptoMazeSessionPV,...
%                                 ALOptoStimPulseWPV,optoStim);
%                             
%     disp('PV active licking middle cue stim 3 sec')
%     n = 15;
%     recDataLabel{n} = 'PV active licking middle cue stim 3 sec';
%     optoStim = 3;
%     [recDataRunPre{n},recDataRunManip{n},recDataRunPost{n},...
%         recDataRunPreOpt{n},recDataRunManipOpt{n},recDataRunPostOpt{n},...
%         recDataRunPreOptCtrl{n},recDataRunManipOptCtrl{n},recDataRunPostOptCtrl{n}] = ...
%                 accumRecDataRun_opto(activeLickOptoPVPath,ALRecSessionsOptoPV,...
%                                 ALOptoMazeTypePV,ALOptoMazeSessionPV,...
%                                 ALOptoStimPulseWPV,optoStim);
%     [recDataCuePre{n},recDataCueManip{n},recDataCuePost{n},...
%         recDataCuePreOpt{n},recDataCueManipOpt{n},recDataCuePostOpt{n},...
%         recDataCuePreOptCtrl{n},recDataCueManipOptCtrl{n},recDataCuePostOptCtrl{n}] = ...
%                 accumRecDataCue_opto(activeLickOptoPVPath,ALRecSessionsOptoPV,...
%                                 ALOptoMazeTypePV,ALOptoMazeSessionPV,...
%                                 ALOptoStimPulseWPV,optoStim);
%     [recDataRewPre{n},recDataRewManip{n},recDataRewPost{n},...
%         recDataRewPreOpt{n},recDataRewManipOpt{n},recDataRewPostOpt{n},...
%         recDataRewPreOptCtrl{n},recDataRewManipOptCtrl{n},recDataRewPostOptCtrl{n}] = ...
%                 accumRecDataRew_opto(activeLickOptoPVPath,ALRecSessionsOptoPV,...
%                                 ALOptoMazeTypePV,ALOptoMazeSessionPV,...
%                                 ALOptoStimPulseWPV,optoStim);
%                             
%     disp('PV active licking start cue stim 3 sec or to < 100 cm')
%     n = 16;
%     recDataLabel{n} = 'PV active licking start cue stim 3 sec or to < 100 cm';
%     optoStim = 7;
%     [recDataRunPre{n},recDataRunManip{n},recDataRunPost{n},...
%         recDataRunPreOpt{n},recDataRunManipOpt{n},recDataRunPostOpt{n},...
%         recDataRunPreOptCtrl{n},recDataRunManipOptCtrl{n},recDataRunPostOptCtrl{n}] = ...
%                 accumRecDataRun_opto(activeLickOptoPVPath,ALRecSessionsOptoPV,...
%                                 ALOptoMazeTypePV,ALOptoMazeSessionPV,...
%                                 ALOptoStimPulseWPV,optoStim);
%     [recDataCuePre{n},recDataCueManip{n},recDataCuePost{n},...
%         recDataCuePreOpt{n},recDataCueManipOpt{n},recDataCuePostOpt{n},...
%         recDataCuePreOptCtrl{n},recDataCueManipOptCtrl{n},recDataCuePostOptCtrl{n}] = ...
%                 accumRecDataCue_opto(activeLickOptoPVPath,ALRecSessionsOptoPV,...
%                                 ALOptoMazeTypePV,ALOptoMazeSessionPV,...
%                                 ALOptoStimPulseWPV,optoStim);
%     [recDataRewPre{n},recDataRewManip{n},recDataRewPost{n},...
%         recDataRewPreOpt{n},recDataRewManipOpt{n},recDataRewPostOpt{n},...
%         recDataRewPreOptCtrl{n},recDataRewManipOptCtrl{n},recDataRewPostOptCtrl{n}] = ...
%                 accumRecDataRew_opto(activeLickOptoPVPath,ALRecSessionsOptoPV,...
%                                 ALOptoMazeTypePV,ALOptoMazeSessionPV,...
%                                 ALOptoStimPulseWPV,optoStim);
%                             
%     disp('PV active licking middle cue stim 3 sec or to black out start')
%     n = 17;
%     recDataLabel{n} = 'PV active licking middle cue stim 3 sec or to black out start';
%     optoStim = 8;
%     [recDataRunPre{n},recDataRunManip{n},recDataRunPost{n},...
%         recDataRunPreOpt{n},recDataRunManipOpt{n},recDataRunPostOpt{n},...
%         recDataRunPreOptCtrl{n},recDataRunManipOptCtrl{n},recDataRunPostOptCtrl{n}] = ...
%                 accumRecDataRun_opto(activeLickOptoPVPath,ALRecSessionsOptoPV,...
%                                 ALOptoMazeTypePV,ALOptoMazeSessionPV,...
%                                 ALOptoStimPulseWPV,optoStim);
%     [recDataCuePre{n},recDataCueManip{n},recDataCuePost{n},...
%         recDataCuePreOpt{n},recDataCueManipOpt{n},recDataCuePostOpt{n},...
%         recDataCuePreOptCtrl{n},recDataCueManipOptCtrl{n},recDataCuePostOptCtrl{n}] = ...
%                 accumRecDataCue_opto(activeLickOptoPVPath,ALRecSessionsOptoPV,...
%                                 ALOptoMazeTypePV,ALOptoMazeSessionPV,...
%                                 ALOptoStimPulseWPV,optoStim);
%     [recDataRewPre{n},recDataRewManip{n},recDataRewPost{n},...
%         recDataRewPreOpt{n},recDataRewManipOpt{n},recDataRewPostOpt{n},...
%         recDataRewPreOptCtrl{n},recDataRewManipOptCtrl{n},recDataRewPostOptCtrl{n}] = ...
%                 accumRecDataRew_opto(activeLickOptoPVPath,ALRecSessionsOptoPV,...
%                                 ALOptoMazeTypePV,ALOptoMazeSessionPV,...
%                                 ALOptoStimPulseWPV,optoStim);
%                             
%     disp('PV active licking control, fiber not completely plugged in')
%     n = 18;
%     recDataLabel{n} = 'PV active licking control, fiber not completely plugged in';
%     optoStim = 9;
%     [recDataRunPre{n},recDataRunManip{n},recDataRunPost{n},...
%         recDataRunPreOpt{n},recDataRunManipOpt{n},recDataRunPostOpt{n},...
%         recDataRunPreOptCtrl{n},recDataRunManipOptCtrl{n},recDataRunPostOptCtrl{n}] = ...
%                 accumRecDataRun_opto(activeLickOptoPVPath,ALRecSessionsOptoPV,...
%                                 ALOptoMazeTypePV,ALOptoMazeSessionPV,...
%                                 ALOptoStimPulseWPV,optoStim);
%     [recDataCuePre{n},recDataCueManip{n},recDataCuePost{n},...
%         recDataCuePreOpt{n},recDataCueManipOpt{n},recDataCuePostOpt{n},...
%         recDataCuePreOptCtrl{n},recDataCueManipOptCtrl{n},recDataCuePostOptCtrl{n}] = ...
%                 accumRecDataCue_opto(activeLickOptoPVPath,ALRecSessionsOptoPV,...
%                                 ALOptoMazeTypePV,ALOptoMazeSessionPV,...
%                                 ALOptoStimPulseWPV,optoStim);
%     [recDataRewPre{n},recDataRewManip{n},recDataRewPost{n},...
%         recDataRewPreOpt{n},recDataRewManipOpt{n},recDataRewPostOpt{n},...
%         recDataRewPreOptCtrl{n},recDataRewManipOptCtrl{n},recDataRewPostOptCtrl{n}] = ...
%                 accumRecDataRew_opto(activeLickOptoPVPath,ALRecSessionsOptoPV,...
%                                 ALOptoMazeTypePV,ALOptoMazeSessionPV,...
%                                 ALOptoStimPulseWPV,optoStim);
%                             
%     disp('PV active licking reward stim 3 sec (activation)')
%     n = 19;
%     recDataLabel{n} = 'PV active licking reward stim 3 sec (activation)';
%     optoStim = 4;
%     [recDataRunPre{n},recDataRunManip{n},recDataRunPost{n},...
%         recDataRunPreOpt{n},recDataRunManipOpt{n},recDataRunPostOpt{n},...
%         recDataRunPreOptCtrl{n},recDataRunManipOptCtrl{n},recDataRunPostOptCtrl{n}] = ...
%                 accumRecDataRun_opto(activeLickOptoPVPathAct,ALRecSessionsOptoPVAct,...
%                                 ALOptoMazeTypePVAct,ALOptoMazeSessionPVAct,...
%                                 ALOptoStimPulseWPVAct,optoStim);
%     [recDataCuePre{n},recDataCueManip{n},recDataCuePost{n},...
%         recDataCuePreOpt{n},recDataCueManipOpt{n},recDataCuePostOpt{n},...
%         recDataCuePreOptCtrl{n},recDataCueManipOptCtrl{n},recDataCuePostOptCtrl{n}] = ...
%                 accumRecDataCue_opto(activeLickOptoPVPathAct,ALRecSessionsOptoPVAct,...
%                                 ALOptoMazeTypePVAct,ALOptoMazeSessionPVAct,...
%                                 ALOptoStimPulseWPVAct,optoStim);
%     [recDataRewPre{n},recDataRewManip{n},recDataRewPost{n},...
%         recDataRewPreOpt{n},recDataRewManipOpt{n},recDataRewPostOpt{n},...
%         recDataRewPreOptCtrl{n},recDataRewManipOptCtrl{n},recDataRewPostOptCtrl{n}] = ...
%                 accumRecDataRew_opto(activeLickOptoPVPathAct,ALRecSessionsOptoPVAct,...
%                                 ALOptoMazeTypePVAct,ALOptoMazeSessionPVAct,...
%                                 ALOptoStimPulseWPVAct,optoStim);
%                             
%     disp('PV active licking running onset stim 3 sec (activation)')
%     n = 20;
%     recDataLabel{n} = 'PV active licking running onset stim 3 sec (activation)';
%     optoStim = 2;
%     [recDataRunPre{n},recDataRunManip{n},recDataRunPost{n},...
%         recDataRunPreOpt{n},recDataRunManipOpt{n},recDataRunPostOpt{n},...
%         recDataRunPreOptCtrl{n},recDataRunManipOptCtrl{n},recDataRunPostOptCtrl{n}] = ...
%                 accumRecDataRun_opto(activeLickOptoPVPathAct,ALRecSessionsOptoPVAct,...
%                                 ALOptoMazeTypePVAct,ALOptoMazeSessionPVAct,...
%                                 ALOptoStimPulseWPVAct,optoStim);
%     [recDataCuePre{n},recDataCueManip{n},recDataCuePost{n},...
%         recDataCuePreOpt{n},recDataCueManipOpt{n},recDataCuePostOpt{n},...
%         recDataCuePreOptCtrl{n},recDataCueManipOptCtrl{n},recDataCuePostOptCtrl{n}] = ...
%                 accumRecDataCue_opto(activeLickOptoPVPathAct,ALRecSessionsOptoPVAct,...
%                                 ALOptoMazeTypePVAct,ALOptoMazeSessionPVAct,...
%                                 ALOptoStimPulseWPVAct,optoStim);
%     [recDataRewPre{n},recDataRewManip{n},recDataRewPost{n},...
%         recDataRewPreOpt{n},recDataRewManipOpt{n},recDataRewPostOpt{n},...
%         recDataRewPreOptCtrl{n},recDataRewManipOptCtrl{n},recDataRewPostOptCtrl{n}] = ...
%                 accumRecDataRew_opto(activeLickOptoPVPathAct,ALRecSessionsOptoPVAct,...
%                                 ALOptoMazeTypePVAct,ALOptoMazeSessionPVAct,...
%                                 ALOptoStimPulseWPVAct,optoStim);
%     
%     disp('PV active licking control, fiber not completely plugged in (activation)')
%     n = 21;
%     recDataLabel{n} = 'PV active licking control, fiber not completely plugged in (activation)';
%     optoStim = 9;
%     [recDataRunPre{n},recDataRunManip{n},recDataRunPost{n},...
%         recDataRunPreOpt{n},recDataRunManipOpt{n},recDataRunPostOpt{n},...
%         recDataRunPreOptCtrl{n},recDataRunManipOptCtrl{n},recDataRunPostOptCtrl{n}] = ...
%                 accumRecDataRun_opto(activeLickOptoPVPathAct,ALRecSessionsOptoPVAct,...
%                                 ALOptoMazeTypePVAct,ALOptoMazeSessionPVAct,...
%                                 ALOptoStimPulseWPVAct,optoStim);
%     [recDataCuePre{n},recDataCueManip{n},recDataCuePost{n},...
%         recDataCuePreOpt{n},recDataCueManipOpt{n},recDataCuePostOpt{n},...
%         recDataCuePreOptCtrl{n},recDataCueManipOptCtrl{n},recDataCuePostOptCtrl{n}] = ...
%                 accumRecDataCue_opto(activeLickOptoPVPathAct,ALRecSessionsOptoPVAct,...
%                                 ALOptoMazeTypePVAct,ALOptoMazeSessionPVAct,...
%                                 ALOptoStimPulseWPVAct,optoStim);
%     [recDataRewPre{n},recDataRewManip{n},recDataRewPost{n},...
%         recDataRewPreOpt{n},recDataRewManipOpt{n},recDataRewPostOpt{n},...
%         recDataRewPreOptCtrl{n},recDataRewManipOptCtrl{n},recDataRewPostOptCtrl{n}] = ...
%                 accumRecDataRew_opto(activeLickOptoPVPathAct,ALRecSessionsOptoPVAct,...
%                                 ALOptoMazeTypePVAct,ALOptoMazeSessionPVAct,...
%                                 ALOptoStimPulseWPVAct,optoStim);
%                             
%     disp('PV active licking, stimulation from reward to run onset (activation)')
%     n = 22;
%     recDataLabel{n} = 'PV active licking, stimulation from reward to run onset (activation)';
%     optoStim = 10;
%     [recDataRunPre{n},recDataRunManip{n},recDataRunPost{n},...
%         recDataRunPreOpt{n},recDataRunManipOpt{n},recDataRunPostOpt{n},...
%         recDataRunPreOptCtrl{n},recDataRunManipOptCtrl{n},recDataRunPostOptCtrl{n}] = ...
%                 accumRecDataRun_opto(activeLickOptoPVPathAct,ALRecSessionsOptoPVAct,...
%                                 ALOptoMazeTypePVAct,ALOptoMazeSessionPVAct,...
%                                 ALOptoStimPulseWPVAct,optoStim);
%     [recDataCuePre{n},recDataCueManip{n},recDataCuePost{n},...
%         recDataCuePreOpt{n},recDataCueManipOpt{n},recDataCuePostOpt{n},...
%         recDataCuePreOptCtrl{n},recDataCueManipOptCtrl{n},recDataCuePostOptCtrl{n}] = ...
%                 accumRecDataCue_opto(activeLickOptoPVPathAct,ALRecSessionsOptoPVAct,...
%                                 ALOptoMazeTypePVAct,ALOptoMazeSessionPVAct,...
%                                 ALOptoStimPulseWPVAct,optoStim);
%     [recDataRewPre{n},recDataRewManip{n},recDataRewPost{n},...
%         recDataRewPreOpt{n},recDataRewManipOpt{n},recDataRewPostOpt{n},...
%         recDataRewPreOptCtrl{n},recDataRewManipOptCtrl{n},recDataRewPostOptCtrl{n}] = ...
%                 accumRecDataRew_opto(activeLickOptoPVPathAct,ALRecSessionsOptoPVAct,...
%                                 ALOptoMazeTypePVAct,ALOptoMazeSessionPVAct,...
%                                 ALOptoStimPulseWPVAct,optoStim);
                            
    fullPath = [folderPath 'allRecData.mat'];
    save(fullPath,'recDataRunPre','recDataRunManip','recDataRunPost',...
        'recDataRunPreOpt','recDataRunManipOpt','recDataRunPostOpt',...
        'recDataRunPreOptCtrl','recDataRunManipOptCtrl','recDataRunPostOptCtrl',...
        'recDataCuePre','recDataCueManip','recDataCuePost',...
        'recDataCuePreOpt','recDataCueManipOpt','recDataCuePostOpt',...
        'recDataCuePreOptCtrl','recDataCueManipOptCtrl','recDataCuePostOptCtrl',...
        'recDataRewPre','recDataRewManip','recDataRewPost',...
        'recDataRewPreOpt','recDataRewManipOpt','recDataRewPostOpt',...
        'recDataRewPreOptCtrl','recDataRewManipOptCtrl','recDataRewPostOptCtrl',...
        'recDataLabel','-v7.3');
end
