function plotAccumulateRecDataCorr()
    RecordingListNT;
    
    fullPath = [folderPath 'allRecData.mat'];
    if(~exist(fullPath,'file'))
        disp([fullPath ' does not exist.']);
        return;
    end
    load(fullPath,'recDataRunManip');
    
    fullPath = [folderPath 'allRecDataStats.mat'];
    load(fullPath,'corrRecDataRunRecStartT','corrRecDataRunPercReward',...
        'corrRecDataRunRecEndT');
    
    nCond = length(recDataRunManip);
    for i = 1:nCond
        path = [folderPath '_numSamples_cond' num2str(i) '_percRew'];
        plotRegress(recDataRunManip{i}.percRewarded,recDataRunManip{i}.numSamplesMean,...
            corrRecDataRunPercReward{i}.numSamplesB,...
            corrRecDataRunPercReward{i}.numSamplesStats([1 3]),'Perc reward','No. samples',...
            ['Cond' num2str(i) ],path);
        
        path = [folderPath '_maxSpeed_cond' num2str(i) '_percRew'];
        plotRegress(recDataRunManip{i}.percRewarded,recDataRunManip{i}.maxSpeedMean,...
            corrRecDataRunPercReward{i}.maxSpeedB,...
            corrRecDataRunPercReward{i}.maxSpeedStats([1 3]),'Perc reward','Max speed (mm/s)',...
            ['Cond' num2str(i) ],path);
        
        path = [folderPath '_meanSpeed_cond' num2str(i) '_percRew'];
        plotRegress(recDataRunManip{i}.percRewarded,recDataRunManip{i}.meanSpeedMean,...
            corrRecDataRunPercReward{i}.meanSpeedB,...
            corrRecDataRunPercReward{i}.meanSpeedStats([1 3]),'Perc reward','Mean speed (mm/s)',...
            ['Cond' num2str(i) ],path);
        
        path = [folderPath '_maxRunLenT_cond' num2str(i) '_percRew'];
        plotRegress(recDataRunManip{i}.percRewarded,recDataRunManip{i}.maxRunLenTMean,...
            corrRecDataRunPercReward{i}.maxRunLenTB,...
            corrRecDataRunPercReward{i}.maxRunLenTStats([1 3]),'Perc reward','Longest running bout (s)',...
            ['Cond' num2str(i) ],path);
        
        path = [folderPath '_totRunLenT_cond' num2str(i) '_percRew'];
        plotRegress(recDataRunManip{i}.percRewarded,recDataRunManip{i}.totRunLenTMean,...
            corrRecDataRunPercReward{i}.totRunLenTB,...
            corrRecDataRunPercReward{i}.totRunLenTStats([1 3]),'Perc reward','Total run time (s)',...
            ['Cond' num2str(i) ],path);
        
        path = [folderPath '_numRun_cond' num2str(i) '_percRew'];
        plotRegress(recDataRunManip{i}.percRewarded,recDataRunManip{i}.numRunMean,...
            corrRecDataRunPercReward{i}.numRunB,...
            corrRecDataRunPercReward{i}.numRunStats([1 3]),'Perc reward','No. running bouts',...
            ['Cond' num2str(i) ],path);
        
        path = [folderPath '_maxAcc_cond' num2str(i) '_percRew'];
        plotRegress(recDataRunManip{i}.percRewarded,recDataRunManip{i}.maxAccMean,...
            corrRecDataRunPercReward{i}.maxAccB,...
            corrRecDataRunPercReward{i}.maxAccStats([1 3]),'Perc reward','Max acceleration (mm/s^2)',...
            ['Cond' num2str(i) ],path);
        
        path = [folderPath '_meanAcc_cond' num2str(i) '_percRew'];
        plotRegress(recDataRunManip{i}.percRewarded,recDataRunManip{i}.meanAccMean,...
            corrRecDataRunPercReward{i}.meanAccB,...
            corrRecDataRunPercReward{i}.meanAccStats([1 3]),'Perc reward','Mean acceleration (mm/s^2)',...
            ['Cond' num2str(i) ],path);
        
        path = [folderPath '_totStopLenT_cond' num2str(i) '_percRew'];
        plotRegress(recDataRunManip{i}.percRewarded,recDataRunManip{i}.totStopLenTMean,...
            corrRecDataRunPercReward{i}.totStopLenTB,...
            corrRecDataRunPercReward{i}.totStopLenTStats([1 3]),'Perc reward','Total stop time (s)',...
            ['Cond' num2str(i) ],path);
        
        path = [folderPath '_startCueToRun_cond' num2str(i) '_percRew'];
        plotRegress(recDataRunManip{i}.percRewarded,recDataRunManip{i}.startCueToRunMean,...
            corrRecDataRunPercReward{i}.startCueToRunB,...
            corrRecDataRunPercReward{i}.startCueToRunStats([1 3]),'Perc reward','Start cue to run onset (s)',...
            ['Cond' num2str(i) ],path);
        
        path = [folderPath '_numLicksBefRew_cond' num2str(i) '_percRew'];
        plotRegress(recDataRunManip{i}.percRewarded,recDataRunManip{i}.numLicksBefRewMean,...
            corrRecDataRunPercReward{i}.numLicksBefRewB,...
            corrRecDataRunPercReward{i}.numLicksBefRewStats([1 3]),'Perc reward','No. licks before reward',...
            ['Cond' num2str(i) ],path);
        
        path = [folderPath '_numLicksRew_cond' num2str(i) '_percRew'];
        plotRegress(recDataRunManip{i}.percRewarded,recDataRunManip{i}.numLicksRewMean,...
            corrRecDataRunPercReward{i}.numLicksRewB,...
            corrRecDataRunPercReward{i}.numLicksRewStats([1 3]),'Perc reward','No. licks after reward',...
            ['Cond' num2str(i) ],path);
        
        path = [folderPath '_medLickDistBefRew_cond' num2str(i) '_percRew'];
        plotRegress(recDataRunManip{i}.percRewarded,recDataRunManip{i}.medLickDistBefRewMean,...
            corrRecDataRunPercReward{i}.medLickDistBefRewB,...
            corrRecDataRunPercReward{i}.medLickDistBefRewStats([1 3]),'Perc reward','Median lick distance befrore reward (mm)',...
            ['Cond' num2str(i) ],path);
        
        path = [folderPath '_percNonStop_cond' num2str(i) '_percRew'];
        plotRegress(recDataRunManip{i}.percRewarded,recDataRunManip{i}.percNonStop,...
            corrRecDataRunPercReward{i}.percNonStopB,...
            corrRecDataRunPercReward{i}.percNonStopStats([1 3]),'Perc reward','Percent. non-stop trials',...
            ['Cond' num2str(i) ],path);
        
        path = [folderPath '_pumpLfpInd_cond' num2str(i) '_percRew'];
        plotRegress(recDataRunManip{i}.percRewarded,recDataRunManip{i}.pumpLfpIndMean,...
            corrRecDataRunPercReward{i}.pumpLfpIndB,...
            corrRecDataRunPercReward{i}.pumpLfpIndStats([1 3]),'Perc reward','Pump on lfp index',...
            ['Cond' num2str(i) ],path);
        
        path = [folderPath '_pumpMM_cond' num2str(i) '_percRew'];
        plotRegress(recDataRunManip{i}.percRewarded,recDataRunManip{i}.pumpMMMean,...
            corrRecDataRunPercReward{i}.pumpMMB,...
            corrRecDataRunPercReward{i}.pumpMMStats([1 3]),'Perc reward','Pump on distance (mm)',...
            ['Cond' num2str(i) ],path);
        
        pause;
        close all;
    end
    
end

function plotRegress(x,y,b,stats,xl,yl,tit,path)
    if(isnan(stats(2)))
        return;
    end
    figure;
    h = plot(x,y,'.');
    set(h,'MarkerSize',12,'Color',[0.3 0.3 0.3]);
    hold on;
    h = plot(x,b(1)+b(2)*x,'-');
    set(h,'MarkerSize',8,'Color',[1 0.5 0.5]);
    text(0.2*(max(x)-min(x))+min(x),0.8*(max(y)-min(y))+min(y),[ num2str(stats(1),'r = %f, ') num2str(stats(2),'p = %f')]);
    xlabel(xl);
    ylabel(yl);
    if(~isempty(tit))
        title(tit);
    end
    set(gca,'fontSize',12,'YLim',[min(y) max(y)],'XLim', [min(x) max(x)]);
    print('-painters', '-dpdf', path, '-r600')
    savefig([path '.fig']);
end
