function plotAccumulateRecData_optovsCtrl(mode)
% plot the comparison between optogenetic trials and the control trials
% during the optogenetic session
    if(mode == 1)
        RecordingListNT_opto1; % including the continous stimulation
    elseif(mode == 2)
        RecordingListNT_opto2; % without the continous stimulation
    else
        RecordingListNT_opto;
    end
    
    fullPath = [folderPath 'allRecData.mat'];
    if(~exist(fullPath,'file'))
        disp([fullPath ' does not exist.']);
        return;
    end
    load(fullPath,'recDataRunManipOpt','recDataRunManipOptCtrl');
    
    fullPath = [folderPath 'allRecDataStats.mat'];
    load(fullPath,'meanRecDataRunManipOpt','semRecDataRunManipOpt',...
            'signedRankRecDataRunOptCtrl','meanRecDataRunManipOptCtrl','semRecDataRunManipOptCtrl');
            
    nCond = length(meanRecDataRunManipOpt);
    for i = 1:nCond
        disp(['Condition ' num2str(i)])
        if(length(recDataRunManipOpt{i}.indRec)<=1)
            continue;
        end
        path = [folderPath 'Figure\_numSamples_cond' num2str(i) '_OptVsOptCtrl'];
        plotStat(recDataRunManipOpt{i}.numSamplesMean,recDataRunManipOptCtrl{i}.numSamplesMean,[],...
            meanRecDataRunManipOpt{i}.numSamples,meanRecDataRunManipOptCtrl{i}.numSamples,[],...
            semRecDataRunManipOpt{i}.numSamples,semRecDataRunManipOptCtrl{i}.numSamples,[],...
            signedRankRecDataRunOptCtrl{i}.numSamples,[],[],'Session','No. samples',['Cond' num2str(i)],path);
        
        path = [folderPath 'Figure\_maxSpeed_cond' num2str(i) '_OptVsOptCtrl'];
        plotStat(recDataRunManipOpt{i}.maxSpeedMean,recDataRunManipOptCtrl{i}.maxSpeedMean,[],...
            meanRecDataRunManipOpt{i}.maxSpeed,meanRecDataRunManipOptCtrl{i}.maxSpeed,[],...
            semRecDataRunManipOpt{i}.maxSpeed,semRecDataRunManipOptCtrl{i}.maxSpeed,[],...
            signedRankRecDataRunOptCtrl{i}.maxSpeed,[],[],'Session','Max speed (mm/s)',['Cond' num2str(i)],path);
                
        path = [folderPath 'Figure\_meanSpeed_cond' num2str(i) '_OptVsOptCtrl'];
        plotStat(recDataRunManipOpt{i}.meanSpeedMean,recDataRunManipOptCtrl{i}.meanSpeedMean,[],...
            meanRecDataRunManipOpt{i}.meanSpeed,meanRecDataRunManipOptCtrl{i}.meanSpeed,[],...
            semRecDataRunManipOpt{i}.meanSpeed,semRecDataRunManipOptCtrl{i}.meanSpeed,[],...
            signedRankRecDataRunOptCtrl{i}.meanSpeed,[],[],'Session','Mean speed (mm/s)',['Cond' num2str(i)],path);
                    
        path = [folderPath 'Figure\_maxRunLenT_cond' num2str(i) '_OptVsOptCtrl'];
        plotStat(recDataRunManipOpt{i}.maxRunLenTMean,recDataRunManipOptCtrl{i}.maxRunLenTMean,[],...
            meanRecDataRunManipOpt{i}.maxRunLenT,meanRecDataRunManipOptCtrl{i}.maxRunLenT,[],...
            semRecDataRunManipOpt{i}.maxRunLenT,semRecDataRunManipOptCtrl{i}.maxRunLenT,[],...
            signedRankRecDataRunOptCtrl{i}.maxRunLenT,[],[],'Session','Longest running bout (s)',['Cond' num2str(i)],path);
                
        path = [folderPath 'Figure\_totRunLenT_cond' num2str(i) '_OptVsOptCtrl'];
        plotStat(recDataRunManipOpt{i}.totRunLenTMean,recDataRunManipOptCtrl{i}.totRunLenTMean,[],...
            meanRecDataRunManipOpt{i}.totRunLenT,meanRecDataRunManipOptCtrl{i}.totRunLenT,[],...
            semRecDataRunManipOpt{i}.totRunLenT,semRecDataRunManipOptCtrl{i}.totRunLenT,[],...
            signedRankRecDataRunOptCtrl{i}.totRunLenT,[],[],'Session','Total run time (s)',['Cond' num2str(i)],path);
                
        path = [folderPath 'Figure\_numRun_cond' num2str(i) '_OptVsOptCtrl'];
        plotStat(recDataRunManipOpt{i}.numRunMean,recDataRunManipOptCtrl{i}.numRunMean,[],...
            meanRecDataRunManipOpt{i}.numRun,meanRecDataRunManipOptCtrl{i}.numRun,[],...
            semRecDataRunManipOpt{i}.numRun,semRecDataRunManipOptCtrl{i}.numRun,[],...
            signedRankRecDataRunOptCtrl{i}.numRun,[],[],'Session','No. running bouts',['Cond' num2str(i)],path);
                
        path = [folderPath 'Figure\_maxAcc_cond' num2str(i) '_OptVsOptCtrl'];
        plotStat(recDataRunManipOpt{i}.maxAccMean,recDataRunManipOptCtrl{i}.maxAccMean,[],...
            meanRecDataRunManipOpt{i}.maxAcc,meanRecDataRunManipOptCtrl{i}.maxAcc,[],...
            semRecDataRunManipOpt{i}.maxAcc,semRecDataRunManipOptCtrl{i}.maxAcc,[],...
            signedRankRecDataRunOptCtrl{i}.maxAcc,[],[],'Session','Max acceleration (mm/s^2)',['Cond' num2str(i)],path);
        
        path = [folderPath 'Figure\_meanAcc_cond' num2str(i) '_OptVsOptCtrl'];
        plotStat(recDataRunManipOpt{i}.meanAccMean,recDataRunManipOptCtrl{i}.meanAccMean,[],...
            meanRecDataRunManipOpt{i}.meanAcc,meanRecDataRunManipOptCtrl{i}.meanAcc,[],...
            semRecDataRunManipOpt{i}.meanAcc,semRecDataRunManipOptCtrl{i}.meanAcc,[],...
            signedRankRecDataRunOptCtrl{i}.meanAcc,[],[],'Session','Mean acceleration (mm/s^2)',['Cond' num2str(i)],path);
        
        path = [folderPath 'Figure\_totStopLenT_cond' num2str(i) '_OptVsOptCtrl'];
        plotStat(recDataRunManipOpt{i}.totStopLenTMean,recDataRunManipOptCtrl{i}.totStopLenTMean,[],...
            meanRecDataRunManipOpt{i}.totStopLenT,meanRecDataRunManipOptCtrl{i}.totStopLenT,[],...
            semRecDataRunManipOpt{i}.totStopLenT,semRecDataRunManipOptCtrl{i}.totStopLenT,[],...
            signedRankRecDataRunOptCtrl{i}.totStopLenT,[],[],'Session','Total stop time (s)',['Cond' num2str(i)],path);
                
        path = [folderPath 'Figure\_startCueToRun_cond' num2str(i) '_OptVsOptCtrl'];
        plotStat(recDataRunManipOpt{i}.startCueToRunMean,recDataRunManipOptCtrl{i}.startCueToRunMean,[],...
            meanRecDataRunManipOpt{i}.startCueToRun,meanRecDataRunManipOptCtrl{i}.startCueToRun,[],...
            semRecDataRunManipOpt{i}.startCueToRun,semRecDataRunManipOptCtrl{i}.startCueToRun,[],...
            signedRankRecDataRunOptCtrl{i}.startCueToRun,[],[],'Session','Start cue to run onset (s)',['Cond' num2str(i)],path);
        
        path = [folderPath 'Figure\_numLicksBefRew_cond' num2str(i) '_OptVsOptCtrl'];
        plotStat(recDataRunManipOpt{i}.numLicksBefRewMean,recDataRunManipOptCtrl{i}.numLicksBefRewMean,[],...
            meanRecDataRunManipOpt{i}.numLicksBefRew,meanRecDataRunManipOptCtrl{i}.numLicksBefRew,[],...
            semRecDataRunManipOpt{i}.numLicksBefRew,semRecDataRunManipOptCtrl{i}.numLicksBefRew,[],...
            signedRankRecDataRunOptCtrl{i}.numLicksBefRew,[],[],'Session','No. licks before reward',['Cond' num2str(i)],path);
        
        path = [folderPath 'Figure\_numLicksRew_cond' num2str(i) '_OptVsOptCtrl'];
        plotStat(recDataRunManipOpt{i}.numLicksRewMean,recDataRunManipOptCtrl{i}.numLicksRewMean,[],...
            meanRecDataRunManipOpt{i}.numLicksRew,meanRecDataRunManipOptCtrl{i}.numLicksRew,[],...
            semRecDataRunManipOpt{i}.numLicksRew,semRecDataRunManipOptCtrl{i}.numLicksRew,[],...
            signedRankRecDataRunOptCtrl{i}.numLicksRew,[],[],'Session','No. licks after reward',['Cond' num2str(i)],path);
        
        path = [folderPath 'Figure\_med1stFiveLickDist_cond' num2str(i) '_OptVsOptCtrl'];
        plotStat(recDataRunManipOpt{i}.med1stFiveLickDistMean,recDataRunManipOptCtrl{i}.med1stFiveLickDistMean,[],...
            meanRecDataRunManipOpt{i}.med1stFiveLickDist,meanRecDataRunManipOptCtrl{i}.med1stFiveLickDist,[],...
            semRecDataRunManipOpt{i}.med1stFiveLickDist,semRecDataRunManipOptCtrl{i}.med1stFiveLickDist,[],...
            signedRankRecDataRunOptCtrl{i}.med1stFiveLickDist,[],[],'Session','Median first-5-lick distance (mm)',['Cond' num2str(i)],path);
                
        path = [folderPath 'Figure\_medLickDist_cond' num2str(i) '_OptVsOptCtrl'];
        plotStat(recDataRunManipOpt{i}.medLickDistMean,recDataRunManipOptCtrl{i}.medLickDistMean,[],...
            meanRecDataRunManipOpt{i}.medLickDist,meanRecDataRunManipOptCtrl{i}.medLickDist,[],...
            semRecDataRunManipOpt{i}.medLickDist,semRecDataRunManipOptCtrl{i}.medLickDist,[],...
            signedRankRecDataRunOptCtrl{i}.medLickDist,[],[],'Session','Median lick distance (mm)',['Cond' num2str(i)],path);
               
        path = [folderPath 'Figure\_med1stFiveLickDistBefRew_cond' num2str(i) '_OptVsOptCtrl'];
        plotStat(recDataRunManipOpt{i}.med1stFiveLickDistBefRewMean,recDataRunManipOptCtrl{i}.med1stFiveLickDistBefRewMean,[],...
            meanRecDataRunManipOpt{i}.med1stFiveLickDistBefRew,meanRecDataRunManipOptCtrl{i}.med1stFiveLickDistBefRew,[],...
            semRecDataRunManipOpt{i}.med1stFiveLickDistBefRew,semRecDataRunManipOptCtrl{i}.med1stFiveLickDistBefRew,[],...
            signedRankRecDataRunOptCtrl{i}.med1stFiveLickDistBefRew,[],[],'Session','Median first-5-lick distance befrore reward (mm)',['Cond' num2str(i)],path);
        
        path = [folderPath 'Figure\_medLickDistBefRew_cond' num2str(i) '_OptVsOptCtrl'];
        plotStat(recDataRunManipOpt{i}.medLickDistBefRewMean,recDataRunManipOptCtrl{i}.medLickDistBefRewMean,[],...
            meanRecDataRunManipOpt{i}.medLickDistBefRew,meanRecDataRunManipOptCtrl{i}.medLickDistBefRew,[],...
            semRecDataRunManipOpt{i}.medLickDistBefRew,semRecDataRunManipOptCtrl{i}.medLickDistBefRew,[],...
            signedRankRecDataRunOptCtrl{i}.medLickDistBefRew,[],[],'Session','Median lick distance befrore reward (mm)',['Cond' num2str(i)],path);
        
        path = [folderPath 'Figure\_percRewarded_cond' num2str(i) '_OptVsOptCtrl'];
        plotStat(recDataRunManipOpt{i}.percRewarded,recDataRunManipOptCtrl{i}.percRewarded,[],...
            meanRecDataRunManipOpt{i}.percRewarded,meanRecDataRunManipOptCtrl{i}.percRewarded,[],...
            semRecDataRunManipOpt{i}.percRewarded,semRecDataRunManipOptCtrl{i}.percRewarded,[],...
            signedRankRecDataRunOptCtrl{i}.percRewarded,[],[],'Session','Percent. rewarded',['Cond' num2str(i)],path);
                
        path = [folderPath 'Figure\_percNonStop_cond' num2str(i) '_OptVsOptCtrl'];
        plotStat(recDataRunManipOpt{i}.percNonStop,recDataRunManipOptCtrl{i}.percNonStop,[],...
            meanRecDataRunManipOpt{i}.percNonStop,meanRecDataRunManipOptCtrl{i}.percNonStop,[],...
            semRecDataRunManipOpt{i}.percNonStop,semRecDataRunManipOptCtrl{i}.percNonStop,[],...
            signedRankRecDataRunOptCtrl{i}.percNonStop,[],[],'Session','Percent. non-stop trials',['Cond' num2str(i)],path);
        
        path = [folderPath 'Figure\_pumpLfpInd_cond' num2str(i) '_OptVsOptCtrl'];
        plotStat(recDataRunManipOpt{i}.pumpLfpIndMean,recDataRunManipOptCtrl{i}.pumpLfpIndMean,[],...
            meanRecDataRunManipOpt{i}.pumpLfpInd,meanRecDataRunManipOptCtrl{i}.pumpLfpInd,[],...
            semRecDataRunManipOpt{i}.pumpLfpInd,semRecDataRunManipOptCtrl{i}.pumpLfpInd,[],...
            signedRankRecDataRunOptCtrl{i}.pumpLfpInd,[],[],'Session','Pump on lfp index',['Cond' num2str(i)],path);
                
        path = [folderPath 'Figure\_pumpMM_cond' num2str(i) '_OptVsOptCtrl'];
        plotStat(recDataRunManipOpt{i}.pumpMMMean,recDataRunManipOptCtrl{i}.pumpMMMean,[],...
            meanRecDataRunManipOpt{i}.pumpMM,meanRecDataRunManipOptCtrl{i}.pumpMM,[],...
            semRecDataRunManipOpt{i}.pumpMM,semRecDataRunManipOptCtrl{i}.pumpMM,[],...
            signedRankRecDataRunOptCtrl{i}.pumpMM,[],[],'Session','Pump on distance (mm)',['Cond' num2str(i)],path);
                
        path = [folderPath 'Figure\_speedSimMean_cond' num2str(i) '_OptVsOptCtrl'];
        plotStat(recDataRunManipOpt{i}.speedSimMean,recDataRunManipOptCtrl{i}.speedSimMean,[],...
            meanRecDataRunManipOpt{i}.speedSimMean,meanRecDataRunManipOptCtrl{i}.speedSimMean,[],...
            semRecDataRunManipOpt{i}.speedSimMean,semRecDataRunManipOptCtrl{i}.speedSimMean,[],...
            signedRankRecDataRunOptCtrl{i}.speedSimMean,[],[],'Session','speed Sim Mean',['Cond' num2str(i)],path);
        
        path = [folderPath 'Figure\_lickSimMean_cond' num2str(i) '_OptVsOptCtrl'];
        plotStat(recDataRunManipOpt{i}.lickSimMean,recDataRunManipOptCtrl{i}.lickSimMean,[],...
            meanRecDataRunManipOpt{i}.lickSimMean,meanRecDataRunManipOptCtrl{i}.lickSimMean,[],...
            semRecDataRunManipOpt{i}.lickSimMean,semRecDataRunManipOptCtrl{i}.lickSimMean,[],...
            signedRankRecDataRunOptCtrl{i}.lickSimMean,[],[],'Session','lick Sim Mean',['Cond' num2str(i)],path);
        
        path = [folderPath 'Figure\_speedEucMean_cond' num2str(i) '_OptVsOptCtrl'];
        plotStat(recDataRunManipOpt{i}.speedEucMean,recDataRunManipOptCtrl{i}.speedEucMean,[],...
            meanRecDataRunManipOpt{i}.speedEucMean,meanRecDataRunManipOptCtrl{i}.speedEucMean,[],...
            semRecDataRunManipOpt{i}.speedEucMean,semRecDataRunManipOptCtrl{i}.speedEucMean,[],...
            signedRankRecDataRunOptCtrl{i}.speedEucMean,[],[],'Session','speed Euc Mean',['Cond' num2str(i)],path);
        
        path = [folderPath 'Figure\_lickEucMean_cond' num2str(i) '_OptVsOptCtrl'];
        plotStat(recDataRunManipOpt{i}.lickEucMean,recDataRunManipOptCtrl{i}.lickEucMean,[],...
            meanRecDataRunManipOpt{i}.lickEucMean,meanRecDataRunManipOptCtrl{i}.lickEucMean,[],...
            semRecDataRunManipOpt{i}.lickEucMean,semRecDataRunManipOptCtrl{i}.lickEucMean,[],...
            signedRankRecDataRunOptCtrl{i}.lickEucMean,[],[],'Session','lick Euc Mean',['Cond' num2str(i)],path);
        
        path = [folderPath 'Figure\_speedStdMean_cond' num2str(i) '_OptVsOptCtrl'];
        plotStat(recDataRunManipOpt{i}.speedStdMean,recDataRunManipOptCtrl{i}.speedStdMean,[],...
            meanRecDataRunManipOpt{i}.speedStdMean,meanRecDataRunManipOptCtrl{i}.speedStdMean,[],...
            semRecDataRunManipOpt{i}.speedStdMean,semRecDataRunManipOptCtrl{i}.speedStdMean,[],...
            signedRankRecDataRunOptCtrl{i}.speedStdMean,[],[],'Session','speed Std Mean',['Cond' num2str(i)],path);
        
        path = [folderPath 'Figure\_lickStdMean_cond' num2str(i) '_OptVsOptCtrl'];
        plotStat(recDataRunManipOpt{i}.lickStdMean,recDataRunManipOptCtrl{i}.lickStdMean,[],...
            meanRecDataRunManipOpt{i}.lickStdMean,meanRecDataRunManipOptCtrl{i}.lickStdMean,[],...
            semRecDataRunManipOpt{i}.lickStdMean,semRecDataRunManipOptCtrl{i}.lickStdMean,[],...
            signedRankRecDataRunOptCtrl{i}.lickStdMean,[],[],'Session','lick Std Mean',['Cond' num2str(i)],path);
        
%         pause;
        close all;
    end
end

function plotBoxPlot(x1,x2,yl,fn,pathAnal,ylimit,p12,colorSel)
    [figNew,pos] = CreateFig();
    set(0,'Units','pixels')
    set(figure(figNew),'OuterPosition',...
            [pos(1) pos(2) 200 400])
    if(colorSel == 0)
        colorArr = [163 207 98;...
                234 131 114;...
                163 207 98]/255;
    elseif(colorSel == 1)            
        colorArr = [234 131 114;...
                116 53 61;...
                234 131 114]/255;
    else        
        colorArr = [163 207 98;... 
            63 79 37;...
            163 207 98]/255;
    end
    x = [x1;x2];
    g = [repmat(1,length(x1),1);...
        repmat(2,length(x2),1)];
    boxplot(x,g,'Notch','on','Widths',0.3,'Symbol','');
    h = findobj(gca,'Tag','Box');
    for j = 1:length(h)
        patch(get(h(j),'XData'),get(h(j),'YData'),colorArr(j,:),'FaceAlpha',0.5);
    end
    if(~isempty(ylimit))
        set(gca,'YLim',ylimit);
    end
    ylabel(yl);
    text(1,ylimit(2)*0.75,num2str(p12,'p = %f'));
        
    fileName1 = [pathAnal fn];
    saveas(gcf,fileName1);
    print('-painters', '-dpdf', fileName1, '-r600')
end

function plotStat(dataX,dataY,dataZ,meanX,meanY,meanZ,semX,semY,semZ,...
                rankXY,rankXZ,rankYZ,xlab,ylab,ti,path)    
    if(~isempty(rankXZ))  
        dataArr = [dataX' dataY' dataZ'];
        meanArr = [meanX meanY meanZ];
        errBar = [semX semY semZ];
        
        barPlotWithStat(1:3,meanArr,errBar,dataArr,xlab,ylab,ti,rankXY,rankXZ,rankYZ);
    else
        dataArr = [dataX' dataY'];
        meanArr = [meanX meanY];
        errBar = [semX semY];
        
        barPlotWithStat(1:2,meanArr,errBar,dataArr,xlab,ylab,ti,rankXY,[],[]);       
    end
    print('-painters', '-dpdf', path, '-r600')
    savefig([path '.fig']);
end