function plotAccumulateRecDataCue_optovsCtrl(mode)
% plot the comparison between optogenetic trials and the control trials
% during the optogenetic session
    if(mode == 1)
        RecordingListNT_opto1; % including the continous stimulation
    elseif(mode == 2)
        RecordingListNT_opto2; % without the continous stimulation
    else
        RecordingListNT_opto;
    end
    
    fullPath = [folderPath 'allRecData.mat'];
    if(~exist(fullPath,'file'))
        disp([fullPath ' does not exist.']);
        return;
    end
    load(fullPath,'recDataCueManipOpt','recDataCueManipOptCtrl');
    
    fullPath = [folderPath 'allRecDataStats.mat'];
    load(fullPath,'meanRecDataCueManipOpt','semRecDataCueManipOpt',...
            'rankRecDataCueOptCtrl','meanRecDataCueManipOptCtrl','semRecDataCueManipOptCtrl');
            
    nCond = length(meanRecDataCueManipOpt);
    for i = 1:nCond
        disp(['Condition ' num2str(i)])
        if(length(recDataCueManipOpt{i}.indRec)<=1)
            continue;
        end
        path = [folderPath 'Figure\_numSamplesCue_cond' num2str(i) '_OptVsOptCtrl'];
        plotStat(recDataCueManipOpt{i}.numSamplesMean,recDataCueManipOptCtrl{i}.numSamplesMean,[],...
            meanRecDataCueManipOpt{i}.numSamples,meanRecDataCueManipOptCtrl{i}.numSamples,[],...
            semRecDataCueManipOpt{i}.numSamples,semRecDataCueManipOptCtrl{i}.numSamples,[],...
            rankRecDataCueOptCtrl{i}.numSamples,[],[],'Session','No. samples',['Cond' num2str(i)],path);
        
        path = [folderPath 'Figure\_maxSpeedCue_cond' num2str(i) '_OptVsOptCtrl'];
        plotStat(recDataCueManipOpt{i}.maxSpeedMean,recDataCueManipOptCtrl{i}.maxSpeedMean,[],...
            meanRecDataCueManipOpt{i}.maxSpeed,meanRecDataCueManipOptCtrl{i}.maxSpeed,[],...
            semRecDataCueManipOpt{i}.maxSpeed,semRecDataCueManipOptCtrl{i}.maxSpeed,[],...
            rankRecDataCueOptCtrl{i}.maxSpeed,[],[],'Session','Max speed (mm/s)',['Cond' num2str(i)],path);
                
        path = [folderPath 'Figure\_meanSpeedCue_cond' num2str(i) '_OptVsOptCtrl'];
        plotStat(recDataCueManipOpt{i}.meanSpeedMean,recDataCueManipOptCtrl{i}.meanSpeedMean,[],...
            meanRecDataCueManipOpt{i}.meanSpeed,meanRecDataCueManipOptCtrl{i}.meanSpeed,[],...
            semRecDataCueManipOpt{i}.meanSpeed,semRecDataCueManipOptCtrl{i}.meanSpeed,[],...
            rankRecDataCueOptCtrl{i}.meanSpeed,[],[],'Session','Mean speed (mm/s)',['Cond' num2str(i)],path);
                    
        path = [folderPath 'Figure\_maxRunLenTCue_cond' num2str(i) '_OptVsOptCtrl'];
        plotStat(recDataCueManipOpt{i}.maxRunLenTMean,recDataCueManipOptCtrl{i}.maxRunLenTMean,[],...
            meanRecDataCueManipOpt{i}.maxRunLenT,meanRecDataCueManipOptCtrl{i}.maxRunLenT,[],...
            semRecDataCueManipOpt{i}.maxRunLenT,semRecDataCueManipOptCtrl{i}.maxRunLenT,[],...
            rankRecDataCueOptCtrl{i}.maxRunLenT,[],[],'Session','Longest running bout (s)',['Cond' num2str(i)],path);
                
        path = [folderPath 'Figure\_totRunLenTCue_cond' num2str(i) '_OptVsOptCtrl'];
        plotStat(recDataCueManipOpt{i}.totRunLenTMean,recDataCueManipOptCtrl{i}.totRunLenTMean,[],...
            meanRecDataCueManipOpt{i}.totRunLenT,meanRecDataCueManipOptCtrl{i}.totRunLenT,[],...
            semRecDataCueManipOpt{i}.totRunLenT,semRecDataCueManipOptCtrl{i}.totRunLenT,[],...
            rankRecDataCueOptCtrl{i}.totRunLenT,[],[],'Session','Total run time (s)',['Cond' num2str(i)],path);
                
        path = [folderPath 'Figure\_numRunCue_cond' num2str(i) '_OptVsOptCtrl'];
        plotStat(recDataCueManipOpt{i}.numRunMean,recDataCueManipOptCtrl{i}.numRunMean,[],...
            meanRecDataCueManipOpt{i}.numRun,meanRecDataCueManipOptCtrl{i}.numRun,[],...
            semRecDataCueManipOpt{i}.numRun,semRecDataCueManipOptCtrl{i}.numRun,[],...
            rankRecDataCueOptCtrl{i}.numRun,[],[],'Session','No. running bouts',['Cond' num2str(i)],path);
                
        path = [folderPath 'Figure\_maxAccCue_cond' num2str(i) '_OptVsOptCtrl'];
        plotStat(recDataCueManipOpt{i}.maxAccMean,recDataCueManipOptCtrl{i}.maxAccMean,[],...
            meanRecDataCueManipOpt{i}.maxAcc,meanRecDataCueManipOptCtrl{i}.maxAcc,[],...
            semRecDataCueManipOpt{i}.maxAcc,semRecDataCueManipOptCtrl{i}.maxAcc,[],...
            rankRecDataCueOptCtrl{i}.maxAcc,[],[],'Session','Max acceleration (mm/s^2)',['Cond' num2str(i)],path);
        
        path = [folderPath 'Figure\_meanAccCue_cond' num2str(i) '_OptVsOptCtrl'];
        plotStat(recDataCueManipOpt{i}.meanAccMean,recDataCueManipOptCtrl{i}.meanAccMean,[],...
            meanRecDataCueManipOpt{i}.meanAcc,meanRecDataCueManipOptCtrl{i}.meanAcc,[],...
            semRecDataCueManipOpt{i}.meanAcc,semRecDataCueManipOptCtrl{i}.meanAcc,[],...
            rankRecDataCueOptCtrl{i}.meanAcc,[],[],'Session','Mean acceleration (mm/s^2)',['Cond' num2str(i)],path);
        
        path = [folderPath 'Figure\_totStopLenTCue_cond' num2str(i) '_OptVsOptCtrl'];
        plotStat(recDataCueManipOpt{i}.totStopLenTMean,recDataCueManipOptCtrl{i}.totStopLenTMean,[],...
            meanRecDataCueManipOpt{i}.totStopLenT,meanRecDataCueManipOptCtrl{i}.totStopLenT,[],...
            semRecDataCueManipOpt{i}.totStopLenT,semRecDataCueManipOptCtrl{i}.totStopLenT,[],...
            rankRecDataCueOptCtrl{i}.totStopLenT,[],[],'Session','Total stop time (s)',['Cond' num2str(i)],path);
                
        path = [folderPath 'Figure\_med1stFiveLickDistCue_cond' num2str(i) '_OptVsOptCtrl'];
        plotStat(recDataCueManipOpt{i}.med1stFiveLickDistMean,recDataCueManipOptCtrl{i}.med1stFiveLickDistMean,[],...
            meanRecDataCueManipOpt{i}.med1stFiveLickDist,meanRecDataCueManipOptCtrl{i}.med1stFiveLickDist,[],...
            semRecDataCueManipOpt{i}.med1stFiveLickDist,semRecDataCueManipOptCtrl{i}.med1stFiveLickDist,[],...
            rankRecDataCueOptCtrl{i}.med1stFiveLickDist,[],[],'Session','Median first-5-lick distance (mm)',['Cond' num2str(i)],path);
                
        path = [folderPath 'Figure\_medLickDistCue_cond' num2str(i) '_OptVsOptCtrl'];
        plotStat(recDataCueManipOpt{i}.medLickDistMean,recDataCueManipOptCtrl{i}.medLickDistMean,[],...
            meanRecDataCueManipOpt{i}.medLickDist,meanRecDataCueManipOptCtrl{i}.medLickDist,[],...
            semRecDataCueManipOpt{i}.medLickDist,semRecDataCueManipOptCtrl{i}.medLickDist,[],...
            rankRecDataCueOptCtrl{i}.medLickDist,[],[],'Session','Median lick distance (mm)',['Cond' num2str(i)],path);
              
        path = [folderPath 'Figure\_speedSimMeanCue_cond' num2str(i) '_OptVsOptCtrl'];
        plotStat(recDataCueManipOpt{i}.speedSimMean,recDataCueManipOptCtrl{i}.speedSimMean,[],...
            meanRecDataCueManipOpt{i}.speedSimMean,meanRecDataCueManipOptCtrl{i}.speedSimMean,[],...
            semRecDataCueManipOpt{i}.speedSimMean,semRecDataCueManipOptCtrl{i}.speedSimMean,[],...
            rankRecDataCueOptCtrl{i}.speedSimMean,[],[],'Session','speed Sim Mean',['Cond' num2str(i)],path);
        
        path = [folderPath 'Figure\_lickSimMeanCue_cond' num2str(i) '_OptVsOptCtrl'];
        plotStat(recDataCueManipOpt{i}.lickSimMean,recDataCueManipOptCtrl{i}.lickSimMean,[],...
            meanRecDataCueManipOpt{i}.lickSimMean,meanRecDataCueManipOptCtrl{i}.lickSimMean,[],...
            semRecDataCueManipOpt{i}.lickSimMean,semRecDataCueManipOptCtrl{i}.lickSimMean,[],...
            rankRecDataCueOptCtrl{i}.lickSimMean,[],[],'Session','lick Sim Mean',['Cond' num2str(i)],path);
                
        path = [folderPath 'Figure\_speedEucMeanCue_cond' num2str(i) '_OptVsOptCtrl'];
        plotStat(recDataCueManipOpt{i}.speedEucMean,recDataCueManipOptCtrl{i}.speedEucMean,[],...
            meanRecDataCueManipOpt{i}.speedEucMean,meanRecDataCueManipOptCtrl{i}.speedEucMean,[],...
            semRecDataCueManipOpt{i}.speedEucMean,semRecDataCueManipOptCtrl{i}.speedEucMean,[],...
            rankRecDataCueOptCtrl{i}.speedEucMean,[],[],'Session','speed Euc Mean',['Cond' num2str(i)],path);
        
        path = [folderPath 'Figure\_lickEucMeanCue_cond' num2str(i) '_OptVsOptCtrl'];
        plotStat(recDataCueManipOpt{i}.lickEucMean,recDataCueManipOptCtrl{i}.lickEucMean,[],...
            meanRecDataCueManipOpt{i}.lickEucMean,meanRecDataCueManipOptCtrl{i}.lickEucMean,[],...
            semRecDataCueManipOpt{i}.lickEucMean,semRecDataCueManipOptCtrl{i}.lickEucMean,[],...
            rankRecDataCueOptCtrl{i}.lickEucMean,[],[],'Session','lick Euc Mean',['Cond' num2str(i)],path);
        
%         pause;
        close all;
    end
end

function plotBoxPlot(x1,x2,yl,fn,pathAnal,ylimit,p12,colorSel)
    [figNew,pos] = CreateFig();
    set(0,'Units','pixels')
    set(figure(figNew),'OuterPosition',...
            [pos(1) pos(2) 200 400])
    if(colorSel == 0)
        colorArr = [163 207 98;...
                234 131 114;...
                163 207 98]/255;
    elseif(colorSel == 1)            
        colorArr = [234 131 114;...
                116 53 61;...
                234 131 114]/255;
    else        
        colorArr = [163 207 98;... 
            63 79 37;...
            163 207 98]/255;
    end
    x = [x1;x2];
    g = [repmat(1,length(x1),1);...
        repmat(2,length(x2),1)];
    boxplot(x,g,'Notch','on','Widths',0.3,'Symbol','');
    h = findobj(gca,'Tag','Box');
    for j = 1:length(h)
        patch(get(h(j),'XData'),get(h(j),'YData'),colorArr(j,:),'FaceAlpha',0.5);
    end
    if(~isempty(ylimit))
        set(gca,'YLim',ylimit);
    end
    ylabel(yl);
    text(1,ylimit(2)*0.75,num2str(p12,'p = %f'));
        
    fileName1 = [pathAnal fn];
    saveas(gcf,fileName1);
    print('-painters', '-dpdf', fileName1, '-r600')
end

function plotStat(dataX,dataY,dataZ,meanX,meanY,meanZ,semX,semY,semZ,...
                rankXY,rankXZ,rankYZ,xlab,ylab,ti,path)    
    if(~isempty(rankXZ))  
        dataArr = [dataX' dataY' dataZ'];
        meanArr = [meanX meanY meanZ];
        errBar = [semX semY semZ];
        
        barPlotWithStat(1:3,meanArr,errBar,dataArr,xlab,ylab,ti,rankXY,rankXZ,rankYZ);
    else
        dataArr = [dataX' dataY'];
        meanArr = [meanX meanY];
        errBar = [semX semY];
        
        barPlotWithStat(1:2,meanArr,errBar,dataArr,xlab,ylab,ti,rankXY,[],[]);       
    end
    print('-painters', '-dpdf', path, '-r600')
    savefig([path '.fig']);
end