function accumulateRecData()
    
    RecordingListNT;
    
    % muscimol active licking
    recDataLabel{1} = 'Muscimol active licking';
    [recDataRunPre{1},recDataRunManip{1},recDataRunPost{1}] = ...
                accumRecDataRun(activeLickMuscPath,recSessionsALMusc,...
                                ALMuscSessions,ALMuscMazeSession);
    [recDataCuePre{1},recDataCueManip{1},recDataCuePost{1}] = ...
                accumRecDataCue(activeLickMuscPath,recSessionsALMusc,...
                                ALMuscSessions,ALMuscMazeSession);
        
    % muscimol passive licking
    recDataLabel{2} = 'Muscimol passive licking';
    [recDataRunPre{2},recDataRunManip{2},recDataRunPost{2}] = ...
            accumRecDataRun(passiveLickMuscPath,recSessionsPLMusc,...
                            PLMuscSessions,PLMuscMazeSession);
    [recDataCuePre{2},recDataCueManip{2},recDataCuePost{2}] = ...
            accumRecDataCue(passiveLickMuscPath,recSessionsPLMusc,...
                            PLMuscSessions,PLMuscMazeSession);
    
    % scopolamine active licking
    recDataLabel{3} = 'Scopolamine active licking';
    [recDataRunPre{3},recDataRunManip{3},recDataRunPost{3}] = ...
            accumRecDataRun(activeLickScopPath,recSessionsALScop,...
                            ALScopSessions,ALScopMazeSession);
    [recDataCuePre{3},recDataCueManip{3},recDataCuePost{3}] = ...
            accumRecDataCue(activeLickScopPath,recSessionsALScop,...
                            ALScopSessions,ALScopMazeSession);
        
    % pirenzepine active licking
    recDataLabel{4} = 'Pirenzepine active licking';
    [recDataRunPre{4},recDataRunManip{4},recDataRunPost{4}] = ...
            accumRecDataRun(activeLickPirePath,recSessionsALPire,...
                            ALPireSessions,ALPireMazeSession);
    [recDataCuePre{4},recDataCueManip{4},recDataCuePost{4}] = ...
            accumRecDataCue(activeLickPirePath,recSessionsALPire,...
                            ALPireSessions,ALPireMazeSession);
    
    % propranolol active licking
    recDataLabel{5} = 'propranolol active licking';
    [recDataRunPre{5},recDataRunManip{5},recDataRunPost{5}] = ...
            accumRecDataRun(activeLickPropPath,recSessionsALProp,...
                            ALPropSessions,ALPropMazeSession);
    [recDataCuePre{5},recDataCueManip{5},recDataCuePost{5}] = ...
            accumRecDataCue(activeLickPropPath,recSessionsALProp,...
                            ALPropSessions,ALPropMazeSession);
    
    % SCH23390 active licking
    recDataLabel{6} = 'SCH23390 active licking';
    [recDataRunPre{6},recDataRunManip{6},recDataRunPost{6}] = ...
            accumRecDataRun(activeLickSCHPath,recSessionsALSCH,...
                            ALSCHSessions,ALSCHMazeSession);
    [recDataCuePre{6},recDataCueManip{6},recDataCuePost{6}] = ...
            accumRecDataCue(activeLickSCHPath,recSessionsALSCH,...
                            ALSCHSessions,ALSCHMazeSession);
    
    %% saline active licking
    recDataLabel{7} = 'saline active licking';
    [recDataRunPre{7},recDataRunManip{7},recDataRunPost{7}] = ...
            accumRecDataRun(activeLickSalPath,recSessionsALSal,...
                            ALSalSessions,ALSalMazeSession);
    [recDataCuePre{7},recDataCueManip{7},recDataCuePost{7}] = ...
            accumRecDataCue(activeLickSalPath,recSessionsALSal,...
                            ALSalSessions,ALSalMazeSession);
    
    %% CNO Som-cre active licking
    recDataLabel{8} = 'CNO SST-IRES-Cre hipp. HM4Di inj.';
    [recDataRunPre{8},recDataRunManip{8},recDataRunPost{8}] = ...
            accumRecDataRun(activeLickSOMCNOPath,recSessionsALSOMCNO,...
                            ALSOMCNOSessions,ALSOMCNOMazeSession);
    [recDataCuePre{8},recDataCueManip{8},recDataCuePost{8}] = ...
            accumRecDataCue(activeLickSOMCNOPath,recSessionsALSOMCNO,...
                            ALSOMCNOSessions,ALSOMCNOMazeSession);
    
    %% Saline Som-cre active licking
    recDataLabel{9} = 'Saline SST-IRES-Cre hipp. HM4Di inj.';
    [recDataRunPre{9},recDataRunManip{9},recDataRunPost{9}] = ...
            accumRecDataRun(activeLickSOMSalPath,recSessionsALSOMSal,...
                            ALSOMSalSessions,ALSOMSalMazeSession);
    [recDataCuePre{9},recDataCueManip{9},recDataCuePost{9}] = ...
            accumRecDataCue(activeLickSOMSalPath,recSessionsALSOMSal,...
                            ALSOMSalSessions,ALSOMSalMazeSession);
    
    %% CNO PV-cre active licking
    recDataLabel{10} = 'CNO PV-Cre hipp. HM4Di inj.';
    [recDataRunPre{10},recDataRunManip{10},recDataRunPost{10}] = ...
            accumRecDataRun(activeLickPVCNOPath,recSessionsALPVCNO,...
                            ALPVCNOSessions,ALPVCNOMazeSession);
    [recDataCuePre{10},recDataCueManip{10},recDataCuePost{10}] = ...
            accumRecDataCue(activeLickPVCNOPath,recSessionsALPVCNO,...
                            ALPVCNOSessions,ALPVCNOMazeSession);
    
    %% Saline PV-cre active licking
    recDataLabel{11} = 'Saline PV-Cre hipp. HM4Di inj.';
    [recDataRunPre{11},recDataRunManip{11},recDataRunPost{11}] = ...
            accumRecDataRun(activeLickPVSalPath,recSessionsALPVSal,...
                            ALPVSalSessions,ALPVSalMazeSession);
    [recDataCuePre{11},recDataCueManip{11},recDataCuePost{11}] = ...
            accumRecDataCue(activeLickPVSalPath,recSessionsALPVSal,...
                            ALPVSalSessions,ALPVSalMazeSession);

    %% CNO control animal active licking
    recDataLabel{12} = 'CNO C57Bl6J';
    [recDataRunPre{12},recDataRunManip{12},recDataRunPost{12}] = ...
            accumRecDataRun(activeLickCNOPath,recSessionsALCNO,...
                            ALCNOSessions,ALCNOMazeSession);
    [recDataCuePre{12},recDataCueManip{12},recDataCuePost{12}] = ...
            accumRecDataCue(activeLickCNOPath,recSessionsALCNO,...
                            ALCNOSessions,ALCNOMazeSession);
    
    fullPath = [folderPath 'allRecData.mat'];
    save(fullPath,'recDataRunPre','recDataRunManip','recDataRunPost',...
        'recDataCuePre','recDataCueManip','recDataCuePost','recDataLabel','-v7.3');
end
